### ISSUE TITLE
build_init fails

### ISSUE THREAD

**Issue by Roysten** [postmarketOS/pmbootstrap#1]
An asterix does not get expanded when it is surrounded by quotes:
```
Traceback (most recent call last):
  File "./pmbootstrap.py", line 60, in main
    pmb.build.init(args, args.suffix)
  File "/mnt/data/pmos/pmbootstrap/pmb/build/init.py", line 50, in init
    "/etc/apk/keys/"], suffix)
  File "/mnt/data/pmos/pmbootstrap/pmb/chroot/root.py", line 72, in root
    return_stdout, check)
  File "/mnt/data/pmos/pmbootstrap/pmb/helpers/run.py", line 51, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: (native) % cp '/home/user/.abuild/*.pub' /etc/apk/keys/
```
Causing the copy to fail.

**Comment by ollieparanoid** [comment]
Thank you for trying it out and reporting the bug! I'll work on a fix. In the meantime, just manually copy the keys:
```
sudo cp ~/.local/var/pmbootstrap/chroot_native/home/user/.abuild/*.pub ~/.local/var/pmbootstrap/chroot_native/etc/apk/keys/
```

**Comment by ollieparanoid** [comment]
It should work now.
One more thing, all shell commands are escaped with Python's shlex. This means, that asterisks will never work inside them (for security reasons), so it's necessary to do the globbing with Python's glob module first (look at the commit for an example).
