### ISSUE TITLE
Project website

### ISSUE THREAD

**Issue by kskarthik** [postmarketOS/pmbootstrap#10]
Deploy a website postmarketos.github.io so that it serves as main project site. People would find it easy in search results. Jekyll would be good or your homebaked makefile cms 😀

**Comment by dzervas** [comment]
:+1:

**Comment by ollieparanoid** [comment]
I think a landing page (one `index.html` without any subpages) would be enough, which quickly shows a photo, the relevant information and most important links:
* [Introduction](https://ollieparanoid.github.io/post/postmarketOS/)
* [/r/postmarketOS](https://reddit.com/r/postmarketOS)
* [GitHub](https://github.com/postmarketOS)
* [Wiki](https://github.com/postmarketOS/pmbootstrap/wiki)

This could be done quickly, and wouldn't be much effort to maintain. I'd work on something like that the next few days. Opinions on that?

**Comment by kskarthik** [comment]
Yes, one page is enough. Also, link to ported devices can be added.

**Comment by dzervas** [comment]
@ollieparanoid can you fork [it](https://github.com/dzervas/postmarketos.github.io)? I can't create the page, as it has to be the same username. I copied most of your first post and I altered it a bit to be more project-specific (and not blog-specific). Do you like it?

**Comment by ollieparanoid** [comment]
Thank you for your effort. But this is not quite what I had in mind.

That initial blog post I wrote is my idea of how it should be, and what  motivates me. But this is not what we can reach in the these early days of development, if we can reach it at all. So I'd really not want to duplicate contents (even if partially) of that post, but make a small landing page instead, that lists the important links (including a link to that full introduction post, for people who want to read it).

"The relevant information", as I said above, was kind of vague - sorry for that. What I meant was a one-liner, like used in the GitHub Repo already:

*Touch-optimized, pre-configured Alpine Linux with own packages, that can be installed on smartphones. (Not usable for most people yet!)*

Also... what's the benefit of using Jekyll for such a simple landing page? I feel that it would be simpler without Jekyll - just a plain `index.html`. But convince me otherwise, if you want to.

So please don't get me wrong, I appreciate that you have stepped up and contributed this!
Do you want to give it another try?

**Comment by dzervas** [comment]
Oh, I understand.

I'll give it another try!

-----Original Message-----

**Comment by kskarthik** [comment]
A blog to announce status of project needs Jekyll. However, its your choice

**Comment by ollieparanoid** [comment]
I'd rather have announcements made in /r/postmarketOS - because then everyone can post and we don't need to set up permissions first.

**Comment by dhruvkar** [comment]
I've squatted on the domains postmarketos.com & postmarketos.org for now. Will transfer to @ollieparanoid whenever.

@dzervas What about hosting an index.html on netlify.com? Netlify just pulls from a Github repository. No jekyll or other ssg is necessary and it doesn't limit your naming convention like Github does.

**Comment by dzervas** [comment]
Guys I'm caught up in a tight schedule so I can't make it right now (and I'm also really hyped to get n5 to work).

I'm sorry but can someone else do it?

**Comment by dhruvkar** [comment]
I'll do it. Still waiting for my old android phone 👍

**Comment by ollieparanoid** [comment]
@dzervas: No problem, we all do this in our free time - and @dhruvkar: thanks for helping out!

**Comment by kskarthik** [comment]
@dhruvkar are you working ?

**Comment by dhruvkar** [comment]
sorry, next three days I'll have something.

**Comment by kskarthik** [comment]
Meanwhile, I will also try :)

**Comment by kskarthik** [comment]
I made the site https://rawgit.com/kskarthik/website-source/master/index.html

**Comment by ollieparanoid** [comment]
This is pretty much what I imagined, thanks a lot! What do you guys say?

**Comment by PabloCastellano** [comment]
I really like its simple design

**Comment by kskarthik** [comment]
`Tor` friendly :wink:

**Comment by ollieparanoid** [comment]
It's live now: https://postmarketos.github.io
If someone wants to change something, simply make a PR.

**Comment by dhruvkar** [comment]
Site is also live (via a fork on netlify) at https://www.postmarketos.org/

**Comment by ollieparanoid** [comment]
Cool! Will the fork get updated automatically, when something gets changed?

**Comment by dhruvkar** [comment]
I'm using https://github.com/1egoman/backstroke#how-it-works to inform me of changes to the repo, so it's a one-click, but manual process to update the fork.

**Comment by ollieparanoid** [comment]
@dhruvkar: Could you push it to `postmarketos.org`? Thanks!

**Comment by dhruvkar** [comment]
@ollieparanoid done

**Comment by ollieparanoid** [comment]
...and again please :)

**Comment by kskarthik** [comment]
@ollieparanoid postmarketos.github.io or postmarketos.org  which is official? If the latter one is yes, then we can rename repo to website-source or something like that so that visitors won't confuse with two domains hosting the same  content

**Comment by ollieparanoid** [comment]
`postmarketos.org` is the shorter domain, and it is a mirror of `postmarketos.github.io`. So if it is in snyc, it is "official" as well. We can't rename the repository, or hosting on GitHub won't work.

**Comment by dhruvkar** [comment]
@ollieparanoid done again 👍

**Comment by bhush9** [comment]
@ollieparanoid you can however put CNAME file in the repo of `postmarketos.github.io` so you don't have to manually sync or mirror the other website..

**Comment by ollieparanoid** [comment]
@bhush9: As I understand, `https://` will throw a warning then, which isn't ideal either. (Or am I misinformed here?). Thanks for the idea!

**Comment by kskarthik** [comment]
Netlify solves https:// problem with github custom domains & also builds, updates the site whenever there is new commit pushed.

**Comment by dhruvkar** [comment]
yup, which is what we're using right now.

**Comment by kskarthik** [comment]
Good! In that case we necessarily don't need the github subdomain active....

**Comment by ollieparanoid** [comment]
@dhruvkar, could you pull the source again (maybe automatize this?)  (#268)
Thanks!

**Comment by dhruvkar** [comment]
@ollieparanoid pulled & merged. I'll look into a way to automate it further.

**Comment by ollieparanoid** [comment]
@dhruvkar: could you update it again? Also can I help with automatizing this? Seems like Netlify has a webhook we could call from GitHub on new pushes, would that work?
https://www.netlify.com/docs/webhooks/

**Comment by dhruvkar** [comment]
@ollieparanoid I've regenerated the site. If you have the energy/time please go for it! 
These last two months have been overly busy, I apologize.

**Comment by ollieparanoid** [comment]
No problem, this is a free time project and that you set up the hosting in the first place and registered the domain has already helped a lot!

@MartijnBraam: so I guess it would make sense, if we moved the homepage to the same server as `wiki.postmarketos.org`, so we can re-generate it automatically with a push-hook. Could we work on that together? And if so, could you please open up a new issue so we can discuss it there with everyone? This one is long enough and it is a different topic after all. Thanks!

**Comment by MartijnBraam** [comment]
Opened issue about hosting migration on https://github.com/postmarketOS/postmarketos.github.io/issues/19
