### ISSUE TITLE
Enable networking service in postmarketos-base

### ISSUE THREAD

**Issue by drebrez** [postmarketOS/pmbootstrap#1000]
What you think about enabling the `networking` service directly in the `postmarketos-base` package?
At least with:
```
auto lo
iface lo inet loopback
```
and devices with a working wifi can add the `wlan0` interface (like it's already done in some devices: sony-castor_windy, lenovo-karate,...) or the `eth0` for the qemu packages.

In `postmarketos-base` there is `chronyd` enabled but it's not working without the `networking` service enabled

**Comment by drebrez** [comment]
@ollieparanoid I've worked on this few weeks ago but I had a blocking issue. Adding the `lo` setting in the `postmarketos-base` package and enable the networking service is fine, the problem is with the device packages to also add/edit the `/etc/network/interfaces` file. 
The problem is that the device package is installed before the postmarketos-base package, hence the post.install scripts are executed in the "wrong" order.
Any suggestion?

**Comment by ollieparanoid** [comment]
Thanks for looking into this!

We could force the `postmarketos-base` package being installed before the device packages by letting all device packages depend on `postmarketos-base` - how about that?
Then we could install `/etc/network/interfaces` in `postmarketos-base`, and make the devices modify that file in `post-install` if necessary.

To make sure that this is always the case for device packages, I would recommend to add a check in `pmbootstrap` and/or Travis of some sort. Maybe `pmbootstrap device_check`, that verifies the device package, and that gets executed in Travis (on all devices) as well when doing any `pmbootstrap` action except for `init` with the current device.

**Comment by drebrez** [comment]
@ollieparanoid I was thinking the same but I wasn't sure about adding that dependency just for that. I was also considering to split the `install_packages` variable [here](https://github.com/postmarketOS/pmbootstrap/blob/bdeec7a2557ab27b1b6d916c27a8b0806b8873bb/pmb/install/install.py#L306) and call `pmb.chroot.apk.install` multiple times, first the `pmb.config.install_device_packages` then the rest (or even split further, device/ui/extra/...)

**Comment by ollieparanoid** [comment]
Well, it's some work to do it that way. But it seems cleaner to me to use the existing dependency mechanism instead of emulating it with installing one package after the other in Python code.

To make the checks easier to implement, we could also check at install time if the device package depends on `postmarketos-base`, and raise an error if it does not.

**Comment by drebrez** [comment]
Now that the device packages depends on the `postmarketos-base` it should be possible to implement it like I tried at the beginning.
I will work on it in the next days 👍

**Comment by drebrez** [comment]
Closing since we now have `networkmanager`, so this is not necessary anymore.
