### ISSUE TITLE
Proprietary GLES library implementations

### ISSUE THREAD

**Issue by rrooij** [postmarketOS/pmbootstrap#1003]
# The problem and dilemma

A lot of phones provide proprietary libraries for 3D acceleration with OpenGL ES, similar to the Raspberry Pi. Of course, I would love to see a working free software implementation, but I don't think this is feasible in the short-term. Building against those libraries would improve performance for interfaces like Hilton or plasma-mobile a lot, maybe enable fast video playback with mpv etc.

However, our goal should be to liberate our devices. So I understand that something like this would not be a good option.

As far as I understand, we would need a separate APKBUILD for every device if we want to link them against the proprietary GLES implementation. This would be a little bit troublesome, since a lot of phones would get a seperate APKBUILD for packages like plasma-mobile.

# Proposal

My proposal is to store a variable called `_GL_LIBS` somewhere which the APKBUILDS read from to compile against those proprietary libs.

**Comment by rrooij** [comment]
Thanks for your comment! If libhybris solves this issue, then it is indeed a duplicate. I never knew that this was in progress. I'm glad it is doing well.

**Comment by ollieparanoid** [comment]
@NotKit commented to this issue:
> I suppose it's a bit different issue from libhybris, as some devices have Linux GLES libraries avaiable for them (mainly Mali-400 based Rockchip/Allwinner tablets) 
> software doesn't need to be linked against them specifically though
