### ISSUE TITLE
Most devices need mesa-dri-swrast, but we don't install it yet. How to proceed?

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#1013]
Most devices do not have 3d acceleration yet, so almost all of them would need to install `mesa-dri-swrast` when `mesa` is installed:

```shell
subpackages="$pkgname-mesa"
mesa() {
	install_if="$pkgname mesa"
	depends="mesa-dri-swrast"
	mkdir "$subpkgdir"
}
```
Currently for `armhf`, the package is `3.15` MB in size, and `7.47` MB when installed ([source](https://pkgs.alpinelinux.org/package/edge/main/armhf/mesa-dri-swrast)).

But most devices don't have it, so Hildon for example will not work out of the box for them.
I think we have two options:
a) add this block to all devices, that do not have 3D acceleration, and add it to the `aportgen` code, so it is there by default for new devices
b) add this block to `postmarketos-base` and remove it from all device packages that currently have it

What does everybody think about it?

**Comment by drebrez** [comment]
Solution A requires a bit of work at the beginning, but for new devices the aportgen will simplify it.
For solution B I don't understand how can you remove it, and in the long term would be strange that you have to disable/remove default stuff, no?
So for me I vote for solution A.

**Comment by ollieparanoid** [comment]
Solution B means, that you can't remove it at all and we always ship it. But I agree with you, that isn't nice.

**Comment by lawl** [comment]
I might possibly misunderstand the issue here, but couldn't we just create a 'meta' package, say `swrast`, that depends on `mesa-dri-swrast` (to have that layer of indirection in case mesa-dri-swrast is not be the package for it anymore in the future). And then have the device package simply depend on that (`swrast`)?

That would seem to be like the nicest solution to me and the wording fits perfectly too, this device depends on a software renderer.

**Comment by ollieparanoid** [comment]
That meta package could make sense when we have something from [here](https://wiki.postmarketos.org/wiki/Software_OpenGL) packaged, but *right now* it would only add one level of indirection without any benefit so I would recommend against it.

We can directly depend on `mesa-dri-swrast` as well, and then we don't need the whole block I wrote down in the initial post. But the idea is that `mesa-dri-swrast` only gets installed when you install `mesa` - so you won't have the package when you install postmarketOS without any interface for example. So if you put it directly in `depends` it's kind of against *shipping packages not everyone needs*.

**Comment by lawl** [comment]
All smartphones have a display, So shipping utilities to use that display by default seems okay to me. You could also argue to not install WiFi firmware by default because someone might only use GSM.

I guess really the question here is what your vision for pmOS is. Do you want it to be arch/gentoo/void or *buntu.

Personally I don't like depending directly on `mesa-dri-swrast` because you say "i need this specific package" and not "i need a software renderer", and you might need to change all device packages at some point in the future then, but i don't really have strong feelings about that either way.

I just **really** dislike boilerplate. Boilerplate is a symptom of a system lacking an abstraction imo.

**Comment by ollieparanoid** [comment]
@lawl: Thanks a lot for sharing your thoughts!

### My vision?
> I guess really the question here is what your vision for pmOS is. Do you want it to be arch/gentoo/void or *buntu. Both are perfectly fine choices.

Personally I would like a design that does not drag in unnecessary dependencies, just because the user *might* need it. So it is still possible to build a minimal system that only does what you want it to do (that'd be arch/gentoo/void?).

But for casual users I would like to have a reasonable default install, that includes stuff you would expect on a modern phone (full UI, browser, camera, calendar, contacts book, flashlight function, ideally the matrix crypto dialer from Librem 5 etc. -- so that would be *buntu in your categorization). But that's for the future.

### Comments on your proposal
I have sort of answered you already, but after letting some time pass and thinking about it again, I've changed my opinion about one half. So I hope you don't mind if I boil it down and answer in detail. If I understood you right, you proposed two things:

**1. Directly depend on the swrast implementation in the `device-*` packages, instead of the `install_if` block (that only installs the swrast implementation when mesa is installed):**
  * That saves some boilerplate (the `install_if` lines) in trade for always installing the swrast implementation, even for the untypical case of not installing a graphical environment (UI=none in init). 
  * This is basically solution a) from above, but without the `install_if` lines
  * After thinking some time about it, I think this is a better trade-off than solution a)! :+1:

**2. Abstract the swrast implementation by using a meta-package.**
  * While I understand your reasoning, with this one I don't quite agree:
    * We don't have any alternative to `mesa-dri-swrast` packaged yet, so wrapping it now *increases* boilerplate instead of reducing it
    * When we *do* have an alternative, it could be that it does not work for all devices.
    * Changing the mesa-dri-swrast in all dependency in all device packages at once can be done with a sed-one-liner

### Moving forward
If it's okay for the majority I would make a PR that adds `mesa-dri-swrast` to the depends of every device package that needs it (and replaces the `install_if` mesa section where we've added it already). So it's solution a) from above with modification 1. from @lawl.

Is that acceptable, folks?

**Comment by ollieparanoid** [comment]
@lawl just wrote me regarding this issue:
> yeah that seems fine to me, i just wanted to share my concerns, i don't have too strong feeligs either way :P

**Comment by bhush9** [comment]
I might be (SUPER) late to party but... umm I want to approch this issue slightly differently. my idea is, Let UI selection handle that, if `none` is selected, pmbootstrap will not add swrast package, similarly if plasma-mobile is selected, add the swrast? depending swrast from device package looks bit weird to me, as this will require changes to all device packages when we want to change something...

**Comment by PureTryOut** [comment]
Well, we could have an `install_if="$pkgname postmarketos-ui-plasma-mobile"`. However, if a device *does* have hardware acceleration, like the Castor on non mainline, we should *not* install `mesa-dri-swrast` (which is why we can't *always* add it if a UI is selected).

**Comment by bhush9** [comment]
No, you can install swrast driver even if hardware acceleration is working

**Comment by drebrez** [comment]
I also don't really like this approach, but I think it's the simplest solution for the moment.
Once someone manages to have hardware acceleration on the device, simply removes the `mesa-dri-swrast` package from the device.

**Comment by ollieparanoid** [comment]
The `mesa-dri-swrast` dependency idea is implemented now, but we still can replace it with a better solution.

> depending swrast from device package looks bit weird to me, as this will require changes to all device packages when we want to change something...

But the information whether a device needs software rendering or not is device specific, right? So to me it doesn't feel that wrong to put it in the device page.

There could even be the case that some devices work better with let's say `mesa-dri-swrast` and others work better with `tinygles` or `swiftshader` or whatever other implementation we have.

Maybe I don't quite understand what you mean with "when we want to change something..." - do you mean the software rendering implementation, or something else?

> No, you can install swrast driver even if hardware acceleration is working

Then we could have added it to `postmarketos-base` and be done with it, so it just gets installed everywhere. With the solution we have now, we don't install it for devices working with freedreno or other non-software-rendering drivers.

I see it like @drebrez, I don't think this is the perfect solution, but the simplest one - and this was kind of an important issue to get plasma etc. starting out of the box with software rendering. So please keep on suggesting better ideas - as long as the benefits outweigh possible drawbacks I think it's great if we replace what we have now with the new solution.
