### ISSUE TITLE
Telnet into initramfs doesn't work with --nofde

### ISSUE THREAD

**Issue by lawl** [postmarketOS/pmbootstrap#1019]
Telnet get's immediately killed again when running with --no-fde and the device boots normally, leaving no time to actually inspect the initramfs. With FDE the init script blocks [here](https://github.com/postmarketOS/pmbootstrap/blob/master/aports/main/postmarketos-mkinitfs/init.sh.in#L42).

Without, we run right past that and immediately kill it again [here](https://github.com/postmarketOS/pmbootstrap/blob/master/aports/main/postmarketos-mkinitfs/init.sh.in#L47).

Not sure what a sane default behaviour would be. block while telnetd is still running and then document that you have to killall telnetd via telnet to resume the boot process?

**Comment by ollieparanoid** [comment]
Thanks for reporting! We already have an issue about waiting in the initramfs when the usb-shell hook is installed here: #885
