### ISSUE TITLE
timestamp based rebuilds thinks everything needs to be rebuilt after "git merge" instead of "git rebase"

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#1023]
@MoreRobustThanYou wrote:
> here's the verbose output for ```pmbootstrap -v build binutils-armhf```: https://pastebin.com/KaSUiQuz

You have the timestamp based rebuilds feature enabled, in which we ask git how much has changed in your aports folder when compared to `origin`. Usually that should only be what you are working on, e.g. a few APKBUILDs or python files at most. But in your case, there are tons of files.

This is how I think most people use git with `pmbootstrap`.

Initial clone:
```shell
git clone https://github.com/postmarketOS/pmbootstrap
cd pmbootstrap
git remote add git remote add -f MoreRobustThanYou git@github.com:MoreRobustThanYou/pmbootstrap
```

Updating `master` (which points to `postmarketOS/pmbootstrap`):
```shell
git checkout master
git pull
```

Updating your repo:
```shell
git fetch MoreRobustThanYou
```

Workarounds:
* Disable timestamp based rebuilds
* Clone the repo as described above

Some questions to help debugging this:
* How did you setup your repo?
* How do you integrate new changes? (you mentioned merging them?)

**Comment by ollieparanoid** [comment]
rroij reported the same issue in #postmarketOS along with this log of `pmbootstrap install -v`: http://lpaste.net/raw/517125057554677760

Just like in @MoreRobustThanYou's log, the list after "(006749) [22:15:17] % cd /home/my_pc_user/git/pmbootstrap && git diff --name-only origin" is very long.

I understand the problem now. `pmbootstrap` expects that you rebase on master when updating the source in your branches. But in both your cases you guys run `git merge master`, after which `pmbootstrap` can't properly detect what you have changed compared to `master` anymore and thinks that everything was modified.

My approach to fix this is better documentation in the porting guide.

@MoreRobustThanYou: you could either change the way you use git (`rebase master` instead of `git merge`) or disable timestamp based rebuilds in `pmbootstrap init`.

**Comment by rrooij** [comment]
It would be nice to see this fixed. I prefer merging because I have to commit or stash my working tree when using git rebase.

**Comment by ollieparanoid** [comment]
I can look into this some time after the blog post has been released - for now I recommend to disable timestamp based rebuilds if you use `git merge`. Just remember to `pmbootstrap build --force` all packages you have modified.
