### ISSUE TITLE
Nexus 7 2012

### ISSUE THREAD

**Issue by computer777** [postmarketOS/pmbootstrap#1024]
With pmbootstrap got clone today when executing pmbootstrap flasher flash_system the error I get is - command failed (native) % fastboot -I ' ' flash system ....

**Comment by PureTryOut** [comment]
Please run `pmbootstrap log` in a separate terminal and post the log it outputs when running the failing command. Also please join our IRC or [Matrix room](https://matrix.to/#/#postmarketos:disroot.org) for quicker help.

**Comment by PureTryOut** [comment]
Since we have not received any more information from you, and you haven't yet joined our Matrix/IRC room, I'm closing this for now. Please re-open if you have more information.
