### ISSUE TITLE
Replace v4l rules workaround with proper solution

### ISSUE THREAD

**Issue by bhush9** [postmarketOS/pmbootstrap#1033]
All it needs is

```
sudo ln -s /dev/null /etc/udev/rules.d/60-persistent-v4l.rules
```

**Comment by ollieparanoid** [comment]
Thanks for sharing! Will this make the booting delay go away on the hammerhead?

**Comment by bhush9** [comment]
Yes

**Comment by bhush9** [comment]
https://github.com/Halium/lxc-android/tree/master/etc/udev/rules.d

In general on Android devices you may want to mask more use rules like this..

(Ignore firmware.rules, it's halium specific given we run ueventd inside container)

**Comment by ollieparanoid** [comment]
I am uncertain if that rule should be added to all devices (`postmarketos-base` package) or only to devices which had the `v4l` hack enabled.

Could you explain a bit what the rule does, and if this would interfere with getting the camera working one day?

**Comment by bhush9** [comment]
This should be added in devices which run android kernel and possibly are qcom devices, there /dev/video* devices mostly require the camera binary blobs and android camera service to function, so they will not work with generic linux v4l tools.

But yeah, it makes no sense to add v4l rules in `postmarketos-base`

**Comment by ollieparanoid** [comment]
Thanks! So I'm focusing on the blog post right now - if someone wants to tackle this in the meantime, these are the devices that need to be updated:
```shell-session
$ cd pmbootstrap/aports
$ grep -r "v4l" device/device-* | cut -d '/' -f 2 | sort -u
device-lg-hammerhead
device-lg-mako
device-motorola-titan
device-sony-yuga
```
