### ISSUE TITLE
Ability to export 2nd boot partition and rootfs in seperate image files

### ISSUE THREAD

**Issue by bhush9** [postmarketOS/pmbootstrap#1049]
On hammerhead mainline somehow one partiton with sub partition doesn't work properly so I need to flash boot image to system partition and rootfs to userdata.. I do it manually currently but would be lovely if `pmbootstrap export` offered way for it

**Comment by drebrez** [comment]
Is it really necessary? seems like a workaround.

**Comment by ollieparanoid** [comment]
I think this is a good thing to support, as it helps @bhush9's use case and also allows to boot the postmarketOS rootfs without using our initramfs. Yes, it's a workaround, but `pmbootstrap` should make development as easy as possible in my opinion, and that includes helping people working on mainlining devices where certain features are broken at the moment.

@drebrez idea with adding a parameter to `install` so we don't build the full image and split it later sounds logical to me. `export` would provide symlinks for the split files, just like it provides symlinks for the whole image now.

**Comment by drebrez** [comment]
Workaround: https://wiki.postmarketos.org/wiki/Mainlining_FAQ#How_to_flash_each_postmarketOS_partition_from_the_rootfs_to_a_different_partition_on_the_phone
