### ISSUE TITLE
Docker os

### ISSUE THREAD

**Issue by schvabodka-man** [postmarketOS/pmbootstrap#1064]
Will there be any docker images with PmOS? There is already qemu based stuff, but it would be really good to see a possibility of using it inside of docker container(terminal server for phones, for example).

**Comment by PureTryOut** [comment]
postmarketOS is basically just Alpine Linux with some phone specific packages. Since Alpine Linux is already really popular in the Docker world, I don't see why we would make our own image for it.

**Comment by PabloCastellano** [comment]
@schvabodka-man I don't see why is useful building the pmOS images for Docker. Can you elaborate on the possible scenarios?

The only scenario I can think using Docker is beneficial is when building pmOS itself.

**Comment by schvabodka-man** [comment]
I would make attempt to package pmos releated stuff(hildon, sdl keyboard, etc) using base alpine linux image, and i see if everything will work good(but image will be most likely x86-only). 

Usecase:
I want myself a 'remote desktop' server. One docker container as desktop, one for mobile stuff. First is accessed from my pi's and thinkpads, second from n900 and jornada(personal 'cloud' workspaces accessed using x2go/freenx).

**Comment by ollieparanoid** [comment]
That's an interesting usecase! To turn Alpine into postmarketOS:
* Install Alpine Linux
* Add this mirror to the top of `/etc/apk/repositories`:
```
http://postmarketos.brixit.nl
```
* Install the packages for the device and UI you want to have, for example:
```
apk add -u postmarketos-base device-nokia-rx51 postmarketos-ui-hildon
```

**Comment by ollieparanoid** [comment]
Looks like this is answered. If it is not, just reply here 👍
