### ISSUE TITLE
Don't allow pmbootstrap to run as root

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#1065]
We use sudo when we need to run commands as root. Two people have run pmbootstrap as root today and screwed up their work folder permissions that way, it would be better if we checked for this.

**Comment by PabloCastellano** [comment]
What option do you think is better?

1. Just don't allow running pmbootstrap as root
1. Allow running pmbootstrap as root if some flag like `--allow-root` is specified

I'd go for the second but would like to hear more opinions first

**Comment by PureTryOut** [comment]
About 2, why would somebody need to run pmbootstrap as root? Like @ollieparanoid said, it'll use sudo when it needs to. I'd say we just forbid running it as root altogether.

**Comment by lawl** [comment]
There is a usecase for this, when people refuse to run sudo, e.g. the OpenBSD people who decided `sudo` is bloated and full of bugs and wrote `doas` instead. I used to run my gentoo systems without sudo too.

I don't really mind this change as I have `sudo` in my pmOS dev box, just to bring in a different perspective.

**Comment by Matt07211** [comment]
I have not run it as root, have a look at my comment here. https://github.com/postmarketOS/pmbootstrap/issues/1066#issuecomment-354647212

**Comment by ollieparanoid** [comment]
@Matt07211: thanks for clearing that up!

I think the check would still be useful. The use-case for actually running it as root I can think of is, when you quickly want to try something out, so you install something like Arch Linux in a VM (which comes without an user account and sudo by default) and then you want to run `pmbootstrap` there. Might be a bit far fetched, and I don't think this has a great impact, but I would prefer if we added the `--as-root` flag.
