### ISSUE TITLE
Pmbootstrap uses wrong compiler (?)

### ISSUE THREAD

**Issue by OctoNezd** [postmarketOS/pmbootstrap#1069]
[Here is my APKBUILD](https://gist.github.com/OctoNezd/c47a9360d862d15c734c93e5f1deac7f)

[And here is log](https://gist.github.com/OctoNezd/17537c7fac820e9aaf4728b4c59a63c3)

[By googling this error, I found out that the wrong compiler is being used](https://lists.linaro.org/pipermail/linaro-toolchain/2014-May/004254.html)

**Comment by OctoNezd** [comment]
And when I do `HOSTCC="aarch64-alpine-linux-musl-gcc ${CROSS_COMPILE}"`, I get a different error:
```
/home/pmos/build/src/android_kernel_leeco_msm8976-71d6189dbc7f8ece64c4f876f61ff2cafead7a3d/scripts/basic/fixdep.c:106:23: fatal error: sys/types.h: No such file or directory
 #include <sys/types.h>
                       ^
compilation terminated.
```

**Comment by Halamix2** [comment]
The first error is `ld: unrecognized option '-Wl,--as-needed'`, it may be the source of the problem

**Comment by PureTryOut** [comment]
It *is* the source of the problem. Next time, if you have errors, please try the build again with `-j1` (like `pmbootstrap -j1 build --strict linux-****-****`). This will tell pmbootstrap to only compile with 1 core, causing the error to show up last in the log. Without it, the other cores still have to finish their jobs before the full build is cancelled, causing a lot of unnecessary log under the error.

**Comment by OctoNezd** [comment]
But where it is located? I cant find anything in sources what contains `ld --as-needed`

**Comment by OctoNezd** [comment]
And I am not building, only trying to run `menuconfig`

**Comment by Halamix2** [comment]
Cannot reproduce this error
 [My attempt (my content of linux-leeco-s2](https://gist.github.com/Halamix2/2b7f1d139c2b8e7fdb91511f65c41a95)

**Comment by ollieparanoid** [comment]
> But where it is located? I cant find anything in sources what contains `ld --as-needed`

This is probably, because it gets called a bit differently, you could try to search for `--as-needed` only. But since @Halamix2 couldn't reproduce the error, what happens if you use his `APKBUILD`?

If you can't get it working, please post the full `linux` and `device` aports (e.g. fork `pmbootstrap` on GitHub and commit them to a new branch there).

**Comment by OctoNezd** [comment]
His APKBUILD worked, but wont compile with assembly error. I suppose this issue can be closed.

**Comment by Halamix2** [comment]
However I've got another error:
```
/tmp/ccpcJjIl.s: Assembler messages:
/tmp/ccpcJjIl.s:22: Error: .err encountered
/tmp/ccpcJjIl.s:23: Error: .err encountered
/tmp/ccpcJjIl.s:24: Error: .err encountered
/tmp/ccpcJjIl.s:52: Error: .err encountered
/tmp/ccpcJjIl.s:53: Error: .err encountered
/tmp/ccpcJjIl.s:54: Error: .err encountered
make[1]: *** [scripts/Makefile.build:308: arch/arm64/kernel/psci.o] Error 1
```
patch 02 may be fixing only symptoms, not the source of the problem (R_METAG_ADDR32 should be defined either way, the only file that defines EM_METAG defines also R_METAG_ADDR32  and R_METAG_NONE )
