### ISSUE TITLE
odin export fails, because it runs "rmdir /tmp/odin-flashable-tar" and the folder is not empty

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#1072]
Reported by tikh_av89 on IRC:
```
(005606) [12:05:37] (rootfs_samsung-lt013g) % rmdir /tmp/odin-flashable-tar 
rmdir: '/tmp/odin-flashable-tar': Directory not empty 
```

**Comment by drebrez** [comment]
@ollieparanoid I've just tried it after zapping the chroot and `pmbootstrap export --odin` works fine. Maybe in a previous run it failed and something has not been cleaned correctly in that folder

**Comment by ollieparanoid** [comment]
How about we `rm -r` it to handle a previous failure better?

**Comment by ollieparanoid** [comment]
After looking at the code, it should really not fail when using `rmdir`, so if we used `rm -r` instead we would just cover whatever other bug happened here. I don't think we should replace `rmdir`.

I've ran it as well and can not reproduce it either.
Closing until someone can reproduce it - in that case, please:
* attach the "pmbootstrap log" output
* check what is inside the temp folder: `ls ~/.local/var/pmbootstrap/chroot_rootfs_samsung-lt013g/tmp/odin-flashable-tar` (adjust work folder and device name)

**Comment by ollieparanoid** [comment]
@drebrez wrote in the chat:
> FYI, sometime ago there was someone that mentioned the generated odin tar wasn't working. the same issue I have it with the samsung S5.
In pmbootstrap we create the files <partition>.bin.md5 with the md5sum appended at the end of the file itself, then all the files packaged in a tar.md5 with the md5sum of the tar appended.
The second part (tar.md5 with the appended md5sum) I suppose it's standard for every device.
But the files inside, specifically for the Samsung S5 they have to be named <partition>.img and without the appended md5.

**Comment by drebrez** [comment]
Ttikh_av89 wrote in the chat:
> I agree with drebrez[m]. I guess that time I didn't zap it.

@ollieparanoid do you this we should anyway add a `rm -r` to clean a previous run? I would say at the beginning when we create the temporary folder.
For your last quote about the different odin tar format I think it's better if we open a separate issue and try to gather some additional info about the various formats for the various devices or odin versions

**Comment by ollieparanoid** [comment]
> do you this we should anyway add a `rm -r` to clean a previous run? I would say at the beginning when we create the temporary folder.

That sounds good! I thought the quote was related to this issue, you're right it makes more sense to split that part off into a new issue.
