### ISSUE TITLE
Custom (pmOS specific) configuration for each GUI

### ISSUE THREAD

**Issue by moondeck** [postmarketOS/pmbootstrap#1098]
When solving https://github.com/postmarketOS/pmbootstrap/issues/464 i found out that even though they should, not all desktop environments use /usr/share/wallpapers for wallpapers, and it had me thinking that we should have some sort of pmOS specific configuration for each DE. Perhaps that could be a package like postmarketos-branding (like openSUSE's SUSEstudio)?

**Comment by PureTryOut** [comment]
We already have that for stuff like Xfce and Mate, in their respective meta packages (e.g. `postmarketos-ui-xfce` and `postmarketos-ui-mate`). They make panels, icons, etc bigger and such. Or are you thinking of something else? I'm not sure what it has to do with `/usr/share/wallpapers`...

**Comment by moondeck** [comment]
Yes, that is what i am talking about. Can these config files make UIs point to a common directory for wallpapers? @ollieparanoid found out in #464 that ` /usr/share/wallpapers` is what DEs should be using, but i found that it is not true, at least for XFCE.

**Comment by moondeck** [comment]
I have packaged wallpapers, so they get fetched from the artwork repo, and then extracted to /usr/share/wallpapers

**Comment by PureTryOut** [comment]
Probably... Using Xfce myself, I can just point it to any folder. I assume that can be set in a config file as well.

**Comment by ollieparanoid** [comment]
@moondeck: when the `postmarketos-artwork` PR is through, you could adjust the [default XFCE4 config we ship](https://github.com/postmarketOS/xfce4-phone) to use that folder, and to set a postmarketOS wallpaper by default if you want 👍

**Comment by drebrez** [comment]
@moondeck @ollieparanoid what exactly is the issue in this thread? is it for having the postmarketOS wallpaper as default in every DE? In this case I suggest renaming the title and start tracking which DE doesn't have it yet.

**Comment by ollieparanoid** [comment]
I think that was the intention originally. But since that isn't really clear, and the conversation above is dated: how about starting a new issue instead of renaming this one?

@moondeck: is that okay with you?

**Comment by moondeck** [comment]
Sure, it's okay, sorry for the confusion. I can't work on the issue at the moment though.
