### ISSUE TITLE
Nexus 7 2012 (asus grouper) Plasma Mobile too big for system partition

### ISSUE THREAD

**Issue by jambonmcyeah** [postmarketOS/pmbootstrap#1108]
The system partition is around 602MB and the image built with plasma-mobile is around 700MB

**Comment by z3ntu** [comment]
Time for putting stuff on the data partition?

**Comment by jambonmcyeah** [comment]
how to put stuff in the data partition?

**Comment by PureTryOut** [comment]
Yeah this is exactly why we want to use LVM, the system partition is often just too small for such a, relatively, large DE.

That said, on the Amami, flashing Plasma with fastboot gives this error, while flashing through TWRP works fine. Have you tried that?

**Comment by drebrez** [comment]
@jambonmcyeah you can choose which partition to use when flashing:
example:
```
pmbootstrap flasher flash_system --partition userdata
```

**Comment by ollieparanoid** [comment]
I've added this information to the [installation](https://wiki.postmarketos.org/wiki/Installation_guide#pmbootstrap_flash) and [porting guide](https://wiki.postmarketos.org/wiki/Porting_to_a_new_device#Flashing), so it should be easier to find in the future. 👍
