### ISSUE TITLE
Porting device Amazon Fire Gen 5

### ISSUE THREAD

**Issue by acocalypso** [postmarketOS/pmbootstrap#1117]
I wanted to port this project over to my Amazon Fire Gen 5 with the codename FORD

All I get after typing:
```
./pmbootstrap.py init
Device [samsung-i9100]: Ford
ERROR: Input did not pass validation (regex: [a-z0-9]+-[a-z0-9]+). Please try again
```

Anything wrong with the codename?

**Comment by acocalypso** [comment]
issue closed. my fault.

**Comment by fastriker** [comment]
Hello @acocalypso,

did you have any luck?

**Comment by acocalypso** [comment]
Not really and its currently ON ICE in my side

**Comment by fastriker** [comment]
Ok, thx for trying and your fast reply!
