### ISSUE TITLE
Tests fail if there is no aport for the curent device

### ISSUE THREAD

**Issue by MayeulC** [postmarketOS/pmbootstrap#1128]
I don't exactly know how to put it... But look at the logs.
I last worked on the device "sony-seagull", then switched branch to work on something else and run the tests. pmbootstrap remembered my choice, but it seems that it is confused by the non-existent device information.

Proposed solution: store the suggestions, run the tests and restore them. There might be another, easier way.

```
test/test_build_is_necessary.py:34: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pmb/parse/arguments.py:388: in arguments
    setattr(args, "deviceinfo", pmb.parse.deviceinfo(args))
_ _ _ _ _ _ _ _ _ ___ _ _ _ _ _ _ _ _ _ _ _ _ 

args = Namespace(action='chroot', alpine_version='edge', aports='/run/media/mayeul/DATA/postmarketos/pmbootstrap/aports', arc...rope/Paris', ui='weston', user='pmuser', verbose=False, work='/run/media/mayeul/DATA/postmarketos/pmbootstrap_workdir')
device = 'sony-seagull'

    def deviceinfo(args, device=None):
        """
        :param device: defaults to args.device
        """
        if not device:
            device = args.device
    
        if not os.path.exists(args.aports):
            logging.fatal("Aports directory is missing")
            logging.fatal("Please provide a path to the aports directory using the -p flag")
            raise RuntimeError("Aports directory missing")
    
        aport = args.aports + "/device/device-" + device
        if not os.path.exists(aport) or not os.path.exists(aport + "/deviceinfo"):
            logging.fatal("You will need to create a device-specific package")
            logging.fatal("before you can continue. Please create at least the")
            logging.fatal("following files:")
            logging.fatal(aport + "/APKBUILD")
            logging.fatal(aport + "/deviceinfo")
>           raise RuntimeError("Incomplete device information")
E           RuntimeError: Incomplete device information

pmb/parse/deviceinfo.py:43: RuntimeError
------------ Captured stderr setup ----------------
deviceinfo.py               38 CRITICAL You will need to create a device-specific package
deviceinfo.py               39 CRITICAL before you can continue. Please create at least the
deviceinfo.py               40 CRITICAL following files:
deviceinfo.py               41 CRITICAL /run/media/mayeul/DATA/postmarketos/pmbootstrap/aports/device/device-sony-seagull/APKBUILD
deviceinfo.py               42 CRITICAL /run/media/mayeul/DATA/postmarketos/pmbootstrap/aports/device/device-sony-seagull/deviceinfo
--------------------- Captured log setup -------------------
deviceinfo.py               38 CRITICAL You will need to create a device-specific package
deviceinfo.py               39 CRITICAL before you can continue. Please create at least the
deviceinfo.py               40 CRITICAL following files:
deviceinfo.py               41 CRITICAL /run/media/mayeul/DATA/postmarketos/pmbootstrap/aports/device/device-sony-seagull/APKBUILD
deviceinfo.py               42 CRITICAL /run/media/mayeul/DATA/postmarketos/pmbootstrap/aports/device/device-sony-seagull/deviceinfo
=================== 1 passed, 13 error in 2.28 seconds==================
```

**Comment by MartijnBraam** [comment]
An easy way is to run the tests with this script:

```bash
#!/bin/sh
cp -v ~/.config/pmbootstrap.cfg ~/.config/pmbootstrap.cfg.bak
./pmbootstrap.py config device qemu-amd64
yes "" | ./pmbootstrap.py init
python3 setup.py test
cp -v ~/.config/pmbootstrap.cfg.bak ~/.config/pmbootstrap.cfg
rm ~/.config/pmbootstrap.cfg.bak
```

this makes a backup of the current config and then switches the device to qemu-amd64 and at the and the backup is restored.

**Comment by ollieparanoid** [comment]
That would work! It seems a bit like a hack though, but on the other hand we can not specify the device throughout all testcases programmatically right now (we can set `args.device`, but sometimes we directly execute `./pmbootstrap.py` from the test cases).

Another idea would be checking if the current device is valid in `test/testcases_fast.sh` (which is what Travis CI also executes) before running any tests.

Any opinions on which of those is better (or new ideas)?

**Comment by MayeulC** [comment]
Mmm, how about adding an additional flag or environment variable like `--config`, PMBOOTSTRAP_CONFIG_FILE, or even `--use_config_file=" (depending on your preference).

This way, we retain compatibility with the current config file, still cover most of the code, and we can add additional tests to check the behavior governed by the config file :)

**Comment by ollieparanoid** [comment]
Actually there *is* a `--config` parameter already for `pmbootstrap` :wink: But using that flag in every test case is a lot more work than checking if the current device is valid before running the tests.

That is because we generate a new `args` variable in each test case file, so we would need to put the config there, and in some cases we start `pmbootstrap.py` directly, so we would also need to pass the config there -- and additionally we would need to store the test config somewhere.
