### ISSUE TITLE
Rename device-nokia-rm-696 to device-nokia-rm696 for consistency?

### ISSUE THREAD

**Issue by pavelmachek** [postmarketOS/pmbootstrap#1143]
We have device-nokia-rx51, and extra "-" in the name sounds little weird. If it is ok to rename I can prepare the pull request. (We could rename rx51 to rx-51, but I believe rx51 follows the other codenames better...)

**Comment by pavelmachek** [comment]
@filippz

**Comment by filippz** [comment]
Admittedly, that 3rd `-` doesn't feel right, but according to wikipedia/FCC the dash is part of devices codename (and n900 code name is in fact rx`-`51 according to same source). So for consistency either we rename rx51 to rx`-`51 or we rename rm`-`696 to rm696.
Also, I see nothing wrong in calling these N900/N9/N950 as opposed to rx-51/rm-696/rm-680 (or rx51/rm696/rm680) we're aiming for.

**Comment by ollieparanoid** [comment]
@MartijnBraam: You chose the `device-nokia-rx51` package name. What do you think?

**Comment by MartijnBraam** [comment]
I did choose for rx51 because I found `device-nokia-rx-51` weird. I also agree with @filippz that it might even be neater to call it n900 instead of rx-51.

We also have the case of the fairphone2 codename not being correct since it should be uppercase but I think its more important to have consitency than correctness

**Comment by ollieparanoid** [comment]
Alright, @pavelmachek, do you want to make a PR that changes the following?
* `device-nokia-rx51` -> `device-nokia-n900`
* `device-nokia-rm-696` -> `device-nokia-n9`

**Comment by pavelmachek** [comment]
Ok, I'll do the renaming.

**Comment by pavelmachek** [comment]
Done, pull request #1146.

-- 
(english) http://www.livejournal.com/~pavelmachek
(cesky, pictures) http://atrey.karlin.mff.cuni.cz/~pavel/picture/horses/blog.html
