### ISSUE TITLE
Hildon: Bad patch for missing titlebar on x86_64

### ISSUE THREAD

**Issue by freemangordon** [postmarketOS/pmbootstrap#1148]
https://github.com/postmarketOS/pmbootstrap/blob/0c3ce04a6209fd454b9c28798cea252d5ade1b55/aports/maemo/hildon-desktop/APKBUILD#L26 is not a correct fix, see https://github.com/maemo-leste/libmatchbox2/commit/50d64e6f204b00a7f13386febb62701511032d99, which is the reason for missing title bar.

Also, we'd appreciate if you open an issue on leste bugtracker next time you hit a bug in some of its packages.

**Comment by ollieparanoid** [comment]
When will the next `libmatchbox2` release get tagged, which includes this fix?

> Also, we'd appreciate if you open an issue on leste bugtracker next time you hit a bug in some of its packages.

Will do, thanks a lot for opening this issue!

**Comment by freemangordon** [comment]
It was released (as in tagged) before I opened the issue here, see https://github.com/maemo-leste/libmatchbox2/releases/tag/0.2.94

**Comment by ollieparanoid** [comment]
Oh, I've missed that. Awesome! :tada: 

@NotKit: do you want to prepare a PR that updates `libmatchbox2` and removes the patch from `hildon-desktop`?

**Comment by NotKit** [comment]
@ollieparanoid sure, will do. I wasn't sure if it was a bug in package or a bug due to musl vs glibc back then.

**Comment by freemangordon** [comment]
keep in mind that libmatchbox is statically linked in hildon-desktop, so make sure that you rebuild hildon-desktop against fixed libmatchbox
