### ISSUE TITLE
What to do about timestamp based rebuilds?

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#1167]
### Timestamp based rebuilds recap
Quoting the [50 days post](https://ollieparanoid.github.io/post/50-days-of-postmarketOS/#timestamp-based-rebuilds):
> `abuild` is the package building program from Alpine Linux, that `pmbootstrap` wraps around. Just like in most Linux distributions it considers packages up to date, when the [binary] package version is equal with the version of the package recipe. This has the side-effect, that package developers must pass `--force` to rebuild a package if they changed anything, but do not want to increase the version yet.
> [@mmaret [expected](https://github.com/postmarketOS/pmbootstrap/issues/69#issuecomment-307321715)] it to work like the classic [`make`](https://en.wikipedia.org/wiki/Make_(software)) build automation program, which means that **after modifying one file anywhere in the source tree, it automatically detects which packages are out of date and rebuilds them** [...]

### Three open bugs caused by this feature
As you know, I'm trying to fix all pmbootstrap bugs before working on new features. Of the [6 bugs](https://github.com/postmarketOS/pmbootstrap/issues?utf8=%E2%9C%93&q=label%3Abug+label%3Apmbootstrap+is%3Aopen+) we have right now, 3 bugs are in the timestamp based rebuilds feature:

* #1156 gtk+2.0-maemo-2.24.31-r3.apk is rebuilt in each and every build
* #1023: timestamp based rebuilds thinks everything needs to be rebuilt after "git merge" instead of "git rebase"
* #985: Binary repo hinders / confuses

(The other 3 bugs have PRs waiting for reviews, which directly resolve them or at least work towards resolving them.)

### Why is it so complicated?
Quote from https://github.com/postmarketOS/pmbootstrap/issues/1156#issuecomment-359954250:
> This seems easy at first, but in combination with `git`, when you switch branches or just cloned a repo, then the files will have newer timestamps than the binary packages. So pmbootstrap would think they need to be rebuilt.

> To work around this, we ask git to diff against current master, and only look at the files that have changed in regard to `master`. But this only seems to work correctly when using `git rebase` instead of `git merge` (and I'm not 100% sure of that even, need to investigate this more). This feature got even more complicated as the binary repo was introduced.

### Drop it?
Unfortunatelly I do not see a straight forward way to fix the issues. And because it is so complicated, it makes the code hard to maintain and PRs get really hard to review and understand.

I'm not saying this lightheartedly, because I spent a great deal of time to implement this in the first place. But what if we just dropped this feature and documented instead, that `--force` is necessary when not changing the version?

**Comment by drebrez** [comment]
@ollieparanoid I have to admit that I have disabled the feature for a while now and I am now used to adding the `--force` argument when I need to build a package.
I agree that it's quite complicated to detect the changes with git and the various fork/branches, so for me it's fine to drop it and make it clear that the `--force` is necessary to rebuild the same version.

**Comment by PureTryOut** [comment]
I have used `--force` for as long as I know it existed, also because in the beginning I was confused about the timestamp based rebuild function. It doesn't bother me at all that I have to use it, it becomes part of your standard workflow. Honestly, I'd say drop it. We seem to get more trouble from it than it's worth.

**Comment by mmaret** [comment]
@ollieparanoid I'm impress by your memory (And the work done so far btw :)).
As I haven't played with the BS for a long time, my opinion is not like from a "really user".

But anyway, for new incomers, it's easier to understand a BS that work like some others.
Things like Make or Bitbake got this rebuild if needed functionality.

Of course, they can have the issue of rebuilding everything because of a branch change. But, for Android AOSP for exemple, this is mitigated by:
* Having several small repository that won't all necessary change because of a branch modification
* use of CCACHE (but I remember that's already used here right ?)

So even if it could be a pain, people are use to it. And at the end of the compilation, you've got in binary what's in your current sources.

On another hand, I've already used some BS that are based on checksum (not on timestamp).  That could be a third solution....

**Comment by ollieparanoid** [comment]
> use of CCACHE (but I remember that's already used here right ?)

Yep.

> Having several small repository that won't all necessary change because of a branch modification

Basically all software packages in postmarketOS / Alpine are in different repositories (or tarballs). In fact we also have binary packages now, and that is what it makes complicated beyond the `git` specific stuff. Let's say the package build recipes on your disk have a very recent timestamp, and the related binary package from the binary repo has an older timestamp, although the version and package content is the same. Then it would be a bad user experience, if we built the package from source, because `pmbootstrap` should use the binary version to save the user compile time.

> On another hand, I've already used some BS that are based on checksum (not on timestamp). That could be a third solution....

I've thought about that as well. Let's say we save the checksums of all files involved with the `aport` stored right next to the `apk` binary packages, both locally and in the binary repository. Then we could check if the aport was modified at all before compiling it, even without asking `git` anything (`git` uses hashes internally anyway). So that sounds all nice and clean, but ...

...it makes it impossible to update `APKBUILD`s without increasing the `pkgrel`. And sometimes this is really desired: When you want to enable compiling a package for a new architecture, then it does not make sense to build it for all other architectures again, and require the user to download the packages. Nothing changed, it would only waste resources on all ends. For some packages like `qt5-qtwebengine` (which is a whole Chromium browser + some QT glue code), that really matters.

So that doesn't work either. We could introduce more ugly hacks on top of that, like hashing without the `arch=` variable. But that makes it even more complex and doesn't cover other cases where we might just want to change a comment in the `APKBUILD`.

I totally understand that having the build system detect changes in the aports lowers the bar a bit, because that is what people know from other build systems. My goal with `pmbootstrap` is, to make development of postmarketOS as easy as possible. But postmarketOS development is also maintaining and enhancing `pmbootstrap`, and if this small improvement for new users can only be bought with taking up massive technical debt through a feature that barely works, or only with lots of hacks and is hard to understand, then I do not think the trade-off is worth it.

**Comment by z3ntu** [comment]
To be honest, I really like the timestamp based rebuilds but yes, it seems that everything has a tradeoff with it... I say if it doesn't work properly, at least disable it (we don't have to remove the code just yet but at least don't make it accessible by normal users - until a solution is found).

**Comment by ollieparanoid** [comment]
I don't like the idea of keeping buggy code around just because someone else might fix it some day. In my experience, that never happens, especially when there is no solution in sight and when we disable it by default. The code paths would not get used, because we know they are buggy, so there would be even more bugs, because new changes are never tested with them (and test cases do not catch everything).

So I would remove it altogether.

We use a versioning system after all, so in case someone wants to fix this up and maintain it, it would be easy to find the code and integrate it again. To make it easier, I would [tag a release](https://github.com/postmarketOS/pmbootstrap/releases) just like we did it before all major code changes in `pmbootstrap`.

If this does not sound reasonable to anyone, please reply so we can discuss this further.

**Comment by z3ntu** [comment]
Sounds good.

**Comment by ollieparanoid** [comment]
Here is the tag: [0.4.0](https://github.com/postmarketOS/pmbootstrap/releases/tag/0.4.0)
