### ISSUE TITLE
Mount tmpfs in /dev folder in chroots

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#1175]
We need to have device nodes inside the chroots (which are inside the work folder configured in `pmbootstrap init`). It is possible to create them when the work folder is on an ext4 partition for example, but with lots of other file systems it not possible to create device nodes: ecryptfs, encfs, ntfs, virtualbox shared folders, fat32 and even btrfs (subvolumes only?) as I have just learned in the chat from @WilliamO7.

@MartijnBraam proposed, that we simply mount a devtmpfs inside the chroot's dev-folder, which sounds like a great solution!

@MartijnBraam: Does devtmpfs have an advantage here over tmpfs?

Related: #472

**Comment by MartijnBraam** [comment]
It looks like the difference between tmpfs and devtmpfs is that with devtmpfs the kernel automatically creates device nodes in them which we probably don't want for the chroot. I think we should use a regular tmpfs for it.

we should probably use something like `size=1M,noexec,dev` for the mount options

https://unix.stackexchange.com/questions/77933/using-devtmpfs-for-dev

**Comment by ethanrjones97** [comment]
Reproducible on ZFS as well.

**Comment by ollieparanoid** [comment]
@WilliamO7, @ethanrjones97 or anyone else being affected by this: I have created a patch in branch `feature/1172-tmpfs-in-chroot-dev-folder`. Could you try that out?

**Comment by ethanrjones97** [comment]
Sorry for the wait.
@ollieparanoid I think it worked? `pmbootstrap init` seemed to exit successfully.

**Comment by ethanrjones97** [comment]
I managed to port a device over with the patch applied, that seems to be a pretty good test :man_shrugging:
