### ISSUE TITLE
Nokia N900: minimize firmware dependencies

### ISSUE THREAD

**Issue by pavelmachek** [postmarketOS/pmbootstrap#1184]
linux-firmware may be removed from N900 dependencies. I have this firmware on N900:

./nokia
./nokia/bcmfw.bin
./smia-sensor-0c-208a-03.bin
./wl1251-nvs.bin
./bcmfw.bin
./ti-connectivity
./mt9p012-2802-10.bin
./smia-sensor-01-022b-04.bin
./smia-sensor-01-022b-00.bin
./et8ek8-0002.bin
./wl1251-fw.bin

I tried searching, and I don't think linux-firwmare contains any of that. So it looks to me like linux-firmware package is not needed for N900 at the moment.

**Comment by mirh** [comment]
TI's WiLink stuff is [here](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/ti-connectivity)
And also "bcm" stuff can likely be found in brcm folder.

**Comment by ollieparanoid** [comment]
`linux-firmware-ti-connectivity` has `wl1251-nvs.bin` and `wl1251-fw.bin`:

https://pkgs.alpinelinux.org/contents?file=wl1251-nvs.bin&path=&name=linux-firmware*&branch=edge&repo=main&arch=armhf

Using this search form, I can not find the other files. So `bcmfw.bin` is not there, but maybe you can use one of these files instead?

https://pkgs.alpinelinux.org/contents?file=&path=&name=linux-firmware-brcm&branch=edge&repo=main&arch=armhf

**Comment by mirh** [comment]
It it's actual broadcom firmware, opening it in hex editor (like [this](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/brcm/brcmfmac4329-sdio.bin)) can show original name. 

OF COURSE, for the love of me, I cannot state [enough](https://wiki.postmarketos.org/wiki/Firmware#Wi-Fi_modems) how much official desktop repos are more often than not outdated.

**Comment by ollieparanoid** [comment]
Closing this issue, as we have a duplicate with more recent in #1385.
