### ISSUE TITLE
"./pmbootstrap.py build package --force" doesn't check checksum

### ISSUE THREAD

**Issue by z3ntu** [postmarketOS/pmbootstrap#1185]
Same behavior when running `abuild -f` in the chroot so it might be a bug in abuild.

**Comment by drebrez** [comment]
maybe is this? https://github.com/alpinelinux/abuild/blob/master/abuild.in#L419

**Comment by z3ntu** [comment]
`abuild --help` says ` -f  Force specified cmd, even if they are already done`
and `./pmbootstrap.py build --help` says `  --force               even build if not necessary` so neither one of those indicate that the checksum check is skipped (and the reason to use `--force` is to rebuild some package...)

**Comment by ollieparanoid** [comment]
Totally agree, see the PR I made to fix this above :+1:

**Comment by drebrez** [comment]
@ollieparanoid this seems fixed in https://github.com/alpinelinux/abuild/commit/6981f3a6ae1cab387dd4273e3483a07d932d827f, the issue can be closed?

**Comment by z3ntu** [comment]
Maybe wait until a new abuild version is released?

**Comment by ollieparanoid** [comment]
You're right, the fix was merged. And while it did not make it into a stable `abuild` version yet, the `abuild` version from Alpine's edge repository has the fix since yesterday (which is the one we use) :+1:

**Comment by z3ntu** [comment]
Ah, didn't know the edge repo has basically a -git version of abuild.
