### ISSUE TITLE
[mako] Update kernel to 4.12

### ISSUE THREAD

**Issue by mmaret** [postmarketOS/pmbootstrap#12]
John Stultz worked on mainlining the Nexus 7 (https://plus.google.com/u/0/111524780435806926688/posts/fkQ1BMjNNcn, https://plus.google.com/111524780435806926688/posts/7gNfnn4tpqe) and got cool results with even the Wifi working.
I think that he keeps his work updated as his kernel branch is based on the kernel 4.12 https://git.linaro.org/people/john.stultz/flo.git/log/?h=flo-WIP

Nexus 4 and Nexus 7 are said to be similar so may be it's easier to try this nearly upstream kernel instead of the 3.4 from Lineage ?

**Comment by ollieparanoid** [comment]
I'd love to see that! However, I'll be working on [continuous integration for pmbootstrap](https://ollieparanoid.github.io/post/postmarketOS-next/#ci-testsuite) now, to make contributing easier. I might try this myself at some point in the future, unless someone beats me to it.

**Comment by ollieparanoid** [comment]
It sort of works to directly use the Nexus 7 kernel, see #1079.

However, the better solution seems to be to mainline the Nexus 4 with a DTS file based on the one of the Nexus 7. Closing.
