### ISSUE TITLE
make kconfig_check arch-specific to support CONFIG_LBDAF

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#1218]
The [kconfig option `LBDAF`](https://wiki.postmarketos.org/wiki/Kernel_configuration#CONFIG_LBDAF) is required to mount `ext4` partitions (unless they have been created with non-default settings). But that option is only present in 32 bit (armhf, x86), not 64 bit (aarch64, x86_64) kernels. So if we added it to `kconfig_check` right now, it would incorrectly report the 64 bit device's kernels to be missing that option.

@MartijnBraam pointed out in #postmarketOS, that we could make the options we check for arch specific to resolve this.

The options we are checking for are defined in `pmb/config/__init__.py`:
```py
necessary_kconfig_options = {
    "ANDROID_PARANOID_NETWORK": False,
    "DEVTMPFS": True,
    ...
}
```

One approach would be to group these options:
```py
necessary_kconfig_options = {
    "all": {"ANDROID_PARANOID_NETWORK": False,
            "DEVTMPFS": True, ...},
    "armhf x86": {"LBDAF": True}
}
```

**Comment by Polynomdivision** [comment]
I am currently working on this. Will update this issue (and hopefully create a PR), when I am done.

**Comment by Polynomdivision** [comment]
@ollieparanoid I have created a PR (#1233). However, as it is written in the code, only the first architecture
listed under `arch` in the APKBUILD will be used to check the cofig options.
For me, the question that arises is whether a `linux-<device>` package can have multiple architectures. My guess would be "Yes", as the project is aiming for having a single kernel for every device, but asking never hurts 😄

**Comment by MartijnBraam** [comment]
Hmm that means that `kconfig_check` gets an `--arch` option since the linux packages can definitely contain multiple archs

**Comment by ollieparanoid** [comment]
Yes, one kernel can have multiple architectures, as in `aports/main/linux-postmarketos-*`. But it should work without an extra `--arch` parameter, see https://github.com/postmarketOS/pmbootstrap/pull/1233#discussion_r168916828.

**Comment by Polynomdivision** [comment]
I pushed a new commit, which, as written in the comment under the PR, now extracts the architecture from the name of the config file, instead of getting it from the APKBUILD.
