### ISSUE TITLE
Gracefully handle missing /proc/sys/fs/binfmt_misc

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#1223]
From [the wiki](https://wiki.postmarketos.org/wiki/Troubleshooting#sh:_can.27t_create_.2Fproc.2Fsys.2Ffs.2Fbinfmt_misc.2Fregister:_nonexistent_directory):
> ##  sh: can't create /proc/sys/fs/binfmt_misc/register: nonexistent directory
> This issue is known to happen in Alpine Virthardened. It also happened in Void Linux for one user.  These commands should fix it:
>
>`sudo modprobe binfmt_misc`
>`sudo mount -t binfmt_misc none /proc/sys/fs/binfmt_misc`
>
>If it still does not work, it is probably not supported by your host Linux distribution's kernel (`CONFIG_BINFMT_MISC`). Try to use another kernel. 

While this is on the troubleshooting page, it isn't really obvious and people get stuck with this error. It would be nice if we checked if `/proc/sys/fs/binfmt_misc` existed, and if it did not, printed a link that points to the right location in the troubleshooting wiki.

**Comment by Polynomdivision** [comment]
I created a PR (#1236) that adds a check at the start, so that the user will be warned (and pointed to the Wiki), if binfmt_misc is not loaded.
I am, however, not sure if the start is the right place for this check or if the phrasing of the message would be fitting.
