### ISSUE TITLE
pmbootstrap init: Allow switching between mainline and downstream kernel (for devices that have support for both)

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#1263]
@MayeulC wrote in https://github.com/postmarketOS/pmbootstrap/issues/756#issuecomment-368332143:
> [...] idea regarding multiple kernels: maybe pmbootstrap will be able to offer the user a choice at some point; I think the way pacman handles multiple providers is nice, and such a mechanism could be unified for choosing between DE, kernel and other components.

While we can't implement that at the package manager level (`apk`) that easily, we can do it in `pmbootstrap init`. We could use the same mechanism with subpackages to choose the different kernels like we do from now on with the `nonfree` packages (#1254).

**Comment by MartijnBraam** [comment]
I think the major problem with switching kernels is that you need seperate deviceinfo files for the kernels since certain things might change between the kernels like the DTB name.

**Comment by z3ntu** [comment]
Yes, I have modified the deviceinfo locally for the mainline kernel.

**Comment by ollieparanoid** [comment]
In #1363 it became clear that just using one `deviceinfo` file doesn't work - there's more than `deviceinfo_dtb` and `deviceinfo_modules_initfs` that needs to be changed.

See #1368 for an idea how to implement this.
