### ISSUE TITLE
when installing packages: can only concatenate list (not "odict_keys") to list

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#1287]
@z3ntu wrote in https://github.com/postmarketOS/pmbootstrap/pull/1283#issuecomment-370215308:

> Nothing to do directly with this PR but I sometimes hit the following error while running pmbootstrap:
```
 /m/h/p/pmbootstrap   fix/linux-pmos-mainline-doesnt-boot-weston $…  pmb install --add linux-postmarketos-lts,linux-postmarketos-stable,linux-postmarketos-mainline --no-fde
[10:20:08] *** (1/5) PREPARE NATIVE CHROOT ***
[sudo] password for luca: 
[10:20:12] (native) install
[10:20:13] *** (2/5) CREATE DEVICE ROOTFS ("qemu-amd64") ***
[10:20:13] Update package index (12x)
[10:39:47] (rootfs_qemu-amd64) install
[10:39:47] ERROR: can only concatenate list (not "odict_keys") to list
[10:39:47] Run 'pmbootstrap log' for details.
[10:39:47] See also: <https://postmarketos.org/troubleshooting>
```

@z3ntu: thanks for reporting!
* can you upload the "pmbootstrap log" output for that?
* do you have a workaround (does it go away after zap)?

**Comment by z3ntu** [comment]
Log is https://pastebin.com/dVmRrMP9

Error seems to be gone after a zap (ran two times the install command which both failed, then zapped and install command again which worked). I

**Comment by MartijnBraam** [comment]
I've ran accross this (and fixed it by zapping), at some point the package list is an ordered dict instead of a normal dict and in the `upgrade()` function it runs `.keys()` on that dict to get the names of the packages to install. This results in a odict_keys iterable instead of a list for an ordered dict.

This patch seems to work for me:
```
diff --git a/pmb/chroot/apk.py b/pmb/chroot/apk.py
index f7ab02ce..a8ee69aa 100644
--- a/pmb/chroot/apk.py
+++ b/pmb/chroot/apk.py
@@ -243,7 +243,7 @@ def upgrade(args, suffix="native"):
     pmb.helpers.repo.update(args)
 
     # Rebuild and upgrade out-of-date packages
-    packages = installed(args, suffix).keys()
+    packages = list(installed(args, suffix).keys())
     install(args, packages, suffix)
```

**Comment by z3ntu** [comment]
@MartijnBraam This is exactly the same patch as in #1290 :smile:

**Comment by MartijnBraam** [comment]
I guess it can be merged then :D, I've actually ran across this error a few times this week and finally decided I should check what was crashing.
