### ISSUE TITLE
[Q] Mounting /vendor vs fetching the firmware properly

### ISSUE THREAD

**Issue by Alexandroid99** [postmarketOS/pmbootstrap#1304]
OK, so I'm trying to finish up the device configuration and regarding vendor blobs I might have run into an edgecase here. In theory we wouldn't need to make a firmware package for it as the vendor blobs are already stored on a separate partition /vendor

`/dev/block/mmcblk0p24   /vendor ext4      ro                    0       0`

Now what I'm asking is should I "stick to best practices", so to speak, and still make a proper firmware configuration or should I cook something up that mounts the partition and puts the firmware into the regular spot? (By default the kernel looks for the wifi firmware in that place as well so we wouldn't need to change that configuration and copy the firmware and in general it might save us a lot of pain as it even contains firmware for the tegra chip in /vendor/firmware/tegra123 that the kernel might look at per default as well, don't know in this case. In short, making use of /vendor might save a lot of work since it's the default implementation.)

The alternative would be fetching the firmware from this repo used by LineageOS to get blobs:
https://github.com/TheMuppets/proprietary_vendor_htc/tree/lineage-15.1/flounder-common/proprietary/vendor

**Comment by PureTryOut** [comment]
It seems we're lacking a Wiki entry for this, would be good if someone added it. Long story short: after some discussion we had way earlier, we decided to go with "the best practices" and make a proper firmware image.

**Comment by Alexandroid99** [comment]
So we're not going to make use of a partition that devices are going to increasingly have as time moves on (Project Treble)?
I feel like there should be something to account for this pretty convenient condition in the future. Maybe general support for initramfs to detect and mount /vendor and other goodies. Otherwise it's just wasted and wasted effort to ignore the partition imo.

**Comment by drebrez** [comment]
@PureTryOut @Alexandroid99 here is the wiki entry related to this question => https://wiki.postmarketos.org/wiki/FAQ#Why_don.27t_we_use_firmware_files_from_Android.27s_firmware_partition.3F

**Comment by Alexandroid99** [comment]
Pardon me then. I was looking at the "porting a new device" wiki entry and it mentioned nothing about /vendor.

**Comment by ollieparanoid** [comment]
@Alexandroid99: Thanks for opening the issue, it appears that finding the link that answers the question is not as easy as it should be!
Since you just went through the porting guide, do you have found a good place where we could link to the firmware faq entry (maybe with a `{{note|some note text here}}`)?
If so, it would be super helpful if you could directly add the link there :+1:

**Comment by Alexandroid99** [comment]
I'll see to it once I'm done figuring out which libraries are actually vital and which aren't. Btw somehow themuppets didn't have the wifi firmware that the kernel was pointing to on /vendor so I dumped the files via recovery and made my own repo. I hope that's legitimate?

**Comment by ollieparanoid** [comment]
That's fine, yep.
