### ISSUE TITLE
Stripping binaries fails because file can't be deciphered

### ISSUE THREAD

**Issue by Alexandroid99** [postmarketOS/pmbootstrap#1308]
So I'm building the firmware package for the Nexus 9 and after adding all the firmware files I'm getting this error:
```
>>> firmware-htc-flounder*: Stripping binaries
/usr/bin/strip: Unable to recognise the format of the input file `./lib/firmware/postmarketos/rt5677_elf_vad'
>>> ERROR: firmware-htc-flounder*: prepare_package failed
>>> ERROR: firmware-htc-flounder: all failed
```
Is there any option to skip this step for at least the binary in question?
Binary can be found here: https://github.com/Alexandroid99/vendor_htc_flounder/blob/27024f568d1eee70c4a12f3f46aec33f6ee2f225/firmware/rt5677_elf_vad?raw=true
Maybe it's encoded in an unreadable way or is already stripped, don't know.

**Comment by z3ntu** [comment]
https://wiki.alpinelinux.org/wiki/APKBUILD_Reference#options

**Comment by ollieparanoid** [comment]
The firmware files are not regular Linux executables (ELF), so `strip` can't strip any debug symbols here. As in the link @z3ntu posted, you can use the `!strip` flag to avoid the error.

(Closing. If you have more questions about this, just reply.)
