### ISSUE TITLE
Black Screen on ZTE Kis 3 

### ISSUE THREAD

**Issue by ethanrjones97** [postmarketOS/pmbootstrap#1323]
Currently the display on the the [ZTE Kis 3](https://github.com/postmarketOS/pmbootstrap/pull/1311) is not functional. Even while booting the frame-buffer does not update the screen.   
This issue is for documenting possible fixes.  
I've attempted to use the fixes on the [wiki page](https://wiki.postmarketos.org/wiki/Troubleshooting:display) without any success - the screen stays blank.  
Does anyone have debugging suggestions? Thanks!

**Comment by ollieparanoid** [comment]
You could try this guide:
https://wiki.postmarketos.org/wiki/Tuning_sysfs

**Comment by igordsm** [comment]
I obtained the following when running the commands in that page with my device running TWRP

https://gist.github.com/anonymous/89faf6c7ada0a08253e287109738d665

There seems to be relevant information when searching for /graphics. Unfortunately, I was not able to do the same in pmOS, as it currently refuses my ssh connection.

**Comment by ethanrjones97** [comment]
Here's [TWRP and pmOS](https://gist.github.com/ethanrjones97d5bce3f9a0244a22c63e4739f2ec555e)   @igordsm It's really really slow to boot up - it does work I swear!

**Comment by ethanrjones97** [comment]
Small breakthrough!  
`echo [1,255] > /sys/class/leds/wled-backlight/brightness` get us a backlight :+1:

**Comment by ethanrjones97** [comment]
Here's the [diff ](https://gist.github.com/ethanrjones97/6ef37d599126f3b54a963f69fa05738a) by the way.  
I can't help but feel the `/sys/devices/virtual/graphics/fb0/pan` needs changed from `0,0` to `0,800` but it's giving me an I/O error :thinking:

**Comment by ethanrjones97** [comment]
:grinning: 
![photo_2018-03-12_21-32-34](https://user-images.githubusercontent.com/5385580/37317738-fb9c3644-263c-11e8-82ee-0df73e4c530f.jpg)

**Comment by ethanrjones97** [comment]
I made a couple of patches in my [fork](https://github.com/ethanrjones97/pmbootstrap) going to try and get the touchscreen to work tomorrow I think :100:

**Comment by drebrez** [comment]
@ethanrjones97 Congrats, for the red screen you can find some info here: https://wiki.postmarketos.org/wiki/Troubleshooting:display#My_screen_is_red.21

**Comment by ollieparanoid** [comment]
Awesome \o/
