### ISSUE TITLE
Install issues with ZTE OpenC/Kis3

### ISSUE THREAD

**Issue by igordsm** [postmarketOS/pmbootstrap#1325]
First of all, thanks for the work on this device. I am new to pmOS and this is my first time installing a non-android (or Firefox OS) system.

According to [the wiki](https://wiki.postmarketos.org/wiki/ZTE_Kis_3_(zte-kis3)), I should flash system to sdcard 

> Flashed using an external SD card for system, Fastboot for kernel/initramfs. Fastboot seems to crash when flashing system and using an Android recovery zip seemed unsuccessful as well. 

From my understanding of the docs, I should run `pmbootstrap install --sdcard=/dev/sdc`. However, I get the following message

>RuntimeError: According to the deviceinfo, this device does not support a sdcard installation.

Was this supposed to work? Sorry if this is a dumb question, but it is what I could get from the docs.

**Comment by ethanrjones97** [comment]
Yeah this is a newer bug.  
The branch I was developing on did not have PR #1301 applied. Unfortunately, I'm not quite sure what the new option for allowing SD card installs is - if there is one, or if it's just not [on the wiki](https://wiki.postmarketos.org/wiki/Deviceinfo_reference)

**Comment by ethanrjones97** [comment]
@drebrez Did you implement a new option for external storage booting or should it just automatically allow it with `external_storage` set to `true`?

**Comment by drebrez** [comment]
@igordsm I've just renamed the property, it should work as before. You just need to set `deviceinfo_external_storage="true"` in the deviceinfo if your device has the sd card slot and then you can use the `pmbootstrap install --sdcard=/dev/sdX` command to install it on the sd card.

**Comment by ollieparanoid** [comment]
The line was set, but it had a space at the end of the line and the `deviceinfo` parsing code doesn't handle that well. It's fixed now, just pull again from `master` and it should work again :+1:

**Comment by ethanrjones97** [comment]
thank! :+1:

**Comment by igordsm** [comment]
Thanks! I was able to execute pmbootstrap successfully now.
