### ISSUE TITLE
Can't update linux-postmarketos-mainline because booting into weston is broken

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#1352]
Found by @z3ntu in #1348.

I think the proper way to handle this is:
* do an automated git bisect to find out which commit caused the breakage (I tried that once before and it was hard, but now it should be a lot easier, because we have `build --src` and an automated testcase for booting qemu already which only needs to be slightly modified)
  * write the script
  * run automated git bisect (this takes some hours depending on how fast the PC is)
* mail the author about the breakage
* add a patch that reverts the commit in our packaging
* make sure it works with the patch
* create a new PR to update the kernel
* (remove the patch in the future when the bug was fixed upstream)

@z3ntu:
* can you describe what did not work exactly? Did it get stuck in the initramfs, or in OpenRC, or did weston simply not start?
* do you happen to have time to look into this? If you don't have time, it's totally cool and I'll do it.

**Comment by z3ntu** [comment]
It saw the same behavior that we had before we fixed the kernel config on the mainline flavor. So pmOS booted normally but weston didn't start.

**Comment by ollieparanoid** [comment]
@z3ntu: I can _not_ reproduce this. After building `4.16.0-rc6` it boots up for me in `qemu-amd64` with:
* `dri-virtio` (default)
* `dri-swrast`
* `--spice`

My guess would be, that you had just updated your host kernel before trying it. On distros like Arch this means, that all kernel modules for the current kernel can not be loaded anymore (files don't exist on disk anymore, as there are only the files for the newer kernel version). From what I understand, Qemu loads the `virtio` kernel module on demand (in the host kernel) as soon as you need it, which would explain why that failed in your test.

Could you try it again?

**Comment by z3ntu** [comment]
Yeah it works now... Your explanation is probably correct even though I think the other two kernels worked directly after trying rc6. Sorry for the hassle

**Comment by ollieparanoid** [comment]
No problem, thanks for the quick testing and making the update PR!
