### ISSUE TITLE
change flash_system to flash_rootfs

### ISSUE THREAD

**Issue by MartijnBraam** [postmarketOS/pmbootstrap#1354]
I propose changing `pmbootstrap flasher flash_system` to `pmbootstrap flasher flash_rootfs`.

This will make it less confusing when you have the rootfs on something that is not the android system partition and make it clear what it is actually flashing in the linux installation.

eg:
```
pmbootstrap flasher flash_rootfs --partition=userdata
```

**Comment by pinoaffe** [comment]
Then, maybe also change `pmbootstrap flasher flash_kernel` to `pmbootstrap flasher flash_bootimg`?

**Comment by ollieparanoid** [comment]
The `boot.img` format comes from Android, and it isn't even used for all Android devices (e.g. [`heimdall-isorec`](https://wiki.postmarketos.org/wiki/Deviceinfo_flash_methods#heimdall-isorec)). postmarketOS supports more than Android devices, so I would recommend against changing it to that. 

However, we could extend the description of `pmbootstrap flasher -h` to indicate that this will flash the `boot.img` file for Android devices that support it.
