### ISSUE TITLE
Consider removing 'deviceinfo_modules'

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#137]
We a `deviceinfo_modules` variable in the `deviceinfo` file, that isn't being used yet. The question is, if we even need it, or if we should remove it. Quoting from the channel:

drebrez:
> in the deviceinfo there is "deviceinfo_modules_initfs" which is used to define the modules to be loaded during the initramfs, then there is "deviceinfo_modules" which is not used yet
the idea was to define the modules to load there?

me:
> yeah, the idea for "deviceinfo_modules" was to load them after booting.
the question is now, if we need that at all. it should just work automatically with the dtb file, as MartijnBraam suggested. if it does, then we could remove that variable
(or keep it for information purpose)
...and if it does not work, we could write a simple openrc service, that loads the modules from the deviceinfo file.
if we want to do it that way. or use the /etc/modules-load.d/ directory, like most other distributions (we could create a file in there with the device- package)
(that /etc/modules-load.d thing comes from systemd actually, as the [stackexchange thread](https://unix.stackexchange.com/questions/189670/whats-the-difference-of-etc-modules-load-d-and-etc-modules) you found points out. but openrc is compatible in that matter)

@drebrez: Could you please report here, if automatic loading of your wifi module has worked, without specifying the module anywhere?

**Comment by drebrez** [comment]
without specifying the module anywhere I can confirm that the module **doesn't** get loaded automatically

**Comment by drebrez** [comment]
just tested these solutions:
- append the module name in the `/etc/module` file
- create file `/etc/modules-load.d/00-device-xxx.conf` with the module name to load

and both of them works.

A possible solution is to write the file `/etc/modules-load.d/postmarketos.conf` with the content of the "deviceinfo_modules"

**Comment by MartijnBraam** [comment]
We can also just include the 00-device-flavor.conf file in the device package for the devices that need it, that allows to set module settings also.

**Comment by ollieparanoid** [comment]
> A possible solution is to write the file `/etc/modules-load.d/postmarketos.conf`  with the content of the "deviceinfo_modules"

a) We could do this by installing a hook in postmarketos-base, that watches the `/etc/deviceinfo` file. And when it gets changed, it recreates
`/etc/modules-load.d/postmarketos.conf`.

b) As @MartijnBraam said, we could put a file named `modules-load.conf` or something like that inside the aport, and install it to `/etc/modules-load.d/00-samsung-i9070.conf`.

Advantage of a) is, that we don't need to create an extra file in the aport, while the advantage of b) is, that we don't need to create config files and do not have extra code for the hook.

Personally, I prefer b) (and removing the `deviceinfo_modules` variable, so we don't need to store the information twice). What do you think?

**Comment by drebrez** [comment]
Both are fine for me, I will implement the second one for my device and create a PR very soon
