### ISSUE TITLE
[Feature Request] Automatically add an alias that navigates to top of repo

### ISSUE THREAD

**Issue by Alexandroid99** [postmarketOS/pmbootstrap#1383]
When building Android, the envsetup.sh script adds a few nice commands for navigating the build environment, like croot, for quickly jumping to the root of the repository. It'd be great if pmbootstrap had similar goodies. Just a minor request and not vital, but I think quite a few people could appreciate.

**Comment by pinoaffe** [comment]
I'd rather pmbootstrap leaves my environment untouched

**Comment by Alexandroid99** [comment]
Sure, optional, but what's an extra variable $TOP in your current shell session? Wouldn't hurt that much, or are we suddenly back to the C64 BASIC days where every character in memory has to be considered carefully? :yum: 
Anyway, I'm not good with shell scripting, though maybe I'll try to come up with something. If anyone wants to proceed me, go right ahead, you're probably more versed in it than I am.

**Comment by ollieparanoid** [comment]
Well, `pmbootstrap` is a Python program, which does not get sourced like a shell script, but directly executed instead. So it can't really modify the current shell's environment variables even if we wanted to.

**Comment by pinoaffe** [comment]
One "trick" i could think of to go to the parent dir would be `while [ ! -d .git ]; do cd ..; done`

**Comment by BlitzKraft** [comment]
I think it would be more efficient if there is a variable storing the root directory from where the script will be sourced. The while loop will work, but just "feels" wrong to me.

**Comment by BlitzKraft** [comment]
```bash
$PMB_PATH=$(pwd)
alias pmroot=cd "$PMB_PATH"
```
This should do the trick, when sourced from the pmbootstrap directory.
