### ISSUE TITLE
Commands to rootfs_<package> chroot hang

### ISSUE THREAD

**Issue by cmdr2** [postmarketOS/pmbootstrap#140]
Hi,

**Host OS:** alpine virthardened (with grsec disabled), running in a VM

During the './pmbootstrap install' command, the CREATE DEVICE ROOTFS step hangs. Upon digging into this, it looks like all commands into the rootfs chroot hang, for e.g. `./pmbootstrap chroot --suffix rootfs_samsung-s7562` also hangs.

In the Host OS, the BINFMT_MISC module is loaded and mounted, and the arm magic is set too:
```shell
$ cat /proc/sys/fs/binfmt_misc/status 
enabled

$ cat /proc/sys/fs/binfmt_misc/qemu-arm 
enabled
interpreter /usr/bin/qemu-arm-static
flags: OC
offset 0
magic 7f454c4601010100000000000000000002002800
mask ffffffffffffff00fffffffffffffffffeffffff
```

The `/home/cmdr2/.local/var/pmbootstrap/chroot_rootfs_samsungs7562/proc/sys/fs/binfmt_misc/qemu-arm` file also has the same output.

But qemu-arm-static hangs against any arm program, like 'ldd', for e.g:
```shell
$ /home/cmdr2/.local/var/pmbootstrap/chroot_rootfs_samsung-s7562/usr/bin/qemu-arm-static /home/cmdr2/.local/var/pmbootstrap/chroot_rootfs_samsung-s7562/usr/bin/ldd 
```

Running `file` against the 'ldd' inside the rootfs chroot shows it is an ARM executable: `
ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, stripped, with debug_info`

This command is expected to return immediately with the help options for ldd (since no arguments were passed), but instead hangs indefinitely.

I'm a bit out of ideas for the moment, would appreciate any new ideas to try :)

Cheers
~cmdr2

**Comment by ollieparanoid** [comment]
Great analyzing work! Well... the easy fix I can think of is *not* using the hardened kernel, if that is an option for you. How about that?

**Comment by ollieparanoid** [comment]
This might really help:
> Fixed by setting pax flags (initially RANDMMAP) on /usr/bin/qemu-arm and {chroot_dir}/bin/qemu-arm . 

Source: https://forums.gentoo.org/viewtopic-t-1035274-start-0.html

**Comment by cmdr2** [comment]
Thanks! Disabling RANDMMAP got qemu to stop hanging, but any program run on qemu immediately returns with a "Killed" console output. This is happening with both qemu-arm as well as qemu-x86_64. Also, this used to happen to the x86_64 even before I did the RANDMMAP thing.


I didn't spend a lot of time digging into the "Killed" message, but I'll try changing the kernel to vanilla next and see if that works. I'm not overly attached to using the hardened kernel for now :)


For reference, this is how the RANDMMAP flag was disabled on qemu-arm-static:
```shell
sudo apk add paxctl
sudo paxctl -C /home/cmdr2/.local/var/pmbootstrap/chroot_rootfs_samsung-s7562/usr/bin/qemu-arm-static
sudo paxctl -r /home/cmdr2/.local/var/pmbootstrap/chroot_rootfs_samsung-s7562/usr/bin/qemu-arm-static
```

**Comment by ollieparanoid** [comment]
Okay. I've adjusted the [Troubleshoting:grsec](https://github.com/postmarketOS/pmbootstrap/wiki/Troubleshooting:grsec) page.

**Comment by cmdr2** [comment]
Switching to a vanilla (non-grsec) kernel fixed the problems with qemu getting 'Killed', and the build and image generation completed successfully.
