### ISSUE TITLE
libmatchbox2 depends on maemo-specific functionality

### ISSUE THREAD

**Issue by duncanguthrie** [postmarketOS/pmbootstrap#1411]
Hildon desktop makes use of libmatchbox2.

However, this particular libmatchox2 depends on the gtk+2.0-maemo.

There are reasons that one might want to make use of libmatchbox2 on its own - I had to rename libmatchbox2 to libmatchbox2-maemo in order to package libmatchbox2 upstream.

Is there a reason to keep libmatchbox2 as such?

**Comment by duncanguthrie** [comment]
Just to clarify, my understanding is that we can spin out libmatchbox2 from the matchbox-window-manager-2 source code. This can then be used externally, as far as I understand.

**Comment by ollieparanoid** [comment]
@NotKit, @freemangordon: is there anything special about Maemo Leste's fork of libmatchbox2, or will the upstream version from matchbox-window-manager-2 be compatible with Maemo Leste as well?

**Comment by NotKit** [comment]
@ollieparanoid I checked the Maemo's libmatchbox2 code, there are Hildon-specific bits there, so it's not interchangeable. But as discussed with duncan in IRC, matchbox-window-manager-2 has libmatchbox, not libmatchbox2.

**Comment by ollieparanoid** [comment]
Then they can be packaged side by side and it's all good? :smile:

**Comment by duncanguthrie** [comment]
Yes, I suspect so (if applicable).
