### ISSUE TITLE
Device tree headers not found

### ISSUE THREAD

**Issue by Decatf** [postmarketOS/pmbootstrap#142]
I'm trying to compile a kernel that uses appended device tree. pmbootstrap fails to compile the device tree blobs with the following error.

```
  DTC     arch/arm/boot/dts/tegra20-samsung_p3.dtb
In file included from /home/user/build/src/picasso-kernel-31150ad3f38409100a00fd58e3f7c9bcefc1bc92/arch/arm/boot/dts/tegra20-samsung_p3.dts:4:0:
/home/user/build/src/picasso-kernel-31150ad3f38409100a00fd58e3f7c9bcefc1bc92/arch/arm/boot/dts/tegra20.dtsi:1:43: fatal error: dt-bindings/clock/tegra20-car.h: No such file or directory
 #include <dt-bindings/clock/tegra20-car.h>
                                           ^
compilation terminated.
make[3]: *** [scripts/Makefile.lib:293: arch/arm/boot/dts/tegra20-samsung_p3.dtb] Error 1
make[2]: *** [arch/arm/Makefile:329: dtbs] Error 2
make[2]: *** Waiting for unfinished jobs....
```

[Here is the device specific package I'm working on.](https://github.com/Decatf/pmbootstrap/commit/f9395d336d6285ac710b658aecb350dd04bfb211)

I've been porting newer kernels for this device. This kernel compiles in the Android build env and boots Android so it is a known working kernel.

**Comment by MartijnBraam** [comment]
The .zip files from github don't contain the symlinks in the kernel source. if you change the extension to .tar.gz in your linux package APKBUILD then it should work

**Comment by ollieparanoid** [comment]
I've tested your branch with modifying the source as @MartijnBraam said. This fixes the `No such file or directory` error, but later the compilation fails at compressing the kernel. It finally runs through when adding `xz` to the `makedepends=` in the `APKBUILD` to fix that.

I've added two sections in [troubleshooting](https://github.com/postmarketOS/pmbootstrap/wiki/Troubleshooting)  about these issues, which you can read if you're interested in more details/alternative workarounds.

Thanks for tying out pmbootstrap and starting a new port!

**Comment by Decatf** [comment]
Using tar.gz worked. I am able to boot the kernel but nothing else happens. The kernel log shows all the driver initialization and then it sits idle at the original device boot logo. I guess that's some other issue.

I did not get any error with compressing the kernel. Everything compiled without error after using tar.gz instead of zip.

**Comment by ollieparanoid** [comment]
That is some progress at least :) I recommend joining the [matrix/irc](https://github.com/postmarketOS/pmbootstrap/wiki/Matrix-and-IRC) channel, so we can help you more directly.
