### ISSUE TITLE
Flasher flash_rootfs stuck at "sending 'system'" 

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [postmarketOS/pmbootstrap#1422]
I have a Nexus 7 2012, after building the OS with Mate DE, I ran:

```
./pmbootstrap.py -v flasher flash_rootfs
```

This is the result:

```
[22:53:07] (native) flash rootfs image
< waiting for any device >
FAILED (data write failure (Protocol error))
finished. total time: 1051.761s
target didn't report max-download-size
erasing 'system'...
OKAY [  0.147s]
sending 'system' (716800 KB)...
```

Is it because the size is too big for the devices?

**Comment by ollieparanoid** [comment]
[From the wiki page](https://wiki.postmarketos.org/wiki/Google_Nexus_7_2012_(asus-grouper)#Installation_process):
> ### UI options
> * Weston: Boots, but also occasionally reboots on its own.
> * Hildon: Boots into a black screen. Poking some <code>/sys/</code> variables might make the screen flash or turn on, but it remains unusable
> * KDE: **Never finishes the flash**, which in turn wrecks your device partitions. This has happened even with <code>flasher flash_rootfs --partition userdata</code>'

So it seems like this is a known issue. However, there are other flashing methods you could try out, e.g. netcat (#456). Just make sure you are writing to the right partitions.

**Comment by ollieparanoid** [comment]
That is true, but this isn't about the toolkit, but about the installation image size.

**Comment by Decatf** [comment]
The system partition size on grouper is 650MB[1]. The image you're trying to flash is `716800 KB` or ~700MB

[1]http://anddisa.de/blog/blog/nexus-7-partition-sizes-16gb-model

**Comment by RicardoEPRodrigues** [comment]
So what should I do?

One thing I can do is choose another smaller DE (and I'll try it out), but what if someone wants to use Mate?

**Comment by RicardoEPRodrigues** [comment]
Ok, I tried switching to XFCE4 and this ran smoothly. 

Because it says that `target didn't report max-download-size` followed with and oversized build, maybe it is no possible to detect the error?

Should we note this in the Wiki?

**Comment by RicardoEPRodrigues** [comment]
I think of testing out the several UI options and see the outputs.

I'll be updating the Wiki when I have the time.

Thank you for the great work.

**Comment by Decatf** [comment]
I don't think there's any mechanism in pmbootstrap to validate the image size. In the Android environment the partition size is defined per device in BoardConfig.mk and checked at compile time.

**Comment by PureTryOut** [comment]
Note that #1422 will eventually fix issues like these.

**Comment by drebrez** [comment]
@RicardoEPRodrigues at least you can set the `deviceinfo_flash_fastboot_max_size` variable in the `deviceinfo` and if the generated image is greater it will not try to flash it. 
(ref: https://wiki.postmarketos.org/wiki/Deviceinfo_reference#flash)

**Comment by ollieparanoid** [comment]
Thanks for trying this out! It would be really nice if you could make a pull request with that change, the steps would be:
* adjust `deviceinfo`
* `pmbootstrap checksum device-asus-grouper`
* increase the pkgrel once in `aports/device/device-asus-grouper/APKBUILD` (e.g. with `pmbootstrap pkgrel_bump device-asus-grouper`)

**Comment by RicardoEPRodrigues** [comment]
@ollieparanoid It's done! :smile:

**Comment by ollieparanoid** [comment]
Awesome, thanks for the PR!

> Other small note: The default images for android provided by google have the bootloader broken, meaning it can update it. It does not seem to affect the install process of PostmarketOS, but is something to take into account.

Could you add that information to the device's wiki page?

> I'd love to see XFCE4 or some lightweight desktop working for me to use this tablet as a laptop.

Yeah, let's get that working! A good place to start is looking at the logs with "logread".

If you need further help with that, either ask in the chat or open a new issue in the tracker and we'll help you out :smile:
