### ISSUE TITLE
Issues with lock.sh for screen lock (i3wm/N900)

### ISSUE THREAD

**Issue by sicelo** [postmarketOS/pmbootstrap#1425]
On my N900, the file `/usr/bin/lock.sh` had the permissions 644, which doesn't allow for the script to run in order to lock the screen.

I am not sure what package or config should be responsible for setting correct permissions. Perhaps someone can chime in.

**Comment by ollieparanoid** [comment]
The permissions `644` need to be changed to `755` in `aports/main/postmarketos-ui-i3wm/APKBUILD` to fix this (and the pkgrel of the APKBUILD increased) - would you like to test this and create a pull request if it works?
Thanks for reporting @sicelo! :+1:

**Comment by sicelo** [comment]
Found another issue with `lock.sh` ... will handle in a different issue
