### ISSUE TITLE
linux-postmarketos-qcom: download kernel.org tarball, apply patches on top

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#1436]
As discussed in IRC, it would be nice if we could use the upstream kernel sources and apply few device specific patches on top (until they are mainlined properly), instead of directly downloading a tarball from [postmarketOS/linux](https://github.com/postmarketOS/linux). (The extra repository is needed for easier collaboration in any case.)

Advantages:
* It's obvious how many patches we are carrying
* It's easier to look at these patches
* No need to download the full Linux source over and over again for each version

I've tried to automatize that step, and so far I've got the following:
```shell
#!/bin/sh
# Runs this script inside the linux source folder

# Fake destination folder for now
aport="/tmp/aport"
mkdir -p "$aport"
rm "$aport"/*.patch 2>/dev/null

# Find the most recent common commit
branch_upstream="master"
branch_patched="postmarketos-linux-qcom"
base="$(git merge-base $branch_upstream $branch_patched)"
echo "merge-base: $base"

# Find the related RC tag
tag="$(git describe --match "v*-rc*" --abbrev=0)"
echo "tag: $tag"

# Write patch files
git format-patch -o "$aport" "$tag" "$branch_patched"
```

But when done that way, it outputs the following and then generates thousands of patch files, because right now the branch is not based off a clean RC version, but the latest commit on master at time of creation:
```
merge-base: b284d4d5a6785f8cd07eda2646a95782373cd01e
tag: v4.16-rc7
```

Looking at the branch on GitHub, right now it says:
> This branch is 30 commits ahead, 1379 commits behind torvalds:master. 

So we should be able to get 30 patch files instead. 

I recommend the following to get there:
* Create a new branch `linux-postmarketos-qcom` (instead of `postmarketos-linux-qcom` which we have right now, the new name will be like the package name of the kernel)
* Base that off the latest linux RC version instead of the latest commit on the branch
* Then apply all patches again (and use better commit messages? one has just "stuff")
* Test it on the device

Then I could finish the script above, we could update the APKBUILD and finally delete the old branch.

What do you think about that @bhush9, @opendata26, @MartijnBraam and everyone else interested in `linux-postmarketos-qcom`?

**Comment by z3ntu** [comment]
I think this approach would be good if we had finished commits that are just waiting to be accepted in upstream, but as you said currently the commits are a mess and are basically just a working state without a good history.
So I think for seeing how many and what patches are extra, the GitHub web UI is sufficient and the download of the source is not really an important factor.

**Comment by opendata26** [comment]
yeah, i agree with @z3ntu though ill look into creating a new branch with commits cleaned up and once its tested ill put on main qcom branch.

**Comment by ollieparanoid** [comment]
@z3ntu: In my eyes these 30 commits are not a mess, except for 1/30 it's quite clear what they do from the commit message. We do the same approach for `linux-nokia-n9` and `linux-asus-flo` already (where the commits are not ready to be upstreamed as well) and these aports look pretty clean to me. Could you explain why commits would need to be ready to be upstreamed before we put them there as patch files?

The source downloads need to be done on the building PC each time, so it would be nice to save the duplicated download time and bandwidth, but I agree that it's not crucial.


> yeah, i agree with @z3ntu though ill look into creating a new branch with commits cleaned up and once its tested ill put on main qcom branch.

Thanks!
* What do you think about renaming the main qcom branch `linux-postmarketos-qcom`, so it's the same as the package name?
* Could you start off the latest RC release with that new branch, or would that not work?

**Comment by opendata26** [comment]
They are quite a bit a mess, most have totally wrong ownership, and I don't really fancy having patches that are big hacks like mmssnoc clock in sports, renaming sounds okay but may i suggest branch being QCOM and renaming repo to linux-postmarketos, yeah I think I'll wait till 4.17 is fully out

**Comment by ollieparanoid** [comment]
Sounds good!

Repo is renamed to [linux-postmarketos](https://github.com/postmarketOS/linux-postmarketos) now, all old links (including download tarballs) get redirected.

**Comment by opendata26** [comment]
Should this be closed?
