### ISSUE TITLE
nextbit robin fails install

### ISSUE THREAD

**Issue by fxkrait** [postmarketOS/pmbootstrap#1444]
When installing Nextbit Robin to android-recover.img, I get this error.

* pmbootstrap:
[23:53:38] *** (1/4) PREPARE NATIVE CHROOT ***
[23:53:38] (native) install alpine-base
[23:53:39] (native) install cryptsetup util-linux e2fsprogs parted
[23:53:40] *** (2/4) CREATE DEVICE ROOTFS ("nextbit-robin") ***
[23:53:40] (native) install qemu-user-static-repack qemu-user-static-repack-binfmt
[23:53:41] Register qemu binfmt (aarch64)
[23:53:41] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/toreshi/.local/var/pmbootstrap/log.txt
[23:53:41] ERROR: Command failed: % sudo sh -c echo ":qemu-aarch64:M::\x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-aarch64-static:C" > /proc/sys/fs/binfmt_misc/register
[23:53:41] Run 'pmbootstrap log' for details.
[23:53:41] See also: <https://postmarketos.org/troubleshooting>
void% ./pmbootstrap.py log
(008755) [23:53:40] Verify apk.static signature with /home/toreshi/dev/pmbootstrap/keys/alpine-devel@lists.alpinelinux.org-5261cecb.rsa.pub
(008755) [23:53:40] % openssl dgst -sha1 -verify /home/toreshi/dev/pmbootstrap/keys/alpine-devel@lists.alpinelinux.org-5261cecb.rsa.pub -signature /tmp/pmbootstrap58qpsr_9sig /tmp/pmbootstrapsam3xqqbapk
Verified OK
(008755) [23:53:40] Verify the version reported by the apk.static binary (must match the package version 2.9.1-r3)
(008755) [23:53:40] % /tmp/pmbootstrapsam3xqqbapk --version
apk-tools 2.9.1, compiled for x86_64.
(008755) [23:53:40] (native) calculate depends of qemu-user-static-repack, qemu-user-static-repack-binfmt (pmbootstrap -v for details)
(008755) [23:53:40] (native) install qemu-user-static-repack qemu-user-static-repack-binfmt
(008755) [23:53:40] (native) % apk --no-progress add qemu-user-static-repack qemu-user-static-repack-binfmt
WARNING: Ignoring /mnt/pmbootstrap-packages/x86_64/APKINDEX.tar.gz: No such file or directory
(1/2) Installing qemu-user-static-repack (2.8-r11)
(2/2) Installing qemu-user-static-repack-binfmt (2.8-r11)
Executing busybox-1.28.2-r3.trigger
OK: 107 MiB in 39 packages
(008755) [23:53:41] (native) calculate depends of qemu-user-static-repack, qemu-user-static-repack-binfmt (pmbootstrap -v for details)
(008755) [23:53:41] parsing: /home/toreshi/.local/var/pmbootstrap/chroot_native/usr/share/qemu-user-binfmt.txt
(008755) [23:53:41] filtering by architecture: aarch64
(008755) [23:53:41] => {'mask': '\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\x00\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xfe\\xff\\xff\\xff', 'magic': '\\x7f\\x45\\x4c\\x46\\x02\\x01\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x02\\x00\\xb7\\x00'}
(008755) [23:53:41] Register qemu binfmt (aarch64)
(008755) [23:53:41] % sudo sh -c echo ":qemu-aarch64:M::\x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-aarch64-static:C" > /proc/sys/fs/binfmt_misc/register
sh: 1: cannot create /proc/sys/fs/binfmt_misc/register: Directory nonexistent
(008755) [23:53:41] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(008755) [23:53:41] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/toreshi/.local/var/pmbootstrap/log.txt
(008755) [23:53:41] ERROR: Command failed: % sudo sh -c echo ":qemu-aarch64:M::\x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-aarch64-static:C" > /proc/sys/fs/binfmt_misc/register
(008755) [23:53:41] Run 'pmbootstrap log' for details.
(008755) [23:53:41] See also: <https://postmarketos.org/troubleshooting>
(008755) [23:53:41] Traceback (most recent call last):
  File "/home/toreshi/dev/pmbootstrap/pmb/helpers/run.py", line 69, in core
    stderr=args.logfd)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', 'sh', '-c', 'echo ":qemu-aarch64:M::\\x7f\\x45\\x4c\\x46\\x02\\x01\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x02\\x00\\xb7\\x00:\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\x00\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xfe\\xff\\xff\\xff:/usr/bin/qemu-aarch64-static:C" > /proc/sys/fs/binfmt_misc/register']' returned non-zero exit status 2.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/toreshi/dev/pmbootstrap/pmb/__init__.py", line 61, in main
    getattr(frontend, args.action)(args)
  File "/home/toreshi/dev/pmbootstrap/pmb/helpers/frontend.py", line 179, in install
    pmb.install.install(args)
  File "/home/toreshi/dev/pmbootstrap/pmb/install/_install.py", line 392, in install
    pmb.chroot.apk.upgrade(args, suffix)
  File "/home/toreshi/dev/pmbootstrap/pmb/chroot/apk.py", line 246, in upgrade
    install(args, packages, suffix)
  File "/home/toreshi/dev/pmbootstrap/pmb/chroot/apk.py", line 191, in install
    pmb.chroot.init(args, suffix)
  File "/home/toreshi/dev/pmbootstrap/pmb/chroot/init.py", line 109, in init
    pmb.chroot.binfmt.register(args, arch)
  File "/home/toreshi/dev/pmbootstrap/pmb/chroot/binfmt.py", line 61, in register
    args, ["sh", "-c", 'echo "' + code + '" > ' + register])
  File "/home/toreshi/dev/pmbootstrap/pmb/helpers/run.py", line 164, in root
    return user(args, cmd, log, working_dir, return_stdout, check, background)
  File "/home/toreshi/dev/pmbootstrap/pmb/helpers/run.py", line 151, in user
    background)
  File "/home/toreshi/dev/pmbootstrap/pmb/helpers/run.py", line 82, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: % sudo sh -c echo ":qemu-aarch64:M::\x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-aarch64-static:C" > /proc/sys/fs/binfmt_misc/register

(009157) [23:54:04] % tail -f /home/toreshi/.local/var/pmbootstrap/log.txt -n 60
(009157) [23:54:04] *** output passed to pmbootstrap stdout, not to this log ***

**Comment by ollieparanoid** [comment]
Thanks for reporting @fxkrait!
* Which Linux distribution do you run?
* Do you have support for `binfmt_misc` enabled in your kernel?
* Does `modprobe binfmt_misc` help?

**Comment by fxkrait** [comment]
1) Void Linux x86_64 musl
2) not sure how to check for that.
3) no, I got the same error.

**Comment by fxkrait** [comment]
Got it working an antergos (arch), has to be something wrong void.

**Comment by fxkrait** [comment]
If I do lsmod | grep bin, nothing shows up. I assume that the kernel is missing the module.

Should I close this issue as its more related to the distro itself?

**Comment by fxkrait** [comment]
If I do modprobe, the module does show up.
But the error is still the same.

(012300) [20:29:31] % sudo sh -c echo ":qemu-aarch64:M::\x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-aarch64-static:C" > /proc/sys/fs/binfmt_misc/register
sh: 1: cannot create /proc/sys/fs/binfmt_misc/register: Directory nonexistent

**Comment by ollieparanoid** [comment]
I completely forgot that we dealt with this error before :laughing: 

[There's a wiki entry](https://wiki.postmarketos.org/wiki/Troubleshooting#sh:_can.27t_create_.2Fproc.2Fsys.2Ffs.2Fbinfmt_misc.2Fregister:_nonexistent_directory) explaining how to mount `binfmt_misc`. And most importantly we already have a check for that in the `pmbootstrap` code, which should have printed an error that links directly to that page:

https://github.com/postmarketOS/pmbootstrap/blob/b90a3c1054097f0140562dc5d54c0193cf83b97f/pmb/helpers/other.py#L65-L79

It always gets called before trying to activate `binfmt_misc`:
https://github.com/postmarketOS/pmbootstrap/blob/b90a3c1054097f0140562dc5d54c0193cf83b97f/pmb/chroot/binfmt.py#L39

(further below in the same function)

https://github.com/postmarketOS/pmbootstrap/blob/b90a3c1054097f0140562dc5d54c0193cf83b97f/pmb/chroot/binfmt.py#L57-L61

Now I'm curious why it did not work for you. Could it be that you do **not use the current master** branch from <https://github.com/postmarketOS/pmbootstrap>?

And if you do use the current code, could you try to debug this, so the check works in the future?

**Comment by fxkrait** [comment]
Lol, I've just been downloading the zip, and updating it every once and a while. I'll start using git.
I downloaded the newest version. I did not see the link above you mentioned in the error.
The only link I see is the postmarketos.org/troubleshooting
The fix you posted does work.

**Comment by fxkrait** [comment]
The issues is that the code check for the directory /proc/sys/fs/binfmt_misc/
 This ALWAYS exists, whether or not the module is loaded properly
However, when I run modrprobe -t.... the directory is populated with files "register" and "status"
change the condition to if those files exists, run normally, else output error about binfmt_misc

**Comment by fxkrait** [comment]
I change the above other.py code to
path = "/proc/sys/fs/binfmt_misc/status"
and error works as designed 
I'll let you close and commit this when you get to it. I am not a git ninja... yet.
