### ISSUE TITLE
n900 i3status "no battery"

### ISSUE THREAD

**Issue by fxkrait** [postmarketOS/pmbootstrap#1448]
i3 status wont display the battery percentage. By default it will say "no battery"

in i3status.conf, I set battery path
path = "/sys/class/power_supply/bq27200-0/uevent/"

and I get "no '%d' in battery path"

**Comment by fxkrait** [comment]
Yeah you're right. Still same error though.

**Comment by ollieparanoid** [comment]
The error message sounds like, it expects a literal `%d` in the battery path.

Here's the code:
https://github.com/i3/i3status/blob/82d25dc36295bc59cdf37af8e23c644a9c2e6aad/src/print_battery_info.c#L438

I recommend to make sure that the battery indicator in `/sys/class/...` works in general (run `cat` on the values, I've read that it needs to be calibrated on the N900 or something), and if you are sure that it works, then asking in the i3 community for help with that specific configuration. Finally after figuring it out, it would be super nice to create a pull request that fixes the configuration in the postmarketOS package.

**Comment by fxkrait** [comment]
Yes. It's shown as a percent. I have extended battery so its like 333 percent when full.

**Comment by sicelo** [comment]
I believe 333% is incorrect, even for an extended battery. FWIW, it was showing around 180% for my standard BL-5J. Also, at least to me, that kind of value (higher than 100%) has no value (pun 😛 ).

Overall, maybe I just like seeing my battery reporting as close as possible to how it is reported in Maemo (and even on laptops, etc.), which might be different to what others like. Therefore, it might be best to withdraw my PR, and keep my changes local.

For `%status`, you can use the workaround mentioned at https://github.com/postmarketOS/pmbootstrap/pull/1450#issuecomment-386832258 and yes, %remaining doesn't work.

**Comment by ollieparanoid** [comment]
Fixed in #1470, thanks to both of you!
