### ISSUE TITLE
Add configfs based usb network configuration

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#146]
@Decatf wrote in IRC:
> On newer kernels android uses configfs usb. Has there been any devices ported that succesfully use this?

Looks like we just need to extend the initramfs init script to the networking, like it is done [here](https://github.com/mer-hybris/hybris-boot/pull/79) and it should work.

**Comment by ollieparanoid** [comment]
@Decatf also wrote, that he can only test this after he gets usb networking with that kernel to work in Android. So I'm setting this to "future" for now.

**Comment by Decatf** [comment]
The mainline for Nexus 7 2013 kernel by John Stultz also uses configfs usb (judging from the defconfig). So perhaps anyone who is porting that device or some variant which uses that kernel could also work on this.

**Comment by Decatf** [comment]
@ollieparanoid:
The ConfigFS USB network config is working on Android for my device. USB tethering is indeed working on Android. It only required some defconfigs and android init stuff.

For postmarketOS I tried applying applying the [config method from hybris](https://github.com/mer-hybris/hybris-boot/pull/79/files#diff-06a4f1d6faa676d41fc4b6a039d118c5L194) that you showed me in IRC. Here's the [init_functions.sh](https://github.com/Decatf/pmbootstrap/commit/c109d91ce64d6cf79f252578cefe4771cde2f33f) I'm using now.

With these changes there's no USB device showing up in dmesg on my PC yet. On the device kernel log there are now these two lines.
```
[   19.197869] using random self ethernet address
[   19.198039] using random host ethernet address
```

For reference [this](https://github.com/Decatf/android_device_samsung_p4-common/blob/aosp-7.1-upstream_kernel/rootdir/etc/init.p3.usb.rc) is what is the p4wifi device specific usb init looks like for Android.

**Comment by ollieparanoid** [comment]
Great news, that it's working on Android!

Here is something different from the hybris-boot code (`USB` instead of `UDC`), is that intentional?
```
echo "$(ls /sys/class/udc)" > /config/usb_gadget/g1/USB
```

If that doesn't help it, you could dump the working config from Android while it is running (the configfs folder in this case) - maybe there is something different, that isn't clear from reading the Android usb init script.

**Comment by ollieparanoid** [comment]
Thanks again for your pull request!
