### ISSUE TITLE
Weston doesn't build

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#1477]
Dependency `libfreerdp` has been updated, so we need to rebuild `weston`. But we can't rebuild weston right now, as `libwayland` was updated today, but `mesa-dev` isn't built against it yet in Alpine.

Upstream fix:
https://github.com/alpinelinux/aports/pull/4229

Workaround:
```
$ cd ~/code/pmbootstrap
$ rm -r aports/main/weston
```

This will make `pmbootstrap` use the latest binary package from the postmarketOS repositories (because it doesn't see the current version as outdated anymore). That probably works except for RDP being broken.

**Comment by ollieparanoid** [comment]
Weston still does not build, but for different reasons. I can look into this tomorrow. If someone else has time, it would be nice if they could look into it as well.

**Comment by z3ntu** [comment]
Made a PR to fix this: #1480
Maybe there's a similar patch upstream but I didn't find one.

**Comment by ollieparanoid** [comment]
Awesome :tada: 

I couldn't find an existing patch either, looks like most distros are shipping freerdp 1.x right now (which makes sense, because 2.x is just in the RC state).

The issue is not entirely resolved though, while it builds for `x86_64` now, weston won't build for `aarch64` and `armhf` until the updated `mesa` is built for them in Alpine (currently Alpine's build bots are stuck there).

**Comment by ollieparanoid** [comment]
`mesa` isn't stuck anymore for armhf and aarch64 because @jirutka just fixed it in https://github.com/alpinelinux/aports/commit/a0f262308fc54c06403c8f888536eab05ea87836. Thank you! (cc @NotKit)

So the current status is, that the postmarketOS version of weston builds for `x86_64` and `aarch64` (and we have binary packages). For `armhf`, the `freerdp` package has not been built yet for 2.0.0_rc2-r0, only for 2.0.0_rc1-r0. But the patch only works with the newer rc2. I've tried to add `freerdp` to our temp folder, so we could build it for armhf. But it has problems with distcc, so I don't have a fix for that right now.

The workaround from the initial post in this issue should still work though, or check out 535caa8ad3b9e69e1c5e9b9a5eeb11728d12cd1a which will build weston without RDP support.

**Comment by ollieparanoid** [comment]
Since we can't build freerdp (#1489), I've disabled `backend-rdp` for now. We can enable it again when Alpine's freerdp binary package for all by pmOS supported arches are up to date.
