### ISSUE TITLE
Can't compile Alpine's freerdp package for armhf with pmbootstrap

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#1489]
Right now the binary package for the latest freerdp for armhf in Alpine does not exist, so it would be nice if we could compile it. However, it fails with:
> distcc[24647] (main) CRITICAL! distcc seems to have invoked itself recursively!

**Comment by george-hopkins** [comment]
It seems that FreeRDP has some [built-in handling for ccache](https://github.com/FreeRDP/FreeRDP/blob/2.0.0-rc2/CMakeLists.txt#L126-L139) which conflicts with our instance. The compilation succeeds if we build it with `cmake [...] -DWITH_CCACHE=OFF`. Feel free to ping me if you'd like me to submit the modified APKBUILD. However, the package builds by Alpine [are working](https://pkgs.alpinelinux.org/package/edge/community/armhf/freerdp), so we might not need to fork the package.

**Comment by ollieparanoid** [comment]
I agree, right now we don't need to do anything. But it's really nice to know the cause in case we need it again. We might even be able to export `WITH_CCACHE=OFF` in `/etc/abuild.conf` if this becomes important in the future.

Thank you very much for this analysis! :smile:
