### ISSUE TITLE
pmbootstrap - Allow Setting of Arbitrary Timezone

### ISSUE THREAD

**Issue by sicelo** [postmarketOS/pmbootstrap#1490]
I would like to suggest adding the ability to set any timezone in `pmbootstrap`. My pmOS workflow is as follows: my timezone is SAST (Africa/Mbabane), and due to network and hardware problems, I build off a friend's VPS that has Asia/Tokyo timezone set. My server session has SAST set.

When I run `pmbootstrap` in my session, it offers me to build an image with either Asia/Tokyo or UTC, and does not take into account the SAST TZ set in my session. So I have to set Africa/Mbabane manually in `~/.config/pmbootstrap.py` to workaround the issue, unless I wait to fix it once the system is running.

**Comment by ollieparanoid** [comment]
If it helps, you could also script that config change with `pmbootstrap config timezone $newvalue`.

**Comment by PureTryOut** [comment]
So that basically resolves this issue then right?

**Comment by sicelo** [comment]
Yes, I think so. Haven't yet tested, but thanks for the information.
