### ISSUE TITLE
Samsung Galaxy Tab 3.7.0 stuck on postmarketos loading screen

### ISSUE THREAD

**Issue by hpagseddy** [postmarketOS/pmbootstrap#1494]
I installed postmarketos rootfs on sd and flashed kernel with export and flash with live USB. When i install rootfs with fde, it shows the fde screen then hangs on the loading screen. Either without fde, it just freezes on loading screen. I tried ssh and telnet but connection keeps refusing by device. I also read the log with twrp and it says no error reported. I tried changing de too.

**Comment by ollieparanoid** [comment]
The real plot twist here is, that it boots through fine with the same device for @george99g, as he reported in the chat.

Some ideas:
* Did you try to install postmarketOS before (so you possibly have a left over installation on your device, that it tries to boot instead of the SD card?)
* When you have tried out telnet, did you use the [debug shell hook](https://postmarketos.org/debug-shell)?

**Comment by hpagseddy** [comment]
[log.txt](https://github.com/postmarketOS/pmbootstrap/files/2018648/log.txt)
here is the last_kmsg file from my device

**Comment by hpagseddy** [comment]
An update;
i got working debug shell, but when i continue boot it stucks on loading screen like 5 minutes and reboots itself

**Comment by ollieparanoid** [comment]
In the second line of your log:
> [    0.000000] c0 Linux version 3.4.5~kerNole+ (dave@dave-VirtualBox) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Fri Jul 11 14:38:33 EDT 2014


This does not look like the kernel from postmarketOS (we have GCC 6, the date is not 2018, ...) - could it be that you have another kernel flashed?

**Comment by hpagseddy** [comment]
I did “pmbootstrap flasher flash_kernel” and it can access debug shell and FDE. Can it still be a kernel issue?

**Comment by ollieparanoid** [comment]
What does `uname -a` say in the debug shell?

**Comment by hpagseddy** [comment]
It says
"Linux (none) 3.4.5-blackhawk #1-postmarketOS SMP PREEMPT Sun May 13 00:23:52 UTC 2018 armv7l Linux"

**Comment by ollieparanoid** [comment]
Okay, this means the log you have provided earlier is *not* from booting postmarketOS (the postmarketOS kernel you have probably doesn't write `last_kmesg`, although that could be enabled).

I think a good way to continue debugging from here is opening the telnet shell, then executing one command from the init script after another to see where it fails.

```
$ source ./init_functions.sh
$ show_splash /splash-loading.ppm.gz
$ mount_boot_partition
$ extract_initramfs_extra /boot/... # adjust path here
$ start_charging_mode
$ ait_root_partition
$ resize_root_partition
$ unlock_root_partition
$ resize_root_filesystem
$ mount_root_partition
...
```
The commands from the init script can be found here:
https://github.com/postmarketOS/pmbootstrap/blob/master/aports/main/postmarketos-mkinitfs/init.sh.in

**Comment by hpagseddy** [comment]
Alright, i've faced few errors.
/ # extract_initramfs_extra /boot/... # adjust path here
ERROR: initramfs-extra not found!"

"/ # start_charging_mode
awk: /etc/osk.conf: No such file or directory
sh: thd: not found
/ # sh: charging-sdl: not found"

"/ # resize_root_filesystem
Check/repair root filesystem (/dev/mmcblk1p2)
sh: e2fsck: not found
Resize root filesystem (/dev/mmcblk1p2)
sh: resize2fs: not found"

"/ # mount_root_partition
Mount root partition (/dev/mmcblk1p2)
mount: mounting /dev/mmcblk1p2 on /sysroot failed: Invalid argument
ERROR: unable to mount root partition!"

**Comment by ollieparanoid** [comment]
Thanks for trying this out. This sounds like half of your initramfs-extra is missing.

My guess is that something went wrong with your installation, or that you're possibly having an old installation on your phone, which you are trying to boot with a newer kernel.

Could you flash the rootfs and kernel again?

If that does not help:
> Did you try to install postmarketOS before (so you possibly have a left over installation on your device, that it tries to boot instead of the SD card?)

When that is the case, you would need to format the previous installation, e.g. by installing Android again.

**Comment by ollieparanoid** [comment]
Maybe flashing always goes wrong for your device or something like that.

Could you verify that the `/boot/initramfs-samsung-lt023g-extra` file is the same as the one generated on your PC? You can generate a convenience symlink on the PC with `pmbootstrap export` and then you could compare the checksums and filesize from both your exported file and the one you can find on the device with the debug-shell).

Just make sure you did not re-generate the initramfs after flashing it, or it will likely have another checksum (in that case you could flash the latest one, and then compare it after flashing).

**Comment by hpagseddy** [comment]
@george99g sent me his kernel image and i flashed it with heimdall. It stuck again

**Comment by ollieparanoid** [comment]
Just to make sure we're talking about the same thing here, you did open a telnet session once the debug-shell hook was active, then ran `md5sum` on the device and compared the checksum?

Here is the `extract_initramfs_extra` function BTW, it is pretty straight forward:
https://github.com/postmarketOS/pmbootstrap/blob/2824a525746c0a59b5216c73413ac0179faa0e97/aports/main/postmarketos-mkinitfs/init_functions.sh#L110-L120

@george99g: could you send us the output your device gives when executing the initramfs steps manually like done here https://github.com/postmarketOS/pmbootstrap/issues/1494#issuecomment-393510640?

**Comment by hpagseddy** [comment]
We’re solved the error, he sent me his sdcard’s image and i flashed it to my sd. The problem was rootfs.

**Comment by ollieparanoid** [comment]
Glad you have it working now!
