### ISSUE TITLE
Channel for discussions & help on porting 

### ISSUE THREAD

**Issue by kskarthik** [postmarketOS/pmbootstrap#15]
Hi, A place to discuss about porting & project future would be great. Creating an IRC channel will be very useful. Sailfish porters community is most active on IRC

I created a matrix group https://chat.disroot.org/#/room/#postmarketOS:disroot.org which can be bridged to IRC networks like freenode, moznet

**Comment by MartijnBraam** [comment]
Hmm I can't seem to join it from riot using #postmarketOS:disroot.org

**Comment by Qwertie-** [comment]
Sounds like a good idea, just joined.

**Comment by lawl** [comment]
> #postmarketOS:disroot.org is not accessible at this time

Not too familiar with Matrix, how about #postmarketos@freenode?

**Comment by kskarthik** [comment]
Its your choice. We can bridge both matrix group & freenode channel.

**Comment by kskarthik** [comment]
@ollieparanoid can you plese start a freenode channel. I think dev help is not so comfortable here

**Comment by ollieparanoid** [comment]
Could you open up the channel (or bridge your matrix channel, that sounds interesting)?

I would try to join within the next week or so, kind of busy right now with the rest of the project - and right now, it's easier for me to just use the GitHub issues. But that doesn't mean IRC/matrix chat is a bad idea, it will probably help a lot of people to talk to other devs in real time!

**Comment by lawl** [comment]
I squatted #postmarketos on freenode for now. I will of course transfer ownership over to @ollieparanoid whenever he wants. I'd suggest to bridge to that channel.

**Comment by kskarthik** [comment]
Oh boy! https://freenode.net/groupreg

**Comment by kskarthik** [comment]
@lawl bridge in progress 😀 will be visible in a few hours

**Comment by ollieparanoid** [comment]
Thanks guys :)

**Comment by lawl** [comment]
Created a wiki page: https://github.com/postmarketOS/pmbootstrap/wiki/Matrix-and-IRC

**Comment by kskarthik** [comment]
@lawl what's your username on IRC ? i should send you a request to bridge matrix. channel key too (if available)

**Comment by lawl** [comment]
my username is also "lawl" on freenode.

**Comment by lawl** [comment]
@kskarthik as you mentioned the bridge only seems to work in one direction, also i still can't join your matrix channel, can you please take another look?

I've added the official freenode-matrix bridge to the wiki for now which seems to work fine.

**Comment by kskarthik** [comment]
I can see the irc msgs in group now :)

**Comment by kskarthik** [comment]
The matrix network is overloaded. I feel we don't need yet another room there as anyone can join IRC from matrix account individually.

**Comment by Qwertie-** [comment]
matrix.org is fairly fine but disroot.org is having issues, its going down for an hour or two now to see if they can fix it. Should wait and see if its ok otherwise move the matrix channel to the matrix.org server where there are no issues.

**Comment by kskarthik** [comment]
Okay, but I am asking whether we need yet another channel there as anyone can join individually to IRC without an matrix channel

**Comment by MartijnBraam** [comment]
There is an matrix channel already since I joined

**Comment by Qwertie-** [comment]
There are a few benefits. The automatic bridged irc channels (#freenode_#postmarketos:matrix.org) don't allow any moderators so it all has to be done on irc and you can't change the matrix channel settings or picture.

**Comment by lawl** [comment]
> matrix.org is fairly fine but disroot.org is having issues, its going down for an hour or two now to see if they can fix it. Should wait and see if its ok otherwise move the matrix channel to the matrix.org server where there are no issues.

#postmarketOS:disroot.org still doesn't let me join. #freenode_#postmarketos:matrix.org works fine.

Proposal: Remove disroot.org from the wiki, replace it with the official bridge channel and close this issue.

@kskarthik @Qwertie-

**Comment by kskarthik** [comment]
Done ☑

**Comment by Qwertie-** [comment]
The issues with disroot are gone now. Everything is up and running.
