### ISSUE TITLE
Bluetooth graphical front-end?

### ISSUE THREAD

**Issue by yangxuan8282** [postmarketOS/pmbootstrap#1504]
Not found any GUI front-end to manage bluetooth from repos. Should we build `blueman` or `blueberry`?
Or if we can use lxde plugins [lxplug-bluetooth](https://github.com/raspberrypi-ui/lxplug-bluetooth) from raspberry pi to manage BT on mate or xfce4?

**Comment by Decatf** [comment]
I've made an [aport for Blueman](https://github.com/Decatf/pmbootstrap/tree/feature/blueman). It depends on gobject introspection from libnotify which Alpine doesn't have. I opened an issue on the Alpine bug tracker but there wasn't any response.

It's just one file anyways. I followed the debian convention of generating a separate package named `gir1.0-notify-0.7`

**Comment by yangxuan8282** [comment]
seems with `consolekit2` and `lxpolkit` installed, and use the modified version `start_xfce4.sh` in this [comment](https://github.com/postmarketOS/pmbootstrap/pull/1503#issuecomment-390490882), the blueman can autostart now

**Comment by ollieparanoid** [comment]
Great work!

@Decatf: if you have time, you could directly make a PR to Alpine to enable gobject introspection to libnotify. That probably works better than the bug reports (and if you don't get an answer to your PR within a week, you could kindly ask in #alpine-devel on IRC if someone could take a look at it).

Even better would be if we could upstream Blueman to Alpine as well - but then someone should commit to maintain it upstream (which means updating the package as soon as a new version is out).
