### ISSUE TITLE
htc-ace: Stuck after initramfs

### ISSUE THREAD

**Issue by george-hopkins** [postmarketOS/pmbootstrap#1511]
I tried flashing pmOS on my HTC Desire HD (htc-ace). However, it seems to be stuck after the initramfs. I added the debug-shell hook and was able to login via telnet. After continuing with `pmos_continue_boot`, I'm not able to login via SSH. The device still responds to pings over USB networking, so the kernel should still be alive. Things I tried:
* Enable logging in `/etc/rc.conf`: The log file does not seem to get created (checked after rebooting and logging in over telnet). I tried modifying `rc_log_path` and mounting the partition as read-write to persist the logs across reboots.
* Testing sshd: When chrooting into sysroot from initramfs, sshd/ssh-keygen does work.

Is there any way I can log what happens after `exec switch_root`?

**Comment by PureTryOut** [comment]
Are you trying this with FDE? If so, please disable it for now `pmbootstrap install --no-fde` and make sure the system works without it first.

**Comment by george-hopkins** [comment]
Thanks, so far I tested it without FDE.

**Comment by ollieparanoid** [comment]
Welcome to postmarketOS @george-hopkins!

Some questions:
* What do you see on the screen when it got stuck in the initramfs?
* How did you perform the installation, I guess flashing _both_ the kernel and the initramfs?

A commonly used debugging technique is running the debug-shell hook and connecting via telnet like you did, but instead of `pmos_continue_boot` running the [commands from the init script](https://github.com/postmarketOS/pmbootstrap/blob/ad5328e4a0ad9ea14d8e748d4525bcc1f1c101e0/aports/main/postmarketos-mkinitfs/init.sh.in#L35) one after another to see where it fails (it will probably fail before `switch_root`):

```
$ source /init_functions.sh
$ mount_boot_partition
$ extract_initramfs_extra /boot/...
$ start_charging_mode
$ wait_root_partition
$ resize_root_partition
$ unlock_root_partition
$ resize_root_filesystem
$ mount_root_partition
...
```



CC: @VictorNine who contributed the HTC Desire HD port.

**Comment by george-hopkins** [comment]
Thank you for taking a look!

Before entering via telnet a splash screen shows up for a split second. Displaying a splash screen manually, one can observe the same behaviour:
```
/ # show_splash /splash-loading.ppm.gz
/ # dmesg
[  108.457183] [lcm]spade_sharp_panel_power(1):
[  108.478454] [lcm]lcdc_spade_panel_on
[  108.590240] [lcm]lcdc_spade_panel_on: init sharp_panel
[  108.590301] [lcm]lcdc_spade_panel_on: backlight to 7
[  108.678405] [lcm]lcdc_spade_panel_off: backlight off
[  108.681121] [lcm]lcdc_spade_panel_off: uninit sharp_panel
[  108.682342] [lcm]spade_sharp_panel_power(0):
```
I think it's expected that the splash screen is shown continuously. However, I think this is not the underlying issue (and I'm fine if it's not working correctly, I don't need the screen anytime soon)

When executing the commands manually, everything seems to work correctly. If I activate an LED immediately before the `switch_root` call, it lits up. If I place the statement afterwards, the LED stays dark. I wasn't able to flash the kernel because with the debug hook boot.img is too big (4.2 MB for a 4MB partition). Therefore I use fastboot to boot the kernel.

**Comment by george-hopkins** [comment]
Finally, I figured out why sshd did not start up. After my failed attempt to flash pmOS_boot, the partition was left in a inconsistent state. Because fsck needs to run successfully before sshd, the daemon was never launched. I rebuilt an (empty) partition to keep fsck happy. Now, SSH and weston demos are running smoothly.
