### ISSUE TITLE
"pmb build --src" breaks in special cases

### ISSUE THREAD

**Issue by z3ntu** [postmarketOS/pmbootstrap#1518]
When running `pmb build --src=/mnt/hdd/fairphone/android_kernel_fairphone_FP1 linux-fairphone-fp1` on my APKBUILD I get the following:
```
>>> linux-fairphone-fp1: abuild 3.2.0_rc1-r1
>>> linux-fairphone-fp1: Checking sanity of /home/pmos/build/APKBUILD...
>>> WARNING: linux-fairphone-fp1: No maintainer
>>> linux-fairphone-fp1: Cleaning temporary build dirs...
>>> linux-fairphone-fp1: Copying source from host system: /mnt/hdd/fairphone/android_kernel_fairphone_FP1
'/home/pmos/build/src/android_kernel_fairphone_FP1-b7696d6b1a0743797cda84baf6ba810fa8ba52b0/kernel' -> '/tmp/pmbootstrap-local-source-copy'
ln: /home/pmos/build/src/android_kernel_fairphone_FP1-b7696d6b1a0743797cda84baf6ba810fa8ba52b0/kernel: No such file or directory
>>> ERROR: linux-fairphone-fp1: all failed
```
This happens when the `builddir` variable is not set to the directory where the archive would normally be extracted to (or the directory given with `--src` should be placed) but a subfolder of that (e.g. `builddir="$srcdir/${_repository}-${_commit}/kernel"`) - basically the `$srcdir` directory exists and the `ln` command tries to symlink to `$builddir` but as the parent of `$builddir` doesn't exist in that instance, it fails.

A fix (or workaround?) is adding an additional variable to indicate where the source should be symlinked to and using that, if available.
```diff
diff --git a/aports/device/linux-fairphone-fp1/APKBUILD b/aports/device/linux-fairphone-fp1/APKBUILD
index 3b1cf17b..fdf8b114 100644
--- a/aports/device/linux-fairphone-fp1/APKBUILD
+++ b/aports/device/linux-fairphone-fp1/APKBUILD
@@ -23,7 +23,8 @@ source="
        $_config
        compiler-gcc6.h
 "
-builddir="$srcdir/${_repository}-${_commit}/kernel"
+buildsrcdir="$srcdir/${_repository}-${_commit}"
+builddir="$buildsrcdir/kernel"
 
 prepare() {
        default_prepare
diff --git a/pmb/build/_package.py b/pmb/build/_package.py
index 3a9b74e9..16273734 100644
--- a/pmb/build/_package.py
+++ b/pmb/build/_package.py
@@ -290,7 +290,11 @@ def override_source(args, apkbuild, pkgver, src, suffix="native"):
              }
 
              unpack() {
-                 ln -sv "$_pmb_src_copy" "$builddir"
+                 if [ -z "$buildsrcdir" ]; then
+                     ln -sv "$_pmb_src_copy" "$builddir"
+                 else
+                     ln -sv "$_pmb_src_copy" "$buildsrcdir"
+                 fi
              }
              """
```

**Comment by z3ntu** [comment]
No, because `$_pmb_src_copy` shouldn't be linked into `$builddir` but in my case in the directory above that (so `$builddir/..` basically).

**Comment by ollieparanoid** [comment]
Okay, I've checked out your initial [linux-fairphone-fp1 APKBUILD](https://github.com/z3ntu/pmbootstrap/commit/8017a5496294de73694de6f2faeb7d1e594a17ff#diff-8962c6ea5b340a9eac03c343ddc5dbf6) and applied the patch I wrote above to `pmb/build/_package.py`. As you wrote, that's not enough, it fails because during the kernel build it tries to access `../mediatek/build/kernel/common.mk`.

But I don't think introducing a new `buildsrcdir` variable would be a good solution. What do you think about changing your `builddir` to the real root of the source instead and adjusting the rest of the APKBUILD code to use "$builddir/kernel" where it would use "$builddir"?

```shell
builddir="$srcdir/${_repository}-${_commit}"
```

The APKBUILD reference describes `$builddir` as follows:
> This variable should point to the directory inside the srcdir **where the main package source is unpacked.** This is typically $srcdir/$pkgname-$pkgver. It’s used by the default prepare() function as a working directory when applying patches.

**Comment by z3ntu** [comment]
Hmm fair. I thought I was smart by just changing that variable :wink: Thanks for the help
