### ISSUE TITLE
rootfs not found on rx-51 (Nokia N900)

### ISSUE THREAD

**Issue by craftyguy** [postmarketOS/pmbootstrap#152]
Building pmos for the rx-51, and installing it to an sdcard (./pmbootstrap install --sdcard /dev/sdX) results in a kernel panic due to the kernel not being able to find a root filesystem (see screenshot)

My N900 is using u-boot from here: http://maemo.org/downloads/product/Maemo5/u-boot-flasher/

![img_20170714_185727](https://user-images.githubusercontent.com/1474209/28235679-a00e2e46-68c7-11e7-9d27-e362bf87638b.jpg)

Sorry for the fuzzy photo, the watchdog timer on the N900 reboots the device fairly soon after the kernel panics, so I had to be fast.

**Comment by craftyguy** [comment]
I have tried adding this to the kernel cmdline, but it still fails with the same error: `rootwait root=/dev/mem0`

**Comment by MartijnBraam** [comment]
Ok strange, looks like it's not finding the initramfs, I made video's from my n900 for debugging to see all the errors since they scroll very quickly,

**Comment by craftyguy** [comment]
Turns out the issue was that the initrd that is generated by mkinitfs has a filename of "uInitrd-nokia-rx51", so the boot.scr needs to be tweaked. PR #155 addresses this.
