### ISSUE TITLE
Can't get /dev/block/sda line

### ISSUE THREAD

**Issue by therealkappa11** [postmarketOS/pmbootstrap#1542]
I have a problem while trying to root phone like on this tutorial:
https://forum.xda-developers.com/tmobile-g6/how-to/root-h872-to-including-11g-t3775518
On **PROCEDURE PART 2: Installing TWRP** after **lsof** can't get **/dev/block/sda** line...
These is no such line at all, many others but nothing like that...
I would be grateful for any suggestions. Thanks

**Comment by MayeulC** [comment]
Wow, that's a complex procedure (not clearly explained, with that). My guess is that you are looking for something more like mmcblk0 or similar...

But... Does this have anything to do with PostmarketOS? I would have asked on the XDA forums, or maybe [##postmarketos-offtopic](https://riot.im/app/#/room/#postmarketos-offtopic:disroot.org).

**Comment by PureTryOut** [comment]
Yeah I'm sorry this is not related to postmarketOS. Either come join us on [##postmarketos-offtopic](https://matrix.to/#/#postmarketos-offtopic:matrix.org) or ask on the device section on XDA-developers.
