### ISSUE TITLE
Testing the new Raspberry Pi kernel update

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#1567]
We are directly using the Raspberry Pi kernels from Alpine in postmarketOS, and they have just been updated. Could we check if the new kernels work properly? @clandmeter from Alpine asked if we could test this, so potential problems could be fixed before the upcoming 3.8 release of Alpine. And besides helping out our Alpine friends, it would be good to know whether it works for pmOS uses as well!

(based on the list of who has which device that @drebrez created in #1501):
- [x] Raspberry Pi Zero W (@steamp0rt, @yangxuan8282)
- [ ] Raspberry Pi 1 Model B (@duncanguthrie, @yangxuan8282?)
- [x] Raspberry Pi 2 Model B (@drebrez, @yangxuan8282?)
- [x] Raspberry Pi 3 (@MartijnBraam, @PureTryOut)
- [x] Raspberry Pi 3 B+ (@yangxuan8282)

I've already mentioned the networking problem #1547 to @clandmeter. CC: @ncopa

**Comment by yangxuan8282** [comment]
@ollieparanoid 
it happen yesterday I wrote a small [script](https://gist.github.com/yangxuan8282/d40d590779b93d07effba3d556570652) to install alpine on rpi, after test the new kernel, I can confirm it works on zero w, rpi 3b, 3b+(5G wifi not tested, no idea how to set region on alpine), seems that scripts not work for aarch64(maybe need uboot), it stuck at color splash screen, it indicate that can't found kernel, and I'm not familiar with arm64, so not sure if the aarch64 linux-rpi kernel works
will test on pmos later

**Comment by PureTryOut** [comment]
Well I can confirm it definitely works on the RPi3, but it didn't resolve the network issue I'm having. Everything else appears to work fine just as before though.

**Comment by drebrez** [comment]
@ollieparanoid I can confirm that works on the RPI 2 Model B, I've upgraded the packages, rebooted and everything was working as before.
@PureTryOut FYI: I don't have any issues with the ethernet network, constant delay of 15-20ms (depending what I ping) and 0% packet loss

**Comment by ollieparanoid** [comment]
@ncopa, @clandmeter: Assuming that the Raspberry Pi 1 should work when the Zero works (because they use the same kernel), all versions have been tested :+1:

Slightly off topic pi + Alpine related questions to you:
* Would it be possible to remove the dependency to `linux-firmware-brcm` in the raspberry pi kernel packages? (We've [made firmware optional](https://postmarketos.org/blog/2018/06/09/one-year/#libhybris-and-optional-proprietary-components) for all other devices, so it would be nice to have that for the Pi as well)
* The Raspberry Pi 3B+ requires a newer version of the bootloader files ([see our forked aport](https://github.com/postmarketOS/pmbootstrap/blob/7ab4e3bef9e67ee297079854fe29dea55bb00ba1/aports/temp/raspberrypi-bootloader/APKBUILD)). Could you update them, or would you like a PR?
* What's the best way to talk about Raspberry Pi development in Alpine? We've tried a PR and writing to the alpine-devel mailing list, but that got ignored. Is it best to tag you in #alpine-devel (IRC)?

**Comment by clandmeter** [comment]
* Im not sure about this one, currently our build scripts do not support pulling in brcm firmware other than depending on it. If you have some suggestions please add a PR for it.
* In our rpi releases we use https://github.com/alpinelinux/aports/blob/master/scripts/mkimg.arm.sh#L76
Which is a later commit as yours (it matches the kernel version as we ship).
* PR's are the way to contribute but sometimes they are missed. You can always ping me on IRC I'm there most of the time.

**Comment by ollieparanoid** [comment]
@yangxuan8282: do you or somebody else know what these files do, and if we need them in Alpine/postmarketOS?
> start_x.elf start_cd.elf start_db.elf fixup_x.dat fixup_cd.dat fixup_db.dat

They are from here:
https://github.com/raspberrypi/firmware/tree/master/boot

**Comment by yangxuan8282** [comment]
@ollieparanoid 
here is some info: 
https://www.raspberrypi.org/forums/viewtopic.php?p=198420#p198420
https://elinux.org/RPi_Software

in short:

- fixup.dat, start.elf: the most common use one

- fixup_cd.dat, start_cd.elf: used when GPU memory is set to 16 MB 

- fixup_x.dat, start_x.elf: testing version

**Comment by yangxuan8282** [comment]
hi, @clandmeter ,since the linux-rpi have aarch64 support, do you have interest add aarch64 support for other rpi related packages, like omxplayer, raspberrypi, raspberrypi-libs
I have another question maybe off topic, can we network boot rpi with alpine?

**Comment by clandmeter** [comment]
@yangxuan8282 

* omxplayer is it support by aarch64? I cant find any reference it does.
* yes we can update raspberrypi{-libs} as it seems to be supported for aarch64
* network boot should work if you enable it, i just didnt test it yet (its on my todo)

**Comment by yangxuan8282** [comment]
@clandmeter 

- you have been correct, seems omxplayer not support aarch64, I should try it first

- for `raspberrypi` it have aarch64 support if it use -DARM64=ON (seems you have just pushed the commit)

- rpi alpine network boot not work for me, currently I can only pxe boot Raspbian ( some os based on raspbian should also works), LibreELEC and Lakka, setup with this [docker](https://github.com/yangxuan8282/rpi3-pxe-docker), since the current `linux-rpi` kernel config file based on downstream one, I guess it maybe related to initramfs

**Comment by clandmeter** [comment]
@yangxuan8282 to answer your question:

[Alpine Linux 3.8 RPi netboot](http://dev.alpinelinux.org/~clandmeter/other/rpi-netboot.mp4)

I made some changes locally as you need some initramfs features to do netboot.

**Comment by yangxuan8282** [comment]
@clandmeter 
cool, would you create PR to alpine or share some details?

by the way, here is a package for rpi bluetooth: https://github.com/postmarketOS/pmbootstrap/blob/master/aports/firmware/firmware-pi-bluetooth/APKBUILD , it include firmware, udev rules, openrc init scripts

since the linux-firmware-brcm have added bluetooth firmware, but the udev rules and openrc init scripts
maybe helpful for users, do you think it sense to make it alpine upstream package (name like pi-bluetooth-openrc or something else)? I can create PR

**Comment by yangxuan8282** [comment]
@clandmeter 
can we use partuuid to select root device on alpine with `root=PARTUUID= ` in `cmdline.txt` like raspbian? then we can boot from usb when use sys mode(without modified `root=/dev/mmcblk0p2` to `/dev/sda2` )
actually I'm kind of curiosity how raspbian able to netboot and choose root dev use partuuid without use initramfs (maybe I'm wrong, but seems it not use it)
