### ISSUE TITLE
Plasma mobile regression

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#1574]
I'm a bit busy these days, so I'm only scrolling over the chat backlog currently, not reading every message anymore. But @PureTryOut and @bhush9 mentioned, that plasma mobile does not work since the last update.

Regarding the process:
* How about @PureTryOut and I check if PlaMo is still working at least in Qemu before making the PR/merging the PR (currently we are both only testing if it compiles, right)?
* It would be very nice if someone could create an issue in the bug tracker about such problems, even if there aren't logs available yet. Then the issue is more visible than somewhere in the chatlog.

---

@PureTryOut, @bhush9: do you have any details/logs about the issue, or any way I could hep out with this?

**Comment by PureTryOut** [comment]
Sorry for that, I agree we should've made an issue about that. I've been a bit busy and it slipped through.

I agree, we should start testing it in at least Qemu before merging. Right now I indeed only check if it compiles, which clearly isn't good enough.

Sadly there is no useful log so far, kwin just reports "no GPU found" and then quits. I'm not sure if @bhush9 has done any research on it since our conversation.

**Comment by bhush9** [comment]
Is it any possibility to force pmb to install older packages? I want to ensure that it is indeed Plasma regression and not anything else

**Comment by ollieparanoid** [comment]
You can manually download the old apks (they are still up/I have them archived and can upload them again if you tell me specific versions) and then install them with: `apk add -u /path/to/downloaded-apks/*.apk`. There's no super convenient way to do it from pmbootstrap though.

**Comment by ollieparanoid** [comment]
I did some regression testing, and now I'm sure that "Update Plasma to 5.13.0 (#1555)" broke it. Both tests were done directly after another, so the issue can not be related to Alpine package changes over the last days.

@bhush9: The steps from 2. should allow to easily reproduce this on your PC. How do we proceed here?

---

### 1. Test: before the upgrade:
* checked out d77f807
* updated `py-requests` (as in https://github.com/postmarketOS/pmbootstrap/commit/de1f2449174ea1019ef793395c3f02c093bebe01), because otherwise `extra-cmake-modules` won't build
* selected qemu-amd64 and plasma-mobile in `pmbootstrap init`
* built all packages from scratch from that commit with the pmOS binary repo disabled and ran qemu (ccache was really useful here)
```
pmbootstrap -y zap -p && yes | pmbootstrap --mirror-pmOS="" install --no-fde && pmbootsrap qemu
```
* Test result: it's working fine (top and bottom bars, I can start elisa and the dial app, pmOS wallpaper etc.)

### 2. Test: after the upgrade
* checked out master (which has `py-requests` updated now)
* selected qemu-amd64 and plasma-mobile in `pmbootstrap init`
* qemu installation using pre-built packages:
```
pmbootstrap -y zap && yes | pmbootstrap install --no-fde && pmbootstrap qemu
```
* Test result: PlaMo does not show up, the boot process hangs at the `/etc/motd` getting printed after the OpenRC output is through.

Logging in via SSH and calling `logread`:
```
Jun 12 20:21:43 qemu-amd64 user.notice user:plasma-mobile: kwin_core: Platform does not support input, enforcing libinput support
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile: kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5084:46: this compose sequence is a duplicate of another; skipping line
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile:
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile: kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5086:48: this compose sequence is a duplicate of another; skipping line
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile:
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile: kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5088:48: this compose sequence is a duplicate of another; skipping line
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile:
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile: kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5092:47: this compose sequence is a duplicate of another; skipping line
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile:
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile: kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5094:46: this compose sequence is a duplicate of another; skipping line
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile:
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile: kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5102:48: this compose sequence is a duplicate of another; skipping line
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile:
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile: kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5106:46: this compose sequence is a duplicate of another; skipping line
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile:
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile: kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5108:46: this compose sequence is a duplicate of another; skipping line
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile:
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile: kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5112:45: this compose sequence is a duplicate of another; skipping line
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile:
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile: kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5115:46: this compose sequence is a duplicate of another; skipping line
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile:
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile: kwin_xkbcommon: XKB: created compose table from locale C with path /usr/share/X11/locale/en_US.UTF-8/Compose
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile:
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile: kglobalaccel-runtime: Failed to register service org.kde.kglobalaccel
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile: kwin_core: Init of kglobalaccel failed
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile: kwin_core: Session path: "/org/freedesktop/ConsoleKit/Session1"
Jun 12 20:21:47 qemu-amd64 daemon.warn console-kit-daemon[1161]: WARNING: failed to mute FD with KDSKBMUTE
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile: kwin_core: "ConsoleKit"  seat: "Seat1" / "/org/freedesktop/ConsoleKit/Seat1"
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile: kwin_core: "ConsoleKit"  seat: "Seat1" / "/org/freedesktop/ConsoleKit/Seat1"
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile: kwin_core: Gained session control
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile: Couldn't start kglobalaccel from org.kde.kglobalaccel.service: QDBusError("org.freedesktop.DBus.Error.Disconnected", "Not connected to D-Bus server")
Jun 12 20:21:47 qemu-amd64 user.notice user:plasma-mobile: kwin_wayland_drm: Did not find a GPU
````

**Comment by bhush9** [comment]
https://cgit.kde.org/kwin.git/commit/?id=99376d38f69f6bcc13d7a8ebdb679b7c18e30586 found the culprit ... Will propose fix, but can you verify reverting this fixes it?
