### ISSUE TITLE
'PROC_PID_INIT_INO' undeclared here (not in a function)

### ISSUE THREAD

**Issue by ThomasOHale** [postmarketOS/pmbootstrap#1578]
I get the following error while compiling. Google search returns nothing useful.

Here is my APKBUILD https://pastebin.com/85gTRSHw
Here is my defconfig https://pastebin.com/VHp5J9bi
Below is the output of 'pmbootstrap log'

```
  CC      kernel/exec_domain.o
  CC      kernel/panic.o
  CC      kernel/printk.o
  CC      kernel/cpu.o
  CC      kernel/exit.o
  CC      kernel/itimer.o
  HZFILE  kernel/hz.bc
  BC      kernel/timeconst.h
  CC      kernel/time.o
  CC      kernel/softirq.o
  CC      kernel/resource.o
  CC      kernel/sysctl.o
  CC      kernel/sysctl_binary.o
  CC      kernel/capability.o
  CC      kernel/ptrace.o
  CC      kernel/timer.o
  CC      kernel/user.o
  CC      kernel/signal.o
  CC      kernel/sys.o
  CC      kernel/kmod.o
  CC      kernel/workqueue.o
  CC      kernel/pid.o
kernel/pid.c:81:15: error: 'PROC_PID_INIT_INO' undeclared here (not in a function)
  .proc_inum = PROC_PID_INIT_INO,
               ^~~~~~~~~~~~~~~~~
make[1]: *** [scripts/Makefile.build:308: kernel/pid.o] Error 1
make: *** [Makefile:952: kernel] Error 2
>>> ERROR: linux-lg-v500: all failed
(000477) [20:51:56] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

If anyone has any ideas it would be much appreciated

**Comment by ollieparanoid** [comment]
Welcome to postmarketOS @ThomasOHale :tada: 

For some reason, your `kernel/pid.c` does not have `PROC_PID_INIT_INO` defined.

A [search](https://github.com/LineageOS/android_kernel_lge_v500/search?q=PROC_PID_INIT_INO&unscoped_q=PROC_PID_INIT_INO) shows that it is defined in [`include/linux/proc_fs.h`](https://github.com/LineageOS/android_kernel_lge_v500/blob/651d21fe7292effc0793c4f26ab34b60c27fff9a/include/linux/proc_fs.h#L35).

I have not tested this, but it should be possible to fix this by adding `#include <linux/proc_fs.h>` to the beginning of `kernel/pid.c` (e.g. [below the other includes](https://github.com/LineageOS/android_kernel_lge_v500/blob/651d21fe7292effc0793c4f26ab34b60c27fff9a/kernel/pid.c#L38)) with a patch.

See also: [How to create a patch](https://wiki.postmarketos.org/wiki/How_to_create_a_patch_when_packaging_software)

**Comment by MayeulC** [comment]
Also don't hesitate to join us on [Matrix or IRC](https://wiki.postmarketos.org/wiki/Matrix_and_IRC) to get more support as well!

**Comment by ThomasOHale** [comment]
Yes, that worked! Thanks for the help.
