### ISSUE TITLE
Boot from charging mode

### ISSUE THREAD

**Issue by 5ilver** [postmarketOS/pmbootstrap#1588]
When my powered down device is connected to a usb charger the device wakes and enters a charging mode that displays a large battery. The power button wakes the device for 3 seconds, or turns the screen back off. There seems to be no way to initiate a normal boot from this mode. I notice that a power press and hold does not count toward the screen off timeout and 7s after the screen turns off the device will reboot. Perhaps a shorter hold could be trapped and used to initiate a reboot into normal mode with a confirmation message.

I am using a Galaxy S III i9300

**Comment by 5ilver** [comment]
Wrong repo, dupe of  https://github.com/postmarketOS/charging-sdl/issues/17

**Comment by drebrez** [comment]
@5ilver FYI, I also have a device that has a charging mode directly in the bootloader. It will never use the charging-sdl and that's fine, At least it charges 👍
