### ISSUE TITLE
Telnet connection refused

### ISSUE THREAD

**Issue by derlorenz** [postmarketOS/pmbootstrap#164]
Hello,

currently I am trying to port postmarketOS to my "old" Xperia Z2. I am basing the port on the Sony Xperia Z1 Compact port. I successfully built my own kernel and booted it up - the device gets recognized in ifconfig but the telnet connections fails with connection refused. I also did an nmap scan on the device and as it seems all ports are closed. Also I don't see any logo on the screen. Did I miss something important?

**Comment by MartijnBraam** [comment]
what's the output from ifconfig?

**Comment by derlorenz** [comment]
```
ens33     Link encap:Ethernet  HWaddr 00:0c:29:9e:5f:ee  
          inet addr:192.168.168.128  Bcast:192.168.168.255  Mask:255.255.255.0
          inet6 addr: fe80::fd28:2cd8:2548:38e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:396156 errors:0 dropped:0 overruns:0 frame:0
          TX packets:147693 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:566068266 (566.0 MB)  TX bytes:9808118 (9.8 MB)

ens35u1   Link encap:Ethernet  HWaddr 2e:2a:03:1f:fc:a9  
          inet addr:172.16.42.10  Bcast:172.16.42.255  Mask:255.255.255.0
          inet6 addr: fe80::600:d6e6:4cc0:6c29/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:6 errors:0 dropped:0 overruns:0 frame:0
          TX packets:24 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:898 (898.0 B)  TX bytes:5164 (5.1 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:141279 errors:0 dropped:0 overruns:0 frame:0
          TX packets:141279 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:48918509 (48.9 MB)  TX bytes:48918509 (48.9 MB)
```

I am compiling in VMWare if that matters

**Comment by ollieparanoid** [comment]
You get an IP already, this is good!
Just to make sure, are you connecting with `telnet 172.16.42.1`?

**Comment by derlorenz** [comment]
Yes, that's what I did. I also did a portscan with nmap on the devices IP but no port seems to be open.

**Comment by ollieparanoid** [comment]
* Could it be that VMWare acts as a firewall here?
* Which distribution do you run inside VMWare?

**Comment by derlorenz** [comment]
I run Ubuntu 16.04 in the VM.

I don't think that VMWare blocks it because I also have a local Ubuntu 16.04 installtation which I just tried and got the same error.

Is it possible that something kills the telnet server or it doesn't start at all?

**Comment by ollieparanoid** [comment]
we haven't seen it being killed/not starting on the other devices, but yeah, it could be.
You could try to add the `usb-shell` hook (which starts telned on another port), see the end of the porting guide. Maybe that works.

**Comment by derlorenz** [comment]
What do you mean by adding the usb-shell hook?

**Comment by drebrez** [comment]
@derlorenz you can add the usb-shell hook using the commands explained [here](https://github.com/postmarketOS/pmbootstrap/wiki/Boot-process#getting-a-shell-in-the-initramfs)

**Comment by derlorenz** [comment]
Still not working.
`telnet: could not resolve 172.16.42.1:24/telnet: Name or service not known`

**Comment by drebrez** [comment]
@derlorenz you can look at this page [Initramfs development](https://github.com/postmarketOS/pmbootstrap/wiki/Initramfs-development) which explains how to debug the initramfs.

Some time ago I managed to investigate an issue by changing a bit the [init script](https://github.com/postmarketOS/pmbootstrap/blob/master/aports/postmarketos-mkinitfs/init.sh.in)

if you added the usb-shell hook you can try moving the `while true` loop before the `# Switch root`, this means that the telnetd doesn't get killed and you should be able to connect.

Then you can try to execute the remaining commands manually to see what happen.

**Comment by derlorenz** [comment]
Thanks for your help. Sadly it still doesnt work. I got the same Error as before. Also nmap still reports that no ports are open at all. Maybe someone from the [Xperia Z2 Tablet](https://github.com/postmarketOS/pmbootstrap/wiki/Xperia-Z2-Tablet) Team can help? @opendata26 @rcstar6696

**Comment by drebrez** [comment]
@derlorenz Here are some tests you can try:
- Try to turn on/off some leds by adding an initfs-hook ([see example](https://github.com/drebrez/pmbootstrap/blob/f63dd65fe4ea4f36cabf2143cd7906190b6f4759/aports/device-htc-bravo/initfs-hook.sh))
- Compare the kernel options with the config file of a working device
- Boot the TWRP initramfs using the kernel compiled with pmbootstrap
- Get a working ROM and investigate the various android init.rc files for settings that have to be done (for example something like [this](https://github.com/postmarketOS/pmbootstrap/blob/master/aports/device-samsung-i9070/initfs-hook.sh#L13-L14))

**Comment by opendata26** [comment]
Strange, my own build works fine (apart from fb) on my z2, what model, what kernel?

**Comment by ollieparanoid** [comment]
@derlorenz, just to make sure: what is your telnet command? It should be
```shell
telnet 172.16.42.1 # for the password prompt
telnet 172.16.42.1 24 # for the usb shell hook
```

**Comment by derlorenz** [comment]
@ollieparanoid That was my mistake, I was trying to connect with telnet 172.16.42.1:24, now the usb shell hook works.

@opendata26 
Model: D6503
Kernel: https://github.com/rcstar6696/android_kernel_sony_msm8974

I now connected via telnet and turned some LEDs on and off. I also tried executing the commands from init.sh.in. The command `show_splash /splash2.ppm.gz ` failed with command not found but I  commented it out because it's just the splash screen. 

`umount /dev/pts` failed with `resource busy` but `umount -l /dev/pts` worked just fine

`umount /dev` failed with `invalid argument` but from my knowledge that just means theres nothing mounted on it so it doesn't matter

The `switch_root command` just closes the telnet shell and outputs it's usage instructions.

**Comment by ollieparanoid** [comment]
`show_splash` and other commands do not work, because you would need to source the [`init_functions.sh`](https://github.com/postmarketOS/pmbootstrap/blob/master/aports/postmarketos-mkinitfs/init_functions.sh) first:
````shell
source /init_functions.sh
```

**Comment by PureTryOut** [comment]
Just to make sure, are you sure installed pmOS to either the device or the sdcard as well? I had this same issue before, but it ended up being me not reading the documentation properly and only flashing the kernel and initramfs to the phone, without giving it a system to boot.

Once I installed the system to an sdcard, plugged that into my phone, and then booted the kernel I could suddenly connect fine with telnet.

**Comment by derlorenz** [comment]
@PureTryOut I installed the System via 
    pmbootstrap flasher flash_system
Not on to the SD card, but I don't think it will make a difference.

**Comment by ollieparanoid** [comment]
If you can't get it working, consider asking for help in the [channel](https://github.com/postmarketOS/pmbootstrap/wiki/Matrix-and-IRC).

**Comment by ollieparanoid** [comment]
This ticket does not seem to reflect the status of the Z2 port anymore (see the wiki, @opendata26 did great porting work and now most stuff seems to work), so I'm closing this. Feel free to comment on it to reopen it.
