### ISSUE TITLE
Device naming conventions

### ISSUE THREAD

**Issue by BlitzKraft** [postmarketOS/pmbootstrap#17]
I think we should have an established naming to avoid possible duplicates. I looked through the wiki and couldn't find any established conventions. So, I propose one. 

    {device/linux}-{brand}-{device codename/model number}

Wherever possible, device codename is preferred over the model number.

**Comment by dzervas** [comment]
I think brand is not needed. We can follow lineageos device naming (`{device/linux}-{codename}`) to be able to script any data pulling from lineageos in the future (ex. blobs)

-----Original Message-----

**Comment by MartijnBraam** [comment]
I found that even lineageos doesn't consistently name their stuff, sometimes dashes, sometimes underscores. the repository name for the nexus 5 is completely different than the one for the nexus 4

**Comment by dzervas** [comment]
Oh, you're right. We should settle this now though, on the very start of the project (right?)

-----Original Message-----

**Comment by BlitzKraft** [comment]
Yup. 

I am in favor of including device brand names (samsung, lg, etc.,) just because it makes searching easier. Especially when someone new to the repo doesn't know if the phone is referred by the codename or the model number (for example nexus 5 is hammerhead, model number E960), they can just narrow down available devices by brand.

**Comment by DeeDeeG** [comment]
As a complete noob to this stuff, I'd find having the brand name in there would make it easier to understand  if my device has source code already. The codenames are pretty odd and not intuitive. Just my two cents. I can see why it would be confusing if the names here were very different than the lineage ones, though. But my gut instinct is to have the brands. 

(I'm hoping to eventually contribute to this project! Haven't ported anything to an Android device yet, though!)

**Comment by ollieparanoid** [comment]
Thanks everyone for the proposal and input on this!

I have created the following page based on what you've said:
https://github.com/postmarketOS/pmbootstrap/wiki/Package-naming-convention
