### ISSUE TITLE
Create generic interface for handling device-specific ACPI events in user-definable ways

### ISSUE THREAD

**Issue by craftyguy** [postmarketOS/pmbootstrap#178]
There should be a way to handle ACPI events from things like button presses & switches on a device in a way that is device agnostic and supports users re-defining actions.

ACPI events are not generic, but seem to be specific to different devices even though the 'button' is shared. One example is a 'power button', which might generate different ACPI events on different devices, but the desired behavior for such event might the same across different devices (e.g. to turn off the display or power off the device)

One idea of how this flow would play out, using an example of a keyboard slider that generates a specific, unique (to the specific device) ACPI event:

1) user slides out keyboard on device 

2) acpid receives `KBD_SLIDE/00BB0000` (I made this up, but the point is this can be specific to devices/hardware and is not generic)

3) acpid runs generic handler which matches `KBD_SLIDE/00BB0000` with `KEYBOARD_SLIDE_OUT` (a 'generic' event to associate with what just happened) 

4) The generic handler calls `xdg-open pmarketos:keyboard_slide_out` to run whatever the user wants

5) pmarketos:ACTIONs are defined in `/etc/xdg/mimeapps.list`, device maintainers can provide default settings for their respective devices (e.g. `device-nokia-rx51` provides some defaults for acpi events specific to the rx51)

6) The device-specific-ACPI-event to generic-event mapping is made in some .conf file accessible by the handler, defined by device maintainers, and provided in the device-specific package (e.g. `device-nokia-rx51`)

**Comment by MartijnBraam** [comment]
This stuff is mostly handled by intents in android but linux doesn't really have something like this as far as I know. Also do you have any idea how things like long pressing the power button are handled? can we fire a seperate script with acpid for that?

**Comment by craftyguy** [comment]
@MartijnBraam if it generates a separate acpid event it would be trivial to support a different action. You bring up a good point though, I don't know. Now that I have a kernel which supports NETLINK and a working acpid package, I can test this out later when I get more time. If it does not end up generating a different event, then maybe my suggestion is a no-op :(

**Comment by ollieparanoid** [comment]
I like this concept! @MartijnBraam raises a good concern though with the long presses, but you can test that. We might even extend acpid at some point to support long presses, if necessary, but it would be a good start even without the long presses!

For the Android devices I have tested, the power button turns off the device regardless of the OS running after pressing it for a few seconds.

BTW: I've realized that we will need an OpenRC service for acpid in the long run (I think Gentoo already has one).

One more thought, I'd prefer `pmos` or `postmarketos` over `pmarketos` :)
Actually `postmarketos` should not have any conflicts, and we've used the spelled out version elsewhere already (`postmarketos-base`, `postmarketos-mkinitfs`, ...).

**Comment by craftyguy** [comment]
Closed via c85c15adfcdc716e30e042314db75b659b3cdb4c. Other devices can use this commit as an example for implementing similar functionality
