### ISSUE TITLE
Default WL_CALIBRATION

### ISSUE THREAD

**Issue by MartijnBraam** [postmarketOS/pmbootstrap#182]
It looks like most phones are very close to being calibrated already and I think the calibrations are already done in the touchscreen controller themselves.

For example the calibration for the htc ace:
```
ENV{WL_CALIBRATION}="0.963488 0.004947 14.422623 -0.076271 1.026566 -7.303467"
```
Is very close to a empty calibration:
```
ENV{WL_CALIBRATION}="1 0 0 0 1 0"
```

The formula from the calibration values is:

```
x' = Ax + By + C
y' = Dx + Ey + F
```
The relative big change in the third and last parameter is because those are in pixel values and those are quite close together on phones.

Maybe it's better to use the emtpy calibration for most phones instead the one copied from the mako while porting.

**Comment by craftyguy** [comment]
Just an idea, but what if weston-calibrator is called once on 'first boot' to generate the necessary values for WL_CALIBRATION? This way users have a chance to adjust their screen without having to rely on someone who may not be tapping completely straight :P

**Comment by MartijnBraam** [comment]
Yeah but the point is that most devices should work perfectly fine without a calibration, just by using the empty calibration which maps the pixels from the touchscreen exactly to the display pixels. The only devices that should require user calibration are the ones with a resistive touchscreen like the n900

**Comment by drebrez** [comment]
@MartijnBraam The last device I ported, huawei y530, I didn't added the WL_CALIBRATION and worked fine. I will try to remove it also from my other device and see if they work fine 👍

**Comment by montvid** [comment]
All the devices need empty callibration because if you rotate the screen you need to recalibrate the touchscreen. It is not done automaticaly. At least not in Mate and Hildon.

**Comment by ollieparanoid** [comment]
@montvid: I am not 100% sure, but I think this config is only being used by Weston, and not by X11 (maybe through libinput? but nobody reported that being the case).

**Comment by craftyguy** [comment]
libinput uses a different calibration variable: `LIBINPUT_CALIBRATION_MATRIX`

I configure it on the nokia-rx51 device in a udev rule so that touch works correctly under X11 (when using the libinput driver)

**Comment by montvid** [comment]
Weston and X11 Libinput uses the udev values in the file to calibrate the ts. I use this for X11 and it works fine:
https://github.com/postmarketOS/pmbootstrap/blob/master/aports/device/device-asus-flo/90-android-touch-dev.rules

**Comment by montvid** [comment]
Btw i don't know why but osk-sdl uses a different method so we need another file pointercal unfortunately.

**Comment by craftyguy** [comment]
osk-sdl uses tslib, which has its own pointer calibration settings. I recall @drebrez finding a way to translate between all of the different calibration formats, but it would require making a new tool to do this translation. I didn't think generating a handful of calibration files ONCE for a device was worth the effort of making a new tool, integrating it into the APKBUILD process and pushing updates for all devices :)

**Comment by ollieparanoid** [comment]
**NOTE:** The `lenovo-karate` requires screen calibration, see https://github.com/postmarketOS/pmbootstrap/pull/942#discussion_r153690802.

**Comment by ollieparanoid** [comment]
The porting guide was updated to recommend to try without `WL_CALIBRATION` first.  We have noticed that it is not possible for all Androids we have to remove that line and still have it working.

Closing.
