### ISSUE TITLE
Provide logs online for the IRC/matrix channel

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#188]
It would be nice if someone could set up a bot, that does this.

**Comment by ata2001** [comment]
This tool could probably do it: https://gitlab.com/argit/matrix-recorder

**Comment by ollieparanoid** [comment]
Nowadays we can read the backlog here:
https://chat.disroot.org/#/room/#postmarketos:disroot.org

No bot necessary 👍
