### ISSUE TITLE
TypeError when running pmbootstrap install

### ISSUE THREAD

**Issue by ata2001** [postmarketOS/pmbootstrap#189]
Command:
```
pmbootstrap install --sdcard=/dev/block/mmcblk0
```
Log:
```
(005095) [22:44:26] Calculate depends of packages ['postmarketos-mkinitfs'], arch: armhf
(005095) [22:44:26] ERROR: 'NoneType' object is not subscriptable
(005095) [22:44:26] Run 'pmbootstrap log' for details.
(005095) [22:44:26] See also: <https://postmarketos.org/troubleshooting>
(005095) [22:44:26] Traceback (most recent call last):
  File "./pmbootstrap.py", line 53, in main
    getattr(pmb.helpers.frontend, args.action)(args)
  File "/home/ata/Softwares/pmbootstrap/pmb/helpers/frontend.py", line 73, ininstall
    pmb.install.install(args)
  File "/home/ata/Softwares/pmbootstrap/pmb/install/install.py", line 107, ininstall
    pmb.chroot.initfs.build(args, flavor, suffix)
  File "/home/ata/Softwares/pmbootstrap/pmb/chroot/initfs.py", line 29, in build
    pmb.chroot.apk.install(args, ["postmarketos-mkinitfs"], suffix)
  File "/home/ata/Softwares/pmbootstrap/pmb/chroot/apk.py", line 190, in install
    args, build, arch, package, packages_installed):
  File "/home/ata/Softwares/pmbootstrap/pmb/chroot/apk.py", line 129, in install_is_necessary
    data_repo["version"])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by ata2001** [comment]
It's gone, closing.

**Comment by antonok-edm** [comment]
Would like to mention that I just got this exact same error today using `pmbootstrap install`; it also disappeared on the second run of `pmbootstrap install` immediately after.
Only really notable thing I did was a `pmbootstrap zap -hc -p` before rebuilding device and kernel packages and installing.

**Comment by ollieparanoid** [comment]
While analyzing #341, I think I found the cause for *this* bug:
* We [cache](https://github.com/postmarketOS/pmbootstrap/blob/6a129669a389446bdbbb2bf6e8576043bc80bf29/pmb/helpers/repo.py#L132-L133) a list of APKINDEX files for the runtime of one pmbootstrap command
* When generating that list, files that do not exist, get ignored
* The cache does not get cleared after creating a new APKINDEX file! So after the first `armhf` package has been built for example, the cache is invalid, but still gets used
* When you run `pmbootstrap install` the second time, it directly finds the APKINDEX and therefore doesn't fail anymore.

...so I understand it now. Coming up: a patch, that actually fixes this :)
