### ISSUE TITLE
pmbootstrap.py init i9100 && install fails with /usr/bin/abuild Permission Denied

### ISSUE THREAD

**Issue by bkero** [postmarketOS/pmbootstrap#19]
I'm attempting to build a bone-stock chroot for a samsung-i9100 device.

bkero@Daedalus:~/code/pmbootstrap$ ./pmbootstrap.py install
[15:28:27] *** (1/5) PREPARE NATIVE CHROOT ***
[15:28:27] *** (2/5) CREATE DEVICE ROOTFS (samsung-i9100) ***
[15:28:28] (native) build x86_64/gcc-armhf-6.3.0-r4.apk
[15:29:42] ERROR: Command failed: (native) % cd /home/user/build && su user -c 'CARCH=x86_64 abuild -d'
[15:29:42] Run 'pmbootstrap log' for details.

true "AR_FLAGS=rc" "CC_FOR_BUILD=gcc" "CC_FOR_TARGET=/home/user/build/src/build-cross-final/./gcc/xgcc -B/home/user/build/src/build-cross-final/./gcc/" "CFLAGS=" "CXXFLAGS=-D_GNU_SOURCE" "CFLAGS_FOR_BUILD=-Os -fomit-frame-pointer -Os -fomit-frame-pointer" "CFLAGS_FOR_TARGET=" "INSTALL=/usr/bin/install -c" "INSTALL_DATA=/usr/bin/install -c -m 644" "INSTALL_PROGRAM=/usr/bin/install -c" "INSTALL_SCRIPT=/usr/bin/install -c" "LDFLAGS=" "LIBCFLAGS=" "LIBCFLAGS_FOR_TARGET=" "MAKE=make" "MAKEINFO=makeinfo --split-size=5000000 --split-size=5000000   " "SHELL=/bin/bash" "RUNTESTFLAGS=" "exec_prefix=/usr" "infodir=/usr/share/info" "libdir=/usr/lib" "includedir=/usr/include" "prefix=/usr" "tooldir=/usr/armv6-alpine-linux-muslgnueabihf" "gxx_include_dir=/usr/armv6-alpine-linux-muslgnueabihf/include/c++/6.3.0" "AR=/usr/armv6-alpine-linux-muslgnueabihf/bin/ar" "AS=/home/user/build/src/build-cross-final/./gcc/as" "LD=/home/user/build/src/build-cross-final/./gcc/collect-ld" "RANLIB=/usr/armv6-alpine-linux-muslgnueabihf/bin/ranlib" "NM=/home/user/build/src/build-cross-final/./gcc/nm" "NM_FOR_BUILD=" "NM_FOR_TARGET=/usr/armv6-alpine-linux-muslgnueabihf/bin/nm" "DESTDIR=/home/user/build/pkg/gcc-armhf" "WERROR=" DO=install multi-do # make
make[4]: Nothing to be done for 'install-data-am'.
make[4]: Leaving directory '/home/user/build/src/build-cross-final/armv6-alpine-linux-muslgnueabihf/libstdc++-v3'
make[3]: Leaving directory '/home/user/build/src/build-cross-final/armv6-alpine-linux-muslgnueabihf/libstdc++-v3'
make[2]: Leaving directory '/home/user/build/src/build-cross-final/armv6-alpine-linux-muslgnueabihf/libstdc++-v3'
make[2]: Entering directory '/home/user/build/src/build-cross-final/armv6-alpine-linux-muslgnueabihf/libvtv'
make  install-recursive
make[3]: Entering directory '/home/user/build/src/build-cross-final/armv6-alpine-linux-muslgnueabihf/libvtv'
make[4]: Entering directory '/home/user/build/src/build-cross-final/armv6-alpine-linux-muslgnueabihf/libvtv'
true  DO=all multi-do # make
make[5]: Entering directory '/home/user/build/src/build-cross-final/armv6-alpine-linux-muslgnueabihf/libvtv'
true  DO=install multi-do # make
make[5]: Leaving directory '/home/user/build/src/build-cross-final/armv6-alpine-linux-muslgnueabihf/libvtv'
make[4]: Leaving directory '/home/user/build/src/build-cross-final/armv6-alpine-linux-muslgnueabihf/libvtv'
make[3]: Leaving directory '/home/user/build/src/build-cross-final/armv6-alpine-linux-muslgnueabihf/libvtv'
make[2]: Leaving directory '/home/user/build/src/build-cross-final/armv6-alpine-linux-muslgnueabihf/libvtv'
make[1]: Leaving directory '/home/user/build/src/build-cross-final'
/usr/bin/abuild: line 2356: /home/user/build/pkg/gcc-armhf/usr/share/gdb/python/auto-load/usr/armv6-alpine-linux-muslgnueabihf/lib/: Permission denied
>>> ERROR: gcc-armhf*: package failed
>>> ERROR: gcc-armhf: all failed
(015005) [15:29:42] ERROR: Command failed: (native) % cd /home/user/build && su user -c 'CARCH=x86_64 abuild -d'
(015005) [15:29:42] Run 'pmbootstrap log' for details.
(015005) [15:29:42] Traceback (most recent call last):
  File "/home/bkero/code/pmbootstrap/pmb/helpers/run.py", line 39, in core
    stderr=args.logfd)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '/bin/sh', '-c', 'unset $(env | cut -d= -f1); CHARSET=UTF-8 PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash HISTFILE=~/.ash_history /usr/sbin/chroot /home/bkero/.local/var/pmbootstrap/chroot_native sh -c \'cd /home/user/build;su user -c \'"\'"\'CARCH=x86_64 abuild -d\'"\'"\'\'']' returned non-zero exit status 1

**Comment by dzervas** [comment]
I think it's related with #14

**Comment by ollieparanoid** [comment]
`gcc-armhf` fails to build.

This is caused by a workaround in `pmbootstrap`, that is no longer necessary as of [this commit upstream](https://github.com/alpinelinux/aports/commit/245c7809b92e2423c41ce71180c80f671e13dc12). So right now, the workaround breaks the build.

I have removed the workaround, and I'll push it as soon as I rebuilt `gcc-armhf` to verify this.
