### ISSUE TITLE
[RX51] Wire up display blanking + touch screen disable to acpid

### ISSUE THREAD

**Issue by craftyguy** [postmarketOS/pmbootstrap#193]
There must be some way to turn off power to the display on the RX51. Currently when it is 'off' (when running weston) the backlight is still on. Reducing backlight brightness to 0 doesn't actually turn off the display. 

Feel free to assign this one to me (I don't have permission to assign issues), and I plan on tackling this one soon since it obviously impacts battery life.

**Comment by craftyguy** [comment]
It seems that this can be accomplished by the following: `echo 1 > /sys/devices/platform/omapdrm.0/graphics/fb0/blank`

Writing a `1` so that file turns the display back on.

I changed the scope of this issue, to include also disabling the touchscreen from registering events. This is necessary to prevent unintended things from happening if the device is in your pocket. Both of these events should be wired up to acpid, specifically the 'screenlock' switch.

**Comment by pavelmachek** [comment]
I do have special daemon (in python) to lock screen on n900. yes, it is quite hacky, but maybe suitable for inspiration? https://gitlab.com/tui/tui/blob/master/ofone/lockd.py
