### ISSUE TITLE
pmbootstrap.py can't handle dependencies like "py-alabaster<0.8"

### ISSUE THREAD

**Issue by PureTryOut** [postmarketOS/pmbootstrap#195]
It just complains it can't find `py-alabaster<0.8`, while it should find any py-alabaster version lower than  0.8, which is in fact available in the repositories.

```
(022745) [16:14:59] Build is neccessary for package 'extra-cmake-modules': Binary package out of date (binary: 5.31.0-r0, aport: 5.36.0-r0)
(022745) [16:14:59] Calculate depends of packages ['py-sphinx', 'cmake'], arch: x86_64
(022745) [16:14:59] ERROR: Could not find package 'py3-alabaster<0.8' aport and could not find it in any APKINDEX
```

**Comment by ollieparanoid** [comment]
Thanks for the report! Until this is fixed I suggest omitting the minimum/maximum versions.

**Comment by PureTryOut** [comment]
Well, it's not my APKBUILD but from the default Alpine repo's. I guess I'll overwrite it for now.

**Comment by ollieparanoid** [comment]
Oh, then I misunderstood. Could you give me an example of how you triggered this?

**Comment by PureTryOut** [comment]
Well the latest version of Plasma uses `extra-cmake-modules` version 5.36. In the Alpine repos however there is just version 5.31. Rather than using an older version of every Plasma package I was meaning to just upgrade `extra-cmake-modules` instead. So I just updated the version nummer, tried to build it and it failed with above error due to it's dependency `py-sphinx` having a dependency of `py-alabaster<0.8`.

**Comment by PureTryOut** [comment]
This now actually prevents me from building large parts of Plasma Mobile. `plasma-workspace` requires several Plasma components of at least version 5.34 or higher. Since we're stuck on 5.31 till this issue is resolved, it can not be build.
