### ISSUE TITLE
Weston backend should be defined in weston.ini

### ISSUE THREAD

**Issue by craftyguy** [postmarketOS/pmbootstrap#196]
Configuration of weston backend should be done in `/etc/xdg/weston/weston.ini`, not as a command line parameter in `/etc/profile.d/postmarketos.sh`. The reason for this is because the current backend is fbdev, but on devices that have a DRM driver using the DRM backend would be very desirable to take advantage of things like DPMS. 

Moving this option in `weston.ini` would also allow devices to specify their own backend config, like I am doing #184 & #191 for the keymap config in weston. 

@ollieparanoid, @MartijnBraam - any thoughts or objections? I may go ahead and submit another PR to do this if y'all agree, and implement it in the same way I have done for the keymap stuff in the above two PRs.

**Comment by ollieparanoid** [comment]
This is a good solution :+1:

**Comment by craftyguy** [comment]
#201 implements this

**Comment by craftyguy** [comment]
#201 has been merged
