### ISSUE TITLE
Override kernel cmdline with pmbootstrap flasher boot

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#198]
Suggested by @ata2001 in IRC, and I think it would be useful.

**Comment by drebrez** [comment]
@ollieparanoid @ata2001 isn't this line already doing it? 
https://github.com/postmarketOS/pmbootstrap/blob/master/pmb/config/__init__.py#L258

**Comment by ollieparanoid** [comment]
With this line you can specify it in the `deviceinfo`. But as I understand @ata2001 he meant something like: `pmbootstrap flasher boot --cmdline="alternative arguments here"`.

**Comment by ata2001** [comment]
@ollieparanoid Yeah, changing `deviceinfo` also works, it would be just easier to experiment with cmdline parameters.

**Comment by drebrez** [comment]
@ata2001 I've created a PR to add this possibility #217

**Comment by ata2001** [comment]
@drebrez Thank you!
