### ISSUE TITLE
Try new device port, checksum fail

### ISSUE THREAD

**Issue by kittkott** [postmarketOS/pmbootstrap#20]
./pmbootstrap.py checksum device-samsung-gt-i7500

'module' object has no attribute 'run'
Run 'pmbootstrap log' for details.

P.S.
python3.4

**Comment by ollieparanoid** [comment]
Please upgrade to the latest version, it should solve Python 3.4 specific problems, such as the error you mentioned (#6).

If that does not help you, please provide a chunk from the end of the logfile:
`~/.local/var/pmbootstrap/log.txt`

**Comment by kittkott** [comment]
Sync to current version is fixing "checksum".

> Download https://nl.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
> Download https://nl.alpinelinux.org/alpine/edge/main/x86_64/apk-tools-static-2.7.1-r1.apk
> (native) install alpine-base
> (native) install abuild build-base ccache
> (native) generate abuild keys
> (native) generate checksums for device-samsung-gt-i7500
> Done
>
