### ISSUE TITLE
[titan] /sys is not mounted if FDE is disabled

### ISSUE THREAD

**Issue by PabloCastellano** [postmarketOS/pmbootstrap#204]
Since some days ago, I'm experiencing a weird bug where if I do `install --no-fde`, /sys folder is not mounted (but I can mount it manually) and if I don't disable FDE, everything is fine.

This is weird because it doesn't matter if I build pmOS from an older commit that I'm sure it worked fine. Now it doesn't.

So I think this is not directly related to latest changes in pmOS but it is totally reproducible.

I will also test it in lg-hammerhead just in case.

**Comment by craftyguy** [comment]
For what it is worth, I do not see this issue on the N900 if I install with `--no-fde`.

**Comment by ollieparanoid** [comment]
Check out `/etc/init.d/sysfs` - maybe this service does not get pulled in as dependency, when the disk is not encrypted for some reason? You could also debug the commands in there and check the conditions under which it would mount `/sys`.

**Comment by PabloCastellano** [comment]
Closing because the issue seems solved after installing the most recent version :?
