### ISSUE TITLE
make a proper boot splash screen

### ISSUE THREAD

**Issue by craftyguy** [postmarketOS/pmbootstrap#205]
No offense intended, but the current boot screen of "please wait whi..." (it gets cut off on my N900 because it's portrait only) is not exactly welcoming. This ticket is to call for ideas on a new image!

**Comment by kskarthik** [comment]
How about just **postmarketOS** text

**Comment by drebrez** [comment]
I was thinking the same, maybe with a logo, for example the green recycle icon on this page https://ollieparanoid.github.io/, if you mouse hover it also rotate

**Comment by MartijnBraam** [comment]
I've created #206 to generate splash screens that fit the device exactly.

**Comment by craftyguy** [comment]
Done, by @MartijnBraam !
