### ISSUE TITLE
Split up initramfs to make it smaller

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#211]
The idea is to have a small "real"/"small" initramfs, and a "bigger" initramfs file on the boot partition, that gets loaded from the "small" initramfs. The big one can contain more binaries, such as `resize2fs`, `parted`, `cryptsetup` and an on screen keyboard. Here are the TODOs, how it could be done. It will be some effort though!

* generate a second initramfs file in `postmarketos-mkinitfs`, which is also compressed
* write a new `init.sh` script for the little initramfs:
** find the boot partition (with subpartition support, use kpartx like done now)
** mount it
** extract the second initramfs and pass control ([e.g. like done here, but from a file, not from a partition](https://github.com/postmarketOS/pmbootstrap/blob/e241cca904a1177f0e684b5d469339ae9b0ba283/aports/linux-samsung-i9100/init#L20-L29))
* only include the following files in the small initramfs: busybox, kpartx

From there on we could optimize it further (compile minimal busybox, statically link busybox and kpartx against musl).

**Comment by drebrez** [comment]
I've started adding an initramfs-extra archive with these binaries:
- `cryptsetup`
- `dmsetup`
- `parted`
- `e2fsck`
- `resize2fs`

and these are the current sizes:

`initramfs` => `1516 KiB`
`initramfs-extra` => `3005 KiB`

branch: https://github.com/drebrez/pmbootstrap/tree/initramfs-extra
