### ISSUE TITLE
Boot process (Samsung I9070)

### ISSUE THREAD

**Issue by Roysten** [postmarketOS/pmbootstrap#22]
The Samsung I9070 does not have a separate recovery partition because it uses an Sony Ericsson SOC (U8500). This means I will have to do some work to boot pmOS on this device. However it is unclear to me how the boot process works.

The way I think it works:
Upon booting the device will load the Samsung initramfs from a hardcoded block offset. This initramfs contains an init script which you use to load the pmOS initramfs from the recovery partition. Your initramfs will load the actual kernel and boot pmOS.

Now since I don't have a recovery partition, I'm not sure what would be the best way for me to continue. Can I freely use another partition (such as KERNEL2) for the initramfs?

**Comment by ollieparanoid** [comment]
> Upon booting the device will load the Samsung initramfs from a hardcoded block offset. This initramfs contains an init script which you use to load the pmOS initramfs from the recovery partition.

Pretty much. There is an initramfs, that gets baked into the kernel ([LineageOS source](https://github.com/LineageOS/android_kernel_samsung_smdk4412/blob/cm-14.1/usr/galaxys2_initramfs_files/init)). I've simplified that to always load the recovery partition (because pressing that recovery key combination was a pain and didn't work for me most of the time).
So it's replaced with [this](https://github.com/postmarketOS/pmbootstrap/blob/master/aports/linux-samsung-i9100/init) version, which always boots the initramfs.

> Your initramfs will load the actual kernel and boot pmOS.

We already have the actual kernel booted, but the pmOS initramfs will take care of unlocking the root partition via telnet, showing the splash screens and as soon as the unlocking is done, give control to the openrc inside the encrypted rootfs.

> Now since I don't have a recovery partition, I'm not sure what would be the best way for me to continue. Can I freely use another partition (such as KERNEL2) for the initramfs?

That sounds like a good idea! Two things would need to be adjusted for that:
* the partition in init [here](https://github.com/postmarketOS/pmbootstrap/blob/master/aports/linux-samsung-i9100/init#L21) (in the device package for the I9070, not in the one for the i9100)
* the "--RECOVERY" partition string [here](https://github.com/postmarketOS/pmbootstrap/blob/master/aports/heimdall/heimdall_flash_kernel.sh#L27). We could add a new variable in the deviceinfo file `deviceinfo_flash_heimdall_partition`, and set it to `RECOVERY` for the `i9100` and to `KERNEL2` for the `I9070`.

How about that?

**Comment by ollieparanoid** [comment]
One more thing: The boot process is far simpler for fastboot based devices. There we can flash/boot the kernel and the actual initramfs together.

**Comment by Roysten** [comment]
Thanks for the information!

> That sounds like a good idea! Two things would need to be adjusted for that:
>
>    the partition in init here (in the device package for the I9070, not in the one for the i9100)
>    the "--RECOVERY" partition string here. We could add a new variable in the deviceinfo file deviceinfo_flash_heimdall_partition, and set it to RECOVERY for the i9100 and to KERNEL2 for the I9070.
>
>How about that?

That is exactly what I was thinking of :smile:

**Comment by ollieparanoid** [comment]
Nice :) Do you want to adjust the `heimdall` package, or do you need help?

**Comment by Roysten** [comment]
I don't think that will be the problem ;) I can't find any information on how to create an uart cable for the I9070, so that makes debugging rather difficult...

**Comment by ollieparanoid** [comment]
Ideally, you wouldn't even need debugging. I didn't need to use an UART cable during previous development of postmarketOS :)

**Comment by Roysten** [comment]
Ok, so I tried continuing without a UART cable, but so far no success. What I did was the following:
Changed the line
```
busybox lzop -dc /dev/block/mmcblk0p6 > ${load_image}
````
to:
```
busybox lzop -dc /dev/block/mmcblk0p17 > ${load_image}
```
Which is the Kernel2 partition (which I verified on the device before flashing anything).

I also edited the file `config/__init__.py`, because I need to generate smaller images: the Kernel2 partition is only 16 MB and the System partition only 612 MB. I do not think this should be a problem?

Then I flashed it using the `heimdall` package in which I changed the lines 
```
heimdall flash --RECOVERY /tmp/initramfs.lzo
``` 
to
 ```
heimdall flash --Kernel2 /tmp/initramfs.lzo
```
and
 ```
heimdall flash --KERNEL /tmp/initramfs.lzo
```
to
```
heimdall flash --Kernel /tmp/initramfs.lzo
``` 
Flashing succeeded, but the device will not boot. I tried building the `postmarketos-mkinitfs-hook-usb-shell` package and flashing the initramfs again, but unfortunately I cannot connect to the telnet.

**Comment by ollieparanoid** [comment]
> I also edited the file `config/__init__.py`, because I need to generate smaller images: the Kernel2 partition is only 16 MB and the System partition only 612 MB. I do not think this should be a problem?

No, this shouldn't be a problem. If you run out of space, install less packages in the device rootfs chroot for now (which will get copied into the system image, that will be flashed). You could remove Firefox for example, which pulls in a lot of dependencies. The list of packages to be installed is also in the config.

Oh, this is probably unclear: there is a boot partition inside the system image (which has its own partition table and sub-partitions, so it can be the same layout as on the sdcard, pretty uncommon but it works). That boot partition does not really get used yet, the plan would be to have a bootloader, which allows you to select multiple kernels in case the latest update broke your phone, just like you can do with GNU/Linux.

So the initramfs size can't be set in the config. But it should easily be less than 16 MB.

> heimdall flash --Kernel /tmp/initramfs.lzo

That sounds wrong, you'd need to flash [`"$KERNEL"`](https://github.com/postmarketOS/pmbootstrap/blob/master/aports/heimdall/heimdall_flash_kernel.sh#L33) in the script.

At your GNU/Linux PC, check if you get an IP while you're connected to the Android device. Before you don't have an IP, telnet won't work either. Sometimes I had to re-plugin the USB cable before I got the IP.

**Comment by Roysten** [comment]
> So the initramfs size can't be set in the config. But it should easily be less than 16 MB.
Hmm... so this line `install_size_boot = "100M"` should not be changed?

> That sounds wrong, you'd need to flash "$KERNEL" in the script.
You are right, I just copy and pasted the wrong line :/

**Comment by ollieparanoid** [comment]
> Hmm... so this line install_size_boot = "100M" should not be changed?

You can change it, but it won't change the size of the initramfs, but the size of the boot partition. Here's the layout:
```
/dev/install # system image or sdcard
/dev/installp1 # unencrypted /boot partition with 100M
/dev/installp2 # encrypted / partition with the rest of the size
```
> How does this work? Should I configure my PC to have a static IP address?

Configure your PC to get an IP via dhcp automatically. The phone will run a dhcp daemon.
So basically, when you plug in a LAN cable into your PC and it gets an IP automatically (e.g. with NetworkManager taking care of it), it *should* also work for the phone.
You could run a dhcp client manually too, e.g. `dhcpcd usb0` (replace `usb0` with the usb network device reported by `ip a`).

**Comment by Roysten** [comment]
Ok, so `ip addr` and `ip link list` only returns my network adapter and the loopback device, so the phone does not yet start a dhcp daemon unfortunately.

**Comment by ollieparanoid** [comment]
Too bad. is it feasible for you to get a UART cable? otherwise, we might be able to brainstorm up some more ideas.

**Comment by ollieparanoid** [comment]
One more idea: you could try to copy-paste the network initializing, dhcpcd and telnetd startup code into the init script, that gets baked into the kernel, and start analyzing from there.

**Comment by Roysten** [comment]
I just ordered the required components for an UART cable on Aliexpress, so I'll have to wait a few weeks until I can continue. Thank you for your support so far 😄

**Comment by ollieparanoid** [comment]
You're welcome, thanks for your porting efforts!

*Oh and there are some people (including me, finally) hanging out in the [chat](https://github.com/postmarketOS/pmbootstrap/wiki/Matrix-and-IRC), you might want to join to follow progress more directly.*

**Comment by ollieparanoid** [comment]
Good news, @drebrez also has a i9070, and he made it work :+1: 
https://github.com/drebrez/pmbootstrap/tree/device-samsung-i9070

I have documented the booting process/special initramfs thing of the i9100 in the device's wiki page.
Together we should be able to rewrite the init scripts/flashing scripts to make it work on both devices.
https://github.com/postmarketOS/pmbootstrap/wiki/samsung-i9100-(Samsung-Galaxy-SII)

**Comment by drebrez** [comment]
@Roysten I've made a lot of progress on porting the i9070 ([check the wiki](https://github.com/postmarketOS/pmbootstrap/wiki/Samsung-i9070-(Samsung-Galaxy-S-Advance))), I will create a PR very soon.
If you need help you can contact me in [chat](https://github.com/postmarketOS/pmbootstrap/wiki/Matrix-and-IRC)
