### ISSUE TITLE
Support specifying multiple packages in checksum/build/aportgen commands

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#220]
So you could do: `pmbootstrap checksum aports/device-*` for example.
Relevant files:
`pmb/parse/arguments.py`
`pmb/helpers/frontend.py`

**Comment by PureTryOut** [comment]
`aports/` shouldn't be needed honestly, as now we can also do `pmbootstrap checksum device-whatever`. All aports are somewhere in `aports/` anyway.

**Comment by ollieparanoid** [comment]
Right, I've made a wrong example. right now, `aports/` isn't needed and we shouldn't change that.
