### ISSUE TITLE
Add #201 deviceinfo changes to wiki page

### ISSUE THREAD

**Issue by craftyguy** [postmarketOS/pmbootstrap#222]

**Comment by ollieparanoid** [comment]
*Also `deviceinfo_flash_offset_base` needs to be documented again, because we re-introduced it. the key point is that the base number gets extracted to a file from `unpackbootimg`, and it can be read from there.*

**Comment by craftyguy** [comment]
Done. Have a look at the flash_offset_base description. I'm not familiar with this one and tried to write the description based on your comment but you might want to tweak it a little further if it's not 100% correct.
