### ISSUE TITLE
Use `.tar.gz` instead of `.zip` for kernel sources

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#223]
It's more the unix way, and busybox' zip has problems with symlinks (though that will be [fixed](https://bugs.busybox.net/show_bug.cgi?id=10031) in the next release - whenever that hits Alpine). At least `linux-lg-mako` uses `.zip` as source, and that is the APKBUILD the porting guide uses as reference.

**Comment by craftyguy** [comment]
The rx51 doesn't apply here, since I am pulling kernel source from kernel.org (which is currently tar.xz and extracts just fine with BB tar)

**Comment by ollieparanoid** [comment]
Sure, this was specific to replacing `zip` with `.tar.gz` for kernels from GitHub. `.tar.xz` and `.tar.bz2` are compressed more, and therefore better formats (smaller download size).
