### ISSUE TITLE
Attempting to checksum kernel package files for a new device results in an error

### ISSUE THREAD

**Issue by hadenodom** [postmarketOS/pmbootstrap#234]
Hi!  I'm following the porting guide and trying to get the Nokia N810 up and going.  I'm at the step in the porting guide where you'd run `./pmbootstrap.py checksum linux-$device-$name`, and I'm experiencing the following error:

> [01:07:41] ERROR: Command failed: (native) % cd /home/user/build && su user -c 'abuild checksum'

Screenshot and the log.txt are attached.  

![screenshot_2017-07-23_01-12-08](https://user-images.githubusercontent.com/5101247/28497108-efedd600-6f43-11e7-9b8d-437586498063.png)
[log.txt](https://github.com/postmarketOS/pmbootstrap/files/1167891/log.txt)

**Comment by MartijnBraam** [comment]
To get the full error log you need to start `./pmbootstrap.py log` in another terminal and restart this command in this terminal again.

**Comment by ollieparanoid** [comment]
We will know more with the log, but it could be that the download link does not work and it gets a `404` when downloading the kernel.

**Comment by MartijnBraam** [comment]
I think the nokia n810 can use the same kernel package as the n900, especially the unified kernel since that has all the dtb files.

**Comment by ollieparanoid** [comment]
@MartijnBraam that would be great! But the mainline kernel PR 
#228 is not finished yet, right?

So the easiest way for @hadenodom would be to copy-paste the [config-nokia-rx51.armhf
](https://github.com/postmarketOS/pmbootstrap/blob/14f164b8a27e4ba1f037983114013907bafc9b13/aports/linux-nokia-rx51/config-nokia-rx51.armhf) kernel config for now?

**Comment by MartijnBraam** [comment]
The easiest is copying the whole `linux-nokia-rx51` package and change 2 lines to append another dtb file (once in the make command and once in the package step)

**Comment by hadenodom** [comment]
Just woke up, glad to see a response.  Thanks, guys.  I'll switch the name of my device code to "rx44" as indicated by @MartijnBraam and will copy the N900 kernel config and see what happens.

**Comment by hadenodom** [comment]
I had a successful checksum & build.  Now, to figure out how to flash...

**Comment by MartijnBraam** [comment]
The easiest way is installing uboot on your device so you can run everything from the sd card.

**Comment by hadenodom** [comment]
Yeah, I just attempted to do it with 0xFFFF and gave up.  Going to U-boot now.

**Comment by PabloCastellano** [comment]
Closing as the issue is solved now
