### ISSUE TITLE
Unable to install Plasma Mobile due to "unsatisfiable constraints"

### ISSUE THREAD

**Issue by PureTryOut** [postmarketOS/pmbootstrap#237]
This would not really be a problem if it at least told me which packages it's missing. However:

```
ERROR: unsatisfiable constraints:
  Huh? Error reporter did not find the broken constraints.
```

`--verbose` does show me it's searching for a lot of packages, but from what I see all of them are found.

I'm guessing some package is missing a runtime dependency (`depends=""`), but this way it's impossible to find out which one. Maybe `pmbootstrap.py` can try to find out which packages it's missing?

**Comment by ollieparanoid** [comment]
Could you please attach a chunk from the end of your log?

**Comment by PureTryOut** [comment]
[The full log](https://paste.pound-python.org/show/oVnr0gdezbJsldgbej12/).

**Comment by ollieparanoid** [comment]
Thanks! That error comes from `apk`'s [commit.c](https://github.com/alpinelinux/apk-tools/blob/677d3240a845833dfb5c76491c0fd05efb934b2b/src/commit.c#L661), we might have hit a bug there.

Let's try to get some more output of apk: Could you try to enter a chroot `pmbootstrap chroot` and then run this command, to get more output (`-vv` is for most verbose log level), then post the output here?
```shell
apk -vv add -u /home/user/packages/user/armhf/plasma-mobile-5726.978b03c-r1.apk /home/user/packages/user/armhf/plasma-phone-components-r558.bbf9c0c-r1.apk /home/user/packages/user/armhf/plasma-workspace-5.10.4-r0.apk /home/user/packages/user/armhf/kpeople-5.36.0-r1.apk /home/user/packages/user/armhf/telepathy-qt-0.9.7-r1.apk qt5-qtgraphicaleffects /home/user/packages/user/armhf/kjsembed-5.36.0-r1.apk /home/user/packages/user/armhf/knotifyconfig-5.36.0-r1.apk qt5-qttools xsetroot /home/user/packages/user/armhf/kactivitymanagerd-5.10.4-r1.apk xprop /home/user/packages/user/armhf/milou-5.10.4-r1.apk /home/user/packages/user/armhf/kwin-5.10.4-r1.apk /home/user/packages/user/armhf/kdelibs4support-5.36.0-r1.apk /home/user/packages/user/armhf/kxmlgui-5.36.0-r1.apk /home/user/packages/user/armhf/kdesu-5.36.0-r1.apk iso-codes /home/user/packages/user/armhf/kservice-5.36.0-r1.apk /home/user/packages/user/armhf/kwidgetsaddons-5.36.0-r1.apk /home/user/packages/user/armhf/kitemviews-5.36.0-r1.apk qt5-qtdeclarative qt5-qtbase /home/user/packages/user/armhf/telepathy-farstream-0.6.2-r4.apk so:libQt5Core.so.5 so:libQt5Gui.so.5 so:libQt5Qml.so.5 so:libQt5Quick.so.5 qt5-qtsvg /home/user/packages/user/armhf/ki18n-5.36.0-r1.apk /home/user/packages/user/armhf/kjs-5.36.0-r1.apk /home/user/packages/user/armhf/kio-5.36.0-r1.apk so:libQt5DBus.so.5 so:libQt5Network.so.5 so:libQt5Sql.so.5 so:libQt5Widgets.so.5 so:libQt5Xml.so.5 /home/user/packages/user/armhf/krunner-5.36.0-r1.apk xcb-util-cursor /home/user/packages/user/armhf/plasma-framework-5.36.0-r2.apk /home/user/packages/user/armhf/kunitconversion-5.36.0-r1.apk /home/user/packages/user/armhf/kitemmodels-5.36.0-r1.apk /home/user/packages/user/armhf/kemoticons-5.36.0-r1.apk /home/user/packages/user/armhf/kded-5.36.0-r1.apk /home/user/packages/user/armhf/kparts-5.36.0-r1.apk /home/user/packages/user/armhf/kglobalaccel-5.36.0-r1.apk /home/user/packages/user/armhf/ktextwidgets-5.36.0-r1.apk /home/user/packages/user/armhf/kpty-5.36.0-r1.apk /home/user/packages/user/armhf/kconfig-5.36.0-r1.apk /home/user/packages/user/armhf/kcrash-5.36.0-r1.apk /home/user/packages/user/armhf/kdbusaddons-5.36.0-r1.apk so:libQt5Test.so.5 so:libicui18n.so.59 so:libicuuc.so.59 so:libpcre2-16.so.0 /home/user/packages/user/armhf/telepathy-glib-0.24.1-r1.apk /home/user/packages/user/armhf/farstream-0.2.8-r2.apk so:libxcb-icccm.so.4 so:libxcb-image.so.0 so:libxcb-keysyms.so.1 so:libxcb-render-util.so.0 /home/user/packages/user/armhf/solid-5.36.0-r1.apk /home/user/packages/user/armhf/kjobwidgets-5.36.0-r1.apk libxslt desktop-file-utils /home/user/packages/user/armhf/knotifications-5.36.0-r1.apk /home/user/packages/user/armhf/threadweaver-5.36.0-r1.apk qt5-qtquickcontrols /home/user/packages/user/armhf/kactivities-5.36.0-r1.apk /home/user/packages/user/armhf/kdeclarative-5.36.0-r1.apk /home/user/packages/user/armhf/kwayland-5.36.0-r1.apk /home/user/packages/user/armhf/karchive-5.36.0-r1.apk /home/user/packages/user/armhf/kinit-5.36.0-r1.apk /home/user/packages/user/armhf/kcompletion-5.36.0-r1.apk /home/user/packages/user/armhf/kiconthemes-5.36.0-r1.apk /home/user/packages/user/armhf/sonnet-5.36.0-r1.apk /home/user/packages/user/armhf/kcoreaddons-5.36.0-r1.apk /home/user/packages/user/armhf/kwindowsystem-5.36.0-r1.apk qt5-x11extras dbus-glib so:libxcb-util.so.1 /home/user/packages/user/armhf/media-player-info-22-r1.apk upower so:libgcrypt.so.20 /home/user/packages/user/armhf/phonon-dev-4.9.1-r1.apk /home/user/packages/user/armhf/kcodecs-5.36.0-r1.apk /home/user/packages/user/armhf/kpackage-5.36.0-r1.apk /home/user/packages/user/armhf/kconfigwidgets-5.36.0-r1.apk so:libgudev-1.0.so.0 so:libusb-1.0.so.0 so:libgpg-error.so.0 /home/user/packages/user/armhf/kauth-5.36.0-r1.apk /home/user/packages/user/armhf/kguiaddons-5.36.0-r1.apk /home/user/packages/user/armhf/polkit-qt5-0.112.0-r0.apk polkit
```

Also if it does not work, as a workaround, you could modify the commandline until it does. The `polkit` is specified as `polkit` and as `/home/user/packages/user/armhf/polkit-qt5-0.112.0-r0.apk` -- *maybe* that is why it fails.

**Comment by PureTryOut** [comment]
`apk -vv add -u <packages>` gives me the same result:

```
ERROR: unsatisfiable constraints:
  Huh? Error reporter did not find the broken constraints.
```

I'll try package by package till it breaks, might take some time.

**Comment by PureTryOut** [comment]
Found them!

The packages failing are `/home/user/packages/user/armhf/plasma-mobile-5726.978b03c-r1.apk` and `/home/user/packages/user/armhf/plasma-phone-components-r558.bbf9c0c-r1.apk`. Not exactly sure how that can be, as their runtime dependencies just installed fine.

**Comment by ollieparanoid** [comment]
Were you able to install them now? Or could you write down a minimal failing command?
Also if the packages aren't that big, could you upload them? (or at least the package description files inside the packages, they should be the interesting part)

**Comment by PureTryOut** [comment]
No, I couldn't install them even after installing all other packages first.

* [plasma-mobile](https://matrix.org/_matrix/media/v1/download/matrix.org/iEGdbXebCPgPlHgJwhdLSWsF)
* [plasma-phone-components](https://matrix.org/_matrix/media/v1/download/matrix.org/vorSQZwujBAbhPCbidrRUqzj)

`apk -vv add -u home/user/packages/user/armhf/plasma-mobile-5726.978b03c-r1.apk` and `apk -vv add -u /home/user/packages/user/armhf/plasma-phone-components-r558.bbf9c0c-r1.apk` both fail.

**Comment by ollieparanoid** [comment]
I'll analyze what's going wrong. shot in the dark: this also fails without `-u` (which is for allowing packages to be updated), and this also happens after zapping the chroot (not the packages!)?

**Comment by PureTryOut** [comment]
* without `-u`: yes
* zapped chroot: yes

**Comment by ollieparanoid** [comment]
@PureTryOut I think the problem is, that they have their own package name in the `provides=` line:
* [plasma-phone-components](https://github.com/postmarketOS/pmbootstrap/blob/3fcab74abb7c42dfc7dba0592959051b9bf77b9c/aports/plasma-phone-components/APKBUILD#L10)
* [plasma-mobile](https://github.com/postmarketOS/pmbootstrap/blob/3fcab74abb7c42dfc7dba0592959051b9bf77b9c/aports/plasma-mobile/APKBUILD#L10)

Could you please remove that, rebuild and check if it works then?

**Comment by PureTryOut** [comment]
That worked! Awesome.

**Comment by ollieparanoid** [comment]
Upstream feature request for a better error message: [here](https://bugs.alpinelinux.org/issues/7586)
