### ISSUE TITLE
Multiple runs of `pmbootstrap init` should update aports location in config file

### ISSUE THREAD

**Issue by craftyguy** [postmarketOS/pmbootstrap#246]
Re-running `pmbootstrap init` should update the aports location in ~/.config/pmbootstrap.cfg. While this may not do anything for normal users, for developers who are working across different forks (and want to maintain them in different directories), being able to re-use the config file (preserving device, parallel compile settings, etc) would be desirable.

**Comment by ollieparanoid** [comment]
Thanks for resolving this in #247!
