### ISSUE TITLE
HTC Ace screen has stopped working

### ISSUE THREAD

**Issue by VictorNine** [postmarketOS/pmbootstrap#248]
The screen on my HTC Ace has stopped working. This has happend sometime after commit 56b9c2206e7f9380e7ce6f6c5350c6e95698e117. (SSH etc is still working)

```
localhost:~$ cat /tmp/weston.log 
Date: 1980-01-06 GMT
[00:03:39.822] weston 2.0.0
               http://wayland.freedesktop.org
               Bug reports to: https://bugs.freedesktop.org/enter_bug.cgi?product=Wayland&component=weston&version=2.0.0
               Build: 1.99.94-2-g4c4f13d configure.ac: bump to version 2.0.0 for the official release (2017-02-24 16:19:03 -0800)
[00:03:39.822] Command line: weston
[00:03:39.823] OS: Linux, 3.0.101-ODP, #2-Alpine PREEMPT Sun Jul 23 21:11:42 GMT 2017, armv7l
[00:03:39.823] Starting with no config file.
[00:03:39.823] Output repaint window is 7 ms maximum.
[00:03:39.823] Loading module '/usr/lib/libweston-2/x11-backend.so'
[00:03:39.840] fatal: failed to create compositor backend
localhost:~$ modprobe /usr/lib/libweston-2/x11-backend.so
modprobe: FATAL: Module /usr/lib/libweston-2/x11-backend.so not found in directory /lib/modules/3.0.101-ODP
```

**Comment by MartijnBraam** [comment]
The problem is that it's missing the weston config file. 

I guess it's broken since d931ac430cf4cb53bcdcaaceb767e61858cbc11c which removes the `--backend=fbdev-backend.so` argument from weston and defines it in the config file.

The weston.ini should be generated by the post-install script from `postmarketos-base` and it doesn't seem to do that for you, can you find the relevant logs for that in the install step?

**Comment by VictorNine** [comment]
Found the file and it looks good to me

work/chroot_rootfs_htc-ace/etc/xdg/weston/weston.ini

`[core]
backend=fbdev-backend.so
[keyboard]`

**Comment by VictorNine** [comment]
PS the log file is also complaining about other files it can not find in 3.0.101-ODP

```
modprobe: WARNING: Module drm_kms_helper not found in directory /lib/modules/3.0.101-ODP
modprobe: WARNING: Module drm not found in directory /lib/modules/3.0.101-ODP
modprobe: WARNING: Module dm_crypt not found in directory /lib/modules/3.0.101-ODP
modprobe: WARNING: Module ext4 not found in directory /lib/modules/3.0.101-ODP
```

**Comment by MartijnBraam** [comment]
yep that's because those are added by default but are not compiled as modules. that doesn't change the graphics stuff.

**Comment by drebrez** [comment]
@VictorNine did you reflashed the system image on the device?

**Comment by VictorNine** [comment]
On to the SD card as before. I've also tried sending kernel and ramdrive with fastboot. Both has the same result

**Comment by ollieparanoid** [comment]
I'm sorry that it's broken for your device.

Could you zap your chroots (`pmbootstrap zap`), then install and flash again, and see if it works?
If it still does not work, I suggest using [git bisect](https://stackoverflow.com/a/4714297) to find the exact commit, that broke it.

**Comment by VictorNine** [comment]
Looks like the problem might be the device or sd card. Now the screen is working but I have new problems. I'll close this issue
