### ISSUE TITLE
[RX51] uboot is unable to find kernel after #228

### ISSUE THREAD

**Issue by craftyguy** [postmarketOS/pmbootstrap#262]
It appears that nothing actually gets installed to /boot after 21228a14d1a42cdbc1f09747da62b020d3d959ab. I've rebased off of master, zapped everything, and did a `pmbootstrap install --sdcard <my sdcard device>`, but when I mount the /boot partition on my computer it's completely empty.

@MartijnBraam, fyi. Just reporting it now, I haven't had time to try to debug it yet.

**Comment by MartijnBraam** [comment]
Ok that's strange, the `linux-postmarketos` package should at least create `/boot/vmlinuz-postmarketos` and the mkinitfs script should build the uImage.

**Comment by craftyguy** [comment]
It looks like `/chroot_rootfs_nokia-rx51/boot ` has the images, but they aren't being pushed to /boot on the SD card for some reason. I currently can't try to reproduce this because I'm dealing with #263.. which might actually be related somehow.

**Comment by craftyguy** [comment]
Ok I *think* this was somehow related to #263, since I haven't experienced this since the fix for that was merged. I'll re-open this issue if I come across this again and have more details to post.
