### ISSUE TITLE
distccd address in use

### ISSUE THREAD

**Issue by MartijnBraam** [postmarketOS/pmbootstrap#27]
The install command tries to start distccd processes but I get an address in use error:

```
distccd[26325] (dcc_job_summary) client: 127.0.0.1:36234 COMPILE_OK exit:0 sig:0 core:0 ret:0 time:941ms gcc tools/zunitc/src/zuc_junit_reporter.c
distccd[25073] (dcc_job_summary) client: 127.0.0.1:36238 COMPILE_OK exit:0 sig:0 core:0 ret:0 time:1310ms gcc xwayland/hash.c
distccd[25080] (dcc_job_summary) client: 127.0.0.1:36236 COMPILE_OK exit:0 sig:0 core:0 ret:0 time:4106ms gcc tests/surface-screenshot.c
distccd[25285] (dcc_job_summary) client: 127.0.0.1:36248 COMPILE_OK exit:0 sig:0 core:0 ret:0 time:3013ms gcc compositor/cms-static.c
distccd[25084] (dcc_job_summary) client: 127.0.0.1:36232 COMPILE_OK exit:0 sig:0 core:0 ret:0 time:5137ms gcc ivi-shell/ivi-shell.c
distccd[26427] (dcc_job_summary) client: 127.0.0.1:36246 COMPILE_OK exit:0 sig:0 core:0 ret:0 time:4901ms gcc ivi-shell/input-panel-ivi.c
distccd[26061] (dcc_job_summary) client: 127.0.0.1:36280 COMPILE_OK exit:0 sig:0 core:0 ret:0 time:789ms gcc compositor/cms-helper.c
distccd[25816] (dcc_job_summary) client: 127.0.0.1:36282 COMPILE_OK exit:0 sig:0 core:0 ret:0 time:834ms gcc libweston/animation.c
distccd[25935] (dcc_job_summary) client: 127.0.0.1:36266 COMPILE_OK exit:0 sig:0 core:0 ret:0 time:2147ms gcc tests/ivi_layout-internal-test.c
distccd[9512] (dcc_listen_by_addr) ERROR: bind of 127.0.0.1:33632 failed: Address in use
```

Might have something to do with settings the build process count to 20 (fast machine)

**Comment by ollieparanoid** [comment]
I have only had this problem, when running postmarketOS in a chroot (e.g. Debian chroot for testing), and outside of a chroot. Then the instance in the working dir could have started `distccd` already, when the outside instance tries to start it, thus the port would be blocked.

Have you done anything, like deleting a chroot folder without `pmbootstrap zap`? Because the zap command stops `distccd` first.

Does the problem persist, after `sudo killall distccd` and zapping the chroots?

**Comment by MartijnBraam** [comment]
I haven't zapped anything while i'm building, killing distccd fixes exactly one build step, the next one crashes again.

I'm not running the builds in a container

**Comment by ollieparanoid** [comment]
That is strange. Does the [pid file](https://github.com/postmarketOS/pmbootstrap/blob/master/pmb/chroot/distccd.py#L28) exist, when distccd is running, and deleted when your run `pmbootstrap shutdown`?
Maybe - for some reason - the permissions are broken inside the user folder and it can't be written?

**Comment by ollieparanoid** [comment]
It could also be, that [sending the kill signal](https://github.com/postmarketOS/pmbootstrap/blob/master/pmb/chroot/distccd.py#L42) fails.

**Comment by ollieparanoid** [comment]
I assume, that this isn't a problem anymore. If it still is, please comment.
