### ISSUE TITLE
Allow export --force

### ISSUE THREAD

**Issue by PabloCastellano** [postmarketOS/pmbootstrap#278]
After https://github.com/postmarketOS/pmbootstrap/pull/250 has been merged I've found a situation where `flasher export` crashes:

When the symlink already exists but points to an non-existing file, the [os.path.exists condition](https://github.com/postmarketOS/pmbootstrap/blob/master/pmb/flasher/export.py#L68) is False and then "ln -s" fails.

Reproduce:

```
pmb flasher export
cd /tmp/postmarketOS-export
ln -sf /unexisting initramfs-motorola-titan  # adjust name
pmb flasher export
```

Proposed solution:

We could allow a `--force` argument that ignores if file already exists and also forces the symlink creation ("ln -sf")

**Comment by PureTryOut** [comment]
Hmm, not sure if that is the correct thing to do. It would mean the script still crashes before you find out what's wrong. It's probably preferable to prevent the crash from happening in the first place, instead of using a workaround.

**Comment by PabloCastellano** [comment]
Sorry, I didn't explain that the crash comes from executing `ln -s` when the link already exists:

```
$ ln -s /etc/passwd p  # first time succeeds
$ ln -s /etc/passwd p  # second time fails
ln: failed to create symbolic link 'p': File exists
```

In the actual this situation is not handled because os.path.exists fails (link points to an unexisting file) and `ln -s` fails because there is a link already

**Comment by craftyguy** [comment]
Instead of adding a new option to `export`, why not just make `export` clean up old (and/or broken) links by default before trying to create new ones?

**Comment by ollieparanoid** [comment]
@PabloCastellano made PR #279, which includes a patch for this issue. I suggest commenting the patch there.
