### ISSUE TITLE
Source kernel from local folder

### ISSUE THREAD

**Issue by kskarthik** [postmarketOS/pmbootstrap#3]
Hey!  I already have kernel in my PC for my device.  How can I source it. Please help

**Comment by Roysten** [comment]
You can specify the path to the kernel sources in the APKBUILD, however this makes it impossible for others to build the kernel with your APKBUILD.

**Comment by kskarthik** [comment]
When I upstream. I will provide link :) for now, I want to source from local folder. Should I prefix `file:///` in URL: ?

**Comment by ollieparanoid** [comment]
You could put the kernel in a `.tar.gz` file inside the aports folder of your kernel, for example:
`aports/linux-my-custom-kernel/source.tar.gz`
...and then add `source.tar.gz` to your APKBUILD's [source](https://wiki.alpinelinux.org/wiki/APKBUILD_Reference#source) variable. After running `./pmbootstrap.py checksum linux-my-custom-kernel`, you can build it with `./pmbootstrap.py build linux-my-custom-kernel --arch=armhf` (it will build dependencies first, such as the cross-compiler).

(We're trying to have less kernels though, ideally just one, so whenever possible, use an existing upstream repository and apply patches to it, if you need to change something.)

**Comment by kskarthik** [comment]
thanks guys ! will be back if any issues. BTW i am building for Mozilla flame
