### ISSUE TITLE
dtb files are not installed to /usr/share by linux-postmarketos

### ISSUE THREAD

**Issue by craftyguy** [postmarketOS/pmbootstrap#305]
When building/installing `linux-postmarketos` for the RX51, the dtb files are not installed to `/usr/share/dtb`. I see this in the pmbootstrap log file:

    cat: can't open '/usr/share/dtb/omap3-n900.dtb': No such file or directory  

I did some digging around, looks like the the `linux-postmarketos` [APKBUILD is actually installing dtb files](https://github.com/postmarketOS/pmbootstrap/blob/master/aports/main/linux-postmarketos/APKBUILD#L119) to `/usr/share/dts`... but for some reason not even this happens with the rx51 and the latest from master. The condition in the APKBUILD seems to be true when I look in the build directory, the `arch/arm/boot/dts` path exists there, so I have no idea why this is not being picked up by the `package()` method in the APKBUILD.

I have no `/usr/share/dtb` or `/usr/share/dts` directory in the device rootfs chroot (hence the error in the log from mkinit.sh)

The end result of this issue is that master does not boot on the RX51, since the kernel is unable to find the sdcard.

**Comment by ollieparanoid** [comment]
Fixed by @MartijnBraam in #307.
