### ISSUE TITLE
`postmarketos-mkinitfs` should fail hard, if it should generate something, but the dependency is missing

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#312]
Fail hard, when:
* `generate_bootimg` is set, but `mkbootimg` is not installed or failed
* `generate_legacy_uboot_initfs` is set, but `mkimage` is not installed

It should print a meaningful error message, that explains how to fix this. Example:
```
ERROR: You have set "deviceinfo_generate_bootimg" to true, but the "mkbootimg" package is not installed.
In order to fix this, please add "mkbootimg" it to your device-package's "depends=" line.
```
... and after that bail out with `exit 1` (so both `apk` and `pmbootstrap` will return an error).

**Comment by PabloCastellano** [comment]
Similar when https://github.com/postmarketOS/pmbootstrap/issues/299 gets fixed:

- `flash_sparse` is set, but `libsparse` is not installed

**Comment by ollieparanoid** [comment]
Sorry, I've tagged this a bit wrong. This is about `postmarketos-mkintifs` not about pmbootstrap.

As explained [here](https://github.com/postmarketOS/pmbootstrap/issues/299#issuecomment-319401861), we can install the package, which contains img2simg on the fly in the install step - so we don't even need to specify it as explicit dependency.

**Comment by z3ntu** [comment]
Unfortunately using sparse images doesn't solve the problem on the fp2... But it's most likely a problem with the Fairphone bootloader and not with pmOS.
```
$ ./pmbootstrap.py flasher flash_system
[21:25:46] (native) flash system image
[sudo] password for luca: 
target reported max download size of 536870912 bytes
erasing 'system'...
OKAY [  0.029s]
sending sparse 'system' 1/2 (524285 KB)...
OKAY [ 16.494s]
writing 'system' 1/2...
FAILED (remote: Unknown chunk type)
finished. total time: 16.533s
[21:29:37] ERROR: Command failed: (native) % fastboot flash system /home/user/rootfs/fairphone-fp2.img
[21:29:37] Run 'pmbootstrap log' for details.
[21:29:37] See also: <https://postmarketos.org/troubleshooting>
```

**Comment by ollieparanoid** [comment]
Does the fairphone2 use a different `img2simg` program or something like that?

**Comment by z3ntu** [comment]
No, apparently it's just a bug that only appears when flashing large images with fastboot. Android gets installed with the recovery normally so this issue doesn't appear there.

**Comment by drebrez** [comment]
@z3ntu fastboot is known for it's limitations on flashing large images, for that reason I came up with this alternative solution => https://github.com/postmarketOS/pmbootstrap/issues/456

**Comment by z3ntu** [comment]
I'm working on packaging make_ext4fs right now.

**Comment by ollieparanoid** [comment]
We drifted a bit off-topic here - I recommend posting further comments regarding libsparse in a new issue, and discussing the "should fail hard if dependency missing" thing in *this* issue again.

See https://github.com/postmarketOS/pmbootstrap/issues/299#issuecomment-334808875 for more information about how @z3ntu solved it for the Fairphone 2.

**Comment by z3ntu** [comment]
Yeah I know, sorry ^^
And https://github.com/postmarketOS/pmbootstrap/issues/312#issuecomment-319350629 is also not needed anymore because pmbootstrap installs `libsparse` automatically with the `flash_sparse` option.

**Comment by ollieparanoid** [comment]
No problem and thanks for pointing that out 👍

**Comment by drebrez** [comment]
same problem with `deviceinfo_bootimg_qcdt="true"` in the deviceinfo and you run `pmbootstrap initfs build`, in the log it shows:
```
==> initramfs: creating boot.img
usage: mkbootimg [-h] --kernel KERNEL [--ramdisk RAMDISK] [--second SECOND]
                 [--cmdline CMDLINE] [--base BASE]
                 [--kernel_offset KERNEL_OFFSET]
                 [--ramdisk_offset RAMDISK_OFFSET]
                 [--second_offset SECOND_OFFSET] [--os_version OS_VERSION]
                 [--os_patch_level OS_PATCH_LEVEL] [--tags_offset TAGS_OFFSET]
                 [--board BOARD]
                 [--pagesize {2048,4096,8192,16384,32768,65536,131072}] [--id]
                 [--dt DT] -o OUTPUT
mkbootimg: error: argument --dt: can't open '/boot/dt.img': [Errno 2] No such file or directory: '/boot/dt.img'
```
but the operation didn't failed
