### ISSUE TITLE
Add flag to print output during long builds for Travis CI

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#314]
Travis will kill the job, if there's no output for 10 minutes.
For #64 we need to build packages in pmbootstrap, which will not have any output for that long.
It would be useful to have a flag, that when enabled, prints out a dot every minute or so to let Travis know, that pmbootstrap is still doing what it should.

**Comment by MartijnBraam** [comment]
Couldn't you switch the python logger to stdout instead of the logfile so you will get actually useful output in the logs?

You can also put markers in the output to make new collapsible regions in the travis output

**Comment by ollieparanoid** [comment]
Yeah, I could also do that. Right now it outputs the full log at the end.
