### ISSUE TITLE
`pmbootstrap menuconfig linux-postmarketos` causes kernel compilation error

### ISSUE THREAD

**Issue by antonok-edm** [postmarketOS/pmbootstrap#319]
When I run `pmbootstrap menuconfig linux-postmarketos`, then save+exit without making any changes, the kernel configuration file becomes heavily modified and the kernel compilation fails with the following error:

```
In file included from /home/user/build/src/linux-4.12.4/include/uapi/linux/stddef.h:1:0,
                 from /home/user/build/src/linux-4.12.4/include/linux/stddef.h:4,
                 from /home/user/build/src/linux-4.12.4/include/uapi/linux/posix_types.h:4,
                 from /home/user/build/src/linux-4.12.4/include/uapi/linux/types.h:13,
                 from /home/user/build/src/linux-4.12.4/include/linux/types.h:5,
                 from /home/user/build/src/linux-4.12.4/fs/xfs/xfs_linux.h:21,
                 from /home/user/build/src/linux-4.12.4/fs/xfs/xfs.h:32,
                 from /home/user/build/src/linux-4.12.4/fs/xfs/xfs_super.c:19:
In function 'xfs_check_ondisk_structs',
    inlined from 'init_xfs_fs' at /home/user/build/src/linux-4.12.4/fs/xfs/xfs_super.c:1990:2:
/home/user/build/src/linux-4.12.4/include/linux/compiler.h:529:38: error: call to '__compiletime_assert_119' declared with attribute error: XFS: sizeof(xfs_dir2_sf_entry_t) is wrong, expected 3
  _compiletime_assert(condition, msg, __compiletime_assert_, __LINE__)
                                      ^
/home/user/build/src/linux-4.12.4/include/linux/compiler.h:512:4: note: in definition of macro '__compiletime_assert'
    prefix ## suffix();    \
    ^~~~~~
/home/user/build/src/linux-4.12.4/include/linux/compiler.h:529:2: note: in expansion of macro '_compiletime_assert'
  _compiletime_assert(condition, msg, __compiletime_assert_, __LINE__)
  ^~~~~~~~~~~~~~~~~~~
/home/user/build/src/linux-4.12.4/include/linux/bug.h:54:37: note: in expansion of macro 'compiletime_assert'
 #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
                                     ^~~~~~~~~~~~~~~~~~
/home/user/build/src/linux-4.12.4/fs/xfs/xfs_ondisk.h:22:2: note: in expansion of macro 'BUILD_BUG_ON_MSG'
  BUILD_BUG_ON_MSG(sizeof(structname) != (size), "XFS: sizeof(" \
  ^~~~~~~~~~~~~~~~
/home/user/build/src/linux-4.12.4/fs/xfs/xfs_ondisk.h:119:2: note: in expansion of macro 'XFS_CHECK_STRUCT_SIZE'
  XFS_CHECK_STRUCT_SIZE(xfs_dir2_sf_entry_t,  3);
  ^~~~~~~~~~~~~~~~~~~~~
```

The error seems to suggest an issue with XFS configuration, but I cannot find any related lines in the config file.
The kernel compiles fine directly after a fresh pull from upstream/master (but then I cannot use menuconfig to make changes).

[Output of git diff aports/main/linux-postmarketos/config-postmarketos.armhf](https://pastebin.com/Zbw7RhvV)
Note that the diff is 1412 lines long, which does not seem like expected behavior.

**Comment by ollieparanoid** [comment]
It looks like, there was a bug introduced regarding XFS and menuconfig in the kernel. There are a lot of search results for "XFS: sizeof(xfs_dir2_sf_entry_t) is wrong, expected 3".

To get this fixed upstream, you could do some more research to see whether they already know about this issue (I think there is a high chance, that they do), and if they do not, write to the current [maintainer](https://github.com/torvalds/linux/blob/26c5cebfdb6ca799186f1e56be7d6f2480c5012c/MAINTAINERS#L14454) of XFS.

And as workaround, I suggest we simply disable XFS for now, as we don't have an use case for it at this point. According to the [Gentoo wiki](https://wiki.gentoo.org/wiki/XFS), it should be possible to disable it here (right now it is configured as module, as I see in your diff):
```
File systems  --->
   <*> XFS filesystem support
```

If you do disable it, please also note that at the beginning of the `APKBUILD` (you could reference this issue with `#319`).

**Comment by craftyguy** [comment]
@ollieparanoid

Actually, the problem seems to be that the x86 config is being pulled in, replacing the armhf config (notice how the git diff output shows all ARM stuff removed from the config).

**Comment by ollieparanoid** [comment]
Thanks for clarifying, that makes more sense! Then we have a bug in pmbootstrap here (or in the `APKBUILD`, but I think it's probably in [menuconfig.py](https://github.com/postmarketOS/pmbootstrap/blob/master/pmb/build/menuconfig.py#L60)).

**Comment by ollieparanoid** [comment]
I've made PR #328 that fixes the issue for me, please test it.
