### ISSUE TITLE
Save version in the generated system partition

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#324]
This would make debugging the version number easier. We could add the following information in the system partition somewhere:
* pmbootstrap version
* pmbootstrap git hash

**Comment by MartijnBraam** [comment]
I suggest using `/etc/pmos-release` and make it somewhat compliant to lsb_release

**Comment by PabloCastellano** [comment]
How would you do to have $version and $hash variables available in the post-install script?

**Comment by PabloCastellano** [comment]
One idea is writing these values during the install stage to some file in the device rootfs (e.g. `/tmp/version`) and then source this file from the post-install script. What do you think? Any simpler option?

**Comment by ollieparanoid** [comment]
I think the easiest option would be to write the entire `/etc/os-release` from within the Python code for now.

**Comment by craftyguy** [comment]
When would `VERSION` be set? As pmbootstrap is now, it's more of a rolling release, it seems that for this to be meaningful there would need to be discrete "releases". 

Or, maybe `VERSION` is the git hash? That doesn't seem like a good solution if/when the project becomes more stable.

**Comment by MartijnBraam** [comment]
It would be the current git rel which might be a tag or a hash

**Comment by ollieparanoid** [comment]
> Or, maybe `VERSION` is the git hash? That doesn't seem like a good solution if/when the project becomes more stable.

True. I imagine that at some point we put the `aports` in an extra repository, and release stable versions of `pmbootstrap` (which we could put up on `pip` and maybe provide it for various Linux distributions, just like you can install `debootstrap` pretty much everywhere).

How about using the current version tag *plus* the hash as `VERSION` value? That way it would be upwards-compatible. Example:
`0.2.0-asdfasdf` (where `0.2.0` is from `pmb/config/__init__.py` and `asdfasdf` would be the first 8 letters of the last git hash).

**Comment by MartijnBraam** [comment]
Including the hash is important so you can see if the build is from something in master or from a branch, i'm for always including it.

**Comment by PabloCastellano** [comment]
Following @MartijnBraam's comment, I've tried to implement this feature in two different ways but none of these work.

https://github.com/PabloCastellano/pmbootstrap/commit/e0340d83c6d2a75636c53dcdef31a171a11bd94c (the file doesn't get created. Is it because we cannot use ">" in the command or something else?)

https://github.com/PabloCastellano/pmbootstrap/commit/1ad63c3f5de94d06eed71309a88f68cef87614b1 (Permission denied, since the script runs with user permissions).

Any pointers?
@ollieparanoid How would you write it from within the Python code?

**Comment by craftyguy** [comment]
Can you use pmb.chroot.user or pmb.chroot.root?

**Comment by PabloCastellano** [comment]
@craftyguy In my [first try](https://github.com/PabloCastellano/pmbootstrap/commit/e0340d83c6d2a75636c53dcdef31a171a11bd94c), I used pmb.chroot.root as

```
pmb.chroot.root(args, ["echo", os_release, ">", "/etc/os-release"], suffix)
```

But the file doesn't get created

**Comment by drebrez** [comment]
@PabloCastellano [here](https://github.com/postmarketOS/pmbootstrap/blob/1c13ca4fd9e32952a8e559987f82cd0925cddee9/pmb/chroot/initfs.py#L64) is the solution/workaround for the redirection in chroot

**Comment by ollieparanoid** [comment]
@PabloCastellano: you are right, for security reasons, the commands do not directly get executed in a shell.

There are two methods used for such cases throughout the `pmbootstrap` source:

1. Write the file with Python to `args.work + "/chroot_" + suffix + "/tmp"`, then copy the file with pmb.chroot.root()` to the right location and `chown` it (what @drebrez linked)

2. Use something like `["sh", "-c", "echo a > /tmp/test"]` (but when you have variables involved in the command string, then you should use `shlex` to escape them properly, and it gets ugly.

For writing `/etc/os-release` I recommend method 1.

**Comment by PabloCastellano** [comment]
Thanks for the advices!

PR is ready. This is the content my /etc/os-release now

```
PRETTY_NAME="postmarketOS 0.2.0"
NAME="postmarketOS"
VERSION_ID="0.2.0"
VERSION="0.2.0-783a0dde"
ID="postmarketos"
ID_LIKE="alpine"
HOME_URL="http://www.postmarketos.org/"
SUPPORT_URL="https://github.com/postmarketOS/"
BUG_REPORT_URL="https://github.com/postmarketOS/"
PMOS_HASH="783a0dde1645b2d6c9ebaa434206291b304c324c"
```

**Comment by PabloCastellano** [comment]
Also, documented the workaround to redirect shell input/output in the [development guide](https://github.com/postmarketOS/pmbootstrap/wiki/Development-guide).
