### ISSUE TITLE
Do not show telnet splash for devices with deviceinfo_keyboard="true"

### ISSUE THREAD

**Issue by PabloCastellano** [postmarketOS/pmbootstrap#325]
Actually it makes no sense to ask the enduser to connect through telnet (even if he is still allowed) when there is a physical keyboard.

Thanks @MartijnBraam for reporting on Matrix!

**Comment by PabloCastellano** [comment]
But the telnet splash is displayed from initramfs and we do not include /etc/deviceinfo in the initramfs. How can we check the value then?

**Comment by drebrez** [comment]
@PabloCastellano [this](https://github.com/postmarketOS/pmbootstrap/blob/master/aports/main/postmarketos-mkinitfs/mkinitfs.sh#L145-L149) is how it's done for the other variables

**Comment by ollieparanoid** [comment]
Just wrote that in the channel:
> Currently we do not install the deviceinfo file in the initramfs, so you can not access it. Instead we have variables in the init.sh.in `@varname@` and replace those in mkinitfs. But I think we should use the deviceinfo in the long term, because right now we end up duplicating all of these variables, and the deviceinfo file itself is just a very small text file.

**Comment by drebrez** [comment]
@ollieparanoid I completely agree that having the deviceinfo directly in the initramfs is better than keep adding variables replaces.

**Comment by PureTryOut** [comment]
So, since we don't use telnet at all any-more and instead rely on osk-sdl nowadays, I assume this issue can now be closed?
