### ISSUE TITLE
Add setup.py (setuptools)

### ISSUE THREAD

**Issue by PabloCastellano** [postmarketOS/pmbootstrap#327]
With setuptools we can have pmbootstrap available in PyPi and have pmbootstrap installed to $PATH easily (I'd also like to have a `pmb` alias)

**Comment by ollieparanoid** [comment]
I think before publishing to pypi, we should split `pmbootstrap` and the `aports` into different repositories. Or does anyone see it differently?

**Comment by PureTryOut** [comment]
If not doing that means the `aports` folder ends up in pypi as well, then yes, it should probably be moved first.

**Comment by MartijnBraam** [comment]
hmm it shouldn't end up on pypi if you don't explicitly add the aports folder in the setup.py
