### ISSUE TITLE
Proper way to activate postmarketos-mkinitfs-hook-usb-shell?

### ISSUE THREAD

**Issue by lawl** [postmarketOS/pmbootstrap#33]
This seems invaluable for development, but I'm not quite sure how to properly activate it? I have just patched the init script with that line so this isn't of any priority at all, but I'd like to add the proper way to use it to the porting guide.

**Comment by ollieparanoid** [comment]
This is the proper way:
```
pmbootstrap build postmarketos-mkinitfs-hook-usb-shell
pmbootstrap chroot --suffix="buildroot_samsung-i9100"
apk add postmarketos-mkinitfs-hook-usb-shell
exit
pmbootstrap install
```

**Comment by lawl** [comment]
Thanks, added it to the wiki.
