### ISSUE TITLE
[flame] System image: use make_ext4fs/ext2img instead of libsparse

### ISSUE THREAD

**Issue by yuvadm** [postmarketOS/pmbootstrap#337]
Currently the sparse system image built for the Mozilla Flame [is unflashable](https://github.com/postmarketOS/pmbootstrap/wiki/Mozilla-Flame#unknown-chunk-type).

Diffing the pmOS image against the original B2G image shows these differences:

```bash
$ file B2G-system.img 
B2G-system.img: Android sparse image, version: 1.0, Total of 107392 4096-byte output blocks in 1228 input chunks.
$ file pmOS-system.img
pmOS-system.img: Android sparse image, version: 1.0, Total of 91136 4096-byte output blocks in 87 input chunks.
```

There is a noticable difference in input chunks.

Digging deeper into the B2G build logs, it seems they build the rootfs using [`make_ext4fs`](https://android.googlesource.com/platform/system/extras/+/master/ext4_utils/make_ext4fs.c) with some custom parameters:

```
16:56:50     INFO -  + make_ext4fs -s -S out/target/product/flame/root/file_contexts -l 439877632 -a system out/target/product/flame/obj/PACKAGING/systemimage_intermediates/system.img out/target/product/flame/system
16:56:55     INFO -  Creating filesystem with parameters:
16:56:55     INFO -      Size: 439877632
16:56:55     INFO -      Block size: 4096
16:56:55     INFO -      Blocks per group: 32768
16:56:55     INFO -      Inodes per group: 6720
16:56:55     INFO -      Inode size: 256
16:56:55     INFO -      Journal blocks: 1678
16:56:55     INFO -      Label:
16:56:55     INFO -      Blocks: 107392
16:56:55     INFO -      Block groups: 4
16:56:55     INFO -      Reserved block group size: 31
16:56:55     INFO -  Created filesystem with 1286/26880 inodes and 74641/107392 blocks
```

I wonder whether this might be the cause of my invalid system image (WIP), and in general whether we might want to use `make_ext4fs` for creating the rootfs.

Alternatively, I might be barking up the wrong tree and this might be similar to https://github.com/anestisb/android-simg2img/issues/2 in which case we can look into using `ext2simg` instead of `img2simg` for sparse images.

**Comment by ollieparanoid** [comment]
Too bad that it didn't work yet - but you made some nice research on alternative tools, so we really should be able to get this working!

I recommend to create a system image with both new tools (`make_ext4fs` and `ext2simg`) *outside of pmbootstrap's process* and testing which image works (maybe even both images work!).
Then we could decide which method to use and how to properly integrate it.

**Comment by yuvadm** [comment]
@ollieparanoid sounds good! Will update once I figure out how to properly build those tools outside of the Android build system.

**Comment by ollieparanoid** [comment]
A quick and dirty solution would be: `gcc -o output *.c` in most cases, because from what I have seen, these Android programs are usually just a few C files. Doing it that way would be good enough for an initial test to see if it is working at all.

**Comment by yuvadm** [comment]
Per our discussion on IRC today I'm going to drop this effort. The SD card installation is good enough at this point.

There are two root problems here if anyone wants to attempt resolving them in the future:
1. System image is larger than max download size reported by the bootloader (~301MB) so regular (un-sparse images cannot be flashed)
2. Bootloader is very picky about which sparse images it will accept.

For now SD card installation is the only supported method for the Flame.

**Comment by z3ntu** [comment]
Same for the fp2:
```
images/system.img: Android sparse image, version: 1.0, Total of 524288 4096-byte output blocks in 2282 input chunks.
/home/luca/.local/var/pmbootstrap/chroot_native/home/user/rootfs/fairphone-fp2.img: Android sparse image, version: 1.0, Total of 163328 4096-byte output blocks in 99 input chunks.
```

**Comment by z3ntu** [comment]
And
```
creating system.img...
BuildImage: in_dir = /tmp/targetfiles-s3qLCi/system, out_file = /tmp/system-Fk34mN.img
fs type is not ext4
Running:  mkuserimg.sh -s /tmp/targetfiles-s3qLCi/system /tmp/system-Fk34mN.img ext4 system 2147483648 -T 1230768000 -C /tmp/targetfiles-s3qLCi/META/filesystem_config.txt -B /tmp/system-blocklist-OSZaOn.map -L system /tmp/targetfiles-s3qLCi/META/file_contexts.bin
make_ext4fs -s -T 1230768000 -S /tmp/targetfiles-s3qLCi/META/file_contexts.bin -C /tmp/targetfiles-s3qLCi/META/filesystem_config.txt -B /tmp/system-blocklist-OSZaOn.map -L system -l 2147483648 -a system /tmp/system-Fk34mN.img /tmp/targetfiles-s3qLCi/system
loaded 2510 fs_config entries
Creating filesystem with parameters:
    Size: 2147483648
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 8192
    Inode size: 256
    Journal blocks: 8192
    Label: system
    Blocks: 524288
    Block groups: 16
    Reserved block group size: 127
Created filesystem with 2520/131072 inodes and 162028/524288 blocks
Running ['mkuserimg.sh', '-s', '/tmp/targetfiles-s3qLCi/system', '/tmp/system-Fk34mN.img', 'ext4', 'system', '2147483648', '-T', '1230768000', '-C', '/tmp/targetfiles-s3qLCi/META/filesystem_config.txt', '-B', '/tmp/system-blocklist-OSZaOn.map', '-L', 'system', '/tmp/targetfiles-s3qLCi/META/file_contexts.bin'] command, exit code = 0
```
This [script](https://github.com/LineageOS/android_system_extras/blob/cm-14.1/ext4_utils/mkuserimg.sh) will call the make_ext4fs with the correct parameters.
(from the build log for LineageOS 14.1)
