### ISSUE TITLE
Network not starting after unlocking

### ISSUE THREAD

**Issue by MartijnBraam** [postmarketOS/pmbootstrap#34]
The usb network adapter is created (I can see usb0 being created in my host kernel log) but the rest of the networking on the phone is not starting.

Kernel log on the phone:
```
 * Starting networking ...awk: /etc/network/interfaces: No such file or directory
 * ERROR: networking failed to start
```

**Comment by ollieparanoid** [comment]
Note: the usb networking is brought up [inside the initramfs](https://github.com/postmarketOS/pmbootstrap/blob/master/aports/postmarketos-mkinitfs/10-usb-unlock.sh#L5) already, before OpenRC starts.

**Comment by ollieparanoid** [comment]
So the goal here would be getting wlan working. If someone wants to give it a try, I recommend starting with manual setup: https://wiki.archlinux.org/index.php/Wireless#Manual_setup

We might also need binary blobs for that? I have not done much research on this topic yet.

**Comment by ollieparanoid** [comment]
You've said NetworkManager is more or less working, which should make this issue obsolete (which uses the normal `networking` init.d service). Please comment/reopen if you see this otherwise.
(If this is just about the service, maybe we can simply disable it?)
