### ISSUE TITLE
ERROR: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by PureTryOut** [postmarketOS/pmbootstrap#341]
From a clean chroot, I'm trying to install Plasma Mobile to an sdcard. I do have to note that I use the packages from my [binary repo](https://github.com/puretryout/pmos-plasma-mobile).

Running `./pmbootstrap.py install --add plasma-mobile,plasma-phone-components` gives me the error in the title just after creating the initramfs. The last message before the error is `Calculate depends of packages ['postmarketos-mkinitfs'], arch: armhf`.

It kills the process.

```
(020456) [12:15:33] Calculate depends of packages ['postmarketos-mkinitfs'], arch: armhf
(020456) [12:15:33] ERROR: 'NoneType' object is not subscriptable
(020456) [12:15:33] Run 'pmbootstrap log' for details.
(020456) [12:15:33] See also: <https://postmarketos.org/troubleshooting>
(020456) [12:15:33] Traceback (most recent call last):
  File "./pmbootstrap.py", line 53, in main
    getattr(pmb.helpers.frontend, args.action)(args)
  File "/home/****/Documents/Projects/Personel/postmarketos-pmbootstrap/pmb/helpers/frontend.py", line 91, in install
    pmb.install.install(args)
  File "/home/****/Documents/Projects/Personel/postmarketos-pmbootstrap/pmb/install/install.py", line 138, in install
    pmb.chroot.initfs.build(args, flavor, suffix)
  File "/home/****/Documents/Projects/Personel/postmarketos-pmbootstrap/pmb/chroot/initfs.py", line 29, in build
    pmb.chroot.apk.install(args, ["postmarketos-mkinitfs"], suffix)
  File "/home/****/Documents/Projects/Personel/postmarketos-pmbootstrap/pmb/chroot/apk.py", line 190, in install
    args, build, arch, package, packages_installed):
  File "/home/****/Documents/Projects/Personel/postmarketos-pmbootstrap/pmb/chroot/apk.py", line 129, in install_is_necessary
    data_repo["version"])
TypeError: 'NoneType' object is not subscriptable
```

I've uploaded a full log [here](http://bpaste.net/show/c353508d0277). The command used was `./pmbootstrap.py --verbose install --add plasma-mobile,plasma-phone-components --sdcard=/dev/mmcblk0`.

**Comment by ollieparanoid** [comment]
From my analysis I have learned, that I can trigger this bug the following way:
1. `pmbootstrap build postmarketos-splash`
2. `sudo rm ~/.local/var/pmbootstrap/packages/armhf/postmarketos-splash-*`
3. `pmbootstrap initfs` (with an `armhf` device!)

The reason is, that `postmarketos-splash` is a `noarch` package (no native binaries, only architecture independent Python code), so the check whether this package needs to be built or not just checks if the native `x86_64` version is there (and not if the symlinks to the other architectures exist).

That would have been a wonderful explanation. But @PureTryOut told me in the channel, that he tried `pmbootstrap zap -p` a few times, and the bug still appeared. Bummer. It looks like, we have an additional bug somewhere, e.g. the symlink does not get created in the first place for some reason.

**Comment by ollieparanoid** [comment]
*Further reading the log...*
* `postmarketos-splash` gets built
* `armhf` symlink get created
* `armhf` repo gets indexed again

@PureTryOut could you upload your `$work/packages/armhf/APKINDEX.tar.gz` file?

**Comment by PureTryOut** [comment]
[APKINDEX.tar.gz](https://github.com/postmarketOS/pmbootstrap/files/1203315/APKINDEX.tar.gz)

**Comment by ollieparanoid** [comment]
Thanks! That `APKINDEX.tar.gz` contains an entry for the `postmarketos-splash` package:
```json
pmbootstrap parse_apkindex APKINDEX.tar.gz postmarketos-splash
{
    "pkgname": "postmarketos-splash",
    "version": "1-r2",
    "timestamp": "1502028075",
    "depends": [
        "ttf-dejavu",
        "ttf-droid",
        "py3-pillow"
    ],
    "provides": []
}
```

I'll create a workaround now at least, until we can fix this properly.

**Comment by ollieparanoid** [comment]
Here is a workaround:
```patch
--- a/pmb/chroot/apk.py
+++ b/pmb/chroot/apk.py
@@ -122,9 +122,17 @@ def install_is_necessary(args, build, arch, package, packages_installed):
     if package not in packages_installed:
         return True

+    # Not found in binary repository - this should not happen!
+    data_repo = pmb.parse.apkindex.read_any_index(args, package, arch)
+    if not data_repo:
+        logging.info("WARNING: Workaround for bug #341, rebuilding " +
+                     package + " for " + arch + " (with force!)")
+        pmb.build.package(args, package, arch, True)
+        return install_is_necessary(args, build, arch, package,
+            packages_installed)
+
     # Compare the installed version vs. the version in the repos
     data_installed = packages_installed[package]
-    data_repo = pmb.parse.apkindex.read_any_index(args, package, arch)
     compare = pmb.parse.apkindex.compare_version(data_installed["version"],
                                                  data_repo["version"])
     # a) Installed newer (should not happen normally)
```

**Comment by ollieparanoid** [comment]
I still can't figure out what *really* causes this, and I suspect it is related to caching mechanisms.
Could you please comment out the following code, and check if the error still appears (you can leave the patch from above applied, as it will show the warning):
1. https://github.com/postmarketOS/pmbootstrap/blob/6a129669a389446bdbbb2bf6e8576043bc80bf29/pmb/helpers/repo.py#L132-L133
2. https://github.com/postmarketOS/pmbootstrap/blob/6a129669a389446bdbbb2bf6e8576043bc80bf29/pmb/parse/apkindex.py#L191-L194

Thanks!
