### ISSUE TITLE
Travis CI build fails

### ISSUE THREAD

**Issue by ata2001** [postmarketOS/pmbootstrap#349]
`test/test_checksums.py` fails on Travis with the following error:

`ERROR: The pkgname must be equal to the name of the folder, that contains the APKBUILD!`

I have no problem running that test locally.

Pull request: #348 

Full log: https://travis-ci.org/postmarketOS/pmbootstrap/jobs/262145557

**Comment by yuvadm** [comment]
I can't even build packages locally, all APKBUILDs that have the line:

    'pkgname=linux-${_flavor}'

are failing. This is a common pattern in many packages.

**Comment by yuvadm** [comment]
@ollieparanoid this is due to your latest commit  7fe2bc18c3c6f503a9bf59ae546e24f5980df77c

**Comment by ollieparanoid** [comment]
Sorry for the trouble, it is fixed now. *Of course the variables need to be replaced /before/ checking the folder name against the `pkgname`!*
