### ISSUE TITLE
[hammerhead] Make `pmbootstrap flasher flash_kernel` work

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#35]
Hi @dzervas and @MartijnBraam,

amazing progress with hammerhead! Wifi is working? Wow! :D

So there is `pmboostrap flasher boot`, which should do the same as the command specified in the wiki: `fastboot boot /mnt/rootfs_lg-hammerhead/boot/vmlinuz-lg-hammerhead /mnt/rootfs_lg-hammerhead/boot/initramfs-lg-hammerhead`

Does that work?

(Also, can you upload photos and maybe share them on /r/postmarketOS?)

**Comment by MartijnBraam** [comment]
The fastboot boot command isn't what currently makes it boot, I shall update the wiki.

The workaround at the bottom of the wiki with generating a seperate boot.img and flashing that to the boot partition or starting it with fastboot boot boot.img does work. The automatic image creation from fastboot seems to have issues.

**Comment by ollieparanoid** [comment]
To fix that, we could add a script, that builds the bootimg in a temporary folder with [mkbootimg](https://github.com/postmarketOS/pmbootstrap/tree/master/aports/mkbootimg), and then flashes that bootimg.

If someone wants to try it:
* modify the fastboot package and add such a shell script
* [change the config(https://github.com/postmarketOS/pmbootstrap/blob/master/pmb/config/__init__.py#L202), so the script gets called instead of fastboot directly (look at the heimdall part - there are also scripts getting called, instead of heimdall directly)

**Comment by ollieparanoid** [comment]
Is the only problem here the kernel commandline, that does not get passed to fastboot yet (so this would be fixed in #50)?
Or is fastboot really creating broken bootimg files, and we must use `mkbootimg` instead, and pass the generated image to fastboot?

**Comment by MartijnBraam** [comment]
I still use mkbootimg manually to flash my images.

**Comment by ollieparanoid** [comment]
I know, but is it really necessary, or is the actual reason missing kernel commandlines in `pmbootstrap flasher`?

**Comment by MartijnBraam** [comment]
It's necesairy because fastboot cannot live-create a bootable image for me for some reason, If I don't specify the cmdline in mkbootimg then I still get a flashable image, If I let fastboot create the boot.img then it will complain about the partition table.

**Comment by lawl** [comment]
`flasher boot` works for me on my hammerhead

**Comment by MartijnBraam** [comment]
Hmm yes `flasher boot` works and `flasher flash_system` works. `flasher flash_kernel` doesn't

**Comment by ollieparanoid** [comment]
That would make sense, I did not try "flasher flash_kernel" with the `lg-mako` (which is the only fastboot device I have tested).
So flashing *does* work when you manually use mkbootimg, and then fastboot?

**Comment by MartijnBraam** [comment]
Yes, with the command in the device page on the wiki

**Comment by ollieparanoid** [comment]
Could somebody please test, if it works with 615880e1615a1b01ec3973b82a87f2b86d31056c?

**Comment by MartijnBraam** [comment]
It works with the change in #132

**Comment by PabloCastellano** [comment]
Great!

Closing as it looks fixed now.

**Comment by MartijnBraam** [comment]
I've just tried the hammerhead build on the current mainline again and this stopped working, the workaround on the wiki still works

**Comment by ollieparanoid** [comment]
Could you port the error symptoms?

**Comment by drebrez** [comment]
@MartijnBraam which workaround you used? you created a boot.img and booted directly without flashing? that workaround to create the boot.img in the host shouldn't be necessary anymore, please try with `pmbootstrap flasher boot`, which does the same thing, if it works

**Comment by MartijnBraam** [comment]
No the flasher boot and flasher_flash kernel both don't work. The workaround is creating the boot.img outside pmbootstrap and using fastboot outside the chroot to flash it.

**Comment by drebrez** [comment]
@MartijnBraam so that means the `mkbootimg` we are using is not working for the hammerhead? 
can you try with the osm0sis version? #441 
Which program you used to create the working boot.img?

**Comment by MartijnBraam** [comment]
Hmm I found the error, the code works fine but the deviceinfo offsets were wrong. Should've checked first.
