### ISSUE TITLE
PC fails to connect to network on phone

### ISSUE THREAD

**Issue by PureTryOut** [postmarketOS/pmbootstrap#355]
As of commit 6a12966, both my PC's fail to connect to the usb network provided by pmOS on the phone. A new interface appears, but NetworkManager can't do anything with it.

As requested by @ollieparanoid, here the result of `./pmbootstrap initfs ls` before and after the failing commit.

Before: https://bpaste.net/show/8e0049c36fc1
After: https://bpaste.net/show/c15324ce6e9d

**Comment by ollieparanoid** [comment]
The output is very helpful! So `/etc/postmarketos-mkinitfs/hooks` only gets generated in the "before" log, not in the "after" log. I'll work on a fix!

**Comment by ollieparanoid** [comment]
Does your issue get resolved, when you use `master`, but add `/etc` here?

https://github.com/postmarketOS/pmbootstrap/blob/b06a55f4a30f8db243be6546479a4088cc64fc23/aports/main/postmarketos-mkinitfs/mkinitfs.sh#L36-L37

If it does, please make a PR with this fix 👍
