### ISSUE TITLE
pmbootstrap init: Explain, that old user interfaces are still installed when the rootfs chroot exists

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#361]
This is unintuitive if not explained, as aleph- let us know in the IRC:
> Also fwy, choosing none in the initialization process, for some reason weston is still selected instead of just plain framebuffer.

**Comment by craftyguy** [comment]
I'm not sure I understand what the exact steps to reproduce this are.. did the user previously have a pmbootstrap config file with 'weston' set, or did they do something else? When I enter 'none', I do not get any UI (e.g. weston) installed.

**Comment by ollieparanoid** [comment]
You're right, my issue description could have been worded better. Here are the steps to reproduce:

1. pmbootstrap init -> select weston
2. pmbootstrap install
3. pmbootstrap init -> select none
4. pmbootstrap install

After running this procedure, `weston` will still be installed in the device rootfs chroot, *unless* you ran `pmbootstrap zap` before 4.

What we could do now, is display a `NOTE:` in the second run of `install`, that the `rootfs` chroot already exists, and that packages from previous runs of `install` will get updated, but not deleted.

**Comment by craftyguy** [comment]
Thanks for the clarification. I think that running `pmbootstrap init` should include automatically zapping the chroot rootfs, especially as `init` increasingly includes package selection/deselection options (like UI). If `init` does not zap the chroot rootfs, then they become 'out of sync' as this issue suggests.

**Comment by ollieparanoid** [comment]
Good point! So how about asking at the end of init (where the work folder is already defined), if the user wants to zap the old rootfs, in case it exists?

**Comment by MartijnBraam** [comment]
I think most developer half-expect the install thing to bootstrap a new clean rootfs (which is pretty quick anyway)

**Comment by craftyguy** [comment]
@ollieparanoid why even ask the user? I think it makes more sense to just do it automatically so that it'll be configured exactly how the user specified in the init questions.

**Comment by ollieparanoid** [comment]
Okay, then just do it without asking. I thought about asking, because we change behavior here. But it makes sense that most users would expect that anyway.

**Comment by craftyguy** [comment]
@ollieparanoid #385 resolves this by calling zap at the end of init. Since pmb.chroot.zap calls shutdown, this should be sufficient, right? It seems to work as intended in all cases I could come up with for validation (config exist, config not exist, chroots exist/not exist, and calling `pmbootstrap zap` still prompts as expected)
