### ISSUE TITLE
Put /etc/deviceinfo in the initramfs, get rid of variable replacements in init.sh.in

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#362]
From https://github.com/postmarketOS/pmbootstrap/issues/325#issuecomment-321708141:
> Currently we do not install the deviceinfo file in the initramfs, so you can not access it. Instead we have variables in the init.sh.in `@varname@` and replace those in mkinitfs. But I think we should use the deviceinfo in the long term, because right now we end up duplicating all of these variables, and the deviceinfo file itself is just a very small text file.

**Comment by craftyguy** [comment]
I think this is pretty much required for osk-sdl, since I'm going to have to rely fairly heavily on device-specific configuration options (e.g. defining the touchscreen device)

**Comment by craftyguy** [comment]
would be copying deviceinfo to /etc in initramfs, and then sourcing this file prior to init.sh (or in init_functions.sh) be sufficient for then replacing all of the @varname@'s in the current implementation with their equivalents from deviceinfo?

**Comment by ollieparanoid** [comment]
There's already a PR open, that integrated the `/etc/deviceinfo`: #394.
It should get merged soon, I recommend basing your work directly on that PR.

**Comment by craftyguy** [comment]
Nice! I totally missed that PR :)
