### ISSUE TITLE
Calculating system image size does not ignore home folder

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#363]
@opendata26 reported in IRC:
> the system image size also includes things in the home folder [in the rootfs chroot]

The thing is, that we do *not* copy this folder to the actual image (and this isn't really documented anywhere, which makes it totally understandable that we didn't pay attention to this), so the size calculation is slightly wrong, when there's a big file in the home folder.

@drebrez: Since you have implemented the minimum size calculation, would you like to take a look at this?

**Comment by drebrez** [comment]
@ollieparanoid just found [this](https://github.com/postmarketOS/pmbootstrap/blob/master/pmb/install/install.py#L85-L88), I didn't know either about it.

If the busybox `du` command has the `--exclude` option, then will be an easy fix.

`du` command is executed [here](https://github.com/postmarketOS/pmbootstrap/blob/master/pmb/install/install.py#L48)

**Comment by opendata26** [comment]
just checked It doesnt we could probably either do
du -cm \`ls | grep -v home\`
Or
list = []
for folder in glob.glob(Mountpoint):
if folder != "/home":
list.append(folder)
du -cm list

**Comment by ollieparanoid** [comment]
The second option would be cleaner in my opinion, as it does not rely on parsing the output of `ls`.

**Comment by drebrez** [comment]
another option is to have an utility function like `get_folder_size`, since we need to use it for the boot folder also, and then we loop through the folders like you said, and sum the folder size of each, skipping home.

**Comment by ollieparanoid** [comment]
That sounds like a good solution! I'll work on a PR.
