### ISSUE TITLE
[flame] Screen output flicker and inactivity

### ISSUE THREAD

**Issue by yuvadm** [postmarketOS/pmbootstrap#375]
The Flame device screen is essentially inactive. A very brief flicker appears upon boot, but immediately disappears and screen turns blank. Debugging this by entering a `loop_forever` right after `show_splash` yielded the same behavior.

In `dmesg` the following (truncated) output shows that framebuffer seems to load correctly:

```
[    0.000000] Node qcom,mdss_fb_primary memblock_reserve memory 3200000-3a00000
[    0.740375] mdss_dsi_panel_init: Panel Name = ili9806c wvga video mode dsi panel
[    0.740634] mdss_dsi_panel_init:1033 Continuous splash flag enabled.
[    0.740647] mdss_dsi_panel_init:1045 Partial update disabled.
[    0.741262] mdss_register_panel: adding framebuffer device fdd00000.qcom,mdss_dsi
[    0.768116] mdp3_alloc: allocating 3280896 bytes at c3200000 (3200000 phys) for fb 0
[    0.768510] mdss_fb_register: FrameBuffer[0] 480x854 size=3280896 registered successfully!
[    0.768728] Registered led device: lcd-backlight
```

There are also some errors coming from `msm_vidc` which do not appear on a normal B2G boot, but do appear on a B2G recovery boot and the screen works there, so they can possibly be ignored (might be related to more advanced screen functions irrelevant for the framebuffer driver)
```
[    3.390004] msm_vidc: 1: Failed to read qcom,load-freq-tbl from device tree
[    3.390017] msm_vidc: 1: no elements in frequency table
[    3.390027] msm_vidc: 1: Failed to read qcom,reg-presets from device tree
[    3.390106] msm_vidc: 1: Failed to read qcom,buffer-type-tz-usage-table from device tree
[    3.390127] msm_vidc: 1: Q6 hfi device probe called
```

All sysfs parameters seem to be set correctly when diffed against the B2G params, except for one param that is set manually to match:

```bash
echo "480,1708" > /sys/devices/virtual/graphics/fb0/virtual_size
```

`fbset` output:

```bash
mode "480x854-4"
	# D: 2.252 MHz, H: 3.263 kHz, V: 3.650 Hz
	geometry 480 854 480 1708 32
	timings 444139 100 100 8 20 10 12
	accel false
	rgba 8/24,8/16,8/8,8/0
endmode
```

This workaround didn't seem to help either:

```
# cat /sys/class/graphics/fb0/modes > /sys/class/graphics/fb0/mode
# cat /sys/class/graphics/fb0/mode
U:480x854p-3
```

This also doesn't do anything:

```
# cat /dev/urandom > /dev/fb0
cat: write error: No space left on device
```

Similar symptoms to #29

**Comment by ollieparanoid** [comment]
For hammerhead, the framebuffer worked after removing support for the proprietary 3d driver in the kernel: https://github.com/postmarketOS/pmbootstrap/pull/66

Maybe that also works for the flame?

**Comment by yuvadm** [comment]
@ollieparanoid nice idea, but that didn't change much

**Comment by ollieparanoid** [comment]
I wonder if the flickering happens again, if you manually run `fbset`.

I'm asking, because on the `lg-mako` the splash screens only appear very briefly and then the screen is black again, but when `fbset` gets executed again, something appears again. Also `weston` works on that device - have you tried to simply run `weston` despite of the `fbset` errors (by booting through)?

**Comment by yuvadm** [comment]
What does running fbset mean? Besides showing the details I can't really get anything out of it.

Sure I'm booting through every single time. Running weston yields:

```
# XDG_RUNTIME_DIR=/tmp/0-runtime-dir/ weston --tty=1
Date: 1970-01-01 GMT
[01:01:06.812] weston 2.0.0
               http://wayland.freedesktop.org
               Bug reports to: https://bugs.freedesktop.org/enter_bug.cgi?product=Wayland&component=weston&version=2.0.0
               Build: 1.99.94-2-g4c4f13d configure.ac: bump to version 2.0.0 for the official release (2017-02-24 16:19:03 -0800)
[01:01:06.813] Command line: weston --tty=1
[01:01:06.813] OS: Linux, 3.4.0, #7-Alpine SMP PREEMPT Mon Aug 14 15:31:57 GMT 2017, armv7l
[01:01:06.813] Using config file '/etc/xdg/weston/weston.ini'
[01:01:06.814] Output repaint window is 7 ms maximum.
[01:01:06.814] Loading module '/usr/lib/libweston-2/fbdev-backend.so'
[01:01:06.815] initializing fbdev backend
[01:01:06.816] /dev/tty1 is already in graphics mode, is another display server running?
[01:01:06.816] fatal: fbdev backend should be run using weston-launch binary or as root
[01:01:06.816] fatal: failed to create compositor backend
```

Or is there another way to run it?

**Comment by ollieparanoid** [comment]
Uh, I meant `fbsplash`. Anyway, from your `weston.log`:
>  guessing 3 Hz and 96 dpi

That seems to be wrong! Maybe it's working when you force 60 Hz directly in the driver?
https://github.com/postmarketOS/pmbootstrap/pull/348/files

I doubt that this will magically make your screen work. But you would need that fix anyway. You could also compare your weston logs with the working weston logs from the "paste your weston.log" issue #141, maybe there's more that you can hardcode in the driver, which could really fix your issue.

**Comment by yuvadm** [comment]
Some more results:

`fbsplash -s splash-telnet.ppm` doesn't do anything

Next, I applied the fixed framerate hack, and now I get:

```
mode "480x854-97"
	# D: 60.002 MHz, H: 86.960 kHz, V: 97.271 Hz
	geometry 480 854 480 1708 32
	timings 16666 100 100 8 20 10 12
	accel false
	rgba 8/24,8/16,8/8,8/0
endmode
```

And weston guesses 100hz (?!):

```
[02:47:52.484] Opening fbdev frame buffer.
[02:47:52.824] Calculating pixman format from:
                - type: 0 (aux: 0)
                - visual: 2
                - bpp: 32 (grayscale: 0)
                - red: offset: 24, length: 8, MSB: 0
                - green: offset: 16, length: 8, MSB: 0
                - blue: offset: 8, length: 8, MSB: 0
                - transp: offset: 0, length: 8, MSB: 0
                - pixman_type: 0
[02:47:52.824] Type guessed: 9:
[02:47:52.824] Mapping fbdev frame buffer.
[02:47:52.824] fbdev output 480×854 px
               guessing 100 Hz and 96 dpi
```

**Comment by yuvadm** [comment]
Also interestingly enough running `fbset` on a recovery B2G image yields the exact same output as the original `fbset`, so maybe the timings *are* correct?

**Comment by yuvadm** [comment]
My current guess is that none of the existing B2G images actually use the framebuffer driver and thus I might be a bit in the dark about what is missing, since I have no working baseline to compare to.

**Comment by drebrez** [comment]
@yuvadm can you try with a patch like this https://github.com/postmarketOS/pmbootstrap/blob/master/aports/device/linux-huawei-y530/05_fix_mdp3_ctrl_off.patch? 
The problems seems like the one I had with the huawei and that patch fixed it.
Please share the full kernel log if it doesn't work, maybe I can help.

**Comment by yuvadm** [comment]
@drebrez wow, this is the first progress I've had so far! The screen actually shows something instead of just flickering once. This is the current splash screen:

![photo5886487700234676767](https://user-images.githubusercontent.com/315080/30261765-c28df28e-96d6-11e7-971a-fd031704a810.jpg)

I'm currently using both the `mdp3-ctrl-off` patch as well as the `fb-refresh-rate` patch. Any ideas?

**Comment by drebrez** [comment]
@yuvadm yes, I had the exactly same output, it's an issue with the bits_per_pixel value, I fixed with this patch (https://github.com/postmarketOS/pmbootstrap/blob/master/aports/device/linux-huawei-y530/06_fix_mdss_fb_rgb_mode.patch)

**Comment by yuvadm** [comment]
Sweet! Will be able to test this later today. Thanks for the great suggestions :)

**Comment by drebrez** [comment]
@yuvadm i've spent various hours debugging that mdss driver, I'm really happy to see that it was worth it and we are getting other devices working 😊

**Comment by yuvadm** [comment]
@drebrez IT'S ALIVE!! 🎉

**Comment by drebrez** [comment]
🌟 💥 Hurray! 💥 🌟

**Comment by kskarthik** [comment]
@yuvadm wow 😀 congrats !
