### ISSUE TITLE
Change Travis CI notifications

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#381]
Right now, Travis CI sends out an e-mail for every check in a PR, and @PureTryOut finds that annoying.
Let's discuss how we want it, here are the options:
https://docs.travis-ci.com/user/notifications/#Changing-notification-frequency

I think IRC notifications would be cool, and I don't need e-mail at all. But we also have `on_failure` as option which could be useful to remind people that their PR can't be merged yet.

**Comment by PureTryOut** [comment]
I myself rather not have any emails from Travis at all, but if we're going for it anyway then at least make it `on_failure` only.

IRC/Matrix (Riot has a Github integration thing we can use) notifications are good enough for me.

**Comment by ollieparanoid** [comment]
I've tried Riot's GitHub integration, and it didn't work for me (they only allowed to integrate with my personal repos, not with those of the postmarketOS organization - and generally I'd like to keep the connected services count as low as possible for security reasons). But having Travis send messages is even more useful than having GitHub send messages, because Travis can tell us whether the build is good or not.
