### ISSUE TITLE
Improve cross-compiling speed with distcc's pump mode

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#384]
Some quotes ([source](https://github.com/distcc/distcc/blob/master/README.pump)):
> Distcc's "pump" mode improves on plain distcc by distributing not only
compilation but also preprocessing to distcc servers.

> Pump mode is able to distribute compilations up to 10X faster than
plain distcc. But because building also involves linking and perhaps
generation of source files, the overall speed-up of the build time is
variable.

> The pump mode was developed to be used with large clusters of distcc
servers, providing hundreds of CPUs. With versions of gcc >= 4.1.1,
pump mode will probably not show major performance gains using
clusters of less than ten CPUs. The preprocessor running on the
workstation is fast enough to keep that many machines busy.

It *might* speed up building if we enable distcc's *pump mode*. I couldn't find any data on the net telling if it really gets faster with the `qemu` setup involved, that we use. Thankfully @PureTryOut agreed to do some benchmarks.

---

It *should* be possible to enable pump mode by changing the following line in `pmb/build/package.py` (at least according to [Gentoo's wiki](https://wiki.gentoo.org/wiki/Distcc#Specifying_participating_hosts)):
```diff
-        env["DISTCC_HOSTS"] = "127.0.0.1:" + args.port_distccd
+        env["DISTCC_HOSTS"] = "127.0.0.1:" + args.port_distccd + ",cpp,lzo"
```

Notes:
* When benchmarking, I suggest doing 3 builds with pump mode and 3 without. Because we have caching throught `ccache` involved etc. Curious to see if it speeds it up! 👍 
* There's `pmbootstrap [--verbose] log_distccd`, which might be helpful. Please note, that `--verbose` may have a performance impact.

**Comment by zhuowei** [comment]
I tried doing this (adding cpp,lzo to the command line, adding distcc-pump to the build chroot, and wrapping the build command with pump), and while compiling hello-world worked, when compiling ksysguard it just didn't distribute. No error messages. Not sure why.

**Comment by ollieparanoid** [comment]
Thanks for trying that out! `pmbootstrap -v` also runs `distccd` in verbose mode, maybe that helps to understand the error.

**Comment by ollieparanoid** [comment]
From [`man 1 distcc`](https://linux.die.net/man/1/distcc):
> distcc's pump mode is not compatible with ccache.
