### ISSUE TITLE
root autologin for tty0 is not a good idea

### ISSUE THREAD

**Issue by craftyguy** [postmarketOS/pmbootstrap#396]
Currently root is set to autologin to tty0, this is not a good idea for security reasons and for reasons where running a UI as `user` is desired (most UIs seem to try and run on tty0).

Weston doesn't run as non-superuser due to weston-launcher not being built in the Alpine APKBUILD. This must be considered since it is the *only* 'official' UI of pmos at the moment.

I can think of two possible solutions to the problem:

1) we can do "user autologin on tty0" and then to run weston you would do "sudo <start_weston>". 

Or

2) do "root autologin on tty0" only if the weston UI has been selected in init (else do "user autologin on tty0" if no UI or other UI is selected)

Or (bonus option)

3) no autologin at all

The second option would not affect the current behavior when weston is selected as the ui, while allowing more secure config if 'none' is selected for ui during init (allowing for running other UIs manually for now).

The first option would be the easiest/fastest to implement, and more secure since it would never allow root autologin.

The third option is the most secure, but requires a way to login to the device (either ssh or local w/ on-screen keyboard or hw keyboard). I only included this option for completeness.

@ollieparanoid, thoughts welcome!

**Comment by ollieparanoid** [comment]
Thanks for opening this issue!

I think a good solution for now would be a mix of 2 and 3:
*No autologin by default, and root autologin enabled in `postmarketos-ui-weston`.*

(To do that, we would move the autologin-part of the `post-install` script from `postmarketos-base` to `postmarketos-ui-weston`.)

We will also need a `postmarketos-ui-plasma-mobile` package sooner or later, which for now could do the autologin to `user`, enable the consolekit2 daemon and start up kwin.

In the long-term, we might want to have some kind of display manager, where you could choose the UI in case you have installed multiple UIs - but we could do that once we have multiple UIs working, and weston starting without root rights.

**Comment by MartijnBraam** [comment]
I think we need something like nodm without the X dependencies. Nodm currently handles autologin and setting all variables in the session and the other xdg stuff

**Comment by ollieparanoid** [comment]
That sounds useful, but isn't that the same as doing the autologin, as we do it right now? If so, I consider not adding an extra program more lightweight.

**Comment by craftyguy** [comment]
Yea I'd rather not add any additional programs and let DMs set themselves up (as they've been designed to do). For the 'no UI' case, that's almost certainly going to be used for development/debug (or crazy people like me).

**Comment by craftyguy** [comment]
#407 implements the option 2 + option 3 method described by @ollieparanoid

**Comment by MartijnBraam** [comment]
DE's arent really meant to set themself up, there are also a bunch of user services that needs to be started which on arch is handled partially by the DE (in case of gnome) and partially by the login manager. Logind usually creates the user dbus instance for example.

If you're using xinitrc then it's the stuff you add before the exec line. It's not a very complex thing (I think nodm is just a shell script) but it makes launching DE's a bit more consistent. It also means you don't have to enable any autologin things in in the inittab, the login manager is startted as service which means you can also enable/disable the graphical desktop with the service tools.

We can basically create a shell script that
- sets up the PAM stuff
- sets up the user dbus
- sets up the consolekit session
- sets up pulseaudio
- start the password wallet
- starts the DE that the user wants

Then add a openrc service for that script and make it start at the right moment

**Comment by craftyguy** [comment]
You bring up a good point and I think all of that is valid, but outside the scope of tho PR I submitted to address this one particular issue: root autologin shouldn't happen by default
