### ISSUE TITLE
Nexus 7 (2013) Help

### ISSUE THREAD

**Issue by jsprada** [postmarketOS/pmbootstrap#40]
Hi All,

I have a 2013 Nexus 7, and am trying to port postmarketOS to it.   I have some questions about the process, I'm hoping to get answered.  I'm also interested in building a more detailed guide on how to do this, once I get it sorted out. 

Is there anyone available, who I can ask some specific questions about the process?

**Comment by ollieparanoid** [comment]
Welcome! You have come to the right place - just ask in this very thread.

If you're more into live chatting, join the [channel](https://github.com/postmarketOS/pmbootstrap/wiki/Matrix-and-IRC). (I still need to set up a client, and have planned to do it this weekend.)

**Comment by jsprada** [comment]
Thank you!  We last chatted just before this whole thing blew up.  I came back from the weekend to see this project trucking along, awesome!

I'm building an image to an SD card (and will try booting from there, prior to installing it on the device itself)  I keep seeing references to `/usr/bin/abuild` missing.   This seems to be an Alpine Linux builder, and I'm not clear if it needs to exist on my host computer, or in the chroot environment.   Will you please advise?


I'll join the IRC!

**Comment by ollieparanoid** [comment]
Ah sorry, I remember now :)

It will get automatically installed inside the (native) chroot, once you tell pmbootstrap to build something.
Nothing gets installed on the host GNU/Linux system.

**Comment by jsprada** [comment]
OK, I see that it exists in ~/.local/..../chroot_native/usr/bin/abuild   

Also, to note, when attempting to run:
#     pmbootstrap chroot
I receive the following error:

ERROR: Package chroot: Could not find aport, and could not find this package in any APKINDEX!

Any chance these are related (Alpine tools, I presume)

**Comment by ollieparanoid** [comment]
That sounds like, you typed in: `pmbootstrap build chroot` (which is wrong, use `pmbootstrap chroot` instead).

When posting errors, please attach a chunk at the end of the logfile from ~/.local/var/pmbootstrap/log.txt. Also make sure, that you run the latest code from git (just got updated).

**Comment by ollieparanoid** [comment]
Run `pmbootstrap --help`,  `pmbootstrap build --help` etc. to get information about the available commands :)

**Comment by jsprada** [comment]
Thank you for the pointers!  You mentioned that this device might be able to use a mainline kernel.  How do I attempt that (rather than cloning lg-mako)?

**Comment by ollieparanoid** [comment]
`lg-mako` does not use a mainline kernel in postmarketOS yet (though we could attempt that at some point, see #12).

Basically, you would switch the kernel source in the APKBUILD, and adjust the config so everything works (whatever that means).

I recommend, that you start with the LineageOS kernel. When that works, you could experment with mainline (what I have learned from developing postmarketOS is: don't take too many steps at once - make tiny steps and version everything, so you can go back easily when you broke something).

**Comment by jsprada** [comment]
OK, that makes perfect sense.  This is the first time I've attempted to port an OS to a tablet.  Rather, I'm attempting to install what you guys have already ported.  So please pardon me while I ask lots of questions.

I started with a fresh pull from the repository, ran the init, cloned the recommended samsung package, and am about to edit the APKBUILD and deviceinfo files prior to doing this, I'm following the instructions about locating the lineageOS settings for my device.  

I ran `pmbootstrap build unpackbootimg`  then  upon running  `pmbootstrap chroot`  I enter my password for sudo, then am left with a non active prompt, and the following entries in the log:

    (020221) [12:13:28] (native) % sh
    (020221) [12:13:28] Using selector: EpollSelector
    (020221) [12:13:28] (native) % sh

I was assuming that I'd be able to chroot to the temp build in .local, and grab the appropriate settings from the lineage kernel that I located, but the prompt just hangs.  I ^Z stopped it, and tried again with the same results.

**Comment by jsprada** [comment]
I figured it out!

    ./pmbootstrap chroot apk add unpackbootimg
    ./pmbootstrap chroot su ....

I understand now, the chroot parameter passes commands, one at a time, rather than entering the user into a perpetual chroot environment.

**Comment by ollieparanoid** [comment]
You should be able to enter a chroot with `pmbootstrap chroot`, but this is broken now (sorry!). I'll fix that in a few minutes though.

**Comment by jsprada** [comment]
OK, thank you!  That makes sense, I'll give it another go when you're through.

**Comment by ollieparanoid** [comment]
It should work now again

**Comment by jsprada** [comment]
Thank you, I'm chrooted, with a shell now, resuming process!

**Comment by jsprada** [comment]
I successfully unpacked the info for the package "flo" (Google Nexus 7 2013):

    Android magic found at: 0
    BOARD_KERNEL_CMDLINE console=ttyHSL0,115200,n8 androidboot.hardware=flo user_debug=31 
    msm_rtb.filter=0x3F ehci-hcd.park=3 vmalloc=340M buildvariant=userdebug
    BOARD_KERNEL_BASE 00008000
    BOARD_RAMDISK_OFFSET 02000000 
    BOARD_SECOND_OFFSET 00f00000
    BOARD_TAGS_OFFSET 00000100
    BOARD_PAGE_SIZE 2048 
    BOARD_SECOND_SIZE 0
    BOARD_DT_SIZE 0


And it isn't clear which of these map to the exact key/values in the `deviceinfo` file.    
    
    # You can for example extract these from an existing boot.img
    deviceinfo_flash_offset_base=""
    deviceinfo_flash_offset_kernel=""
    deviceinfo_flash_offset_ramdisk=""
    deviceinfo_flash_offset_second=""
    deviceinfo_flash_offset_tags=""
    deviceinfo_flash_pagesize=""


Most of these seem obvious , except `deviceinfo_flash_offset_kernel=""`   Do I use the value from `BOARD_KERNEL_CMDLINE` in the boot.img?

Thank you!

**Comment by MartijnBraam** [comment]
The offset_kernel is the same as kernel_base

**Comment by ollieparanoid** [comment]
Maybe this is helpful: `fastboot --help`:
```
 -b, --base <base_addr>                   Specify a custom kernel base
                                           address (default: 0x10000000).
  --kernel-offset                          Specify a custom kernel offset.
                                           (default: 0x00008000)
  --ramdisk-offset                         Specify a custom ramdisk offset.
                                           (default: 0x01000000)
  --tags-offset                            Specify a custom tags offset.
                                           (default: 0x00000100)
  -n, --page-size <page size>              Specify the nand page size
                                           (default: 2048).
```

**Comment by jsprada** [comment]
Thank you @MartijnBraam  do I leave the offset_base blank?  or is it equal to offset_kernel, which is derived from KERNEL_BASE?

**Comment by lawl** [comment]
Ollie will probably tell me off for binary blobs again. But i suggest you check my comment here: https://github.com/postmarketOS/pmbootstrap/issues/18

As always when downloading random code from github, use a VM. But this reports the exact values you need unabigously, including the base.

**Comment by jsprada** [comment]
@lawl  Just so I'm clear, you're suggesting that I try using the utility in the thread linked (https://github.com/xiaolu/mkbootimg_tools) to unpack a copy of the lineageOS kernel to extract the values?  Perhaps it works better, or gets more details than the `unpackbootimg`  Alpine package that I build in my chroot environment?

Naturally, I'd perform this in a VM.

This also brings a point, once we pull this information, would it make sense to store it, perhaps on a wiki page for each phone/image under this project?  Or will each, eventually, exist as it's own package in the project?

Thank you.

**Comment by lawl** [comment]
@jsprada i'm not suggesting anything, do whatever works for you, that's just what I've done.

The idea is to put these values into the deviceinfo file and have them live there in a package per device, yes.

**Comment by jsprada** [comment]
Most excellent, thank you for sharing what worked for you.  I also tried this, and was able to unpack images for the two devices I'm attempting to port to:

# flo

Unpack & decompress /home/johnny/Downloads/lineage-14.1-20170530-nightly-flo-signed/boot.img to /home/johnny/flo
  kernel         : kernel
  ramdisk        : ramdisk
  page size      : 2048
  kernel size    : 5036456
  ramdisk size   : 1384892
  base           : 0x80200000
  kernel offset  : 0x00008000
  ramdisk offset : 0x02000000
  tags offset    : 0x00000100
  cmd line       : console=ttyHSL0,115200,n8 androidboot.hardware=flo user_debug=31 msm_rtb.filter=0x3F ehci-hcd.park=3 vmalloc=340M buildvariant=userdebug
ramdisk is gzip format.
Unpack completed.


# ghost

Unpack & decompress /home/johnny/Downloads/lineage-13.0-20170527-nightly-ghost-signed/boot.img to /home/johnny/ghost
  kernel         : kernel
  ramdisk        : ramdisk
  page size      : 2048
  kernel size    : 3788928
  ramdisk size   : 1037845
  dtb size       : 792716
  base           : 0x80200000
  kernel offset  : 0x00008000
  ramdisk offset : 0x02200000
  tags offset    : 0x00000100
  dtb img        : dt.img
  cmd line       : console=ttyHSL0,115200,n8 androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x3F ehci-hcd.park=3 maxcpus=2 androidboot.write_protect=0
ramdisk is gzip format.
Unpack completed.


Now I'll carry on with my port.

**Comment by jsprada** [comment]
OK, when attempting to install the image onto an SD card, I get the following results (whether I attempt to install on the device /dev/sdd, or the partition /dev/sdd1, I get the same results. 

(011422) [17:10:18] *** (1/5) PREPARE NATIVE CHROOT ***
(011422) [17:10:18] *** (2/5) CREATE DEVICE ROOTFS (asus-nexus7) ***
(011422) [17:10:18] (rootfs_asus-nexus7) % apk update
fetch https://nl.alpinelinux.org/alpine/edge/main/armhf/APKINDEX.tar.gz
fetch https://nl.alpinelinux.org/alpine/edge/community/armhf/APKINDEX.tar.gz
fetch https://nl.alpinelinux.org/alpine/edge/testing/armhf/APKINDEX.tar.gz
v3.6.0-206-gce4ebf229c [https://nl.alpinelinux.org/alpine/edge/main]
v3.6.0-123-ga9574f08d3 [https://nl.alpinelinux.org/alpine/edge/community]
v3.6.0-140-g2275192021 [https://nl.alpinelinux.org/alpine/edge/testing]
OK: 10279 distinct packages available
(011422) [17:10:22] (rootfs_asus-nexus7) % passwd user
(011422) [17:10:22] *** output passed to pmbootstrap stdout, not to this log ***
(011422) [17:10:31] *** (3/5) PREPARE INSTALL BLOCKDEVICE ***
(011422) [17:10:31] ERROR: The sdcard path does not look valid. We will not attempt to format this!
(011422) [17:10:31] Run 'pmbootstrap log' for details.
(011422) [17:10:31] Traceback (most recent call last):
  File "./pmbootstrap.py", line 68, in main
    pmb.install.install(args)
  File "/home/johnny/files/projects/pmbootstrap/pmb/install/install.py", line 96, in install
    pmb.install.blockdevice.create(args)
  File "/home/johnny/files/projects/pmbootstrap/pmb/install/blockdevice.py", line 101, in create
    mount_sdcard(args)
  File "/home/johnny/files/projects/pmbootstrap/pmb/install/blockdevice.py", line 44, in mount_sdcard
    raise RuntimeError("The sdcard path does not look valid. We will"
RuntimeError: The sdcard path does not look valid. We will not attempt to format this!

**Comment by jsprada** [comment]
And when I attempt to flash, without installing, I get the following:

(017354) [17:16:21] (native) boot lg-mako kernel
(017354) [17:16:21] ERROR: action boot is not configured for method heimdall!
(017354) [17:16:21] Run 'pmbootstrap log' for details.
(017354) [17:16:21] Traceback (most recent call last):
  File "./pmbootstrap.py", line 70, in main
    pmb.flasher.frontend(args)
  File "/home/johnny/files/projects/pmbootstrap/pmb/flasher/frontend.py", line 82, in frontend
    kernel(args)
  File "/home/johnny/files/projects/pmbootstrap/pmb/flasher/frontend.py", line 49, in kernel
    pmb.flasher.run(args, "boot", kernel, ramdisk)
  File "/home/johnny/files/projects/pmbootstrap/pmb/flasher/run.py", line 30, in run
    " configured for method " + method + "!")
RuntimeError: action boot is not configured for method heimdall!



Finally, I've attempted to flash straight to my device, but the script seems to detect my device - the device isn't detected.  I'm not quite sure how to prepare it to receive the image.

**Comment by ollieparanoid** [comment]
about the sdcard issue: if you are sure, that `/dev/sdd` is the correct partition, you could add this path to the pmb/config/__init__.py (look for `mmcblk` there). on your local copy only, I think we should add a flag, that overrides the check for pmbootstrap.
I thought, that sdcards would never be in `/dev/sdd` on GNU/Linux o_O You are sure, that this is the right device?

**Comment by MartijnBraam** [comment]
sdcards on my system are also /dev/sd* devices, depends on the sd card adapter driver.

**Comment by jsprada** [comment]
Thank you for the hint on this one!  I'll check out the init.py!  

I'm 100% certain that my card is /dev/sdd.   I do a LOT of work with Raspberry Pis and such, I image SD cards almost daily.  

I think any naming convention is possible using udev rules, to decide how to name block devices.  

I use Arch Linux, which distros do you all use?

**Comment by jsprada** [comment]
FYI, I found the setting @ollieparanoid mentioned in __init__.py and added my specific path `/dev/sdd`

I made a bit of progress, however, subsequently failed.  It appears that there are some assumptions about mount point/naming conventions, or some sort of mount auto-naming coming into play.  

Does this have anything to do with needing to `zap` ?

I did a search on `mmcblk` and it appears to exist in a few places.  I can take a peek at what those do in a bit. 

I'll be back in a couple of hours to work on this later.   

[12:00:54] EVERYTHING ON /dev/sdd WILL BE ERASED! CONTINUE? (y/n) [n] y
(010309) [12:00:57] (native) mount /dev/install (host: /dev/sdd)
(010309) [12:00:57] % sudo touch /home/johnny/.local/var/pmbootstrap/chroot_native/dev/install
(010309) [12:00:57] % sudo mount --bind /dev/sdd /home/johnny/.local/var/pmbootstrap/chroot_native/dev/install
(010309) [12:00:57] (native) partition /dev/install (boot: 100M, root: the rest)
(010309) [12:00:57] (native) % parted -s /dev/install mktable msdos
(010309) [12:00:58] (native) % parted -s /dev/install mkpart primary ext2 2048s 100M
(010309) [12:00:58] (native) % parted -s /dev/install mkpart primary 100M 100%
(010309) [12:00:58] (native) % parted -s /dev/install set 1 boot on
(010309) [12:00:58] % sudo touch /home/johnny/.local/var/pmbootstrap/chroot_native/dev/installp1
(010309) [12:00:58] % sudo mount --bind /dev/sddp1 /home/johnny/.local/var/pmbootstrap/chroot_native/dev/installp1
mount: special device /dev/sddp1 does not exist
(010309) [12:00:58] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(010309) [12:00:58] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/johnny/.local/var/pmbootstrap/log.txt
(010309) [12:00:58] ERROR: Command failed: % sudo mount --bind /dev/sddp1 /home/johnny/.local/var/pmbootstrap/chroot_native/dev/installp1
(010309) [12:00:58] Run 'pmbootstrap log' for details.
(010309) [12:00:58] Traceback (most recent call last):
  File "/home/johnny/files/projects/pmbootstrap/pmb/helpers/run.py", line 39, in core
    stderr=args.logfd)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', 'mount', '--bind', '/dev/sddp1', '/home/johnny/.local/var/pmbootstrap/chroot_native/dev/installp1']' returned non-zero exit status 32.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./pmbootstrap.py", line 68, in main
    pmb.install.install(args)
  File "/home/johnny/files/projects/pmbootstrap/pmb/install/install.py", line 97, in install
    pmb.install.partition(args)
  File "/home/johnny/files/projects/pmbootstrap/pmb/install/partition.py", line 57, in partition
    partitions_mount(args)
  File "/home/johnny/files/projects/pmbootstrap/pmb/install/partition.py", line 35, in partitions_mount
    args.work + "/chroot_native/dev/install" + suffix)
  File "/home/johnny/files/projects/pmbootstrap/pmb/helpers/mount.py", line 75, in bind_blockdevice
    destination])
  File "/home/johnny/files/projects/pmbootstrap/pmb/helpers/run.py", line 76, in root
    return user(args, cmd, log, working_dir, return_stdout, check)
  File "/home/johnny/files/projects/pmbootstrap/pmb/helpers/run.py", line 67, in user
    return core(args, cmd, "% " + " ".join(cmd), log, return_stdout, check)
  File "/home/johnny/files/projects/pmbootstrap/pmb/helpers/run.py", line 52, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: % sudo mount --bind /dev/sddp1 /home/johnny/.local/var/pmbootstrap/chroot_native/dev/installp1

**Comment by ollieparanoid** [comment]
Cool, that you've made progress.
Well, the naming scheme is different for `/dev/sd...` devices:
* for `/dev/mmcblk0`, the first partition is at `/dev/mmcblk0p1`
* for `/dev/sdd`, the first partition is at `/dev/sdd1`

As a workaround, you could take the places in the source that fail, and remove the "p" letter I guess (might be a lot of effort though). I'll open an extra ticket, to fix this properly.

**Comment by ollieparanoid** [comment]
I have adjusted the code - it should be possible to use `/dev/sdd` etc. as sdcard device now, without modifying anything.

**Comment by jsprada** [comment]
Thank you for the quick solutions!  We're getting closer!   

The script is now recognizing the SD card, partitioning it, but still failing.  The error indicates that it's looking for `/dev/sdd1`  which exists, but can't seem to find it.

(023868) [12:58:27] *** (3/5) PREPARE INSTALL BLOCKDEVICE ***
[12:58:27] EVERYTHING ON /dev/sdd WILL BE ERASED! CONTINUE? (y/n) [n] y
(023868) [12:58:34] (native) mount /dev/install (host: /dev/sdd)
(023868) [12:58:34] % sudo touch /home/johnny/.local/var/pmbootstrap/chroot_native/dev/install
(023868) [12:58:34] % sudo mount --bind /dev/sdd /home/johnny/.local/var/pmbootstrap/chroot_native/dev/install
(023868) [12:58:34] (native) partition /dev/install (boot: 100M, root: the rest)
(023868) [12:58:34] (native) % parted -s /dev/install mktable msdos
(023868) [12:58:34] (native) % parted -s /dev/install mkpart primary ext2 2048s 100M
(023868) [12:58:34] (native) % parted -s /dev/install mkpart primary 100M 100%
(023868) [12:58:34] (native) % parted -s /dev/install set 1 boot on
(023868) [12:58:35] ERROR: Unable to find the partition prefix, expected the first partition of /dev/sdd to be located at /dev/sdd1 or /dev/sddp1!
(023868) [12:58:35] Run 'pmbootstrap log' for details.
(023868) [12:58:35] Traceback (most recent call last):
  File "./pmbootstrap.py", line 68, in main
    pmb.install.install(args)
  File "/home/johnny/files/projects/pmbootstrap/pmb/install/install.py", line 97, in install
    pmb.install.partition(args)
  File "/home/johnny/files/projects/pmbootstrap/pmb/install/partition.py", line 70, in partition
    partitions_mount(args)
  File "/home/johnny/files/projects/pmbootstrap/pmb/install/partition.py", line 43, in partitions_mount
    "1 or " + prefix + "p1!")
RuntimeError: Unable to find the partition prefix, expected the first partition of /dev/sdd to be located at /dev/sdd1 or /dev/sddp1!


FYI:
    johnny@static:pmbootstrap[master ?] $ lsblk
    NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
    sda      8:0    0 111.8G  0 disk 
    ├─sda1   8:1    0   512M  0 part /boot
    ├─sda2   8:2    0  99.5G  0 part /
    ├─sda3   8:3    0     8G  0 part [SWAP]
    └─sda4   8:4    0   3.8G  0 part 
    sdb      8:16   0 238.5G  0 disk 
    └─sdb1   8:17   0 238.5G  0 part /home
    sdc      8:32   0 931.5G  0 disk 
    └─sdc1   8:33   0 931.5G  0 part /mnt/1tb
    sdd      8:48   1   7.4G  0 disk 
    ├─sdd1   8:49   1    94M  0 part 
    └─sdd2   8:50   1   7.3G  0 part 


OK, I'll get on the chat!

**Comment by ollieparanoid** [comment]
We might need to run `partprobe` after formatting the sdcard, so the kernel picks up the changes before looking for `/dev/sdd1`.
Does it work, when you run it two times in a row (-> when the partition was already present before)?

**Comment by voltagex** [comment]
Is there a more current issue for the 2013 Nexus 7?

**Comment by ollieparanoid** [comment]
I couldn't ind any. I suggest you start new issues about specific problems, and linking them on the [device page](https://wiki.postmarketos.org/wiki/Google_Nexus_7_2013_(asus-flo)).
