### ISSUE TITLE
Complete ROM available for Xperia C3 Dual?

### ISSUE THREAD

**Issue by Adguarder** [postmarketOS/pmbootstrap#402]
Xperia C3 Dual please created ROM for my smartphone

**Comment by ollieparanoid** [comment]
Hello and welcome to postmarketOS!

We do not have a port for the Xperia C3 yet as shown on the [Devices](https://github.com/postmarketOS/pmbootstrap/wiki/Devices) page. But other Xperia devices have been ported yet, so it could be feasible to do it.

If you have some Linux skills and want to learn something, then you can do the port yourself by following the [porting guide](https://github.com/postmarketOS/pmbootstrap/wiki/Porting-to-a-new-device) and asking either by commenting on this page, or in the [irc/matrix channel](https://github.com/postmarketOS/pmbootstrap/wiki/Matrix-and-IRC) (recommended) if you get stuck, so we can help you.

If you don't have Linux experience, then you could take the friendly offer by @PabloCastellano in his [Milestones](https://github.com/postmarketOS/pmbootstrap/wiki/Milestones#pablo-castellano) section, where he offers to try to do the port for you if you send him your device.

And in case you do *not* want to learn something new, but just have a phone OS, that is easy to use: postmarketOS is not the right OS for you at this point. It can't even make phone calls, and Wifi only works on some devices. But check out end-user friendly projects from other people in the community such as [ubports](https://ubports.com/) (Ubuntu Touch), [LineageOS](http://lineageos.org) and [CopperheadOS](https://copperhead.co/android)!

**Comment by ollieparanoid** [comment]
Closing this, as the initial question is answered. Feel free to write here or in the channel if you have more questions.
