### ISSUE TITLE
How port it, please.

### ISSUE THREAD

**Issue by zhenyolka** [postmarketOS/pmbootstrap#403]
Sorry for my very bad English.
How port it to my LG device. I have qualcomm chipset(8610). And screen mount physically rotated(180 degress).
How port?
Thank you!

**Comment by PureTryOut** [comment]
Please [read the wiki](https://github.com/postmarketOS/pmbootstrap/wiki/Porting-to-a-new-device), it's there for a reason.

**Comment by ollieparanoid** [comment]
If you have trouble with the language, there are translation services.
And you can ask in the [chat](https://github.com/postmarketOS/pmbootstrap/wiki/Matrix-and-IRC) if something is hard to understand (click on the matrix link for direct access).
