### ISSUE TITLE
Error. I try "menuconfig" command

### ISSUE THREAD

**Issue by zhenyolka** [postmarketOS/pmbootstrap#409]
Error. I try "menuconfig" command.
log in file.
[log.txt](https://github.com/postmarketOS/pmbootstrap/files/1233927/log.txt)

**Comment by PureTryOut** [comment]
Please upload the log file to a pastebin service like https://pastebin.com or https://bpaste.net

**Comment by zhenyolka** [comment]
https://pastebin.com/HUEgYAgi

**Comment by yuvadm** [comment]
@zhenyolka are you trying to port a new device `lg-d285`? It looks like you have a typo in your `APKBUILD`, please post it as well.

**Comment by zhenyolka** [comment]
https://pastebin.com/a4Eap6aW
log from terminal

**Comment by yuvadm** [comment]
@zhenyolka it seems you are working on a new device and that the `pmbootstrap/aports/device/linux-lg-d285/APKBUILD` file you wrote has something wrong/missing in it. Please post that file.
