### ISSUE TITLE
Cannot enter password (pmbootstrap install)

### ISSUE THREAD

**Issue by Roysten** [postmarketOS/pmbootstrap#41]
At some point after running the install command it will ask for the password of the user (passwd user). This password cannot be entered anymore using the latest version (text appears but does not get passed to the underlying passwd executable, text appearing is a bug in itself since a password should not show up in the terminal). Does this have to do with pr #25?

**Comment by ollieparanoid** [comment]
Thanks for the bug report. As a workaround, use the previous version (git checkout $lastworkingcommit), I'll work on a fix.

**Comment by ollieparanoid** [comment]
#25 is reverted now, it should work again.
