### ISSUE TITLE
Please port it to lg l65.

### ISSUE THREAD

**Issue by zhenyolka** [postmarketOS/pmbootstrap#413]
I try port, but cant(pc small resources, i dont know android). 
Please port it to lg l65 if you can.

**Comment by ollieparanoid** [comment]
I wrote this in a similar thread https://github.com/postmarketOS/pmbootstrap/issues/402#issuecomment-323126801:
> If you have some Linux skills and want to learn something, then you can do the port yourself by following the [porting guide](https://github.com/postmarketOS/pmbootstrap/wiki/Porting-to-a-new-device) and asking either by commenting on this page, or in the [irc/matrix channel](https://github.com/postmarketOS/pmbootstrap/wiki/Matrix-and-IRC) (recommended) if you get stuck, so we can help you.
>
> If you don't have Linux experience, then you could take the friendly offer by @PabloCastellano in his [Milestones](https://github.com/postmarketOS/pmbootstrap/wiki/Milestones#pablo-castellano) section, where he offers to try to do the port for you if you send him your device. That only makes sense if you are eager to learn a lot of new stuff, though.
>
> And in case you do *not* want to learn something new, but just have a phone OS, that is easy to use: postmarketOS is not the right OS for you at this point. It can't even make phone calls, and Wifi only works on some devices. But check out end-user friendly projects from other people in the community such as [ubports](https://ubports.com/) (Ubuntu Touch), [LineageOS](http://lineageos.org) and [CopperheadOS](https://copperhead.co/android)!
