### ISSUE TITLE
ADB server didn't ACK

### ISSUE THREAD

**Issue by ata2001** [postmarketOS/pmbootstrap#426]
When trying to run the following in the native chroot:

`adb start-server`

I get:

```
* daemon not running. starting it now on port 5037 *
ADB server didn't ACK
* failed to start daemon *
error: cannot connect to daemon
```

strace: https://github.com/postmarketOS/pmbootstrap/files/1237075/adbtrace.txt

**Comment by ollieparanoid** [comment]
That's funny, it seems to work when you explicitly start it:

```
/ # adb start-server
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
/ # adb devices
List of devices attached
```

...and when you start it again, it simply gets ignored. So you could change the code to always start it before and it should work.

```python
    "adb": {
            "depends": ["android-tools"],
            "actions":
            {
                "list_devices": [["adb", "start-server"],
                                 ["adb", "devices"]],
                "sideload": [["adb", "start-server"],
                             ["adb", "wait-for-usb-sideload"],
                             ["adb", "sideload", "$RECOVERY_ZIP"]],
            }
    },
```

**Comment by ata2001** [comment]
@ollieparanoid This didn't help, however I found out, when I mount the whole sysfs inside the chroot, adb starts working.

Maybe something is not mounted, that is needed for networking/adb in the chroot?

**Comment by ata2001** [comment]
after mounting /sys/dev/, it works perfectly

**Comment by ollieparanoid** [comment]
Cool, that you've found that out!
