### ISSUE TITLE
Can't launch Qemu for ARM

### ISSUE THREAD

**Issue by PureTryOut** [postmarketOS/pmbootstrap#428]
After installing the Qemu ARM device, `./pmbootstrap.py qemu --arch=arm` errors with `ERROR: Could not find the 'qemu-system-arm' executable in your PATH. Please install it in order to run qemu.`

`./pmbootstrap.py log`:
```
(026310) [20:49:58] Running postmarketOS in QEMU VM (arm)
(026310) [20:49:58] % sudo chmod 666 /home/****/.local/var/pmbootstrap/chroot_native/home/user/rootfs/qemu-vexpress.img
(026310) [20:49:58] ERROR: Could not find the 'qemu-system-arm' executable in your PATH. Please install it in order to run qemu.
(026310) [20:49:58] Run 'pmbootstrap log' for details.
```

**Comment by ollieparanoid** [comment]
What the message means is: install it with your distributions package manager (or compile it yourself, in your case, with `emerge`).
