### ISSUE TITLE
404 Page Not Found: for Device Package and Kernel Package for Huawei Y350

### ISSUE THREAD

**Issue by jamesjames** [postmarketOS/pmbootstrap#432]

**Comment by yuvadm** [comment]
Seems you are referring to the links on this wiki page https://github.com/postmarketOS/pmbootstrap/wiki/Huawei-Ascend-Y530

Indeed I can't find those files on any particular branch. @drebrez can you please update those links?

**Comment by drebrez** [comment]
@jamesjames @yuvadm the links are now working fine.
