### ISSUE TITLE
Qemu ARM warnings

### ISSUE THREAD

**Issue by PureTryOut** [postmarketOS/pmbootstrap#433]
When running the ARM Qemu image, several warnings are printed out. They might not block anything, but it would probably be good to get them worked out anyway.

Our current networking solution is great, but deprecated it seems.

```
qemu-system-arm: -redir tcp:2222::22: The -redir option is deprecated. Please use '-netdev user,hostfwd=...' instead.
```

Since we don't specify the image format, Qemu starts guessing and mentions it's dangerous. This probably affects performance quite a lot.
```
WARNING: Image format was not specified for '/home/bart/.local/var/pmbootstrap/chroot_native/home/user/rootfs/qemu-vexpress.img' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
```

Last but not least some PulseAudio errors:

```
pulseaudio: set_sink_input_volume() failed
pulseaudio: Reason: Invalid argument
pulseaudio: set_sink_input_mute() failed
pulseaudio: Reason: Invalid argument
```

**Comment by MartijnBraam** [comment]
One of the problems is that the -redir option is deprecated on your version of qemu but not the one in the ubuntu repo's for example

The format detection should not affect the performance it only restricts writes to the first block (which we don't need)

The pulseaudio warnings might mean you don't have sound in the VM but it doesn't prevent the VM from running

**Comment by PureTryOut** [comment]
> One of the problems is that the -redir option is deprecated on your version of qemu but not the one in the ubuntu repo's for example

I'm guessing the one in the Gentoo repos is newer than, meaning Ubuntu will get the same eventually. It's definitely not a priority, but it might be good to move away from it eventually.

> The format detection should not affect the performance it only restricts writes to the first block

Aah good. Still, specifying `-raw` (or whatever it needs) shouldn't be too difficult. Even if it's just for a clean boot log 😉 

> The pulseaudio warnings might mean you don't have sound in the VM but it doesn't prevent the VM from running

Like I said, none of the warnings really block anything, but it'd be nice to get rid of them anyway. Since the Qemu images will probably be used in the future to easily test apps for pmOS, having working audio is something we should strive for.

**Comment by MartijnBraam** [comment]
The pulse error is most likely related to your sound setup. I haven't found a way yet to make qemu not open a pulse connection so if you don't run pulse you just get that warning

**Comment by PabloCastellano** [comment]
I've fixed the `-redir` warning in PR https://github.com/postmarketOS/pmbootstrap/pull/482. Can you test it?

Are you still getting the other error related to not specifying the format of the image? I see that we already use the `raw` option.

**Comment by PabloCastellano** [comment]
Quoting @PureTryOut 

> If we're going for virtio, check Arch's wiki. Specifically note Currently a work in progress, supporting only very recent (>= 4.4) Linux guests with mesa (>=11.2) compiled with the option --with-gallium-drivers=virgl.. TL;DR: it won't work with proprietary drivers (like NVIDIA, screw them). Could still be an option though.
>
> EDIT: Actually, I might be misreading that. Is it only talking about the guest support? If that's true then it shouldn't be a problem.
>
> EDIT 2: So, I've just tested virtio-gpu instead, and it seems to work.
>
> I've set CONFIG_DRM_VIRTIO_GPU=m, CONFIG_VIRTIO_PCI=m, and CONFIG_VIRTIO_BALLOON=m in the kernel config, and launched Qemu with -vga virtio -display gtk,gl=on. In Qemu I've installed the mesa-dri-virtio and mesa-dri-swrast packages. Although I didn't get kwin running properly yet, the log reports it initializing the OpenGL backend succesfully using DRM.

That's good news and so, virtio-gpu is definitely the way to go!

Since the spice approach is giving me better performance and virtio-gpu is only supported in recent versions of qemu (I'm not sure if virtio-gpu will work for me), I would like to keep the spice functionality (which would benefit others in my situation).

**We need more testers**

...to learn more about the performance issues and once we get more feedback, we can decide what should be the default behaviour when virtio-gpu is not supported in qemu, that is, if it usually performs bad, then convert `--no-spice` to `--spice`. So by default people will get the most performance approach and in rare cases like mine, I can still use `--spice`.
