### ISSUE TITLE
Clean up APKBUILDs

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#436]
@PabloCastellano wrote in https://github.com/postmarketOS/pmbootstrap/pull/435#discussion_r134242611:
> I've tested that you can just remove build() and nothing bad happens. I don't know why a lot of aports are defining it as return 0 instead of just removing it 🤔

Besides, some `APKBUILD`s probably still have the `|| return 1` after the commands, which is obsolete since a few months or so (upstream change in Alpine's `abuild`).

We should go through all `APKBUILD`s and modernize them.

**Comment by ollieparanoid** [comment]
@drebrez shows a nice way to shorten the `prepare()` functions in kernel packages by calling `default_prepare`, which we should apply to all other kernel packages (except for `linux-postmarketos`, that works differently) in my opinion:

https://github.com/postmarketOS/pmbootstrap/blob/b7b001119530bd1147988ac3d029e2772306d38b/aports/device/linux-lg-dory/APKBUILD#L50-L58

**Comment by drebrez** [comment]
@ollieparanoid in [this](https://wiki.alpinelinux.org/wiki/APKBUILD_examples:Simple) example they have `default_prepare || return`, so probably I have to add it for that APKBUILD.
Another thing to use the `builddir` variable, which is the default path used by the default prepare function ([see here](https://wiki.alpinelinux.org/wiki/APKBUILD_Reference#builddir)).
I think it's the default path also for the build function.

**Comment by drebrez** [comment]
Another thing is the `build` subfolder used to build inside it, instead for the `linux-lg-dory/APKBUILD` you linked above, I used directly the `builddir` to build.
In one case you get all the compiled files inside the subfolder, in the other, the compiled files are among the sources.
I checked some alpine packages and none of them used a subfolder to build. 
Which style has to be followed?

**Comment by montvid** [comment]
The example does not build my kernel. I needed to add this instead and it worked:
`prepare() {
	default_prepare
	mkdir -p "$srcdir"/build
	cp "$srcdir"/$_config "$srcdir"/build/.config || return 1
	make -C "$ksrcdir" O="$srcdir"/build ARCH="$_carch" HOSTCC="$HOSTCC" \
	silentoldconfig
}`

**Comment by ollieparanoid** [comment]
@drebrez:
> @ollieparanoid in [this](https://wiki.alpinelinux.org/wiki/APKBUILD_examples:Simple) example they have `default_prepare || return`, so probably I have to add it for that APKBUILD.

I've removed all `|| return` statements from that wiki page, as they are not needed since a few months back (because alpine got updated). It will fail automatically now, when one executed statement fails. So `default_prepare` is enough here.

> Another thing to use the `builddir` variable, which is the default path used by the default prepare function ([see here](https://wiki.alpinelinux.org/wiki/APKBUILD_Reference#builddir)).

This variable was introduced into the wiki on 2016-10-18, and it looks like not all packages in Alpine have been adjusted to using it yet. But good that you point it out, we should make use of it when possible.

> Another thing is the `build` subfolder used to build inside it, instead for the `linux-lg-dory/APKBUILD` you linked above, I used directly the `builddir` to build.
> In one case you get all the compiled files inside the subfolder, in the other, the compiled files are among the sources.
> I checked some alpine packages and none of them used a subfolder to build. 
> Which style has to be followed?

Our kernel packages are based on [`linux-vanilla`](https://github.com/alpinelinux/aports/blob/8c23c325fcd82598c3a470d7d44a293911e0fae8/main/linux-vanilla/APKBUILD), which [also uses a subfolder for building.](https://github.com/alpinelinux/aports/blob/8c23c325fcd82598c3a470d7d44a293911e0fae8/main/linux-vanilla/APKBUILD#L78) I am not sure why they did this though. If we can do it without the extra folder, and get a cleaner result, I would personally prefer the solution without the extra folder.

@montvid:
> The example does not build my kernel. I needed to add this instead and it worked:

That must be because @drebrez didn't use the extra build folder (which is expected by the rest of your APKBUILD, that's why it did not work).

**Comment by PabloCastellano** [comment]
PR https://github.com/postmarketOS/pmbootstrap/pull/692 solves this issue. 

However it doesn't modify the `prepare()` function to use `default_prepare`. I was not able to compile `linux-motorola-titan` using this approach because patches don't apply. Some path must be incorrect.

If someone wants to debug further, you can do it entering the chroot after failing to compile and then running
`cd /home/user/build && su user -c 'CC=armv6-alpine-linux-muslgnueabihf-gcc CROSS_COMPILE=armv6-alpine-linux-muslgnueabihf- CARCH=armhf abuild -d -f -v`

Notice the ending `-v`!

**Comment by drebrez** [comment]
@PabloCastellano you have to specify the `builddir` variable to make it work (see [here](https://github.com/alpinelinux/abuild/blob/master/abuild.in#L595-L610))

**Comment by ollieparanoid** [comment]
The kernel APKBUILDs need some more refactoring anyway, I suggest we create a template first, then adjust the existing APKBUILDs to that, see: #688
