### ISSUE TITLE
Where to put firmware packages? aports/device or aports/firmware?

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#437]
I've suggested in https://github.com/postmarketOS/pmbootstrap/issues/358#issuecomment-321667956:
> Package the firmware blobs as aports/firmware/firmware-qualcomm-prima (the path is debatable, I think a new firmware folder makes sense. I've tried to stick to the manufacturer-codename scheme with the package name, but please suggest better ideas if you have any!

PR #435 followed this proposal (and I didn't want to block it with this issue, we can simply move the folder afterwards if necessary), while we also have `aports/device/firmware-adreno` from @opendata26's excellent work.

As of now, I think both options are good, but we should settle for one. What do you think, @opendata26, @yuvadm, @PabloCastellano and everyone else in this fantastic community? :)

**Comment by yuvadm** [comment]
As evident from my PR +1 for firmware 😉

**Comment by PabloCastellano** [comment]
For me, `aports/firmware` makes a lot of sense too

**Comment by opendata26** [comment]
Definitely aports/firmware

**Comment by drebrez** [comment]
also for me make sense aports/firmare, since firmware-adreno, for example, is generic and probably shared across devices.
The question I have now is related to the aports/firmware/firmware-mozilla-flame, which is already there, we will put there also the device specific firmwares?

**Comment by ollieparanoid** [comment]
@drebrez: I think it would be a good idea to have that clearly separated. 
So would it be OK for you if we had the `aports/firmware/firmware-samsung-i9070` package?

**Comment by drebrez** [comment]
@ollieparanoid seems good to have it separated, I'll start working on it, PR coming soon

**Comment by drebrez** [comment]
Closing, since a decision has been made.

### Firmware packages will be placed in `aports/firmare` folder.
