### ISSUE TITLE
Rename mozilla-flame to t2m-flame

### ISSUE THREAD

**Issue by fabricedesre** [postmarketOS/pmbootstrap#442]
This is similar to the naming of Nexus device which uses device-lg-hammerhead and not device-google-hammerhead.

Mozilla didn't build the hw, t2m did.

**Comment by ollieparanoid** [comment]
Good catch! Do you want to make a PR for that?

**Comment by fabricedesre** [comment]
ha ha, I see what you did there :) Maybe, but not today.

**Comment by yuvadm** [comment]
@fabricedesre more importantly, would you want to help out doing some of the work on the Flame? I could use a helping hand 😉

**Comment by fabricedesre** [comment]
Sorry, I spent a lot of time working with these devices in the FirefoxOS days, but I don't plan to use them anymore.

I'm not sure which repositories forked from t2m you are talking about. The manifests at https://github.com/mozilla-b2g/b2g-manifest/blob/master/flame.xml point directly at git://github.com/t2m-foxfone/

**Comment by yuvadm** [comment]
Interesting, I've been mostly looking at the manifests for `flame-kk`, not `flame` - https://github.com/mozilla-b2g/b2g-manifest/blob/master/flame-kk.xml and indeed most of the repos there have been forked and use the `b2g` remote.

**Comment by yuvadm** [comment]
First of all, I'm using the manifests for `flame-kk` located at https://github.com/mozilla-b2g/b2g-manifest/blob/master/flame-kk.xml

Second, if you take a look at the important repos (kernel and device, right now) you can see they come from the `b2g` remote.

**Comment by fabricedesre** [comment]
First, you should base on something more recent than kk :)

Then, I'm not sure what you are arguing. Having a fork of the msm kernel doesn't make Mozilla the device manufacturer.

**Comment by yuvadm** [comment]
If there are any more recent kernels for the flame I'd love to use them! I remember that the lollipop kernel isn't that much different than the kitkat one, and I couldn't find any references for it being built on the flame, so I went with kitkat. But if you have any other recommendation I'd love to hear it :)

As for the device name, it's really not much of a difference to me, as long as we keep consistent with the rest of the devices.
