### ISSUE TITLE
Add a -y (--asume-yes) parameter to automatically answer "yes" to questions 

### ISSUE THREAD

**Issue by PabloCastellano** [postmarketOS/pmbootstrap#450]
Actually I miss a `-y` argument that allows me to run `pmbootstrap install` automatically accepting the warning that my system partition is at least XXX MB and I want to include my ssh key in the device.

Same happens when I run `pmbootstrap zap` and I want to delete all my chroots but I have to answer 'y' several times.

**Comment by ollieparanoid** [comment]
Workaround: `yes | pmbootstrap`. But I agree, that would be nice to have!

**Comment by craftyguy** [comment]
> it will also set empty passwords

This is probably obvious, but I want to ask so it's explicitly part of the 'requirements' for this request:

Should `-y` for `install` still prompt for passwords? Or is this request to implement a mode for `install` and `zap` such that they are completely hands-off?

**Comment by PabloCastellano** [comment]
My idea is that `-y` automatically answers yes to yes/no questions. If pmbootstrap asks for a password, then the user still has to enter it. What do you think?

**Comment by MartijnBraam** [comment]
I would `-y` to only answer yes to all answers, for full automated running you would have a `-q` option or something

**Comment by craftyguy** [comment]
Ok, I agree with both of y'all, just want to make sure I understood
the requirements :)

**Comment by ollieparanoid** [comment]
FYI: we already have `-q`, which silences the output for now. I think it makes sense to add a different switch to skip passwords (in case you want to have the output, but want to skip passwords).

**Comment by craftyguy** [comment]
I'll take a shot at implementing this, since I'm now annoyed that I have to spam 'y' :)

**Comment by PabloCastellano** [comment]
@craftyguy Great that you got motivated about this ux feature! :)

I've seen your current PR and looks good. But here's a more generic approach so that we can make this flag more generic and valid for more pmbootstrap commands. Tell me what you think and give it a try if you like it:

- Check `args.assume_yes` inside pmb.helpers.cli.confirm`
- Add the `-y` argument to the main parser (I mean, in the same level as `--version`)

This way `-y` would also work for:
- initfs: confirm overwriting extract folder
- zap: confirm removing chroot
- init: confirm use timebased builds and zap existing chroots

**Comment by craftyguy** [comment]
Oh, that's a great idea. I hadn't thought about other commands. I will modify my PR to include this functionality if we are at a consensus on this

**Comment by craftyguy** [comment]
@PabloCastellano 

I've implemented what you described. It's definitely more elegant, though it makes placement of the option a little awkward. For instance, it's an argument to pmbootstrap and not to the "function":

`./pmbootstrap --assume-yes (or -y) install --blah --blah2`

**Comment by craftyguy** [comment]
Closed via 3942a06a2da101843605a1a19b045080137c6dbf
