### ISSUE TITLE
Multiple flash methods

### ISSUE THREAD

**Issue by ata2001** [postmarketOS/pmbootstrap#460]
Some devices support multiple flash methods by default. Since #404 is merged, you can specify the flash method manually from the command line with the `--method` option. However it is not safe to allow using every flash method on any device.

The plan is to only allow flash methods, which are enabled in the device's `deviceinfo` file (`deviceinfo_flash_methods`).

@ollieparanoid said we should add adb (recovery flashing) to the `deviceinfo` too, but I disagree, because TWRP is not something installed by default, hence I think it doesn't belong in the `deviceinfo` file.

We would like to hear the community's opinion on this, so we could fix this.

**Comment by ollieparanoid** [comment]
As written in #625, our code tends to ignore that there could be multiple flash methods specified. I suggest that we only allow one flash method and rename the variable to `deviceinfo_flash_method` (without the `s`). This would also resolve the question whether we should add `adb` as flash method or not.

If a device still supports multiple flash methods, we could mention that in the device's wiki page along with a description of how to use it (with `--method`).

Any opinions on this?

PS: I think the wiki could use a step-by-step article about the recovery flash method, which mentions that you need to use `pmbootstrap flasher --method=adb sideload`.
