### ISSUE TITLE
Adding postmarketos-artwork

### ISSUE THREAD

**Issue by MartijnBraam** [postmarketOS/pmbootstrap#464]
I guess we need a postmarketos-artwork package to provide default wallpapers for this distro

The *-artwork package name is based on how debian handles artwork for different distro variations, these packages provide a bunch of images in /usr/share (https://packages.debian.org/sid/all/debian-edu-artwork-lines/filelist)

I think we should provide wallpapers and a icon to be used for "start" buttons

Photo's that I made that can be used: http://imgur.com/a/73XW6 (I haven't added a licence to them yet, anyone knows what would be the best one?)

**Comment by PabloCastellano** [comment]
About the licensing I would choose some creative commons variant.
See https://creativecommons.org/choose/

**Comment by MartijnBraam** [comment]
Here is a mint-style wallpaper created with blender

![pmos](https://user-images.githubusercontent.com/6928199/29723289-4ce97d9c-89c4-11e7-9d53-a5f84f3986d5.png)

The blender source:
[pmos.zip](https://github.com/postmarketOS/pmbootstrap/files/1252432/pmos.zip)

**Comment by MartijnBraam** [comment]
I found the solution for the stem of the "p" when using the full name. Smallcaps:

![postmarketos](https://user-images.githubusercontent.com/6928199/29728159-235fbd0c-89d7-11e7-814c-f1482bbcb8bc.png)

**Comment by Jgjot-Singh** [comment]
I have some photos(my own work) that I'd like to make available. Should I just create an imgur gallery and link to it here?

**Comment by MartijnBraam** [comment]
We've moved the artwork to https://github.com/postmarketOS/artwork, you can create a PR there with your wallpapers

**Comment by moondeck** [comment]
I like the idea of a common package, but doesn't that require to either:

1. Have individual packages for each DE (as they store wallpapers in different places)

2. Have some sort of DE detection

**Comment by PabloCastellano** [comment]
I ignore if different DE have different locations for wallpapers. However for this case, we could achieve it this way:

1. Create a postmarketos-artwork package that install the wallpapers to some location like `/usr/share/wallpapers`
2. By using the [install_if](https://wiki.alpinelinux.org/wiki/APKBUILD_Reference#install_if) variable, copy or symlink the files to the proper location for the installed DE.

**Comment by ollieparanoid** [comment]
We have the `postmarketos-ui-*` packages, which handle postmarketOS configuration of the interfaces / desktop environments. I would recommend that we set the default wallpapers also in there instead of the `install_if` block.

Freedesktop.org has a specification where wallpapers should go:

[DesktopThemeSpec](https://www.freedesktop.org/wiki/DesktopThemeSpec/):
> Wallpapers should be installed in $XDG_DATA_DIRS/wallpapers

[XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)
> If $XDG_DATA_DIRS is either not set or empty, a value equal to /usr/local/share/:/usr/share/ should be used. 

=> `/usr/share/wallpapers` seems to be the appropriate location.


Finally I recommend that we don't make the wallpaper/artwork package too big - it's probably good to make use of [subpackages](https://wiki.alpinelinux.org/wiki/APKBUILD_Reference#subpackages) here, so people can only install the wallpapers they want to have and not a huge wallpaper pack that blows up the installation without using them. And we probably don't need to provide everything from the artwork repository in the packages (e.g. the reddit theme).

**Comment by moondeck** [comment]
I will try to package that and submit a pull request then.

**Comment by ollieparanoid** [comment]
During research of the Freedesktop.org spec, I've found [this page](https://wiki.mate-desktop.org/mate-backgrounds) which lists where different desktop environments look for wallpapers (we could add a symlink to that path in the `postmarketos-ui-* package) and how to change them programmatically.

**Comment by MartijnBraam** [comment]
Hmm the DE's I've used all read either `/usr/share/wallpapers` or `/usr/share/backgrounds` but that might just be my luck. Maybe create a `postmarketos-artwork` package with the wallpapers that literally say postmarketOS and a `postmarketos-artwork-extra` that contain all the nice-but-unbranded wallpapers since that will the the big bunch.

**Comment by ollieparanoid** [comment]
I like the idea, but "artwork" might be a bit too generic for wallpapers (what if we want to package ringtones etc. later?) - how about:
* `postmarketos-artwork` (meta-package that depends on the subpackages)
* `postmarketos-artwork-wallpapers` (the wallpapers saying pmOS or postmarketOS)
* `postmarketos-artwork-wallpapers-extra` (the nice-but-unbranded wallpapers)

**Comment by moondeck** [comment]
Sure, i'll do it like that. I don't know if its gonna be tomorrow or (european) sunday, but i will try to package that this weekend.

**Comment by drebrez** [comment]
@MartijnBraam now that the artwork has been packaged, this can be closed?

**Comment by MartijnBraam** [comment]
Yep
