### ISSUE TITLE
Add option to `zap` for clearing out packages that mismatch versions in aports

### ISSUE THREAD

**Issue by craftyguy** [postmarketOS/pmbootstrap#466]
I bounce around between branches fairly often, and packages are frequently updated between branches, I get a lot of these types of warnings: WARNING: Package 'sdl2' in your aports folder has version 2.0.5-r0, but the binary package repositories already have version 2.0.5-r9999!. 

It would make sense to have some form of zap that also clears out any binary packages that are newer than anything in aports, since clearing out ALL packages (-p) is overkill.

**Comment by ollieparanoid** [comment]
See also: https://wiki.postmarketos.org/wiki/Troubleshooting#Newer_version_in_binary_package_repositories_than_in_aports_folder

**Comment by yuvadm** [comment]
+1 on making this a proper feature, I get this a lot as well.

**Comment by craftyguy** [comment]
Closed via a9e5b362dc359458fc6807c1f02e5e8d3b89d900
