### ISSUE TITLE
wrong pkgrel of musl

### ISSUE THREAD

**Issue by robinpaulson** [postmarketOS/pmbootstrap#471]
the file "APKBUILD" in /home/user/build attempts to download this:
https://nl.alpinelinux.org/alpine/edge/main/armhf/musl-1.1.16-r17.apk

but this is the only version available:
https://nl.alpinelinux.org/alpine/edge/main/armhf/musl-1.1.16-r18.apk

how is that file created? can a person with access update the relevant line to r18?

cheers

**Comment by robinpaulson** [comment]
Opps, sorry not enough info. It's the armhf version, i'm building pmos for i9100

Anyhow, it's this file here which is wrong:
https://github.com/postmarketOS/pmbootstrap/blob/master/aports/cross/musl-armhf/APKBUILD

line 6 should be 18, not 17

cheers!

**Comment by ollieparanoid** [comment]
I will fix this ASAP, thanks for letting me know. The fix is to run `pmbootstrap aportgen gcc-armhf`, if you don't want to wait.

**Comment by robinpaulson** [comment]
great, cheers for the quick response!

**Comment by robinpaulson** [comment]
Hmm:
fatal: open /dev/null or dup failed: Permission denied
is the response when I run the command you suggest above. I've seen several errors about accessing /dev/null before, in the log for pmbootstrap

**Comment by ollieparanoid** [comment]
Which filesystem and host OS are you using, and are you running in a VM? Device nodes can not get created on ntfs shares, old versions of ecryptfs, maybe on encfs, shared VM folders, ...

**Comment by ollieparanoid** [comment]
`musl-armhf` has been updated in the `master` branch now. But you will run into the device nodes issues anyway, so make sure that this works. You can also join the [IRC/matrix chat](https://wiki.postmarketos.org/wiki/Matrix_and_IRC) for instant help :)

**Comment by robinpaulson** [comment]
Ubuntu 16.04, ecrypt v111 (apparently the newest is v112). I'm not using a vm or ntfs. I don't know of encfs and don't have it installed. I will check out matrix chat if I can't get it working soon.

**Comment by ollieparanoid** [comment]
the problem is ecryptfs here. It should work when you change the work folder (the one it asks you for in `pmbootstrap init`) to another location.
For example:
```shell
sudo mkdir /opt/pmbootstrap
sudo chown $(id -u) /opt/pmbootstrap
./pmbootstrap config work /opt/pmbootstrap
```

**Comment by robinpaulson** [comment]
OK, so is it worth installing v112 from a ppa on launchpad?

**Comment by ollieparanoid** [comment]
If you really want to, you could try it. I have no idea whether that works. On a side note, I advise against adding unnecessary `ppa`s to your installation for security reasons.
The solution from above should work (although the `pmbootstrap` folder will not be encrypted then).
In case you want to have everything encrypted, I recommend using `cryptsetup/Luks` to encrypt the whole system instead of the home folder only (we also do that in postmarketOS).

**Comment by robinpaulson** [comment]
OK, I tried the suggestion of moving the working directory out of /home. The build is running now. Point taken about the PPA.

As an aside, I think /var may be a more appropriate place for the working dir.

**Comment by dzervas** [comment]
That's been a problem since the early days (specifically musl). Can we automate it in a way? Or detect when a package needs `aportgen` and run it automatically?

**Comment by robinpaulson** [comment]
We could get the release file for the repo and parse that, like any existing package manager.

**Comment by ollieparanoid** [comment]
@robinpaulson: that is what we do exactly. But we only do it when you run the `aportgen` command :)

**Comment by robinpaulson** [comment]
Ah, excellent. I should read more of the code and docs.
