### ISSUE TITLE
Check if it is possible to create device nodes in the work folder

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#472]
We've had a few cases where the device node creation did not work. It would be nice if we check that during `pmbootstrap init` and tell the user what could cause this and what to do about it (use another location, link to a wiki page with details).

Possible causes:
* Shared VM folder
* NTFS folder?
* Old versions of ecryptfs
* maybe encfs

**Comment by MartijnBraam** [comment]
* filesystems with the `nodev` flag enabled
* vfat/exfat
* nfs shares

**Comment by ollieparanoid** [comment]
In all reports, a `/dev/null` device creation fails, so we should try to do that (and remove it afterwards, if it works).

**Comment by drebrez** [comment]
@ollieparanoid Right now it's not allowed to have the work dir inside pmbootstrap folder (#852), this can be closed?

**Comment by ollieparanoid** [comment]
Actually this is a different issue. Some people have put the work folder on a NTFS volume for example, where the driver does not allow to create device nodes (`/dev/null` etc.), as required to set up the chroots properly. Detecting this is not implemented yet.

Thanks for going through the old issues! 😃
