### ISSUE TITLE
Add command to flash system image to userdata partition

### ISSUE THREAD

**Issue by MartijnBraam** [postmarketOS/pmbootstrap#484]
This would be nice for devices with a small system partition. Either `flash_userdata` (which might be taken by some other functionaly in the future if we implement LVM) or `flash_system --to-userdata`

**Comment by ollieparanoid** [comment]
Good idea! (Another variation would be: `flash_system --partition=userdata` - this could help for the cases where the system/userdata partition has a strange name, such as on the i9100.)

**Comment by drebrez** [comment]
I also vote for the `--partition` argument, since I have a device with both partitions (system and userdata) very small but it has another bigger partition (internal sd)
