### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by TheBestDevs** [postmarketOS/pmbootstrap#485]
Making a qt5 based api

**Comment by TheBestDevs** [comment]
Its cross platform and easy to use !

**Comment by ollieparanoid** [comment]
Welcome, @TheBestDevs!

Unlike other mobile operating systems you are not limited by the frameworks and programming languages in postmarketOS. Use *anything* you want to create your applications. Everything that is available in Linux will work. So if you want to make programs in QT5, just do it!
