### ISSUE TITLE
[hammerhead] Fix license

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#49]
@MartijnBraam, @dzervas: Is it okay, if we change the license inside the [APKBUILD](https://github.com/postmarketOS/pmbootstrap/blob/master/aports/device-lg-hammerhead/APKBUILD) from `FIXME` to `MIT`? I've done this for the other device APKBUILDs (which I wrote, thus I can change the license without asking), because FIXME isn't a real license and MIT is what Alpine Linux used for their internal packages.

**Comment by dzervas** [comment]
Yeap, fine by me!

**Comment by MartijnBraam** [comment]
Also fine by me

**Comment by dzervas** [comment]
Now that you mention it, it's a pity that the project is not under a BSD derived license... :/
(no problem though, as long as it's open source)

**Comment by ollieparanoid** [comment]
@dzervas: I chose the GPLv3 for pmbootstrap intentionally, because I didn't want it to end up in a closed source product at some point.
