### ISSUE TITLE
Creating the rootfs image fails sometimes

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#501]
The following error just happened during `pmbootstrap install`:
`losetup: /home/user/rootfs/lg-mako.img: failed to set up loop device: No such file or directory`

When I run `pmbootstrap install` again, it gets created fine. This might be a regression in using `truncate` instead of `fallocate`? Or maybe it is related to the `loop` module not getting loaded properly?

I rand `lsmod | grep loop` directly after the failed `pmbootstrap install` and the `loop` module was loaded.

Full log:
```
(029356) [23:47:15] (native) % rm /home/user/rootfs/lg-mako.img
(029356) [23:47:15] (native) create lg-mako.img (435M)
(029356) [23:47:15] WARNING: Make sure, that your target device's partition table has allocated at least 435M as system partition!
[23:47:15] Continue? (y/n) [y] y
(029356) [23:47:18] (native) % su user -c 'mkdir -p /home/user/rootfs'
(029356) [23:47:18] (native) % truncate -s 435M /home/user/rootfs/lg-mako.img
(029356) [23:47:18] (native) mount /dev/install (lg-mako.img)
(029356) [23:47:18] (native) mount /home/user/rootfs/lg-mako.img (loop)
(029356) [23:47:18] % sudo mount --bind /dev/loop-control /home/user/.local/var/pmbootstrap/chroot_native//dev/loop-control
(029356) [23:47:18] (native) % losetup -f /home/user/rootfs/lg-mako.img
losetup: /home/user/rootfs/lg-mako.img: failed to set up loop device: No such file or directory
(029356) [23:47:19] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(029356) [23:47:19] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/user/.local/var/pmbootstrap/log.txt
(029356) [23:47:19] ERROR: Command failed: (native) % losetup -f /home/user/rootfs/lg-mako.img
(029356) [23:47:19] Run 'pmbootstrap log' for details.
(029356) [23:47:19] See also: <https://postmarketos.org/troubleshooting>
(029356) [23:47:19] Traceback (most recent call last):
  File "/home/user/code/pmbootstrap/pmb/helpers/run.py", line 45, in core
    stderr=args.logfd)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '/usr/bin/sh', '-c', "env -i CHARSET=UTF-8 PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sb
in:/bin SHELL=/bin/ash HISTFILE=~/.ash_history /usr/bin/chroot /home/user/.local/var/pmbootstrap/chroot_native sh -c 'cd /;losetup -f /home/user/rootfs/lg-mako.img'"]
' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/code/pmbootstrap/pmbootstrap.py", line 53, in main
    getattr(pmb.helpers.frontend, args.action)(args)
  File "/home/user/code/pmbootstrap/pmb/helpers/frontend.py", line 136, in install
    pmb.install.install(args)
  File "/home/user/code/pmbootstrap/pmb/install/install.py", line 285, in install
    install_system_image(args)
  File "/home/user/code/pmbootstrap/pmb/install/install.py", line 164, in install_system_image
    pmb.install.blockdevice.create(args, size_image)
  File "/home/user/code/pmbootstrap/pmb/install/blockdevice.py", line 101, in create
    create_and_mount_image(args, size)
  File "/home/user/code/pmbootstrap/pmb/install/blockdevice.py", line 84, in create_and_mount_image
    pmb.install.losetup.mount(args, img_path)
  File "/home/user/code/pmbootstrap/pmb/install/losetup.py", line 44, in mount
    pmb.chroot.root(args, ["losetup", "-f", img_path])
  File "/home/user/code/pmbootstrap/pmb/chroot/root.py", line 86, in root
    return_stdout, check)
  File "/home/user/code/pmbootstrap/pmb/helpers/run.py", line 58, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: (native) % losetup -f /home/user/rootfs/lg-mako.img
```

**Comment by ollieparanoid** [comment]
That's interesting, now I got the following message:
```
losetup -f /home/user/rootfs/qemu-amd64.img
losetup: /home/user/rootfs/qemu-amd64.img: failed to set up loop device: Not a tty
```

And again it worked the second time.

**Comment by BrianOtto** [comment]
I got the same error today too. Running `pmbootstrap install` a second time also worked for me.

```
(004744) [22:57:29] (native) % losetup -f /home/user/rootfs/qemu-amd64.img
losetup: /home/user/rootfs/qemu-amd64.img: failed to set up loop device: No such file or directory
(004744) [22:57:29] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(004744) [22:57:29] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/pmos/.local/var/pmbootstrap/log.txt
(004744) [22:57:29] ERROR: Command failed: (native) % losetup -f /home/user/rootfs/qemu-amd64.img
(004744) [22:57:29] Run 'pmbootstrap log' for details.
(004744) [22:57:29] See also: <https://postmarketos.org/troubleshooting>
(004744) [22:57:29] Traceback (most recent call last):
  File "/home/pmos/Projects/pmbootstrap/pmb/helpers/run.py", line 45, in core
    stderr=args.logfd)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '/bin/sh', '-c', "env -i CHARSET=UTF-8 PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash HISTFILE=~/.ash_history /usr/sbin/chroot /home/pmos/.local/var/pmbootstrap/chroot_native sh -c 'cd /;losetup -f /home/user/rootfs/qemu-amd64.img'"]' returned non-zero exit status 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pmos/Projects/pmbootstrap/pmb/__init__.py", line 53, in main
    getattr(frontend, args.action)(args)
  File "/home/pmos/Projects/pmbootstrap/pmb/helpers/frontend.py", line 136, in install
    pmb.install.install(args)
  File "/home/pmos/Projects/pmbootstrap/pmb/install/install.py", line 285, in install
    install_system_image(args)
  File "/home/pmos/Projects/pmbootstrap/pmb/install/install.py", line 164, in install_system_image
    pmb.install.blockdevice.create(args, size_image)
  File "/home/pmos/Projects/pmbootstrap/pmb/install/blockdevice.py", line 101, in create
    create_and_mount_image(args, size)
  File "/home/pmos/Projects/pmbootstrap/pmb/install/blockdevice.py", line 84, in create_and_mount_image
    pmb.install.losetup.mount(args, img_path)
  File "/home/pmos/Projects/pmbootstrap/pmb/install/losetup.py", line 44, in mount
    pmb.chroot.root(args, ["losetup", "-f", img_path])
  File "/home/pmos/Projects/pmbootstrap/pmb/chroot/root.py", line 86, in root
    return_stdout, check)
  File "/home/pmos/Projects/pmbootstrap/pmb/helpers/run.py", line 58, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: (native) % losetup -f /home/user/rootfs/qemu-amd64.img
```

**Comment by ollieparanoid** [comment]
@BrianOtto: Can you reproduce this reliably? If so, please test if #511 fixes it for you. Otherwise we'll probably merge it anyway, as it should make the issue go away/make pmbootstrap more robust for that case.
Thanks for reporting!

**Comment by PabloCastellano** [comment]
@BrianOtto I guess @ollieparanoid meant https://github.com/postmarketOS/pmbootstrap/pull/518/

**Comment by BrianOtto** [comment]
@ollieparanoid and @PabloCastellano

I am able to reproduce the issue reliably. The only problem is the results of my tests were, well, odd ...

In short, PR #518 does not appear to fix the issue.

I am new to this build process, and it's possible I may not be understanding something and / or testing incorrectly. So let me explain the tests I ran, and the results I got for each.

**Test 1 - An attempt to reproduce the issue**

1) rebooted my computer
2) cloned my fork into a new directory

`git clone https://github.com/GrokBB/pmbootstrap /home/pmos/Projects/pmbootstrap-test1`

3) initialized the build process

```
./pmbootstrap.py init
Device = qemu-amd64
Work Path = /home/pmos/.local/var/pmbootstrap-test1
```

4) ran the install (and then waited 1 Hr)

`./pmbootstrap.py install`

5) Result = ERROR

**Test 2 - An attempt to see if the PR fixes the issue**

1) did NOT reboot my computer
2) cloned my fork into a new directory

`git clone https://github.com/GrokBB/pmbootstrap /home/pmos/Projects/pmbootstrap-test2`

3) pulled in PR #518

```
git remote add upstream https://github.com/postmarketOS/pmbootstrap
git fetch upstream
git pull upstream refs/pull/518/head
```

4) initialized the build process

```
./pmbootstrap.py init
Device = qemu-amd64
Work Path = /home/pmos/.local/var/pmbootstrap-test2
```

5) ran the install (and then waited 1 Hr)

`./pmbootstrap.py install`

6) Result = SUCCESS

**Test 3 - An attempt to see if the PR fixes the issue AFTER a reboot**

1) rebooted my computer
2) cloned my fork into a new directory

`git clone https://github.com/GrokBB/pmbootstrap /home/pmos/Projects/pmbootstrap-test3`

3) pulled in PR #518

```
git remote add upstream https://github.com/postmarketOS/pmbootstrap
git fetch upstream
git pull upstream refs/pull/518/head
```
4) initialized the build process

```
./pmbootstrap.py init
Device = qemu-amd64
Work Path = /home/pmos/.local/var/pmbootstrap-test3
```

5) ran the install (and then waited 1 Hr)

`./pmbootstrap.py install`

6) Result = ERROR

**Test 4 - An attempt to see if the PR fixes the issue AFTER a reboot**

I did **Test 3** a 2nd time, and I got the **losetup** error again.

**Test 5 - An attempt to see if the original code will work when I do NOT reboot**

1) did NOT reboot my computer
2) cloned my fork into a new directory

`git clone https://github.com/GrokBB/pmbootstrap /home/pmos/Projects/pmbootstrap-test5`

3) initialized the build process

```
./pmbootstrap.py init
Device = qemu-amd64
Work Path = /home/pmos/.local/var/pmbootstrap-test5
```

4) ran the install (and then waited 1 Hr)

`./pmbootstrap.py install`

5) Result = SUCCESS

----

So, to summarize, it appears like the **losetup** step will work, regardless of the PR fix or not, as long as I run `./pmbootstrap.py install` a 2nd time AND I don't reboot before doing this... and this works even when creating a clean directory to work in! If I reboot between test attempts then it fails every time.

Is it possible the **qemu-amd64.img** file is temporarily being cached somewhere, outside the chroot, and **losetup** is trying to access this location instead? The code doesn't appear to be doing this, but maybe I am missing something.

Some other interesting things I noticed ...

The **wait_for_image_file()** function you created for the PR is supposed to log a "NOTE", every 0.1 seconds, when it fails to find the image file. This note never showed up in any of my logs. It's as if **os.path.exists()** was returning true, but **losetup** still couldn't find it. Actually, as I type this, I just noticed you are doing a logging.debug, not a logging.info, and so maybe I needed to enable some kind of debug mode to see those messages.

Any time I ran `./pmbootstrap.py init` the **chroot_native** directory (e.g. **/home/pmos/.local/var/pmbootstrap-test4/chroot_native**) would get removed in my PREVIOUS test directory. For example, when I was working in **pmbootstrap-test5**, the **pmbootstrap-test4** one got removed. I thought that by creating a new directory and setting the `Work Path` to this, the changes would be isolated. So either I am misunderstanding how the process works, or the script is accessing previous build files when it shouldn't.

Anyway, those are my results. They don't make a whole lot of sense to me, but I'm hoping they help out in some way. I am running Debian 9.1.0 in VirtualBox 5.1.26, in case this is relevant.

Cheers!

**Comment by ollieparanoid** [comment]
Wow... you have spent a lot of effort debugging this! I am very grateful for that and the information you have found out is more than helpful.

`logging.debug` prints to the log, that is visible with `pmbootstrap log` (the output gets saved to `$work/log.txt`.) So if the chroot folders still exist, you could grep the log messages for the NOTE message to see if it retried successfully.


> [...] would get removed in my PREVIOUS test directory. [...]

Your expectations are correct, this should not have happened and is a bug (#524).

It's great that you can reproduce this issue! Could you try the following? (I have the theory, that losetup may say that the file does not exist, even though it does, when the loop module is not loaded).

### Test if we can reproduce it without building everything
1. Reboot your VM
1. Go into any pmbootstrap directory you have (your fork or master, **without** the patch from #518)
1. Run `pmbootstrap zap` to clear the chroots (including a previous image file)
1. `pmbootstrap install` (without changing the work directory or zapping the *packages*)
1. I expect that the error appears here
1. `pmbootstrap install` again
1. I expect that it goes away

### Maybe this "fixes it?"
1. Reboot your VM
1. Go to the same `pmbootstrap` folder as before
1. Run `pmbootstrap zap` to clear the chroots (including a previous image file)
1. `sudo modprobe loop`
1. `pmbootstrap install`
1. If we're lucky, it works now.

Thanks a lot!

**Comment by BrianOtto** [comment]
@ollieparanoid

> **Maybe this "fixes it?"**

Yes, your solution worked !

I also did the **Test 1** scenario again, just to double check and verify against a brand new build... but this time I ran `sudo modprobe loop` before `./pmbootstrap.py install`, and this is working too.

Your theory is correct, **losetup** thinks that the file doesn't exist when the loop module is not loaded :)

**Comment by ollieparanoid** [comment]
### \o/

Here's how we could fix it: Calling `pmb.helpers.run.root(["modprobe", "loop"])` in `pmb/install/losetup.py` in the `mount()` function before calling `losetup`.

I'm a bit short on time right now, so I can't do the necessary testing etc. But I will make a PR for this soon, unless you want to take a shot at it.

Thanks for testing that theory!

**Comment by BrianOtto** [comment]
Sure, I can take a shot at it. I'll give it a go tonight.

**Comment by BrianOtto** [comment]
PR #528 has been created, tested and confirmed working on my setup.

**Comment by z3ntu** [comment]
I also didn't have any problems after this update. Thanks :)
