### ISSUE TITLE
APKBUILD source doesnt download files with the correct name when file url has a parameter. (Use the Content-Disposition header for file names) 

### ISSUE THREAD

**Issue by JamesHealdUK** [postmarketOS/pmbootstrap#505]
If I set the source in my APKFILE to the desired source (in this case, from a Gitlab instance) like so:
`source="https://git.merproject.org/mer-core/lipstick/repository/archive.tar.gz?ref=${hash}"`
pmbootstrap ends up downloading it with the name: `archive.tar.gz?ref=db74015dd7924dea52b5996d69e8fd7311f2d0f0`

When it should be downloaded as: `lipstick-db74015dd7924dea52b5996d69e8fd7311f2d0f0.tar.gz`.

Heres an example [APKBUILD](https://hastebin.com/umasidituc.bash) (i know some fields are wrong in there, like the description but just throwing together my Asteroid port atm!) and a [link](https://git.merproject.org/mer-core/lipstick/repository/archive.tar.gz?ref=db74015dd7924dea52b5996d69e8fd7311f2d0f0) to the file in question.

I believe this issue can be solved by making sure that [http.py](https://github.com/postmarketOS/pmbootstrap/blob/8b3ffc8dc8fd173b80ab10daa5584cd139fc8807/pmb/helpers/http.py#L46) uses the `Content-Disposition` header to get the correct file name.

Id try and make a fix myself and might if no one else gets round to it tomorrow, but Im going to bed soon.

**Comment by ollieparanoid** [comment]
Thanks for making this issue. Alpine's `abuild` is responsible for downloading the source files, and it has a syntax to use a different file name:
> `$pkgname-$pkgver.tar.gz::http://oss.example.org/?get=software&ver=$pkgver`

More information: https://wiki.alpinelinux.org/wiki/APKBUILD_Reference#source

**Comment by ollieparanoid** [comment]
Note: As you are using a hash, you can use `$pkgname-$hash.tar.gz::http//...`.

**Comment by JamesHealdUK** [comment]
ohh, thanks a lot!
