### ISSUE TITLE
Weston package fails to build

### ISSUE THREAD

**Issue by jonty-comp** [postmarketOS/pmbootstrap#508]
Just picked up this project today and dusted off my old HTC One V (primou) to see if I can get it working - after a lot of fiddling, i'm almost there, but I can't create a system image because a Weston patch fails to apply.  The only thing that looks to be different is a hanging tab on line 224 in `compositor-fbdev.c`, and i've certainly not changed anything in this area since checking out earlier today!

Relevant log output: 
```
>>> weston: Checking sanity of /home/user/build/APKBUILD...
>>> WARNING: weston: No maintainer
>>> weston: Cleaning temporary build dirs...
>>> weston: Checking sha512sums...
weston-2.0.0.tar.xz: OK
no_0hz_refresh_rate.patch: OK
0001-compositor-fbdev-Added-parameter-pixman-type.patch: OK
0002-compositor-fbdev-Add-support-for-ABGR.patch: OK
0003-compositor-fbdev-print-the-pixman-type-guessed-in-ca.patch: OK
>>> weston: Unpacking /var/cache/distfiles/weston-2.0.0.tar.xz...
>>> weston: no_0hz_refresh_rate.patch
patching file libweston/compositor-fbdev.c
Hunk #1 succeeded at 252 (offset -1 lines).
>>> weston: 0001-compositor-fbdev-Added-parameter-pixman-type.patch
patching file compositor/main.c
Hunk #2 succeeded at 1444 (offset -2 lines).
patching file libweston/compositor-fbdev.c
Hunk #1 succeeded at 158 (offset -1 lines).
Hunk #2 succeeded at 180 (offset -1 lines).
Hunk #3 succeeded at 190 (offset -1 lines).
Hunk #4 succeeded at 213 (offset -1 lines).
Hunk #5 succeeded at 296 (offset -1 lines).
Hunk #6 succeeded at 506 (offset -1 lines).
Hunk #7 succeeded at 754 (offset -1 lines).
Hunk #8 succeeded at 794 (offset -1 lines).
patching file libweston/compositor-fbdev.h
patching file libweston/compositor.h
Hunk #1 succeeded at 220 (offset -15 lines).
Hunk #2 succeeded at 789 with fuzz 1 (offset -22 lines).
>>> weston: 0002-compositor-fbdev-Add-support-for-ABGR.patch
patching file libweston/compositor-fbdev.c
Hunk #1 FAILED at 223.
Hunk #2 succeeded at 235 (offset -1 lines).
1 out of 2 hunks FAILED -- saving rejects to file libweston/compositor-fbdev.c.rej
>>> ERROR: weston: all failed
(020763) [18:36:56] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(020763) [18:36:56] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/jonty/.local/var/pmbootstrap/log.txt
(020763) [18:36:56] ERROR: Command failed: (buildroot_armhf) % cd /home/user/build && su user -c 'CARCH=armhf DISTCC_HOSTS=127.0.0.1:33632 PATH=/usr/lib/distcc/bin:/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin abuild -d'
```

Content of `libweston/compositor-fbdev.c.rej`:
```
--- libweston/compositor-fbdev.c
+++ libweston/compositor-fbdev.c
@@ -223,8 +223,8 @@ calculate_pixman_format(struct fb_var_screeninfo *vinfo,
                                     vinfo->blue.length);
        }

-       /* Work out the format type from the offsets. We only support RGBA and
-        * ARGB at the moment. */
+       /* Work out the format type from the offsets. We only support RGBA,
+        * ARGB and ABGR at the moment. */
        type = PIXMAN_TYPE_OTHER;

        if ((vinfo->transp.offset >= vinfo->red.offset ||
```

**Comment by PabloCastellano** [comment]
Looks like a regression caused by 12951dc3cfb44b6541651ce14fc42a24bd5bd773

**Comment by jambonmcyeah** [comment]
I have the same issue and `git reset --hard 3aa95c24cd7540664204797117ac4f8b7e092193` worked for me

**Comment by ollieparanoid** [comment]
@jonty-comp: Thanks for reporting and making a PR that fixes this issue!

@jambonmcyeah: Touch keyboard is a broad topic. What we have to offer right now:

1. The keyboard in the initramfs to type in the unlocking password (as shown in the 100 days blog post). This is currently being integrated, check out #476 and talk to @craftyguy to help make it available for all devices.

2. Weston, our demo UI, brings its own keyboard in `weston-editor`. It can only be used in that application though.

3. plasma-mobile will probably bring its own keyboard. In order to get there, you could help @PureTryOut with testing/developing.

I hope that this answers your question, please let me know if it did not. Cool that both of you gave `pmbootstrap` a short!

**Comment by jambonmcyeah** [comment]
@ollieparanoid I want to thank all of you for creating this. I have always wanted a usable Linux Distribution that works on a mobile device and you guys are slowly making it come true.
