### ISSUE TITLE
Cannot run python3/unpackbootimg in Alpine

### ISSUE THREAD

**Issue by PabloCastellano** [postmarketOS/pmbootstrap#52]
Hello.

I'm following the [guide](https://github.com/postmarketOS/pmbootstrap/wiki/How-to-find-device-specific-information) to find the device specific information and I'm stuck because unpackbootimg fails:

```
vermuth:/tmp/bootimg_info$ unzip lineage-14.1-20170602-nightly-titan-signed.zip 
[...]
vermuth:/tmp/bootimg_info$ unpackbootimg -i boot.img 
Fatal Python error: failed to get random numbers to initialize Python
/tmp/bootimg_info # python3
Fatal Python error: failed to get random numbers to initialize Python
```

I cannot run any python3 script. Any pointers?

**Comment by ollieparanoid** [comment]
[Quick research](https://stackoverflow.com/questions/41985237/python-3-6-fails-to-build-in-qemu-with-failed-to-get-random-numbers-to-initiali) suggests, that this might happen, when `/dev/random` is missing inside your chroot.
The device nodes should get created automatically (see [here](https://github.com/postmarketOS/pmbootstrap/blob/master/pmb/config/__init__.py#L103) and [here](https://github.com/postmarketOS/pmbootstrap/blob/master/pmb/chroot/init.py#L97-L107)). When the creation of the device nodes fails, it should throw an error anyway.

Have you entered your chroot with `pmbootstrap chroot`?
Does this happen, after you delete your chroot and try it again with `pmbootstrap zap`?

**Comment by PabloCastellano** [comment]
Yes, I entered chroot with `pmbootstrap chroot`. It happens also after `pmbootstrap zap`.

I've tried same steps in Linux Mint 18 (Ubuntu 16.04 based) and works out of the box

Both environments show the same output:

```
/tmp # ls -l /dev/*random
crw-r--r--    1 root     root        1,   8 Jun  4 15:08 /dev/random
crw-r--r--    1 root     root        1,   9 Jun  4 15:08 /dev/urandom
```
Looks like some bug fixed in a newer version of some package?

**Comment by ollieparanoid** [comment]
I guess, that this new system does not use ecryptfs?

**Comment by PabloCastellano** [comment]
I'm using ecryptfs in both.

Linux Mint 18.1 (working) has `ecryptfs-utils 111-0ubuntu1.1`
Linux Mint 17 (fails) has `ecryptfs-utils 104-0ubuntu1.14.04.4`

**Comment by ollieparanoid** [comment]
This seems to be a bug with older versions of ecryptfs-utils. I'm closing this ticket, but please comment if you think we should talk more about this.
