### ISSUE TITLE
pmbootstrap hangs everywhere (sudo zombie process problem)

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#526]
It appears that the latest version of sudo as packaged in Arch Linux, `1.8.21`, basically causes this bug with sudo:
https://blog.famzah.net/2010/11/01/sudo-hangs-and-leaves-the-executed-program-as-zombie/

**TL;DR:** `sudo` never realized when a program is finished. You can in `pmbootstrap log` when sudo gets called. Downgrade `sudo` in Arch Linux to `sudo-1.8.20-1-x86_64.pkg.tar.xz` (grab it from Arch Linux archive) until this is resolved upstream.

**Upstream bug report:** https://bugzilla.sudo.ws/show_bug.cgi?id=800

**Comment by z3ntu** [comment]
> Sudo 1.8.21p2 is out now which includes the fix.

The package is also already available on Arch Linux.

**Comment by ollieparanoid** [comment]
Cool, thanks for the heads up!
