### ISSUE TITLE
[rx51] Battery discharges when connected to PC

### ISSUE THREAD

**Issue by pavelmachek** [postmarketOS/pmbootstrap#527]
('Battery 3.89V 3.93V 3.94V', '63% 70% 0%', '0/0 mAh', 'Charging', '-114/650/100 mA')

...which means battery dicharged by 114mA, while connected to PC over USB cable. Fix is to do

echo 500 > /sys/class/power_supply/bq24150a-0/current_limit

somewhere in the startup scripts (which allows 500mA charge; not too fast, but enough to keep battery from discharging). It may be also good idea to disable bright yellow light -- we'll probably want to use the RGB LED for something real.

echo 0 > /sys/class/power_supply/bq24150a-0/stat_pin_enable

does that.

**Comment by craftyguy** [comment]
Did you see that on pmOS? Looks like the limit is already set to `500` on pmOS:
```
localhost:~$ cat /sys/class/power_supply/bq24150a-0/current_limit
500
```

**Comment by craftyguy** [comment]
I'm closing this since this doesn't appear to affect pmos, as I mentioned in my previous comment. If this is not true for you, then we'll need more information about how your device/pmos install differ from the default configuration in order to debug!

**Comment by pavelmachek** [comment]
I definitely seen the "100mA charge" problem on pmOS, but can not
reproduce, so... I'll speak up if it reappears.

But you may want to integrate the second echo... to turn off yellow
light. We'll then be able to use the RGB LED for notifications even
while charging.
