### ISSUE TITLE
samsung-golden build error

### ISSUE THREAD

**Issue by hpagseddy** [postmarketOS/pmbootstrap#529]
sh: 1: cannot create /proc/sys/fs/binfmt_misc/register: Directory nonexistent
[log.txt](https://github.com/postmarketOS/pmbootstrap/files/1285390/log.txt)

**Comment by ollieparanoid** [comment]
The `binfmt_misc` registration is needed to execute `armhf` binaries on `x86_64` with QEMU. Could it be, that this feature is disabled in your kernel?

Which distribution do you run (Ubuntu I assume from your profile picture?), and which kernel version? And do you run it with a custom kernel config?

We should be able to figure this out soon. Thank you very much for trying out `pmbootstrap`!

**Comment by hpagseddy** [comment]
Im using Void Linux and kernel 4.9(i think) but i will change distro to Ubuntu and try again, thanks.

**Comment by ollieparanoid** [comment]
OK, closing this then. Please comment when it still doesn't work.

**Comment by alibabzo** [comment]
To anyone else finding this through searching - building on Void Linux seems to work after executing the command `sudo mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc`. [1]

[1] https://access.redhat.com/solutions/1985633

**Comment by drebrez** [comment]
There is also a discussion about automatically mount it. See #1135
