### ISSUE TITLE
[rx51] X server does not work

### ISSUE THREAD

**Issue by pavelmachek** [postmarketOS/pmbootstrap#536]
I attempted to install Xfce4, following Apline HOWTO.

apk add alpine-desktop xfce4

Then disabled weston

mv /etc/profile.d/start_weston.sh /etc/profile.d/disabled/
killall weston

Unfortunately, neither startxfce4 nor startx works. Problem is the same:

MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/xorg/modules/dri)
gbm: Last dlopen error: Error loading shared library /usr/lib/xorg/modules/dri/omapdrm_dri.so: No such file or directory
failed to load driver: omapdrm
EGL_MESA_drm_image required.

I'd be perfectly fine with unaccelerated X for now, if that is easier.

**Comment by ollieparanoid** [comment]
Judging from how @opendata26 did it for freedreno, you would need to enable omap support in `libdrm` in Alpine first: https://github.com/alpinelinux/aports/commit/9be66b837ba3eaea99733504ce882524b6f255a2

The option for omap seems to be `--omap-experimental-api`, as shown [here](https://cgit.freedesktop.org/mesa/drm/tree/configure.ac#n126).

*In case it is not that obvious, create a folder `aports/main/libdrm` in your checked out `pmbootstrap` folder, then paste the [APKBUILD](https://github.com/alpinelinux/aports/blob/master/main/libdrm/APKBUILD) from Alpine into that folder, and increase the pkgrel, and add the `./configure` parameter. Then run `pmbootstrap build libdrm` to compile it.*

...especially for X11 I think you may also need something like `xf86-video-omap`, which isn't packaged in Alpine yet. It should be more or less work if you take an [existing](https://pkgs.alpinelinux.org/packages?name=xf86-video-*&branch=edge&repo=main&arch=armhf&maintainer=) `xf86-video-*` package and adjust it slightly. All of these `xf86-video-*` packages seem to have the same format, so it should be straight forward.

PS: @opendata26 also changed the mesa package for freedreno, I am not sure if this is also required for omapdrm: https://github.com/alpinelinux/aports/commit/a887914bd02781e944c3380df3e3943350253a14


Let me know if you need any help! And when you get it working, please make pull-requests to Alpine directly, so we don't need to carry around a fork of the package. 👍

**Comment by MartijnBraam** [comment]
Hmm interesting, I've ran i3 on xorg before by manually starting xorg (without installing any device driver packages) and then starting the i3 binary. I've tried xfce by following the manual and then xorg broke for me.

It might be fixed by running `setup-xorg` which is provided by alpine.

**Comment by pavelmachek** [comment]
@Martijn : thanks for the hints. Yes, setup-xorg-base command helped,
and got me working display, but no working input. I tried to follow
@craftyguy 's advice and tried to switch to libinput for input.. but
it either did not work or I was not able to do it properly.

**Comment by craftyguy** [comment]
I was able to get xfce4 to start reliably, and input is fixed by #600.

The steps I followed to install/run xfce4 are no different than what is in the Alpine wiki:

1) run `sudo setup-xorg-base`

2) run `sudo apk add xfce4`

3) as user, run `startxfce4`


I don't see any reason to add this info to the pmOS wiki since it's not really different than what you would do on Alpine (assuming #600 is merged)

**Comment by pavelmachek** [comment]
Ok, it now works for me. Last time it did not work, and it was not
just the calibration. But it work now, good.

**Comment by craftyguy** [comment]
Cool! Should this issue be closed now?

**Comment by craftyguy** [comment]
Closing issue since X server does work using the instructions I posted previously :)
