### ISSUE TITLE
[mako][hammerhead] Package workaround for the red screen bug in Weston

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#54]
robb4 on IRC contributed a hackish patch (see below) on IRC, which "fixes" the screen issue, and posted [this](https://cloud.githubusercontent.com/assets/6033024/26761940/2e3273e0-4928-11e7-8800-0b4ddb14e239.jpg) photo.

So while that works (thanks! :D), a better workaround (which would be worth packaging) would be:
* Find out whether the `PIXMAN_TYPE` can be configured in weston.ini
* (If it can't be configured, write a patch for weston, that allows to do that and upstream it to weston. Until it is upstreamed, add the patch to the pmboostrap aport.)
* Change `device-lg-mako` to configure weston accordingly.

Please note, that this is still a workaround to fix the Weston demo. Weston is not a phone interface (though there could be one at some point, based on libweston? but there's also existing phone interfaces like plasma mobile waiting to be tried out), and the `lg-mako` kernel we currently use is based on the Android kernel, and is pretty outdated compared to the mainline Linux kernel (which is what we really want to use, see #12 , but can't yet). With the mainline kernel, it should not be necessary to apply this workaround, and if it was, we would rather focus on fixing this in the mainline kernel.

It might be worth doing this though, for lg-mako and possibly for more phones, where we'd need to swap the pixman_type to get it working properly.

---
```patch
    diff --git a/libweston/compositor-fbdev.c b/libweston/compositor-fbdev.c
    index e80a5040..39a91895 100644
    --- a/libweston/compositor-fbdev.c
    +++ b/libweston/compositor-fbdev.c
    @@ -219,11 +219,11 @@ calculate_pixman_format(struct fb_var_screeninfo *vinfo,
                 vinfo->transp.length == 0) &&
                vinfo->red.offset >= vinfo->green.offset &&
                vinfo->green.offset >= vinfo->blue.offset)
    -              type = PIXMAN_TYPE_ARGB;
    +              type = PIXMAN_TYPE_RGBA;
            else if (vinfo->red.offset >= vinfo->green.offset &&
                     vinfo->green.offset >= vinfo->blue.offset &&
                     vinfo->blue.offset >= vinfo->transp.offset)
    -              type = PIXMAN_TYPE_RGBA;
    +              type = PIXMAN_TYPE_ARGB;
     
            if (type == PIXMAN_TYPE_OTHER)
                   return 0; 
```

**Comment by ollieparanoid** [comment]
@MartijnBraam wrote on IRC about that (hammerhead appears to have the same issue):
> in msm_fb.c [in the kernel source code] you can change the color packing order to fix the red color

**Comment by MartijnBraam** [comment]
The CONFIG_FB_MSM_DEFAULT_DEPTH_RGBA8888 doesn't help after some testing. I think it's easier to patch weston

**Comment by ollieparanoid** [comment]
Okay. it shouldn't be too hard to patch weston for that - commandline parameters can also be added in [compositor-fbdev.c](https://github.com/wayland-project/weston/blob/master/libweston/compositor-fbdev.c#L778) file, so we could add one for the pixman type. It could even get accepted upstream.

**Comment by ollieparanoid** [comment]
Archiving that photo @MartijnBraam posted, so I can add it to the wiki: [Red-screen bug on hammerhead with weston](https://user-images.githubusercontent.com/6033024/26851053-3f5512fe-4af9-11e7-93da-cf9dd94b6b75.jpg)

**Comment by PabloCastellano** [comment]
I'm working on a patch to submit to upstream

**Comment by PabloCastellano** [comment]
I have a working patch and have submitted it to upstream.
https://bugs.freedesktop.org/show_bug.cgi?id=101472

**Comment by PabloCastellano** [comment]
This is how it should be run

https://github.com/PabloCastellano/pmbootstrap/commit/f960a7b41e121c363936403efe592e137db71d97

but is not ready to be merged. A better way to do it (by ollieparanoid):

```
right now, this looks like it is only necessary as hack for mako and hammerhead, because their framebuffer drivers are buggy. because of that, I would put it somewhere in the device package instead, not in the deviceinfo
just like the hack, that disables xweston for mako
```

**Comment by ollieparanoid** [comment]
After thinking further about this, I think the cleanest way would be to add a new (optional) variable to the deviceinfo file, that has the pixman type.
The deviceinfo file could then be sourced in the profile.sh, and the variable could get passed to Weston in case it is set (but it must also work for devices, where the variable is not set).
