### ISSUE TITLE
firmware-adreno doesn't contain blobs for Adreno 4xx

### ISSUE THREAD

**Issue by zhuowei** [postmarketOS/pmbootstrap#544]
There's a few devices using the Adreno 4xx GPUs that we probably want to support in PostmarketOS (e.g. Nexus 6, Nexus 6P), but firmware-adreno only includes the a2xx and a3xx blobs:

```
_files="a225_pm4.fw a225_pfp.fw a225p5_pm4.fw a300_pfp.fw a300_pm4.fw a330_pfp.fw a330_pm4.fw"
```

Should we add the 4xx blobs to the existing package or create a new package for adreno 4xx blobs? (For the Nexus 6P, the required blobs are `a420_pfp.fw` and `a420_pm4.fw`.)

**Comment by PabloCastellano** [comment]
If we accept to have another package, we would also need to split current firmware-adreno into 2xx and 3xx blobs for coherency. So I would keep all in the same package. What do others think?

**Comment by ollieparanoid** [comment]
`firmware-adreno-1-r2.apk` is only 11 KB in size, so I don't think it is worth the additional maintenance effort involved with a splitted up version. I would add the `4xx` blobs to that package as well.
