### ISSUE TITLE
New init configuration option for free space on the image file

### ISSUE THREAD

**Issue by BrianOtto** [postmarketOS/pmbootstrap#551]
I am currently running **pmbootstrap** in **qemu** and trying to compile a very large application after it boots up. The 20% extra space that #336 automatically adds is not enough. I have to hard code a larger size in the `get_subpartitions_size()` function at `pmb/install/install.py`.

e.g.

```
full *= 1.20

# my hard coded value
full += 2200 * 1024 * 1024

boot += 15 * 1024 * 1024
return (full, boot)
```

It would be nice if this was a configuration option that was asked during `/pmbootstrap.py init`.

**Comment by ollieparanoid** [comment]
It is possible to resize the installation image, after it has been created as documented in the [QEMU](https://wiki.postmarketos.org/wiki/Qemu) wiki article. But I understands, that as we have it now, this is not really intuitive and you are not the first one who asked this so we should improve the situation.

For some context, the initramfs of pmbootstrap automatically adjusts the partition table and filesystem inside the image to take up the full space, in case it takes up less space already. That means, that we don't need to specify the size at the time of generating the image, but we could increase it at any later point as necessary.

I propose the following:
* Add a `--image-size` option, that can be used with qemu like this: `pmbootstrap qemu --image-size=1G`. It would run `truncate` on the image as described in the wiki article.
* Inform the user when starting `pmbootstrap qemu` without that parameter with a message printed to the screen - something like:
> NOTE: Run 'pmbootstrap qemu --image-size=...' to increase the system image size when you run out of space!

(Maybe someone can come up with a better name than `--image-size`?)

If you agree with this solution, would you take a shot at it @BrianOtto?
Thanks for opening this issue!

**Comment by BrianOtto** [comment]
I didn't realize you could resize the image after it had been created. This solution sounds good to me!

I can take a shot at making the changes. The `--image-size` name make sense too, but I'll post here if any other ideas come up.

**Comment by BrianOtto** [comment]
PR #568 has been created, tested and confirmed working on my setup.
