### ISSUE TITLE
pmbootstrap should automatically check for required kernel config options

### ISSUE THREAD

**Issue by zhuowei** [postmarketOS/pmbootstrap#554]
After running `pmbootstrap menuconfig`, it may be helpful to check if the kernel configs (e.g. devfs, vt) required to boot postmarketOS are enabled correctly. We may be able to borrow [Ubuntu Touch's script](https://github.com/janimo/phablet-porting-scripts/blob/master/kernel/check-config).

**Comment by ollieparanoid** [comment]
Great idea, I'm also in favor of doing that!

For the implementation however, I recommend doing it in pmbootstrap's Python code. Then it would be faster than with starting an extra process, and it would be better integrated. One example how it could be done:

* New function `check(args, details=False)` in `pmb/parse/kconfig.py`
* When that function gets called with `details=False`, it does all checks and prints out the following message in case something is wrong:

> WARNING: Your kernel isn't configured properly for postmarketOS, run `pmbootstrap kconfig_check` for details

(or maybe `kcheck`, that's shorter?)
* With details enabled, it tells you exactly which options are set wrong and what effect this has (such as the usual config check scripts).
* We could call the function with details right after menuconfig as you proposed
* We could call it without details right before flashing and before booting the QEMU VM

I see a lot of positive emojis there, so I wonder what everyone thinks about this - and maybe someone wants to give it a shot?

**Comment by drebrez** [comment]
I'm also interested in this because I always forget about what to enable when starting with a new config.
I suggest we first start identifying all the required configs.
It would be good to have a dedicated page in the wiki also (here an example: https://wiki.gentoo.org/wiki/Systemd#Kernel).

**Comment by zhuowei** [comment]
@drebrez There is a page for this: https://wiki.postmarketos.org/wiki/Kernel_configuration

**Comment by drebrez** [comment]
@zhuowei lol 🤣, I missed it completely. Thanks for let me know 😉

**Comment by ata2001** [comment]
Is it safe, to rely on `# CONFIG_XXXX is not set` comments for determining, which option is enabled?

**Comment by zhuowei** [comment]
@ata2001 The Ubuntu script throws an error if one of the required options isn't set, so I guess not?

**Comment by ata2001** [comment]
@zhuowei That means it is set to no I believe, the ubuntu script checks if it's either y or m.

**Comment by ata2001** [comment]
@ollieparanoid I don't know, whether we should design it with non-boolean config options in mind. We don't have any yet, but we may need it in the future.

**Comment by ata2001** [comment]
@ollieparanoid what?

**Comment by ata2001** [comment]
@ollieparanoid I mean your response wasn't clear for me. You've meant we should make it support config options with string and number values?

In my draft I used a tuple with two elements to represent a config option. The first element is the name of the config option, second is the value, which is `bool` type, if the option should be set or unset, `string` if string, `int` if interger.

For example:
```
("DEVTMPFS", True)
```

**Comment by ata2001** [comment]
The ubuntu script has two arrays for options, one for those, that should be enabled, one for those, that shouldn't be set.

If we can make sure, we won't need any string or integer options, we could do the same.

**Comment by ollieparanoid** [comment]
@ata2001: I meant: designing it with non-boolean options in mind is a good idea. I can't say for sure, that we will never need string or integer options.

But we can also do it like in your draft and extend it on demand - especially if that makes the code cleaner for now.

**Comment by ata2001** [comment]
Created PR: #589
