### ISSUE TITLE
iPhone?

### ISSUE THREAD

**Issue by frimdo** [postmarketOS/pmbootstrap#57]
Is there any chance, that this awesome project will support iPhones or windows phones?

**Comment by MartijnBraam** [comment]
iphone would be really difficult / impossible. The current devices are made by the manufacturers to run linux and through the wonders of GPL some source code is available. Iphone doesn't have any of that for its operating system.

Windows phones are easier, they run uefi and a few months back the signing keys were leaked.

**Comment by frimdo** [comment]
So there is a small chance of implementing windows and supertiny chance for iPhones... That answers my question. Issue solved. Thank you :-)

**Comment by ollieparanoid** [comment]
I don't think it is impossible. There was an iphonelinux / Androidiphone project some time back. Use this as starting point. But it will be a lot harder than porting to an Android device, I think.

**Comment by ollieparanoid** [comment]
Start here: https://en.wikipedia.org/wiki/OpeniBoot

**Comment by ollieparanoid** [comment]
I did some research on that some time ago, and they had most drivers working actually, so you could really boot up an android from inside iOS, with something like kexec, and use it like it was an Android device. So if you find the kernel sources somewhere etc, it might be feasible.

(When you have that, getting it to directly boot GNU/Linux, without booting iOS first, would be the next step.)
