### ISSUE TITLE
Put the Android system partition size into the deviceinfo file

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#58]
Right now it is in `pmb/config/__init__.py` and optimized for lg-mako. But the partition size is different for more or less every phone, so it shoud go into the device info, as @MartijnBraam  pointed out in IRC.

**Comment by drebrez** [comment]
@ollieparanoid what you think about a simple solution like this: drebrez/pmbootstrap@e897a4137f190356fb03665f7acbaf9717545032

**Comment by MartijnBraam** [comment]
This also touches how issue #60 is handled. I think we also need the userdata partition size.

**Comment by ollieparanoid** [comment]
Looks good to me!

I am not sure if we should specify the userdata partition size in the deviceinfo. We can do it for informational purpose, but creating an image file that big and flashing it seems to be unnecessary, because we could resize the partition on the fly once pmOS is running on the phone.

**Comment by ollieparanoid** [comment]
This gets obsoleted by #127 (with automatic resize we don't even need to know the partition size, and it would all work even if the user resized the partitions beforehand).
