### ISSUE TITLE
gcc -E problems

### ISSUE THREAD

**Issue by pavelmachek** [postmarketOS/pmbootstrap#590]
I have some vala programs to control ofono. Build system needs C preprocessor; unfortunately, that does not work.

(On Nokia N900; I don't think that's important).

localhost:/my/tui$ sudo apk add gcc
...
OK: 904 MiB in 249 packages
localhost:/tmp$ > delme.C
localhost:/tmp$ gcc -E delme.C
gcc: error trying to exec 'cc1plus': execvp: No such file or directory

**Comment by pavelmachek** [comment]
sudo apk add g++
fixes the problem.

**Comment by ollieparanoid** [comment]
Glad you've figured out and thanks for posting the solution!
