### ISSUE TITLE
Make modules error.

### ISSUE THREAD

**Issue by zhenyolka** [postmarketOS/pmbootstrap#593]
I try compile kernel today.
Kernel compile success, but I get error at start compiling modules.
"The present kernel configuration has module disabled.
Then build a kernel with module support enabled".
I try enable CONFIG_modules with menuconfig, but I get error.

**Comment by ollieparanoid** [comment]
Hello @zhenyolka, cool that you have tried out `pmbootstrap`!

Could you please copy-paste the end of `pmbootstrap log` here, after running `pmbootstrap menuconfig` and trying to change the `CONFIG_MODULES` option?

**Comment by PabloCastellano** [comment]
Closing due inactivity, plus the problem seems to be solved already.
