### ISSUE TITLE
Support for Alcatel A5 LED

### ISSUE THREAD

**Issue by phtom** [postmarketOS/pmbootstrap#601]
Hi!
Alcatel A5 LED is a new super powerful octa-core smartphone! Would it be possible to make a security OS for it? An android rom for it?

**Comment by z3ntu** [comment]
Someone would have to port postmarketOS to that device to be supported.

**Comment by ollieparanoid** [comment]
A quick research shows, that this is an Android phone. So yes, it should be possible to run something like postmarketOS or a custom Android ROM (we can't do support for that here though).

Please note, that pmOS is in alpha state and you won't be able to use it as daily driver (SMS, phone calls don't work, ...). In case you are interested, check out the [porting guide](https://wiki.postmarketos.org/wiki/Porting_to_a_new_device) and head over to the [IRC/matrix](https://wiki.postmarketos.org/wiki/Matrix_and_IRC) chat, so we can help you when you get stuck!
