### ISSUE TITLE
[lg-l65] Framebuffer does not work

### ISSUE THREAD

**Issue by zhenyolka** [postmarketOS/pmbootstrap#603]
Hello! I port it to lg l65.
After boot phone i get only black screen.
I try dd if=/dev/urandom of=/dev/fb0 an get this
"dd: writing '/dev/fb0': No space left on device
6001+0 records in
6000+0 records out", but screen not change.
i try "cat modes > mode", not work.
in file /proc/fb this
"0 mdssfb_80000"
and after boot weston start automatically.
weston.log on pastebin.com
https://pastebin.com/XXHM5MqG

**Comment by ollieparanoid** [comment]
I didn't understand what does not work, which one is it?
a) Weston *does* work, splash screens during boot *do not* work
b) Weston *and* splash screens do not work

Check out the new [Troubleshooting:display](https://wiki.postmarketos.org/wiki/Troubleshooting:display) wiki article (thanks @MartijnBraam for writing it all down!).

If that does not help you: In some cases, it helps to start a working ROM, such as TWRP or Android, and compare the `sysfs` with the `sysfs` from pmbootstrap. See [Tuning sysfs](https://wiki.postmarketos.org/wiki/Tuning_sysfs) for more information.

Make sure that you join the [chat](https://wiki.postmarketos.org/wiki/Matrix_and_IRC), so we can help you more directly. Let us know if you have further issues and thanks for trying out postmarketOS!

**Comment by zhenyolka** [comment]
not work splash screen during boot and weston

**Comment by drebrez** [comment]
@zhenyolka can you share the `dmesg` output?

**Comment by zhenyolka** [comment]
@drebrez dmesg.log https://pastebin.com/qSC1VecB

**Comment by drebrez** [comment]
@zhenyolka thanks for the log, it seems your device also uses the mdp3 driver.
I suggest trying with [this patch](https://github.com/postmarketOS/pmbootstrap/blob/master/aports/device/linux-huawei-y530/05_fix_mdp3_ctrl_off.patch) or create a your own patch if the line doesn't match ([guide](https://wiki.postmarketos.org/wiki/How_to_create_a_patch_when_packaging_software))

**Comment by zhenyolka** [comment]
@drebrez with you patch i cant boot postmarket os. its stop on bootloader screen. on pc i cant see phone.

**Comment by zhenyolka** [comment]
I found same interesting. i check brightness of screen with command "cat /sys/devices/i2c.69/i2c-0/0-0039/backlight/qcom,led-flash/actual_brightness" and get output "0".
if i try "echo 125 > /sys/devices/i2c.69/i2c-0/0-0039/backlight/qcom,led-flash/brightness"
command run success, but if i check actual_brightness file it not change
What do?

**Comment by ollieparanoid** [comment]
Did you try the [sysfs tuning](https://wiki.postmarketos.org/wiki/Tuning_sysfs)?

**Comment by zhenyolka** [comment]
@ollieparanoid i try sysfs tuning i solve problem on 50%. Screen is on(on boot i run command "echo 1 > /sys/devices/fd900000.qcom,mdss_mdp/qcom,mdss_fb_primary.134/leds/lcd-backlight/brightness"). Weston start success and postmarketos-demos start success, BUT i see this artifact.
screenshot(screenshot not full, my screen is 480x800 screenshot is 350x350, but all screen look like on screenshot):
http://images.vfl.ru/ii/1506154563/38db3bd4/18706158_m.png

**Comment by ollieparanoid** [comment]
Awesome progress. [Screen output messed up](https://wiki.postmarketos.org/wiki/Troubleshooting:display#Screen_output_messed_up) will probably fix your problem now.

**Comment by zhenyolka** [comment]
@OK. Problem with artifact solved. Im on finish line to end porting to my device. But i have last 2 not solved problem.
1).Screen in my phone rotated physically upside-down, so all image on my screen rotated on 180 degress.
2).Touchscreen in your os not work. Weston.log in file.
Thanks all for postmarketos!
[weston.log](https://github.com/postmarketOS/pmbootstrap/files/1326632/weston.log)

**Comment by zhenyolka** [comment]
_For touchscreen_
How select driver for touchscreen in weston. My device not support evdev driver, need select mdev driver, i compile mdev driver, but how select it in weston?

**Comment by ollieparanoid** [comment]
> 1).Screen in my phone rotated physically upside-down, so all image on my screen rotated on 180 degress.

That is interesting, we have not seen this before. Could you try to fix this with more sysfs tuning?

Regarding 2). touchscreen: You will need an udev rule with the correct device name, as described in  [Screen Calibration#weston](https://wiki.postmarketos.org/wiki/Screen-Calibration#weston).

I'm happy you made further progress 👍

**Comment by zhenyolka** [comment]
@ollieparanoid i fully solve problem with black screen outside weston. need add in initfs.hook this lines
"
echo 0 > /sys/class/graphics/fb0/blank
echo 1 > /sys/devices/fd900000.qcom,mdss_mdp/qcom,mdss_fb_primary.134/leds/lcd-backlight/brightness
"
and install msm-framebuffer-refresher package.
Tomorrow i try install plasma-mobile, but problem with screen rotate not solve.
