### ISSUE TITLE
Detect errors caused by eCryptFS

### ISSUE THREAD

**Issue by lawl** [postmarketOS/pmbootstrap#61]
eCryptFS seems to make a bunch of trouble, eg. https://github.com/postmarketOS/pmbootstrap/issues/53 https://github.com/postmarketOS/pmbootstrap/issues/51 https://github.com/postmarketOS/pmbootstrap/issues/9 basically it doesn't behave like a regular filesystem.

Proposal: Detect eCryptFS and spit out a warning that this filesystem (in userspace) is unsupported.

**Comment by ollieparanoid** [comment]
as I wrote in #53:
>If we do implement a check, it should really check if /dev/random etc. work after creating them, instead of assuming, that if the filename length is limited, it must be ecryptfs (reminds me of these bad browser checks: if you can't do that, you must be browser xy).

**Comment by lawl** [comment]
That makes sense. Closing this then.

**Comment by lawl** [comment]
Actually, how do we want to proceed here.

**Comment by ollieparanoid** [comment]
My suggestion would be checking if /dev/random etc. work after they have been mounted. If they do not, raise a meaningful exception, that also mentions eCryptFS.
