### ISSUE TITLE
[rx51] ofono is unable to symlink gpios to /dev/cmt

### ISSUE THREAD

**Issue by craftyguy** [postmarketOS/pmbootstrap#630]
Ofono currently tries to create a directory (`/dev/cmt`) and corresponding symlinks to modem gpios if they do not exist: https://git.kernel.org/pub/scm/network/ofono/ofono.git/tree/plugins/nokia-gpio.c#n660

This prevents the existing udev rule in the `device-nokia-rx51` package from successfully creating a symlink. I *could* just call `rmdir /dev/cmt` in the udev rule before trying to symlink, but that seems hackish (and in my test, it didn't even work, but I have no idea why..)

It's currently looking for a `name` property that the gpio pins *should* have: http://elixir.free-electrons.com/linux/v4.13.3/source/arch/arm/boot/dts/omap3-n900.dts#L1039

However none of the gpios have a `name` file in their corresponding gpio device locations in sysfs, so ofono ultimately is unable to bring up the N900 modem.

@sre, any chance you have some ideas that could help? It seems like this did work at one point, else the `nokia-gpio` plugin in ofono would never have worked. 

Maybe a better option is to have the `nokia-modem` driver (or whatever the correct module is) create and populate `/dev/cmt/cm_*`? It seems weird having ofono do this, and it seems weird requiring the user to symlink (e.g. with udev) `/sys/bus/hsi/devices/n900-modem` to `/dev/cmt`

**Comment by sre** [comment]
As I wrote in the other issue, userspace handling gpios has always been a hack. The above patch looks good to me. I think the code you removed is only required for the original N900 kernel and ofono could still be used with them by adding a udev rule to do the symlinking.

I do wonder why ofono affects your udev rule, though. Why is ofono started before your udev rule triggered?

**Comment by craftyguy** [comment]
Thanks for your guidance @sre !

I have no idea why sometimes udev starts before, or after ofono. We're using openrc, and it's quite possible that the ofono init script doesn't 'depend' on udev. I could have probably 'fixed' this by sorting that dependency ordering in the init system. I'd rather prevent ofono from trying to add these symlinks in the first place, since other folks may be using other init systems and/or not using udev for symlinking, and ofono is looking in the wrong location anyways for the gpios :)

**Comment by craftyguy** [comment]
This issue is resolved for me now that #635 has been merged.

**Comment by ollieparanoid** [comment]
FYI: I think we didn't start udev properly, maybe #647 will also resolve the udev weirdness here (I know that you already fixed it another way, but still).

**Comment by craftyguy** [comment]
Yea I saw your PR, hopefully that makes udev startup more deterministic :)
