### ISSUE TITLE
[BUG] TWRP/CWM flashable zip not work.

### ISSUE THREAD

**Issue by zhenyolka** [postmarketOS/pmbootstrap#631]
I make flashable zip. system large is 650mb. i try install with twrp 3.1. I get error on step "INSTALLING rootfs...", in log i see 
"tar -xz rootfs.tar.gz /system
KILLED" i see error about 10 second on start extracting rootfs. I get this error,because my RAM(1 GB)is very small(i see it in output of df command, i run it before start flashing and in time of flashing).

**Comment by dakk** [comment]
How did you generate the flashable zip?

**Comment by zhenyolka** [comment]
pmbootstrap install --android-recovery-zip

**Comment by ata2001** [comment]
@zhenyolka I guess the issue is, the tar archive is extracted from the zip first, so it is present both in the zip, and extracted in /tmp, both in tmpfs. Could you please post the whole log file?

**Comment by zhenyolka** [comment]
@ata2001 i flash success. need not touch phone and poweroff screen. i this case /tmp is empty and free space for flash

**Comment by ata2001** [comment]
@zhenyolka Please try [this patch](https://github.com/postmarketOS/pmbootstrap/commit/fc5e52c5910875fdce78754eee060503f6259e47) out!
