### ISSUE TITLE
Binary repo / Continuous integration should run the testsuite

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#64]
- [x] "lazy reproducible builds" (apks won't be fully reproducible, but all files inside the apks should have the same content, and each apk should contain the same files. the exception is the signature file, which is of course different.)
  - [x] generate a buildinfo.json file with all relevant versions of all dependencies, recursively
  - [x] implement `pmbootstrap challenge`, which makes sure, that the exact dependencies are installed, rebuilds the package, compares all file's contents inside the apks
  - [x] make sure, that all pmbootstrap packages are reproducible (`linux-` packages don't work yet, but they are not required for the testsuite. All other packages work.)
  - [x] Merge `lazy-reproducible` builds into master
- [x] Automatic challenging of every build before publishing:
  - [x] Building and signing on a dedicated machine ("pmbuilder", I wanted to use a libreboot Thinkpad, but that's too much work as of now, might do that later though).
  - [x] That machine gets a dedicated GitHub account (@pmbuilder) and uploads its binaries into [pmOS-binary-packages-staging](https://github.com/pmbuilder/pmOS-binary-packages-staging)
  - [x] Write a script, that finds the next package, that needs to be updated, builds it, and uploads it to a dedicated repo: [pmbuilder](https://github.com/pmbuilder/pmbuilder)
  - [x] Travis CI job, that challenges the build and - on success only - pushes the signed build from @pmbuilder (and *not* its own build!) to the [binary-package-repo](https://github.com/postmarketOS/binary-package-repo), together with the change APKINDEX
- [ ] Stabilization phase:
  - pmbootstrap
    - [x] Include the `.buildinfo.json` file for each package, when releasing it
    - [x] Verify the APKINDEX
      - Usage: `pmbootstrap challenge APKINDEX.tar.gz`
      - Verify, that all files referenced in the APKINDEX exist in the same folder
      - Verify, that there is no extra file in the repo, that is not mentioned in the APKINDEX
    - [x] Testcases for all challenge related functions
    - [x] Add switch `--experimental-binary-pmOS-packages` or something, to be used by the Travis CI  job until it is stable
    - [x] When a package is up-to-date in the binary repo, install it from there and don't build it locally!
    - [ ] Improve the repo description? right now it only says "user". Alpine has the last git commit hash of the aports repo in there, and a meaningful name (e.g. main, community, ...)  [Upstreamed a parameter for that.](https://github.com/alpinelinux/abuild/pull/21)
  - pmbuilder:
    - [x] Challenge the `APKINDEX.tar.gz`, before pushing the changes
  - Travis job:
    - [x] Improve the commit message, that releases a package. To have more transparency, it should include:
        - The Travis CI Job ID, that was run (ideally a link to it)
        - Commit IDs from the following git repos: `staging`, `release`, `pmbootstrap`
        - Generate and display the commit message at the top (so it's easy to verify the information visually) and use it at the bottom when comitting
    - [x] Run `pmbootstrap challenge APKINDEX.tar.gz` on the (updated!) release APKINDEX file, right before pushing
    - [x] Let the Travis CI job use the binary repository, so it can build packages, that depend on others (Example: `gcc-armhf` depends on `binutils-armhf`, `musl-armhf`, and all `armhf` arch packages need `gcc-armhf`)
  - [ ] Fill the binary repo with a lot of packages, especially `gcc-armhf` etc. Fix all bugs, that appear in the process.
  - [ ] Rewrite the scripts to use [git-lfs](https://git-lfs.github.com/) instead of just git, so it performs better
- [ ] Productive phase:
  - [ ] Reset the binary repo for productive usage
  - [ ] Use the real GPG key from @pmbuilder for signing from now on (which also gets used to sign @pmbuilder's commits right now)
  - [ ] Roll out @pmbuilder's key in the `keys` folder of `pmbootstrap`
  - [ ] Adjust `pmbootstrap` to use the repository
  - [ ] Finally run the testsuite in continuous integration
  - [ ] Rebuild every package with CI, when it gets changed in a pull-request, just like Alpine Linux does it.

(Ideally, parts of this effort could be re-used to make the whole Alpine Linux distribution reproducible at some far point in the future.)

**Comment by ollieparanoid** [comment]
Ideally we should build every changed aport in every PR, just like Alpine does (see also: comments in #72).

**Comment by ollieparanoid** [comment]
**Update:** I have started filling the test repo with packages, and fixed a few issues along the way, such as Travis stopping after 10 minutes without any output (#314) and actually updating outdated versions of packages with new versions (the trick is to delete the old versions properly, or the APKINDEX check will rightfully fail).
The current issue is, that `libstdc++.a` is not deterministic - it is the same when built twice on the building machine, but different when [building with Travis](https://api.travis-ci.org/jobs/260402679/log.txt?deansi=true).

I think the solution is in [this comment](http://blog.beuc.net/posts/Practical_basics_of_reproducible_builds_3/#comment-912ba191c0dc43d447d5417fc34f098c):
> Got it, both libstdc++.a were containing the same .o objects, just ordered differently. [...]
> The ordering within one .a file is impacting the final executable.
>
> A mere `ar x` && `ar r *.o` made the build deterministic.

**Comment by ollieparanoid** [comment]
Another update: I have created issues in the binary packages repository:
https://github.com/postmarketOS/binary-package-repo/issues/
...because some of the above points are long-term (such as moving to git-lfs) and stand in the way of making this feature usable rather sooner than later.

**Comment by ollieparanoid** [comment]
Work on the (lazy) reproducible builds has been frozen for over a month now, so here's a status update.

#### Problems
* I am not sure if Travis can compile bigger packages like `linux-postmarketos` in time (each Travis CI job must be finished in 50 minutes)
* Some effort and manual steps involved for each package upgrade (bottleneck!)
* The security benefit is only for postmarketOS packages, but we will always be using most packages of the Alpine repositories anyway
* Problems with git-lfs (GitHub's implementation can not delete unneeded files (which would make us hit space limitations fast), there doesn't seem to be a lightweight self-hosted solution and they probably don't fix this either)

In summary: *this does not scale!* postmarketOS is simply moving too fast for this approach (and this is good!).

#### What now?
This ticket covers two things actually: a binary package repository, and running testcases automatically with Travis CI.

For the testcases, we could already do that - except for the testcase, that verifies the cross-compilers being able to compile packages. Furthermore, some testcases are quite traffic-intense (e.g. downloading the whole aports git repo to verify that our musl-armhf, gcc-armhf etc. packages are up-to-date), so my solution here would be turning on only a few testcases for now, and possibly only when the relevant code parts have changed (don't run Python testcases if only the aports changed for example).

For the binary repository, I would personally like to have more upstreaming. The idea was working as closely together with upstream as possible all along, and if we could share the binary repo, that would bring us even closer together. It was proposed on the [Alpine mailing list](https://lists.alpinelinux.org/alpine-devel/5427.html), that Alpine gets some kind of PPA-like system, where other people could build binary packages on Alpine's build infra structure. This would be perfect for packages that only make sense in pmOS (such as all the Android kernels) - assuming that they are really willing to do that.

Maybe there is a way to properly upstream the cross-compilers, which we generate manually from the `gcc`, `binutils`, `musl` packages after each update, so we could spare the users the compile time, and also run these testcases with Travis.

**Comment by zhuowei** [comment]
@ollieparanoid You mentioned that the Linux builds may take too long on Travis; have your considered other infrastructure such as a cloud server for building instead?

Also, could we just compile packages that don't take much time individually, then? For example, many KDE packages take less than 10 minutes to compile individually, but because there's so many of them it takes a day to build Plasma Mobile. They would benefit from the current binary infrastructure.

**Comment by ollieparanoid** [comment]
I would really prefer if we upstream them to Alpine instead of creating our own infrastructure. Adélie Linux, which is also an Alpine derivative, is also interested in a KDE port (although LTS and not the latest greatest we currently aim for), so they could also benefit from upstreaming those.

Besides, @PureTryOut already made an [inofficial binary repo for the KDE packages](https://github.com/PureTryOut/pmos-plasma-mobile).

**Comment by zhuowei** [comment]
@ollieparanoid Thanks: didn't know about the binary repo, although since my primary device is aarch64 my day of building isn't wasted.

**Comment by ollieparanoid** [comment]
Since the new binary repo has been implemented, I've moved `postmarketOS/binary-package-repo` to my own account (I was the only one working on it anyway) and archived it. This way it is still possible to access the wiki and issues, while it doesn't clutter the postmarketOS repositories list anymore.

https://github.com/ollieparanoid/binary-package-repo
