### ISSUE TITLE
Support changing the username

### ISSUE THREAD

**Issue by MartijnBraam** [postmarketOS/pmbootstrap#666]
Currently the have the hardcoded user named "user" (which is a bit confusing for new users). One thing that annoys me about the current mobile platforms is that I can't change the username so I have to remember what user to use when ssh-ing into the device.

Also for a proper linux installation the username shouldn't matter, I guess the only thing that depends on the username on the phone is some init scripts maybe, most hardcoded stuff is in the build chroots.

**Comment by craftyguy** [comment]
Should it use the username of the user building/installing pmOS, or just prompt the user to enter one or use 'user' as default?

**Comment by PureTryOut** [comment]
I'd say prompt the user and default to `user`.

**Comment by craftyguy** [comment]
Ok, yea that was the path I was going down. This is actually going to
be a fairly large task.. 'user' (and /home/user) are hard-coded in
quite a few places. I'm assuming the chroots should also be
consistent, for instance a user 'bob' on the device would have a
corresponding user 'bob' in all of the chroots used to build pmOS..

**Comment by MartijnBraam** [comment]
I meant the user account on the device, which I don't think is hardcoded that much anywhere (we currently hardcode mostly to run stuff as root anyway) The most hardcoded paths are in the build system.

I don't think the chroots need to be consistent at all with the username on the phone.

**Comment by ollieparanoid** [comment]
In `pmb.chroot.init()` we could check, whether the chroot we're initializing starts with `rootfs_...` and in that case, use the custom username if any is present.
We would also need to extend the logic accordingly in the function, that `--bind`-mounts everything into the chroots, there's also `/home/user` hardcoded (as we execute code in the `rootfs` chroot, this function will be called first).

**Comment by ollieparanoid** [comment]
continued in a new ticket with some more aspects, as discovered in the channel: #709
