### ISSUE TITLE
Useradd done too soon, and twice

### ISSUE THREAD

**Issue by pavelmachek** [postmarketOS/pmbootstrap#669]
(017072) [19:25:51] Add user
(017072) [19:25:51] (rootfs_qemu-amd64) % adduser -D user -u 12345
(017072) [19:25:51] (rootfs_qemu-amd64) % chown -R user:user /home/user
(017072) [19:25:52] (rootfs_qemu-amd64) % apk update

But postmarketos-base.post-install contains different adduser:

```
# Add user account                                                                                     
adduser -u 1000 -D -h /home/user -G users user 2>/dev/null
```

**Comment by pavelmachek** [comment]
Side effect of this is that /etc/skel does not work properly, as useradd is done before content of /etc/skel is finished. @MartijnBraam suggested taking useradd out of postinstall and into pmbootstrap.

**Comment by ollieparanoid** [comment]
Good catch! I'm also in favor of removing the version from postinstall and use the one from the Python code exclusively.

**Comment by pavelmachek** [comment]
Pull request #680 tries to fix it.

**Comment by pavelmachek** [comment]
...and probably fails. Its way more complex. /home/user is used for building in chroot-device, but then it is not copied during installation...
