### ISSUE TITLE
[qemu-amd64] Xserver does not work

### ISSUE THREAD

**Issue by pavelmachek** [postmarketOS/pmbootstrap#672]
I added xfce4 and xf86-video-modesetting,pciutils,xf86-input-libinput,xf86-server-vesa packages. Unfortunately, I'm getting " vesa: ignoring device with bound kernel driver" message. According to google, it seems to be bug in X server, and newer X.org would solve that..?

**Comment by ollieparanoid** [comment]
X11 works for me with qemu-amd64 when configured like in here: #649

That PR is still work in progress. However, you could use it as starting point and change the xinitrc to start xfce4 instead of Hildon.
