### ISSUE TITLE
[pmbootstrap] Unable to build cloudi package from Alpine

### ISSUE THREAD

**Issue by craftyguy** [postmarketOS/pmbootstrap#679]
https://git.alpinelinux.org/cgit/aports/tree/testing/cloudi

This can be reproduced by downloading (or symlinking if you cloned the alpine aports repo) to `aports/main/cloudi` in your pmbootstrap repo.

Build log is here: https://ptpb.pw/keh8

If I manually add the package 'ghc' (and there's one more it can't find, don't recall the name) then the configure script hangs indefinitely trying to test javac.

**Comment by ollieparanoid** [comment]
I guess this is a general error with `javac` hanging in qemu user mode emulation for armhf. Here is a four year old bug report I've found, which sounds like it is related:

https://bugs.launchpad.net/qemu/+bug/1129571/comments/25

**Comment by ollieparanoid** [comment]
I've asked you to report it - thanks that you did. Originally you've tried to build this to fix a failing package from Alpine, that only fails on armhf. But as we have learned later, Alpine wouldn't consider a test in Qemu as valid, only on real hardware (for understandable reasons).

So all in all, fixing this bug upstream is very far away from being even slightly useful to us. If someone is willing to debug this further (e.g. compile the same thing with just `abuild`, see if it works there, dig through the qemu code to understand it, ...), we could re-open this issue of course. But for now it's closed.
