### ISSUE TITLE
pmbootstrap install: Packages in rootfs don't get upgraded automatically

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#68]
@MartijnBraam wrote on IRC:
> I just found out that I should do a apk upgrade in the rootfs after rebuilding the kernel
even if I increase the package version

This is a bug and shouldn't be necessary.

**Comment by MartijnBraam** [comment]
I now do `apk del device-lg-hammerhead && apk add device-lg-hammerhead` so I don't have to enter the passwords in the install prompts to update my kernel.
