### ISSUE TITLE
Ouya port discussion

### ISSUE THREAD

**Issue by rendeko** [postmarketOS/pmbootstrap#683]
I've been attempting to port the Ouya to pmOS, with little success.

For the kernel we have a few options. [the official kernel running 3.x](https://github.com/ouya/ouya_1_1-kernel), [milaq's aftermarket kernel running 3.x](https://github.com/milaq/android_kernel_boxer8_ouya) (the one I personally have been attempting to patch and compile), and [stephank's attempt to run 4.3](https://www.reddit.com/r/ouya/comments/3wupl3/attempting_to_get_mainline_linux_43_on_ouya/). There is also the official [Nvidia Linux for Tegra R16 release](https://developer.nvidia.com/linux-tegra-rel-16) (cardhu) that [kulve uses to run Ubuntu on the Ouya](https://github.com/kulve/tegra-ubuntu), although I can only find the precompiled kernel and have had no luck inserting it into a properly made postmarketos boot.img using abootimg.

It's very important to flash [Ouya Bootmenu](https://github.com/milaq/ouya_bootmenu) using CWM first, to create a failsafe as the Ouya does not have a way to unbrick if you flash a corrupt kernel. [This blog post](https://www.s-config.com/cyanogen-mod-and-the-ouya/) talks about how to flash these, as well as flash CyanogenMod. The latest ROM I was able to flash was "cm-11-20160312-NIGHTLY-ouya", anything past then (including LineageOS roms) would not boot.

I'm definitely no kernel developer, so my attempts to patch milaq's kernel only got me so far before I hit errors with no documentation, while the seemingly same code worked fine on other kernels.

My progress patching milaq's kernel was [replacing if (defined($val)) with if (($val), as that is apparently an outdated and patched method, although I'm not sure if my fix is correct.](https://github.com/milaq/android_kernel_boxer8_ouya/blob/cm-11.0/kernel/timeconst.pl). [I then undid a commit mentioning mach/iomap.h](https://github.com/milaq/android_kernel_boxer8_ouya/commit/55141bc1c80f082648a18ded8278ea5b2d937354#diff-c46e5913db088b249d974233792beba2) when I received errors that mach did not exist. Ultimately, I was given an error about v7_flush_dcache_all not being defined, which I could not solve.

device-ouya-ouya apkbuild:
```pkgname=device-ouya-ouya
pkgver=1
pkgdesc="Ouya"
pkgrel=5
url="https://github.com/postmarketOS"
arch="noarch"
license="MIT"
depends="linux-ouya-ouya mkbootimg"
makedepends=""
install=""
subpackages=""
source="deviceinfo"
options="!check"

build() {
	return 0
}

package() {
	install -D -m644 "$srcdir/deviceinfo" \
		"$pkgdir/etc/deviceinfo"
}

sha512sums="60c9aa95a15b4c8e48737636eb0f2a2e3a942e0c5ebd88beb3946262fc79b1a5e388cf31e12b253015fc59252234c4082fd63c57a92a1e65fef8eb448ce64e3f  deviceinfo"
```

device-ouya-ouya deviceinfo:
```
deviceinfo_format_version="0"
deviceinfo_name="Ouya"
deviceinfo_manufacturer="Ouya"
deviceinfo_date=""
deviceinfo_keyboard="false"
deviceinfo_nonfree="????"
deviceinfo_dtb=""
deviceinfo_modules=""
deviceinfo_modules_initfs=""
deviceinfo_external_disk="false"
deviceinfo_external_disk_install="false"
deviceinfo_flash_methods="fastboot"
deviceinfo_arch="armhf"

# Splash screen
deviceinfo_screen_width="800"
deviceinfo_screen_height="600"

# Fastboot related
deviceinfo_generate_bootimg="true"
deviceinfo_flash_offset_kernel="0x00008000"
deviceinfo_flash_offset_ramdisk="0x01000000"
deviceinfo_flash_offset_second="0x00f00000"
deviceinfo_flash_offset_tags="0x00000100"
deviceinfo_flash_pagesize="131072"

deviceinfo_weston_core_modules="xwayland.so"
```

linux-ouya-ouya apkbuild

```
# APKBUILD based on linux-asus-grouper
# Kernel config based on: android_kernel_boxer8_ouya/arch/s390/defconfig

_vendor=ouya
_flavor=ouya-ouya
_hash="953e26f2709dfe0c185c3c99c50b0c9d56d473a4"
_config="config-${_flavor}.armhf"

pkgname=linux-${_flavor}
pkgver=3.4.0
case $pkgver in
	*.*.*)  _kernver=${pkgver%.*};;
	*.*) _kernver=$pkgver;;
esac
pkgrel=5
arch="armhf"
pkgdesc="Ouya Kernel"
url="https://github.com/milaq/android_kernel_boxer8_ouya"
depends="postmarketos-mkinitfs"
makedepends="perl sed installkernel bash gmp-dev bc linux-headers elfutils-dev"
options="!strip !check !tracedeps"
install=
source="
	$pkgname-$_hash.zip::https://github.com/milaq/android_kernel_boxer8_ouya/archive/cm-11.0.zip
	$_config
	compiler-gcc6.h"
subpackages=""
license="GPL2"

_abi_release=${pkgver}
_carch="arm"
HOSTCC="${CC:-gcc}"
HOSTCC="${HOSTCC#${CROSS_COMPILE}}"

ksrcdir="$srcdir/android_kernel_boxer8_ouya-cm-11.0"

prepare() {
	local _patch_failed=
	cd "$ksrcdir"

	# first apply patches in specified order
	for i in $source; do
		case $i in
		*.patch)
			msg "Applying $i..."
			if ! patch -s -p1 -N -i "$srcdir"/$i; then
				echo $i >>failed
				_patch_failed=1
			fi
			;;
		esac
	done

	if ! [ -z "$_patch_failed" ]; then
		error "The following patches failed:"
		cat failed
		return 1
	fi

	# gcc6 support
	cp -v "$srcdir/compiler-gcc6.h" "$ksrcdir/include/linux/"

	mkdir -p "$srcdir"/build
	cp "$srcdir"/$_config "$srcdir"/build/.config || return 1
	make -C "$ksrcdir" O="$srcdir"/build ARCH="$_carch" HOSTCC="$HOSTCC" \
		silentoldconfig
}



# this is so we can do: 'abuild menuconfig' to reconfigure kernel
menuconfig() {
	cd "$srcdir"/build || return 1
	make ARCH="$_carch" menuconfig
	cp .config "$startdir"/$_config
}

build() {
	cd "$srcdir"/build
	unset LDFLAGS
	make ARCH="$_carch" CC="${CC:-gcc}" \
		KBUILD_BUILD_VERSION="$((pkgrel + 1 ))-Alpine" \
		|| return 1
}

package() {
	install -Dm644 "$srcdir/build/arch/arm/boot/zImage" \
		"$pkgdir/boot/vmlinuz-$_flavor"

	install -D "$srcdir/build/include/config/kernel.release" \
		"$pkgdir/usr/share/kernel/$_flavor/kernel.release"
}

sha512sums="1c1c17307ee2aa46452489ec56109ca937daae4c9811224d177e039b5575ce9e80b00e3a359ad7ef73ac5bc66fc3de47bcf7f62b3d5c70e9482c3691b54d2395  linux-ouya-ouya-953e26f2709dfe0c185c3c99c50b0c9d56d473a4.zip
03ed8385233416961b664ddb3b12513fa995b8d7f8bb38e3097c5e6cce575dfd888a4e6b7c6dd2a9936f9e4aa2d0877d0acf590ac80a0fec0406361497312b5c  config-ouya-ouya.armhf
d80980e9474c82ba0ef1a6903b434d8bd1b092c40367ba543e72d2c119301c8b2d05265740e4104ca1ac5d15f6c4aa49e8776cb44264a9a28dc551e0d1850dcc  compiler-gcc6.h"
```

**Comment by ollieparanoid** [comment]
The kernel complies now! Changes made:
* used .tar.gz instead of zip archive
* used the commit hash in the download url
* based on defconfig: `arch/arm/configs/cyanogenmod_ouya_defconfig`
* enabled `DEVTMPFS` and `VT` as detected by `pmbootstrap kconfig_check`
* removed all -Werror flags in `prepare()` (which cause warnings to be errors that abort the build)
* applied two patches to the code

Uploaded to the `device-ouya-ouya` branch:
https://github.com/postmarketOS/pmbootstrap/tree/device-ouya-ouya/aports/device/linux-ouya-ouya

**Comment by rendeko** [comment]
@ollieparanoid Boots perfectly, with encrypted partition and graphical output. I'm adding my progress with it to the wiki. With this major issue out of the way, I think most discussion on the port can continue on the matrix/irc.

**Comment by ollieparanoid** [comment]
Awesome news, I'm glad to hear that \o/
