### ISSUE TITLE
Make initramfs generation more intuitive

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#69]
I think it's not obvious when the initramfs gets generated (it gets generated, when the trigger gets executed), and sometimes this leads to flashing an outdated initramfs, making debugging harder.

Ideas:
* A command to force-rebuild just the initramfs
* Automatically detecting, if the initramfs is outdated, before attempting to flash it (or simply always rebuild it directly before flashing?)
* Maybe add a command like "lsmkinitramfs", I think I've seen that in Debian. It lists the contents of the initramfs for debugging.

**Comment by ollieparanoid** [comment]
rfs613 on IRC told me, that having a shell is nice for serial debugging.
I could package a hook, which directly spawns a shell.

**Comment by mmaret** [comment]
Automatically detecting is really a key for a build system. It lead to reproducibility and much easier dev.
Android, buildroot, yocto ... are build with this in mind.

**Comment by ollieparanoid** [comment]
I totally agree, and for the most part pmbootstrap is doing that already (*you can do `pmbootstrap build hello-world --arch=armhf`, and it will set up a ton of dependencies automatically: native and armhf chroot, install abuild in both, build/package qemu and the cross-compilers if necessary, set up distccd to connect both etc*).

But it isn't quite there for the initramfs.

**Comment by ollieparanoid** [comment]
Here we go :) This should make it a lot better. The only thing, that doesn't quite work yet is automatically regenerating the initramfs when a hook gets installed (from inside the chroot). As workaround, pmbootstrap forces the regeneration of the initramfs whenever you use it to install/delete a hook, or do the install/flasher flash/flasher boot actions.

```
% pmbootstrap initfs --help
usage: pmbootstrap initfs [-h]
                          {hook_ls,hook_add,hook_del,ls,build,extract} ...

positional arguments:
  {hook_ls,hook_add,hook_del,ls,build,extract}
    hook_ls             list available and installed hook packages
    hook_add            add a hook package
    hook_del            uninstall a hook package
    ls                  list initfs contents
    build               (re)build the initramfs
    extract             extract the initramfs to a temporary folder inside the
                        (native) chroot

optional arguments:
  -h, --help            show this help message and exit

```
