### ISSUE TITLE
Support fat partitions for /boot

### ISSUE THREAD

**Issue by MartijnBraam** [postmarketOS/pmbootstrap#699]
I'm trying to port pmos to the Raspberry Pi but that requires a fat partition instead of ext2 as /boot. We could add a switch in the deviceinfo to make the boot partition fat instead of ext2 and have a firmware package that adds the extra firmware files for the rpi to /boot to make it work.

**Comment by PureTryOut** [comment]
Is it not a possibility that phones support both ext2 and FAT as `/boot`? If so, can't we just use FAT everywhere? Or am I hoping for too much?

**Comment by MartijnBraam** [comment]
Well the n900 also uses the /boot partition directly and requires ext2 on it so it has to be configurable to make it work.

**Comment by craftyguy** [comment]
+1 to adding an option in deviceinfo, maybe `deviceinfo_boot_fs` or something? It should default to ext2 if none is specified, so we don't cause a regression with all devices now that expect ext2 without having to explicitly update their device packages.

**Comment by MartijnBraam** [comment]
Yeah it  should totally default to ext2, this is more a special case for the raspberry pi hardware (and maybe other platforms in the future)

**Comment by montvid** [comment]
What do the rpi devs say - is fat for uefi? Or why can't it be ext?

**Comment by ollieparanoid** [comment]
@montvid: the raspberry pi bootloader needs a fat partition, because it was written that way and we can't change that (at least not easily, and we don't really get benefits from changing the filesystem there). Just like `lk` (littlekernel, the bootloader used on most Androids) reads the `boot.img` format from a special boot partition. More information [here](https://raspberrypi.stackexchange.com/a/44207).

**Comment by mirh** [comment]
Ehrm.. /boot partition being FAT is a [strict requirement](http://www.uefi.org/sites/default/files/resources/UEFI%20Spec%202_7_A%20Sept%206.pdf#page=579) of UEFI spec to be honest. 
Of course, if you aren't a x86 computer caring for windows, you are totally free to do whatever you want.. 

But I just wanted to point out how that's an actual very standard *standard*.
