### ISSUE TITLE
Adding devices to the wiki

### ISSUE THREAD

**Issue by lawl** [postmarketOS/pmbootstrap#7]
Sorry for the issue spam.

I wanted to add that I'm working on a port for the Galaxy Nexus to the wiki and what the status is, but apparently you can't really send pull requests for the wiki on github, so that's a bit annoying and it's not really a wiki.

I would suggest moving the .md files for the individual devices into a folder in the main repo (maybe the device-... folder itself?), that way you'd only have to manually update Devices.md yourself when someone adds a new file (or script that I guess).

This also has the added benefit that one could update this file as a changelog with all the other changes whenever someone shoots you a pull request.

I don't know, maybe you have a better idea or there is something I'm missing?

Anyways, status for my port to samsung-maguro (Google Galaxy Nexus GSM): 

I've extracted the offets from a boot.img, grabbed the kernel from LineageOS that seems to compile now with 2 small patches, real kernel config still needs to be done, so it might break again.

All of this is untested because the battery of this phone is still recovering from not having seen a power outlet in a few years. As soon as it boots again or I've ordered a new battery I will extract the Kernel config and add it (I couldn't find the config LineageOS uses).

Currently this is at: https://github.com/lawl/pmbootstrap I plan to upstream it the first time when/if I manage to boot it and telnet in.

**Comment by ollieparanoid** [comment]
I'm happy when development takes off, so it is no problem when you open a bunch of issues.

Amazing progress for that short time!

So about the wiki... I think every wiki page has an "Edit" button on the top right, that any GitHub user can click, or am I wrong with that?

https://github.com/postmarketOS/pmbootstrap/wiki

I'd currently prefer that over putting a bunch of `md` files in the git repo, because it works much quicker for me, and when editing the files in the browser, you can use the preview functionality.

**Comment by lawl** [comment]
Nope, no edit button. I tried to make a screenshot, but scrot comes back with a white image (the joy of using research operating systems). So I hope you'll take my word for it. In fact I have created a wiki on my fork and there I see the edit button, I don't see one on yours. So I'm fairly sure only you can edit it.

**Comment by ollieparanoid** [comment]
My bad, there was a checkbox that I had to untick:
> Restrict editing to users in teams with push access only 

It should work now :) Please add your cool content there!

**Comment by lawl** [comment]
awesome, done.

**Comment by ollieparanoid** [comment]
About the kernel config: [This page](https://source.android.com/source/building-kernels) says, it is "tuna_defconfig" (find it in arch/arm/config inside the kernel repo).
