### ISSUE TITLE
/etc/sudoers.d/postmarketos does not exist

### ISSUE THREAD

**Issue by pavelmachek** [postmarketOS/pmbootstrap#703]
...and includedir directive in /etc/sudoers is not enabled, anyway. But the file should be generated by ./aports/main/postmarketos-base/APKBUILD . What is going on there?

**Comment by ollieparanoid** [comment]
* `/etc/sudoers.d/postmarketos` does generated on my systems (you need root rights to list the contents of `sudoers.d`)
* the include *is* enabled in the default sudo config shipped with Alpine (probably unmodified from upstream - the `#includedir` is not a comment, that is really confusing!):
```
## Read drop-in files from /etc/sudoers.d
## (the '#' here does not indicate a comment)
#includedir /etc/sudoers.d
```
* Finally `sudo` works as user whenever I tested it

Is any of the above different for you? Thanks for making the issue!

**Comment by PabloCastellano** [comment]
Since #725 the `/etc/sudoers.d/postmarketos` file is not shipped anymore in package `postmarketos-base`. Now the user is added to the wheel group instead of providing a custom sudoers file.

Therefore this issue is not valid anymore.
