### ISSUE TITLE
Less scary warnings in ./pmbootstrap.py install

### ISSUE THREAD

**Issue by pavelmachek** [postmarketOS/pmbootstrap#708]
If we are building qemu image, we probably do not need to ask y/n if that's ok. Qemu images are always safe.

If we are doing sdcard install, it makes sense to print less scary warning if the sdcard already contains pmos.

**Comment by ollieparanoid** [comment]
Yeah, for images in general we can skip the confirmation. Printing out the size it will have is nice to know though.

**Comment by MartijnBraam** [comment]
We can probably create a very fancy warning message by reading `/etc/pmos_version` in the system partition if it exists and ask the developer if they want to overwrite "pmos build xxx"

**Comment by ollieparanoid** [comment]
That will be hard if it is encrypted. But we could read the partition labels without mounting it.

**Comment by MartijnBraam** [comment]
Oh yeah encryption, forgot about that

**Comment by craftyguy** [comment]
Is this ticket about getting rid of this message when running `pmbootstrap install`?

>  WARNING: Make sure, that your target device's partition table has allocated at least 708M as system partition!

**Comment by ollieparanoid** [comment]
Yep, exactly!

**Comment by ollieparanoid** [comment]
*What the hell, GitHub? I've edited the message so it does *not* say fixed ...*
