### ISSUE TITLE
telnetd is currently broken

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#71]
Regression from 1e64a3b511f19d86ba68e4a6a05548cb36757603, sorry for the inconvenience. I'm working on a fix.

*I thought I had tested it, but I've had only flashed the rootfs and not the initramfs.*

(Unlocking the phone via serial is still working.)

Symptom: you can connect via telnet once, but then you get "connection closed" and then you can't connect to telnet anymore (like it crashed).

I think it is related to `CONFIG_FEATURE_DEVPTS`, which was disabled, in the `busyboxconf-extras` file.

**Comment by ollieparanoid** [comment]
Possible workaround: revert to the last working commit, increase the busybox `pkgver` to `999` and build busybox. make sure, that you have installed that version of busybox, and it should work again.
Keep in mind, that your `999` version of the old busybox needs to be removed again, once this is resolved (simply delete it from the packages folder and zap your chroots).

**Comment by MartijnBraam** [comment]
My telnet output:

```
telnet 192.168.2.15                                                                                               ⏎
Trying 192.168.2.15...
Connected to 192.168.2.15.
Escape character is '^]'.
Connection closed by foreign host.
```

**Comment by ollieparanoid** [comment]
It's fixed now :) Alpine's binary package for busybox-extras package should get updated soon.
