### ISSUE TITLE
[rx-51] build fails

### ISSUE THREAD

**Issue by pavelmachek** [postmarketOS/pmbootstrap#710]
Enable access key retention support (KEYS) [Y/?] y
  Enable register of persistent per-UID keyrings (PERSISTENT_KEYRINGS) [N/y/?] n
  Large payload keys (BIG_KEYS) [N/y/?] (NEW) aborted!

Console input/output is redirected. Run 'make oldconfig' to update configuration.

make[2]: *** [/home/user/build/src/linux-4.13/scripts/kconfig/Makefile:39: silentoldconfig] Error 1
make[1]: *** [/home/user/build/src/linux-4.13/Makefile:547: silentoldconfig] Error 2

**Comment by pavelmachek** [comment]
Apparently this is needed: can be obtained by running 
````
./pmbootstrap.py menuconfig linux-postmarketos


index 574b5bc..4f894d1 100644
--- a/aports/main/linux-postmarketos/config-postmarketos.armhf
+++ b/aports/main/linux-postmarketos/config-postmarketos.armhf
@@ -1,6 +1,6 @@
 #
 # Automatically generated file; DO NOT EDIT.
-# Linux/arm 4.13.0 Kernel Configuration
+# Linux/arm 4.13.5 Kernel Configuration
 #
 CONFIG_ARM=y
 CONFIG_ARM_HAS_SG_CHAIN=y
@@ -5004,6 +5004,7 @@ CONFIG_EARLY_PRINTK=y
 #
 CONFIG_KEYS=y
 # CONFIG_PERSISTENT_KEYRINGS is not set
+# CONFIG_BIG_KEYS is not set
 # CONFIG_ENCRYPTED_KEYS is not set
 # CONFIG_KEY_DH_OPERATIONS is not set
 # CONFIG_SECURITY_DMESG_RESTRICT is not set
````

**Comment by MartijnBraam** [comment]
Maybe we should do `yes | make .... silentoldconfig ...` to make the kernel stuff accept the defaults in the prepare step. (I've used this a lot while porting, works fine)

**Comment by pavelmachek** [comment]
yes | seems wrong, it will enable everything, even wrong option.
yes "" | might do the trick, accepting defaults.

**Comment by MartijnBraam** [comment]
oh yeah i've used `yes "" |` before.

**Comment by craftyguy** [comment]
Hmm, I wonder why this kernel built OK for me before I pushed the PR to update it..

**Comment by ollieparanoid** [comment]
@pavelmachek: thanks for reporting!

@craftyguy: that is really odd, I was also able to reproduce it. Are you sure, that it was built? You could check your logs.

@MartijnBraam, @pavelmachek: I've prepared a PR, which uses "olddefconfig". It is essentially the same as `yes "" | ...`, but a bit nicer. I'll add the `yes "" | ...` thing to #688 though, because it also works with older kernels, that don't know "olddefconfig" yet.
