### ISSUE TITLE
Makefile errors while compiling kernel

### ISSUE THREAD

**Issue by fyfyone** [postmarketOS/pmbootstrap#719]
I am getting makefile errors during building the [kernel for Huawei Honor 5X](https://github.com/LineageOS/android_kernel_huawei_kiwi) aka kiwi. [Here are `APKBUILD` and `log.txt`.](https://gist.github.com/fyfyone/477b31c5f361bb67a1b65f87d54a791b) What can I do about them? I have no idea about makefiles.

**Comment by ollieparanoid** [comment]
```
/tmp/ccPPcAMc.s: Assembler messages:
/tmp/ccPPcAMc.s:22: Error: unknown mnemonic `mcr' -- `mcr p15,0,x0,c9,c12,3'
```

The `mcr` assembly instruction [is not available for `aarch64`, only for `armhf`](https://stackoverflow.com/questions/32374599/mcr-and-mrc-does-not-exist-on-aarch64). It looks like your kernel config is screwed up. Also this points to it:
```
warning: (ARM64) selects HAVE_KPROBES which has unmet direct dependencies (HUAWEI_KERNEL_DEBUG)
warning: (ARM64) selects HAVE_KRETPROBES which has unmet direct dependencies (HUAWEI_KERNEL_DEBUG)
warning: (SND_SOC_APQ8084 && SND_SOC_MSM8X16 && SND_SOC_MSM8994) selects SND_SOC_CPE which has unmet direct dependencies (SOUND && !M68K && !UML && SND && SND_SOC && SND_SOC_WCD_CPE)
warning: (ARM64) selects HAVE_KPROBES which has unmet direct dependencies (HUAWEI_KERNEL_DEBUG)
warning: (ARM64) selects HAVE_KRETPROBES which has unmet direct dependencies (HUAWEI_KERNEL_DEBUG)
warning: (SND_SOC_APQ8084 && SND_SOC_MSM8X16 && SND_SOC_MSM8994) selects SND_SOC_CPE which has unmet direct dependencies (SOUND && !M68K && !UML && SND && SND_SOC && SND_SOC_WCD_CPE)
```

Just in case: Please only edit the kernel config with `pmbootstrap menuconfig`, never edit the file directly. Also you mentioned that you switched the architecture, maybe you have copied over the config, and that's how you got this error.

Anyway, I recommend starting over with the right defconfig for your device, which is this one:
https://github.com/LineageOS/android_kernel_huawei_kiwi/blob/cm-14.1/arch/arm64/configs/kiwi-64_defconfig

* Copy that file over your current config
* run `pmbootstrap checksum`
*  `pmbootstrap menuconfig`
* accept the defaults by pressing `return` until the menu appears
* exit the menu to save
* run `pmbootstrap kconfig_check` to find out what you need to adjust
* run `pmbootstrap menuconfig` again and make the changes
* then save again

Please also adjust that in your [APKBUILD](https://gist.github.com/fyfyone/477b31c5f361bb67a1b65f87d54a791b#file-apkbuild-L8).

I know it's a bit complicated, but we're working on making the kernel packaging easier in the future (#688).

**Comment by fyfyone** [comment]
I am now getting a log seems to be pretty similar to the old one. [Could you maybe have a look at it?](https://gist.github.com/fyfyone/3ad1720820b4dd9b012e9dc2aef63bcb)

The reason I'm saying it looks like what I had before is that there is still what you pointed out [here](https://gist.github.com/fyfyone/3ad1720820b4dd9b012e9dc2aef63bcb#file-log-txt-L47-L52), but no more `unknown mnemonic 'mcr'` messages.

**Comment by ollieparanoid** [comment]
There seems to be no error in the log, maybe the warnings are "normal" for that kernel. (Android kernels throw a lot of warnings when compiled with a modern GCC).

So does the build run through? If not, please post the APKBUILD and a log containing the actual error.

**Comment by fyfyone** [comment]
Ouch! Sorry, I did not post the full log. It does not finish successfully, and [here are log and APKBUILD](https://gist.github.com/fyfyone/697fde9f96b8dbdc2833c36f8a5ad90a).

**Comment by fyfyone** [comment]
Thank you for finding that patch! Build has now completed!
