### ISSUE TITLE
Can't install qemu-user-static-repack-2.8-r7.apk

### ISSUE THREAD

**Issue by montvid** [postmarketOS/pmbootstrap#728]
Can't do ./pmbootstrap.py install - I get this error - suggestions?:

(006550) [15:20:30] Build is necessary for package 'qemu-user-static-repack': No binary package available
(006550) [15:20:30] (native) % sed -i -e 's/^export JOBS=.*/export JOBS=5/' /etc/abuild.conf
(006550) [15:20:30] (native) build x86_64/qemu-user-static-repack-2.8-r7.apk
(006550) [15:20:30] % sudo cp -r /home/mst/pmbootstrap/aports/cross/qemu-user-static-repack/ /home/mst/.local/var/pmbootstrap/chroot_native/home/user/build
(006550) [15:20:30] (native) % chown -R user:user /home/user/build
(006550) [15:20:30] (native) % cd /home/user/build && su user -c 'CARCH=x86_64 abuild -d'
>>> qemu-user-static-repack: abuild 3.0.2-r0
>>> qemu-user-static-repack: Checking sanity of /home/user/build/APKBUILD...
>>> WARNING: qemu-user-static-repack: No maintainer
>>> qemu-user-static-repack: Cleaning temporary build dirs...
>>> qemu-user-static-repack: Fetching https://ftp.us.debian.org/debian/pool/main/q/qemu/qemu-user-static_2.8+dfsg-6_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
>>> ERROR: qemu-user-static-repack: all failed

**Comment by PabloCastellano** [comment]
Looks like the download url has changed.

PR #730 should fix it.
