### ISSUE TITLE
/home/user/build/src is empty after successful build

### ISSUE THREAD

**Issue by alexlep** [postmarketOS/pmbootstrap#73]
Hi,

Thanks lot for the project - I really like the fact that smb cares about older android devices.

At the moment I'm trying to prepare port for my LandRover A9 device, which is running on mt6852.

After executing these commands:
```
./pmbootstrap.py checksum device-landrover-a9
./pmbootstrap.py build device-landrover-a9
./pmbootstrap.py checksum linux-landrover-a9
./pmbootstrap.py build linux-landrover-a9 --arch=armhf
./pmbootstrap.py install
```
/home/user/build/src is empty even though #44 seems to be closed. No cleanups in my APKBUILDs.

```
/home/user/build/src # grep CLEANUP /etc/abuild.conf 
CLEANUP=''
ERROR_CLEANUP="deps"
/home/user/build/src # 
```
Also on my device's fastboot is somehow very limited(I'm getting write data errors on all partitions but userdata and cache, and all unlcoking commands simply hang), so I cannot use it to flash kernel and system image. I was using SP flash tool to flash images, and at first I created boot.img manually using mkbootimg from aports. Maybe we could do smth like:
`./pmbootstrap.py build bootimage`
which will build mkbootimg, install it to chroot, and automatically will build boot.img with kernel/ram files and params from deviceinfo?

Thank you,
Oleksandr

**Comment by MartijnBraam** [comment]
I was thinking of something like `pmbootstrap export [path]` to export boot.img and system.img to a specific path.

Does your device show anything when running `fastboot getvar all`? that should contain partition information.

**Comment by alexlep** [comment]
```
/home/user/build/src/dexp_es2 # fastboot getvar all
(bootloader) 	partition-size:fat: 151800000
(bootloader) 	partition-type:fat: fat
(bootloader) 	partition-size:userdata: 32000000
(bootloader) 	partition-type:userdata: ext4
(bootloader) 	partition-size:cache: 7e00000
(bootloader) 	partition-type:cache: ext4
(bootloader) 	partition-size:system: 38400000
(bootloader) 	partition-type:system: ext4
(bootloader) 	partition-size:expdb: a00000
(bootloader) 	partition-type:expdb: raw data
(bootloader) 	partition-size:ebr2: 80000
(bootloader) 	partition-type:ebr2: raw data
(bootloader) 	partition-size:logo: 300000
(bootloader) 	partition-type:logo: raw data
(bootloader) 	partition-size:misc: 80000
(bootloader) 	partition-type:misc: raw data
(bootloader) 	partition-size:sec_ro: 600000
(bootloader) 	partition-type:sec_ro: ext4
(bootloader) 	partition-size:recovery: 1000000
(bootloader) 	partition-type:recovery: raw data
(bootloader) 	partition-size:boot: 1000000
(bootloader) 	partition-type:boot: raw data
(bootloader) 	partition-size:uboot: 60000
(bootloader) 	partition-type:uboot: raw data
(bootloader) 	partition-size:seccfg: 20000
(bootloader) 	partition-type:seccfg: raw data
(bootloader) 	partition-size:protect_s: a00000
(bootloader) 	partition-type:protect_s: ext4
(bootloader) 	partition-size:protect_f: a00000
(bootloader) 	partition-type:protect_f: ext4
(bootloader) 	partition-size:nvram: 500000
(bootloader) 	partition-type:nvram: raw data
(bootloader) 	partition-size:pro_info: 300000
(bootloader) 	partition-type:pro_info: raw data
(bootloader) 	partition-size:ebr1: 80000
(bootloader) 	partition-type:ebr1: raw data
(bootloader) 	partition-size:mbr: 80000
(bootloader) 	partition-type:mbr: raw data
(bootloader) 	partition-size:preloader: c00000
(bootloader) 	partition-type:preloader: raw data
(bootloader) 	kernel: lk
(bootloader) 	product: F090_GPS_KK
(bootloader) 	version: 0.5
all: Done!!
finished. total time: 0.004s
/home/user/build/src/dexp_es2 # fastboot format system -u
Creating filesystem with parameters:
    Size: 943718400
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 7200
    Inode size: 256
    Journal blocks: 3600
    Label: 
    Blocks: 230400
    Block groups: 8
    Reserved block group size: 63
Created filesystem with 11/57600 inodes and 7544/230400 blocks
target didn't report max-download-size
sending 'system' (16568 KB)...
FAILED (remote: 
@DOWNLOAD ERROR@
Please re-plug your USB cable
)
finished. total time: 0.593s
```
And on device I see write data errors.
All lock/unlock commands simply hang with '...' output:
```
/home/user/build/src/dexp_es2 # fastboot flashing unlock_critical
...
```
And formatting works fine for userdata partitiion, for example:
```
/home/user/build/src/dexp_es2 # fastboot format userdata -u
Creating filesystem with parameters:
    Size: 838860800
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 7328
    Inode size: 256
    Journal blocks: 3200
    Label: 
    Blocks: 204800
    Block groups: 7
    Reserved block group size: 55
Created filesystem with 11/51296 inodes and 6651/204800 blocks
target didn't report max-download-size
sending 'userdata' (14952 KB)...
OKAY [  0.569s]
writing 'userdata'...
OKAY [  1.693s]
finished. total time: 2.262s
```
Accordingly to information I've found - fastboot is found in UBOOT (lk.bin). Trying to find the one with, let's say FULL version of fastboot.

**Comment by MartijnBraam** [comment]
You might need to unlock using one of the oem commands (they are not listed in the fastboot help since they're handled by the fastboot firmware)

Also that phone is horrible to google for, cannot find any fastboot docs for it

**Comment by alexlep** [comment]
> is horrible to google for

This is just another clone from millions of devices from Chinese manufacturers.
I'm not much into android guts, but I thought that if you have kernel which supports MT6582 CPU - you have, more or less, working kernel for majority of devices with this CPU.
But the deeper I dig - the worser it gets =) It looks that almost every device with MTK CPU onboard has it's own fork of kernel.
And after realizing this fact I'm starting to like your project and idea of single, mainline kernel more and more =)

**Comment by ollieparanoid** [comment]
@alexlep: Thanks for reaching out and your porting efforts so far! You can get live porting assistance in the [matrix/irc channel](https://github.com/postmarketOS/pmbootstrap/wiki/Matrix-and-IRC), I highly recommend joining while working with pmOS.


### `/home/user/build/src` is empty
Short answer: I think it isn't empty if you enter the `buildroot_armhf` chroot: `pmbootstrap chroot --suffix=buildroot_armhf`

#### Long answer
```
./pmbootstrap.py checksum device-landrover-a9 # (native) clears the build folder
./pmbootstrap.py build device-landrover-a9 # (native) clears and fills the build folder
./pmbootstrap.py checksum linux-landrover-a9 # (native) clears the build folder
./pmbootstrap.py build linux-landrover-a9 --arch=armhf # (buildroot_armhf) clears and fills the build folder
./pmbootstrap.py install
```

`(native)` and `(buildroot_armhf)` are seperate chroots, so it might be that your last build has been made in the `(buildroot_armhf)` chroot if `_pmb_build_in_native_chroot ` is set inside the APKBUILD, which it usually should not be. Read [build internals](https://github.com/postmarketOS/pmbootstrap/wiki/Build-internals) for more information. (Sorry, I know it gets complicated here, you don't have to read/understand all that, if it bores you.)

**Comment by ollieparanoid** [comment]
About the partitions: postmarketOS should also work, if you put the system data on the userdata partition - it will automatically find the partition.
If flashing your kernel does not work, try `pmbootstrap flasher boot` instead.
