### ISSUE TITLE
postmarketos-base-x11 not pulled in automatically for armhf

### ISSUE THREAD

**Issue by drebrez** [postmarketOS/pmbootstrap#731]
If you zap the device arm chroot and you select `xfc4` as UI, when running `pmbootstrap install` the `postmarketos-base-x11` subpackage doesn't get installed.
The problem is not the `install_if` condition, but that the `postmarketos-base` APKBUILD has `noarch`, and after building the package it gets symlinked in the other arch folders ([here](https://github.com/postmarketOS/pmbootstrap/blob/bed1eacbb5b0a668032fc13d32698d93bc5e8b84/pmb/build/package.py#L127-L129)).

The problem is that the subpackages are not symlinked, so they don't exist in the other repositories.

I've tested manually symlinking the `postmarketos-base-x11` subpackage in the armhf and with `pmbootstrap install` was triggered correctly.

Don't know how to change the `symlink_noarch_package` function to automatically symlink the subpackages.

**Comment by craftyguy** [comment]
Would this be fixed by changing `postmarketos-base` to `arch="all"` instead?

**Comment by ollieparanoid** [comment]
Thanks for your detailed bug report 👍
This should be fixed in #740.
