### ISSUE TITLE
ANDROID_PARANOID_NETWORK restricts network access to users who are member of specific groups

### ISSUE THREAD

**Issue by bhuvi8** [postmarketOS/pmbootstrap#737]
when non root user tries to access network they get permission denied errors

**Comment by bhuvi8** [comment]
did a strace and found that permission denied error occurs when a socket is created using socket() system call

**Comment by bhuvi8** [comment]
on further investigation found that it is an android security feature

verified it by creating groups with ids 3003 and 3004 and assigned user to group and user is now able to access network
# apk add shadow
# groupadd -g 3003 aid_inet
# groupadd -g 3004 aid_inet_raw
# usermod -G aid_inet user
# usermod -G aid_inet_raw user

$ ping 8.8.8.8
now works as user

**Comment by bhuvi8** [comment]
Additional reference https://groups.google.com/forum/#!topic/sluggers/g0XY-Qk5C3w

Most other devices having android kernels have this option set...This needs to be disabled for network features in non android OS'es to work properly

**Comment by bhuvi8** [comment]
created a pull request https://github.com/postmarketOS/pmbootstrap/pull/738 to fix this in samsung-i9100

**Comment by z3ntu** [comment]
Better reference: https://elinux.org/Android_Security#Paranoid_network-ing 😉

**Comment by bhuvi8** [comment]
Modified the title to better reflect this issue

**Comment by z3ntu** [comment]
I would edit it to something like "ANDROID_PARANOID_NETWORK restricts network access to root user"

**Comment by bhuvi8** [comment]
Done

**Comment by ollieparanoid** [comment]
We should add this to our `pmbootstrap kconfig_check` code, so we can fix it for all devices (and warn the user when it is enabled). Thanks for reporting! (If someone wants to take a shot at this, please go ahead 👍 )

**Comment by z3ntu** [comment]
Am doing it right now.

**Comment by bhuvi8** [comment]
@z3ntu nice job fixing it for all devices and nice work with the script :-)
