### ISSUE TITLE
Hildon config to rotate screen does not work on Nexus 7

### ISSUE THREAD

**Issue by montvid** [postmarketOS/pmbootstrap#749]
This config does not work for me what should I put instead of fbdev? I tried drm, freedreno, mesa, dri, dri2. I had to install xrandr to rotate the screen but it would be better to find out what config would work instead. There is no problem in Xfce and Mate as they have a gui option for rotation. Maybe we  should add xrandr to Hildon package?
Section "Device"
  Identifier "LCD"
  Driver "fbdev"
  Option "Rotate" "CW"
EndSection

**Comment by ollieparanoid** [comment]
It looks like you can pull out the driver name from the `/usr/lib/xorg/modules/drivers` folder ([source](https://superuser.com/a/169186)).

**Comment by montvid** [comment]
> localhost:~$ ls  /usr/lib/xorg/modules/drivers/
fbdev_drv.so        modesetting_drv.so

So I used the modesetting driver and in Xorg.0.log I get:

> (WW) modeset(0): Option "Rotate" is not used

Any other options I could try? Should we just use "xrandr -o right" in the hildon sh file in default Hildon setup?

**Comment by ollieparanoid** [comment]
> Should we just use "xrandr -o right" in the hildon sh file in default Hildon setup?

Yes, that sounds like an excellent solution!
