### ISSUE TITLE
[titan] Framebuffer doesn't work

### ISSUE THREAD

**Issue by PabloCastellano** [postmarketOS/pmbootstrap#757]
Framebuffer in Motorola G 2014 (titan) never worked fine and I need some help to fix it.

I have started debugging it by enabling the usb shell hook. I'm connected to it and at this point the screen is black and it has never worked.

Some debugging:

```
# cat /dev/urandom  > /dev/fb0 
cat: write error: No such device
```

This command causes the screen to turn on for some milliseconds, I can see the Motorola logo and then instantly turns off, like a single blink. I can run this command many times with the same result. Everytime I run that command I get the following line in dmesg:

```
[  152.895900,0] lm3630a_bl 0-0038: wake up and re-init chip
```

If I run:

```
echo 1 > /sys/devices/f9926000.i2c/i2c-0/0-0038/leds/lm3630a-backlight/brightness
```

I can see the Motorola logo again, and it doesn't turn off. I can also write any value from 0 to 255 to control the backlight.

```
echo 0 > /sys/devices/f9926000.i2c/i2c-0/0-0038/leds/lm3630a-backlight/brightness
# cat /dev/urandom  > /dev/fb0 
cat: write error: No such device
```

After turning off the backlight again and writing to the framebuffer I don't get the short blink anymore.

From this point I don't know what else to try. Maybe msm-fb-refresher?

[...]

If I enter the disk encryption password, pmOS continues to boot and I can connect through ssh. In the current version of pmbootstrap, the screen keeps black and kind of blinks/flashes every some seconds. The backlight is turned on and off and dmesg is flooded with this text (looks to me like the panel doesn't properly initialize and keeps trying):

```
[  491.781571]  491.781571,0] mdss_dsi_on+: ctrl=e1c1c810 ndx=0
[  491.805428]  491.805428,0] mdss_dsi_on-:
[  491.805442]  491.805442,0] mdss_dsi_panel_on+: ctrl=e1c1c810 ndx=0
[  491.806477]  491.806477,0] vddio_disp: operation not allowed
[  491.806792]  491.806792,0] tps65132: operation not allowed
[  492.019898]  492.019898,0] synaptics_dsx_sensor_state: state change SUSPEND -> ACTIVE
[  492.020057]  492.020057,0] mdss_dsi_panel_on-. Pwr_mode(0x0A) = 0x9c
[  492.020223]  492.020223,1] mdss_dsi_panel_off+: ctrl=e1c1c810 ndx=0
[  492.020704]  492.020704,0] lm3630a_bl 0-0038: wake up and re-init chip
[  492.021017]  492.021017,0] synaptics_dsx_sensor_state: state change ACTIVE -> SUSPEND
[  492.202835]  492.202835,0] tps65132: operation not allowed
[  492.204999]  492.204999,0] vddio_disp: operation not allowed
[  492.205012]  492.205012,0] mdss_dsi_panel_off-:
[  492.205024]  492.205024,0] mdss_dsi_off+: ctrl=e1c1c810 ndx=0
[  492.237758]  492.237758,0] mdss_dsi_off-:
```

In a previous version of pmbootstrap, possibly when we had the `cat modes > mode` hack, I could manually run that script that the screen would turn on and show weston but in the latest version that file got removed and doing manually `cat modes > mode` doesn't change anything.

**Comment by drebrez** [comment]
@PabloCastellano can you pastebin the whole dmesg?

**Comment by PabloCastellano** [comment]
Sorry I submitted the issue before finishing writing

**Comment by PabloCastellano** [comment]
Full dmesg: [dmesg_titan.txt](https://github.com/postmarketOS/pmbootstrap/files/1381087/dmesg_titan.txt)

**Comment by montvid** [comment]
Did you install all the firmware in /lib/firmware? Just a guess.

**Comment by PabloCastellano** [comment]
Good news! All I just needed was msm-fb-refresher

Splash screen works and weston shows up smoothly :tada:

The only regression that I found is that none of the weston examples are loaded and I cannot run them manually neither. Is this a known bug or a specific bug in my case?

```
localhost:/etc/profile.d# export XDG_RUNTIME_DIR=/tmp/0-runtime-dir
localhost:/etc/profile.d# weston-smoke 
failed to connect to Wayland display: No such file or directory
failed to create display: No such file or directory
localhost:/etc/profile.d# weston-terminal 
failed to connect to Wayland display: No such file or directory
failed to create display: No such file or directory
```

I have tried running them as root and as normal user

**Comment by drebrez** [comment]
@PabloCastellano they should work as user, try with `export DISPLAY=:0`

**Comment by PabloCastellano** [comment]
@drebrez okay, that works for some of the examples (as weston-smoke or weston-editor) but now fails for weston-terminal:

```
localhost:~$ weston-terminal 
could not load cursor 'dnd-move'
could not load cursor 'dnd-copy'
could not load cursor 'dnd-none'
wl_display@1: error 0: invalid object 0
```

I still need to understand why they are not run on boot

**Comment by drebrez** [comment]
@PabloCastellano weston-terminal has a bug that we didn't discovered how to solve it yet, see #121

**Comment by ollieparanoid** [comment]
Awesome that you have it working now! \o/
Could you make a PR, that adds `msm-fb-refresher` as dependency?

On a side note, `DISPLAY=:0` is only required for X11 applications and XWayland (postmarketos-demos is currently running through XWayland).
