### ISSUE TITLE
Use coveralls.io to display testing coverage?

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#761]
PR #760 will integrate automatic testing on Travis CI, at least for the fast testcases. I would like to display how much testing coverage we have for pmbootstrap in the README.md (with a badge and with details when you click on it).

**Proprietary** service [coveralls.io](https://coveralls.io/) looks like a nice interface and is free to use for open source projects. It is compatible to GitHub and gitlab [in case we decide to move there](https://github.com/postmarketOS/postmarketos.org/issues/37).

I have not found a similar service, where the source code is available (is there any?).

Worst case is, that for some reason we suddenly can't use that service anymore and lose the coverage reports from the past. We can always generate coverage reports ourselves with [pytest-cov](https://github.com/pytest-dev/pytest-cov) (which is the output that gets used for coveralls.)

And of course the upside is, that this motivates (at least me) to make more testcases and have good testing coverage.

So what do you think about this proposal, fellow hackers?

**Comment by MartijnBraam** [comment]
coveralls is pretty nice, you can even configure it to make it deny a PR when the coverage drops too much if it gets merged.

I also haven't found any nice open solutions yet, gitlab has some very very sloppy coverage integration (it parses the coverage percentage from your gitlab-ci log and then basically thows away that information).

**Comment by PabloCastellano** [comment]
Go for it. The trade-off looks good to me and we can always implement another coverage tool that comes out and we like more.
