### ISSUE TITLE
Make it easy to export system.img and boot.img outside of the chroots

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#77]
From issue #73.

@alexlep:
> I was using SP flash tool to flash images, and at first I created boot.img manually using mkbootimg from aports. Maybe we could do smth like:
`./pmbootstrap.py build bootimage`
which will build mkbootimg, install it to chroot, and automatically will build boot.img with kernel/ram files and params from deviceinfo?

@MartijnBraam:
> I was thinking of something like `pmbootstrap export [path]` to export boot.img and system.img to a specific path.

**Comment by MartijnBraam** [comment]
maybe boot.img and rootfs.img is better since system.img is android-specific

**Comment by ollieparanoid** [comment]
As discussed in the channel:
* the boot.img file will get created for Android devices within `mkinitfs`
* the output path to both the boot folder and the full path to the system image will be shown after install
* there will be an export command, which simply creates symlinks to the boot.img file (or all boot files of one kernel flavor?) and the system image.

**Comment by PabloCastellano** [comment]
I think I missed the discussion about the symlinks. Is it necessary or just showing the path to the generated files is enough?

**Comment by ollieparanoid** [comment]
@MartijnBraam suggested the symlinks for convenience. I don't care that much, but I think they don't hurt - and if they improve usability, I think it's better to add them.
