### ISSUE TITLE
GUI info not correct (xfce)

### ISSUE THREAD

**Issue by montvid** [postmarketOS/pmbootstrap#790]
The installer informs us wrongly:
* xfce4: (X11) Lightweight GTK+3 desktop (stylus recommended)
Xfce is basted on Gtk+ 2.24 and not gtk 3 see:
https://wiki.archlinux.org/index.php/xfce
http://docs.xfce.org/xfce/building

**Comment by ollieparanoid** [comment]
Thanks for pointing that out! (Looks like the [next big version](https://blog.alteroot.org/articles/2016-04-12/road-to-xfce-4.14.html) will have fully switched to GTK+3).
