### ISSUE TITLE
syslog -C (shared memory) isn't working with some Android kernels

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#808]
Reported by NTAuthority in #postmarketOS:
> it seems shared memory is disabled in my kernel as syslogd fails when using the ring buffer btw, so I have to start weston manually to get log output from there.. it does see a touch screen however 
> ('logread: can't find syslogd buffer: Function not implemented', and syslogd not running either - and using -C it will just fail) 

Also @drebrez reported the same problem earlier.
The simple workaround is disabling shared memory for syslog for now (new PR) - we enable `-C` in `/etc/conf.d/syslog` in `postmarketos-base`'s `post-install` script right now.

Additionally we could figure out, if there is a kernel option, that always makes it work, and make sure that it is always enabled (add it to `kconfig_check`).

Right now this causes weston to be not working for the devices in question, if I understood correctly.

**Comment by ollieparanoid** [comment]
I think I've found the proper solution [here](https://forum.openwrt.org/viewtopic.php?pid=599#p599):
>  verified this by building a new kernel, changing
> `# CONFIG_SYSVIPC is not set` to `CONFIG_SYSVIPC=y`
> in openwrt-wrt54g-linux.config and rebuilding.  Running syslogd -C then logs into a shared memory area which can be read with logread.
> `@hammock:/# logger hiya`
> `@hammock:/# logread | tail -1`
> `Jan  1 00:07:19 hammock user.notice 0: hiya`

@drebrez: if you have the time, could you verify that enabling SYSVIPC in menuconfig fixes the issue, and then make a PR which adds this to `kconfig_check`?

*Using the -C option has the advantage of writing to RAM only, which will give the internal flash storage a slightly longer life time. It does not matter that much as "newer" flash storage has more write cycles until it dies as I have learned, but still it seems to be good practice to me.*

**Comment by drebrez** [comment]
@ollieparanoid nice, going to test it right now
