### ISSUE TITLE
`pmbootstrap shutdown` only shuts down the binfmt of the currently selected device arch

### ISSUE THREAD

**Issue by drebrez** [postmarketOS/pmbootstrap#811]
I tried to enter the chroot for the aarch64 but it fails with:
```
drebrez@drebrez-laptop:~/pmbootstrap$ pmbootstrap chroot --suffix buildroot_aarch64
[20:31:43] (buildroot_aarch64) % sh
/usr/sbin/chroot: failed to run command 'sh': No such file or directory
[20:31:43] ERROR: Command failed: (buildroot_aarch64) % sh
```
here the failing command:
```
subprocess.CalledProcessError: Command '['sudo', '/bin/sh', '-c', "env -i CHARSET=UTF-8 
PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin 
SHELL=/bin/ash HISTFILE=~/.ash_history /usr/sbin/chroot 
/home/drebrez/.local/var/pmbootstrap/chroot_buildroot_aarch64 sh -c 'cd /;sh'"]' 
returned non-zero exit status 127
```

What I discovered until now:
```
drebrez@drebrez-laptop:~/.local/var/pmbootstrap/chroot_buildroot_aarch64$ lddtree bin/busybox
busybox => bin/busybox (interpreter => /lib/ld-musl-aarch64.so.1)
    libc.musl-aarch64.so.1 => not found
```

**Comment by ollieparanoid** [comment]
I think this might happen, if you kill `pmbootstrap` while it is setting up the chroot (e.g. with `^C`).
What happens, when you zap your chroots and try it again?

**Comment by drebrez** [comment]
Already tried running all possible combinations of `pmbootstrap shutdown` and `pmbootstrap zap`

**Comment by ollieparanoid** [comment]
Could you please zap your chroots again, clear your log file, run `pmbootstrap chroot --suffix buildroot_aarch64` and then upload the entire logfile?

**Comment by drebrez** [comment]
https://hastebin.com/vuceneyaje.swift

**Comment by ollieparanoid** [comment]
This might be an upstream issue, there's some discussion in `#alpine-devel` about /bin/sh missing or something. I need to look into this more to understand it.

**Comment by kaniini** [comment]
it’s failing because you’re not running the initial apk process inside qemu, so the scripts can’t run.  apk cannot set up the /bin/sh symlink because it can’t run busybox, since it’s a different architecture.

this is different than the issue we were discussing today which has to do with upgrades from the docker edge image to latest edge

**Comment by ollieparanoid** [comment]
@kaniini: thanks for having a look! It's clear now that this is not an upstream issue.

@drebrez: somehow, it does not register the binfmt on your system, the lines related to `Register qemu binfmt (aarch64)` are missing from your log.

Could you try to debug what is going wrong with [binfmt.py](https://github.com/postmarketOS/pmbootstrap/blob/master/pmb/chroot/binfmt.py) on your system? It looks like, `is_registered()` would return `True` for you, although it is not registered.

Maybe you have another program/service installed, that configures `binfmt`?

Here's how it looks like on my system:
```
% pmbootstrap chroot -b
[19:09:53] (buildroot_aarch64) % sh
[19:09:53] (native) install alpine-base
[19:09:54] (native) install qemu-user-static-repack qemu-user-static-repack-binfmt
[19:09:55] Register qemu binfmt (aarch64)
[19:09:55] (buildroot_aarch64) install alpine-base
/ #
```

**Comment by drebrez** [comment]
Ok I resolved, the `/proc/sys/fs/binfmt_misc/qemu-aarch64` was already present and that's why it wasn't registering it again. 
With `pmbootstrap shutdown` it wasn't removing it because it only unregister the `binfmt` of the architecture of the device specified in `pmbootstrap init`.
After I changed the device and run shutdown, then it started working.
Output of `update-binfmts --display` before the fix:
```
...
qemu-aarch64 (enabled):
     package = qemu-user-binfmt
        type = magic
      offset = 0
       magic = \x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7\x00
        mask = \xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff
 interpreter = /usr/bin/qemu-aarch64
    detector =
...
```
but look exactly as now that is working.

Should we change `pmbootstrap shutdown` to unregister for all the architectures?

**Comment by ollieparanoid** [comment]
Thanks for analyzing this!
> Should we change `pmbootstrap shutdown` to unregister for all the architectures?

Yes, that would make it work as expected (and also we print a message, in case the user is using binfmt for something else and doesn't want it to be shut down, so at least it's obvious what's going on). Could you take a shot at it?
