### ISSUE TITLE
pmbootstrap build --strict sometimes fails to initialize the chroot

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#818]
A similar error message to:
> `ERROR: Command failed: % sudo /home/kyle/PmOS/Work/apk.static -U --root /home/kyle/PmOS/Work/chroot_native --cache-dir /home/kyle/PmOS/Work/cache_apk_x86_64 --initdb --arch x86_64 add alpine-base`

@PureTryOut wrote in https://github.com/postmarketOS/pmbootstrap/issues/816#issuecomment-338899329:
> I have this error quite often, for me it's always resolved by just re-running the command.
>
> I'm not exactly sure how to reproduce it, but I think for example after building a package (`build --force --strict`) right after having run an install (`install --no-fde`).

I wrote in response:
> @PureTryOut: that sounds like a different issue related to `--strict`, I've also had that once during development of that feature and I thought I fixed it.

**Comment by craftyguy** [comment]
The issue seems to be that the condition here is true on a subsequent run of `build --strict`, so the repo data never gets created: https://github.com/postmarketOS/pmbootstrap/blob/master/pmb/chroot/apk.py#L42

This causes apk in the chroot to fail to find `alpine-base`.
