### ISSUE TITLE
xfce4: /home/user in the configs shipped by postmarketos-ui-xfce4

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#828]
Reported by bhuvi__ in IRC.

The only reference I have found is here:
https://github.com/postmarketOS/xfce4-phone/blob/4750c99f75824eabd117ab5288550f9ed899e946/config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml#L75

We could try to figure out what happens, if we delete this:
```
<property name="plugin-14" type="string" value="directorymenu">
      <property name="base-directory" type="string" value="/home/user"/>
</property>
```

If we really need the entry, we could also alternatively replace /home/user in the config (as copied to the real home folder) with the real username before starting xfce4 in our script.

**Comment by bhuvi8** [comment]
The above entry just creates a link for user home directory in the bottom panel. Removing the entry just removes the link to user home directory in the bottom panel.
In my opinion, this can be safely removed. @ollieparanoid what is your opinion on this?
If this can be removed I'll remove it create a pull request in https://github.com/postmarketOS/xfce4-phone repo.

**Comment by ollieparanoid** [comment]
Sounds good to me!

**Comment by ollieparanoid** [comment]
Meanwhile, the PR was created and merged, and the `postmarketos-ui-xfce4` package was updated to reflect this.
