### ISSUE TITLE
Check if work folder is inside pmbootstrap folder (not supported!)

### ISSUE THREAD

**Issue by ddemarco5** [postmarketOS/pmbootstrap#831]
I'm making efforts to port pmOS over to my old Droid 4, however when pmbootstrap is preparing to build the kernel it fails after building gcc-armhf with this message:
```
ERROR: [Errno 13] Permission denied: '/home/dominic/postmarketOS_experiments/pmbootstrap/ls/chroot_native/proc/1/cwd'
```

upon investigation of the log I see this:
```
ls/packages/x86_64/g++-armhf-6.4.0-r5.apk
ls/packages/x86_64/gcc-armhf-6.4.0-r5.apk
ls/packages/x86_64/musl-armhf-1.1.17-r1.apk
ls/packages/x86_64/musl-dev-armhf-1.1.17-r1.apk
ls/version
(005356) [17:27:02] ERROR: [Errno 13] Permission denied: '/home/dominic/postmarketOS_experiments/pmbootstrap/ls/chroot_native/proc/1/cwd'
```

Interesting... let's have a look at that file
```
ls: cannot read symbolic link ls/chroot_native/proc/1/cwd: Permission denied
lrwxrwxrwx 1 root root 0 Oct 26 17:26 ls/chroot_native/proc/1/cwd
```
You can't see it, but the file path was red, indicating a permission denied error.
I listed out the rest of the directory and saw that cwd, exe, and root were all broken.

I've done a zap, same problem. I've reinitialized, same problem. I'm actually unable to delete these files until I reboot my system and change the ownership of them, even running directly as root.

I've tried just about everything I can think of, this is a huge blocker and I haven't seen anything about it in the issues here, so my first assumption is downlevel packages used by debian, but I have no idea where to start looking.

Has anyone successfully completed the build process on Debian 8?

I've gone ahead and attached the log to this issue, in case anyone wants to try and dig through there to glean any information.
[log.txt](https://github.com/postmarketOS/pmbootstrap/files/1420148/log.txt)

**Comment by ollieparanoid** [comment]
> I'm making efforts to port pmOS over to my old Droid 4

Awesome! `/proc` in the chroot is actually the `/proc` from your host system (via `mount --bind`), so please don't try to delete anything in that.

1. What does `ls -lah` say? This is what I get on my system:
```
./pmbootstrap.py chroot -- ls -lah /proc/1/cwd
lrwxrwxrwx    1 root     root           0 Oct 27 23:54 /proc/1/cwd -> /
```

2. Do you run a special kernel or any other special setup, such as trying to sandbox pmbootstrap?


You have come to the right place with opening an issue, we'll get this working. Welcome to postmarketOS!

**Comment by ollieparanoid** [comment]
Actually, that is mentioned in the [troubleshooting guide](https://wiki.postmarketos.org/wiki/Troubleshooting#Permission_denied:_....2Fpmbootstrap.2Fwork.2Fchroot_native.2Fproc.2F1.2Fcwd.27) and I wrote it down there myself about 3 weeks ago 😆 

Basically you have put your working folder into the pmbootstrap folder, which is not supported. Looks like we better implement a check for that, since you're the second person to run into that.

**Comment by ddemarco5** [comment]
Ohhh I see what you're saying. Yeah I think you should definitely run a check for that, I don't remember reading anything about that in any of the getting started guides (though I may have and promptly forgot... man... those are dense ;P) if you're someone like me that likes to try and keep all his hobby projects self contained, they'll probably run into the same problem I did.
