### ISSUE TITLE
Automatically analyze Android boot.img files and generate the deviceinfo entries

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#835]
This idea is from @MoreRobustThanYou in the chat.

**Comment by MoreRobustThanYou** [comment]
This COULD be done with a well done regex, or more complex methods with unpacking the bootimg.

Also, it'd be nice if it could use extract-dtb to detect deviceinfo_bootimg_qcdt

**Comment by drebrez** [comment]
Closed by #905
