### ISSUE TITLE
Please fix musl-armhf build URL

### ISSUE THREAD

**Issue by zhenyolka** [postmarketOS/pmbootstrap#838]
I get this error on ubuntu 17.10 artful amd64.
musl-armhf: Fetching musl-1.1.17-r1-armhf.apk::https://nl.alpinelinux.org/alpine//edge/main/armhf/musl-1.1.17-r1.apk
The requested URL returned error: 404 Not Found
I try in browser - not found.

**Comment by zhenyolka** [comment]
fix to musl-1.1.17-r2.apk in url.

**Comment by zhenyolka** [comment]
i found only it file in repo

**Comment by ollieparanoid** [comment]
Thanks for reporting!
