### ISSUE TITLE
pmbootstrap unusable due to https://ftp.us.debian.org problems

### ISSUE THREAD

**Issue by pavelmachek** [postmarketOS/pmbootstrap#842]
Hello everyone...
[10:33:39] (native) build x86_64/qemu-user-static-repack-2.8-r8.apk
...now fails, because
https://ftp.us.debian.org/debian/pool/main/q/qemu/qemu-user-static_2.8+dfsg-6+
deb9u2_amd64.deb is not available.
...making pmbootstrap unusable. Should happen to everyone...?

It seems there's wrong certificate on  https://ftp.us.debian.org ?

**Comment by pavelmachek** [comment]
This works around the issue. We still check sha-sum, so should not be too dangerous.

```
--- a/aports/cross/qemu-user-static-repack/APKBUILD
+++ b/aports/cross/qemu-user-static-repack/APKBUILD
@@ -6,7 +6,7 @@ pkgdesc="QEMU user mode emulation binaries (static version)"
 arch=x86_64
 url="https://wiki.debian.org/DebianKernel/ARMMP"
 license="GPL2"
-source="https://ftp.us.debian.org/debian/pool/main/q/qemu/qemu-user-static_${_debver}.deb"
+source="http://ftp.us.debian.org/debian/pool/main/q/qemu/qemu-user-static_${_debver}.deb"
 makedepends="tar xz"

```

**Comment by JBBgameich** [comment]
Just replace ftp.us.debian.org with deb.debian.org. It's debians new https enabled CDN which should be fast all over the world, not just in the US.
