### ISSUE TITLE
Add support for custom fastboot args / vendor ID

### ISSUE THREAD

**Issue by MoreRobustThanYou** [postmarketOS/pmbootstrap#855]
For example, for fastboot to work on ```amazon-thor```, it requires that you add ```-i 0x1949``` after fastboot for it to work

perhaps add ```deviceinfo_fastboot_args```?

**Comment by drebrez** [comment]
Maybe something more specific like `deviceinfo_flash_fastboot_vendor_id`

**Comment by MoreRobustThanYou** [comment]
yeah
