### ISSUE TITLE
Ability to store SWAP on /cache partition?

### ISSUE THREAD

**Issue by MoreRobustThanYou** [postmarketOS/pmbootstrap#870]
The /cache partition remains unused (and can sometimes be ~1 GB)... why not use it for swap?

**Comment by PureTryOut** [comment]
Honestly I prefer putting LVM over all available partitions and use that to define our own partition layout. Check #60.

**Comment by ollieparanoid** [comment]
Good idea @MoreRobustThanYou. You seem to agree with @PureTryOut, that we better use LVM over all partitions, so I'm closing this issue - feel free to contribute to the LVM ideas in the other issue or tell us if there's still something you'd like to discuss in this issue (we can reopen it at any time).
