### ISSUE TITLE
flash_system failed: (remote: Unknown chunk type)

### ISSUE THREAD

**Issue by MoreRobustThanYou** [postmarketOS/pmbootstrap#888]
This is on amazon-thor with sparseness enabled on my local firmware-thor branch

```
(019025) [19:55:14] (native) % fastboot -i 0x1949 flash system /home/pmos/rootfs/amazon-thor.img
[19:55:13] (native) flash system image
target reported max download size of 536870912 bytes
erasing 'system'...
OKAY [  0.020s]
sending 'system' (439355 KB)...
OKAY [ 66.057s]
writing 'system'...
FAILED (remote: Unknown chunk type)
finished. total time: 66.135s
```

**Comment by drebrez** [comment]
I have the same issue with the `huawei-y530`, I didn't figured out what exactly is the problem.

**Comment by drebrez** [comment]
The FairPhone2 had the same issue (see #245) and has been resolved by patching the bootloader (see [here](https://github.com/z3ntu/android_kernel_lk_fairphone_FP2/commit/0255581a47b96b8b0b3d7c5f0336d5f6bef8f2ad))

**Comment by MoreRobustThanYou** [comment]
I've did some testing, it appears ```amazon-thor```'s fastboot has a hard limit on flashing -- around 400 MB. If the limit is hit, this error gets thrown.
