### ISSUE TITLE
Add the ability to do "pmbootstrap gconfig" or "xconfig"?

### ISSUE THREAD

**Issue by steamp0rt** [postmarketOS/pmbootstrap#891]
I kinda wanna use the GUI configs, rather than the ncurses-based ones.

**Comment by ollieparanoid** [comment]
We run `menuconfig` inside the chroot, so we would need to pass the X cookie and display variable. Here's how we could implement it:
* add some syntax to execute either `gconfig` or `xconfig` (how about `pmbootstrap menuconfig -x postmarketos-mainline`, and `-g` for `gconfig`?) in `pmb/parse/arguments.py`
* copy the file from the `XAUTHORITY` environment variable to the native chroot (in a temp folder and delete it after it isn't necessary anymore would be good practice in my opinion) in `pmb/chroot/menuconfig.py`
* set the `XAUTHORITY` and `DISPLAY` variables (`DISPLAY` must be the same as on the host) when executing `gconfig` or `xconfig` also in `pmb/chroot/menuconfig.py`

Do you want to give it a try?

**Comment by MoreRobustThanYou** [comment]
Someone on the IRC came up with the idea of splitting menuconfig and kconfig_check and stuff into one command

```pmbootstrap kconfig gconfig```
```pmbootstrap kconfig xconfig```
```pmbootstrap kconfig menuconfig```
```pmbootstrap kconfig check```

**Comment by MoreRobustThanYou** [comment]
Also I wouldn't know how to code this, sorry

**Comment by ollieparanoid** [comment]
No problem. That syntax also looks nice!

**Comment by ata2001** [comment]
Could we leave menuconfig as default, and add the argument `--frontend` instead?

The syntax would be:

```
pmbootstrap kconfig # launch menuconfig
pmbootstrap kconfig --frontend gconfig # launch gconfig
pmbootstrap kconfig --frontend xconfig # launch xconfig
pmbootstrap kconfig check # check config for necessary settings
```

**Comment by ollieparanoid** [comment]
That would be fine with me. `pmbootstrap kconfig -g` and `-x` would be even shorter if that is desired (`argparse` allows [mutually exclusive options](https://docs.python.org/3/library/argparse.html#mutual-exclusion)).
