### ISSUE TITLE
[sony-amami] backlight workaround for weston is broken

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#912]
@ata2001 reported in the chat, that [fb-workaround.sh](https://github.com/postmarketOS/pmbootstrap/blob/master/aports/device/device-sony-amami/fb-workaround.sh) doesn't work anymore since `weston` doesn't run as `root` anymore. Because it depended on autologin as `root`.

My proposed workaround was using an OpenRC service instead of autologin (which will go away when we have a display manager anyway).

**Comment by drebrez** [comment]
I suggest trying the **rc.local** service, by installing the script in `/etc/local.d/` and enabling the service in [postmarketos-base.post-install#L9-L18](https://github.com/postmarketOS/pmbootstrap/blob/master/aports/main/postmarketos-base/postmarketos-base.post-install#L9-L18)

**Comment by limiter121** [comment]
Also affects `sony-honami`
