### ISSUE TITLE
Is there any value in trying to port postmarketOS to really old devices?

### ISSUE THREAD

**Issue by joshas** [postmarketOS/pmbootstrap#917]
I have few Android devices, that are quite old (released around 2011), with low end specs: 0.5 ~ 1 GHz CPU, 320 x 480 pixels screen, and up to 1GB of RAM. Is it worth trying to port postmarketOS to one of those? I fear that in the end, even if I get working GUI, it will be too slow to be actually usable.
What are your thoughts? Are there recommended hardware specifications to run postmarketOS?

**Comment by ollieparanoid** [comment]
I think it's totally worth it. You can choose the software you want to run on it, so if you choose something lightweight, it will still be pretty fast. Compare with the [specs of the N900](https://wiki.postmarketos.org/wiki/Nokia_N900_(nokia-rx51)) for example, which quite a few people from the postmarketOS community are interested in.

**Comment by joshas** [comment]
Thanks.
