### ISSUE TITLE
postmarketos-demos is broken

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#923]
* The shutdown button is broken (we don't run weston as root anymore, hence it doesn't work)
* Firefox is not installed by default (maybe note that in the button)?

**Comment by PabloCastellano** [comment]
> The shutdown button is broken (we don't run weston as root anymore, hence it doesn't work)

What do you think about adding the user to a group that can run `poweroff` without being root?
In UNIX systems it may make sense that any user cannot shutdown the machine where other users may be working on. But for a smartphone I don't think this is a major drawback
