### ISSUE TITLE
It's not possible to set "none" as flash method in the device wizard (pmbootstrap init)

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#929]
Reported by mishaor in IRC. Some devices, like the Orange Pi in this case, can only be installed via SD card.

**Comment by drebrez** [comment]
@ollieparanoid I can add it, I also want to change that part to also include the `sp-flash-tool` method

**Comment by ollieparanoid** [comment]
That sounds good! 👍
