### ISSUE TITLE
"pmbootstrap qemu" broke with Linux 4.14 (we use Linux LTS as workaround now)

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#936]
@PureTryOut wrote:
> ugh, pmOS Qemu seems dead... with `dri-virtio`, it doesn't boot at all. with `dri-swrast`, the filesystem is readonly which makes it impossible to write to `/tmp` 

@PureTryOut does it work, when adding "rw" to the kernel command line (there's a switch in `pmbootstrap qemu` which lets you directly modify the kernel commandline)?

**Comment by ollieparanoid** [comment]
I can reproduce this issue, and adding "rw" to the kernel command line does *not* fix it.
However, I have noted that OpenRC says:

```
...
 * Checking local filesystems ...
fsck.ext4: Unable to resolve 'LABEL="pmOS_root"'
 * Operational error
 * Remounting root filessystem read/write ...
mount: /: can't find LABEL="pmOS_root".
...
```

**Comment by PureTryOut** [comment]
I wanted to wait for someone else to reproduce the error before making an issue out of it, I guess I was too late 😉

It's an interesting issue, I'm not exactly sure what commit caused this to happen.

**Comment by ollieparanoid** [comment]
My checklist for the partition-by-label not found issue:
* ~~pmbootstrap doesn't write the label to the partition~~ checked, that does not happen
* caused by the last kernel update?
* openrc update? (at least there's no such open issue - and that would mean it happens with non-qemu, too)

**Comment by ollieparanoid** [comment]
The Linux upgrade to 4.14 introduced the "read-only bug", it works fine with the last 4.13 kernel we had packaged.

**Workaround:** choose `none` as UI in `pmbootstrap init` or modify your `postmarketos-ui-*` profile script to drop to a shell. Then remount the root partition with `rw` as @magmastonealex wrote elsewhere.


Next steps:
* Does this also happen with 4.14.2? (yeah we should upgrade our Linux package!)


What I also found out: The errors in OpenRC come from `/etc/init.d/fsck` and `/etc/init.d/root`. Both use `/lib/rc/bin/fstabinfo`, which is a program shipped with OpenRC ([fstabinfo.c](https://github.com/OpenRC/openrc/blob/master/src/rc/fstabinfo.c)).

**Comment by zhuowei** [comment]
Some other weirdness:

- Whenever we try to look for pmOS_root (e.g. with findfs), this shows in the kernel log:

```
[  976.261467] attempt to access beyond end of device
[  976.261471] unknown-block(3,0): rw=0, want=1519621, limit=1519616
[  976.261474] Buffer I/O error on dev hda2, logical block 182139, async page read
[  976.267101] attempt to access beyond end of device
[  976.267103] unknown-block(3,0): rw=0, want=1519621, limit=1519616
[  976.267105] Buffer I/O error on dev hda2, logical block 182139, async page read
```

Is our disk image too small or something?

- Busybox's implementation of mount and findfs works fine, which explains why the initramfs can mount the root filesystem but OpenRC can't:

```
~ # findfs LABEL=pmOS_root
findfs: unable to resolve 'LABEL=pmOS_root'
~ # busybox findfs LABEL=pmOS_root
/dev/hda2
```

**Comment by zhuowei** [comment]
OK, I found one way to workaround this:

- Extend the rootfs manually.
```
chroot_native/home/pmos/rootfs# parted -s qemu-amd64.img 
chroot_native/home/pmos/rootfs# parted -s qemu-amd64.img print
Model:  (file)
Disk chroot_native/home/pmos/rootfs/qemu-amd64.img: 778MB
Sector size (logical/physical): 512B/512B
Partition Table: msdos

Number  Start   End     Size    Type     File system  Flags
 1      1049kB  32.0MB  31.0MB  primary  ext2         boot
 2      32.0MB  778MB   746MB   primary  ext4

chroot_native/home/pmos/rootfs# truncate -s 1G qemu-amd64.img 
chroot_native/home/pmos/rootfs# parted -s qemu-amd64.img print
Model:  (file)
Disk chroot_native/home/pmos/rootfs/qemu-amd64.img: 1074MB
Sector size (logical/physical): 512B/512B
Partition Table: msdos

Number  Start   End     Size    Type     File system  Flags
 1      1049kB  32.0MB  31.0MB  primary  ext2         boot
 2      32.0MB  778MB   746MB   primary  ext4

chroot_native/home/pmos/rootfs# exit
```

- And avoid extending the partition:

```./pmbootstrap.py qemu --display sdl --cmdline "console=tty1 console=ttyS0 PMOS_NO_OUTPUT_REDIRECT"```

And now qemu mounts the rootfs fine.

So this does have something to do with the extra space at the end of the disk. Do we know what changed in Linux 4.14 to cause this?

**Comment by ollieparanoid** [comment]
Thanks for your great research and for the workaround! 

> So this does have something to do with the extra space at the end of the disk.

**That sounds logical!** I think running `strace` on `mount /` (or alternatively `findfs /`) with `4.14.x` and `4.13.x`, then doing a diff on both outputs, should reveal which syscall changed its behavior.


I've looked into OpenRC's fstabinfo and the error does *not* come from there. It calls `mount` (not from `busybox`, as you wrote, but from `core-utils`) and `fsck` (from `e2fsprogs`), which then fail to find the partition by label from `/etc/fstab`.

What I've also found and thought was related (but right now I don't think so anymore):

*We always have two `/` entries in mount in qemu-amd64 without FDE (in both the 4.14.x and 4.13.x kernels). Before the umounts and switch_root in our `init.sh` it is one mount, and in `init_early.sh` from OpenRC there are two mount points. I couldn't figure out exactly where the second one comes from.*

**Comment by ollieparanoid** [comment]
My plan to fix this:
- [ ] package `linux-postmarketos-lts` and let `device-qemu-amd64´ use it until this is fixed (will do that later today)
- [ ] do a git bisect (with a script) with the kernel source to find the commit that caused this... I don't think there's a way around it.

**Comment by ollieparanoid** [comment]
Whatever the problem was, it has been fixed upstream in the kernel. I've just tested it and qemu-amd64 works again with `linux-postmarketos-stable`.

#1041 will make it easier to do git bisects of the kernel if we have a similar problem in the future.
