### ISSUE TITLE
Print a warning/error, when a package is out of date, but the version has not changed

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#94]
As I understand it, it is not intuitive for some, that when something gets changed inside a package folder, the package does not get rebuilt automatically (I think this is what @mmaret wanted to be fixed, right? If not, please correct me).

We could do it like `make` and check if the last modified timestamps of each file inside the `aports/$pkgname/` folder is older than the timestamp of the compiled package.

If this is not the case, print a warning and rebuild the package.

**Comment by MartijnBraam** [comment]
Won't the source files always be older than the package? Maybe the hashes in the package can be compared to the existing files

**Comment by ollieparanoid** [comment]
Comparing hashes is expensive.

I'm talking about the files in the `aports` folder, such as `APKBUILD`, `some_random.patch` etc, not about kernel sources and other files downloaded.

What I meant is: If you update your APKBUILD file, it should get a newer "last modified" timestamp, than the "apk" file, that has been built before, and we could detect that (just like make would do). Or is that a misconception?

**Comment by mmaret** [comment]
Looks Great To Me :)
