### ISSUE TITLE
Add option to update packages instead of completely re-installing the SD card

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#95]
Doing full `pmbootstrap install` all the time can quickly trash an SD card.

Instead, we could provide the following:
* `pmbootstrap install --update [--sdcard=...]`
* This command verifies, that there's a valid installation on the sdcard/in the image file on the disk (abort with an error, if it isn't).
* Then it compiles all packages, which need to be updated (in case the compiled version isn't up to date).
* Then it figures out, which packages need to be updated in the installation medium and updates them.
* Bonus points for getting this working over SCP/SSH (when the installation medium is booted on the target device; we could copy the packages + dependencies with `scp` into `/tmp` and install them via `ssh`)

**Comment by ollieparanoid** [comment]
Alternatively, if your phone has wifi, you can [host your packages over LAN](https://github.com/postmarketOS/pmbootstrap/wiki/Installing-packages-on-a-running-phone).

**Comment by ollieparanoid** [comment]
Now that we can parse Alpine's internal package database (which is almost the same format as `APKINDEX.tar.gz`, but uncompressed), I think this can be done by comparing the package databases of the installation image/sdcard, and of the versions available as binary packages.

**Comment by ollieparanoid** [comment]
@pavelmachek: you mentioned copying stuff via rsync, is this what you had in mind?

**Comment by pavelmachek** [comment]
Heh. Thanks for ping. Yes, something like that. I'd avoid finding out which packages changed, I'd simply rsync. Currently preparing sd card takes cca 15 minutes here, so any improvement would be welcome.

**Comment by ollieparanoid** [comment]
Not directly related to this issue, but since your device has wifi working, you can [directly host your package repo over LAN from your PC](https://wiki.postmarketos.org/wiki/Installing_packages_on_a_running_phone). That should be *a lot* faster!

**Comment by ollieparanoid** [comment]
There has been no interested in this issue in over 3 months, and we have an alternative solution that works well:
* [host your own repository](https://wiki.postmarketos.org/wiki/Installing_packages_on_a_running_phone)
* Connect via Wi-Fi or [USB Network](https://wiki.postmarketos.org/wiki/USB_Internet)
* Just use `apk` to update the packages.

**Comment by pavelmachek** [comment]
Sorry to jump in to old issue... But doing something not to wear out sdcards too quickly would still be nice. .. and it would also speed up installation, a lot. I had seen copying to SD card taking half an hour (with xfce), and I don't believe it can go below 5 minutes (with minimum system). Well, with rsync, it goes down to 15 seconds... and I do have a patch. I believe patch will need some more work (like actually making update behaviour optional), but... let me publish it.

**Comment by pavelmachek** [comment]
I've created PR#1151 .
