### ISSUE TITLE
apk says: "Huh? Error reporter did not find the broken constraints"

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#952]
@magmastonealex reported in IRC:
> Interesting: I can't run `pmbootstrap install`. I get an 'ERROR: unsatisfiable constraints' and 'Huh? Error reporter did not find the broken constraints'.
> More log here: https://pastebin.com/iJV2UdGU
> If I install the packages that pmbootstrap is calculating dependencies for directly, everything seems to install fine 
> this is on master 
> actually, that also wound up being a workaround. By installing them in the rootfs chroot, apk suceeded when running `pmbootstrap install` again 

Most relevant log lines:
```
% apk --no-progress add -u postmarketos-base ttf-droid device-qemu-amd64 vim file mesa-dri-virtio dbus-nox11-libs chrony cryptsetup eudev haveged htop iw nano openssh postmarketos-mkinitfs sudo tmux util-linux wpa_supplicant shadow fontconfig linux-postmarketos-stable lua5.2-libs ncurses-libs libmagic llvm5-libs libdrm libelf expat libgcc mesa-glapi libstdc++ libcap cryptsetup-libs popt udev-init-scripts eudev-libs libblkid kmod libnl3 openssh-client openssh-sftp-server openssh-server busybox-extras lddtree multipath-tools postmarketos-splash device-mapper parted e2fsprogs e2fsprogs-extra osk-sdl ncurses-terminfo libevent findmnt libfdisk libmount libsmartcols libuuid pcsc-lite-libs linux-pam freetype ncurses-terminfo-base libffi libpciaccess device-mapper-libs xz-libs openssh-keygen openssh-server-common libaio json-c readline userspace-rcu ttf-dejavu py3-pillow lvm2-libs libcom_err e2fsprogs-libs sdl2 sdl2_ttf mesa-gl directfb libbz2 libpng encodings mkfontdir mkfontscale py3-olefile libjpeg-turbo lcms2 openjpeg python3 tiff libwebp device-mapper-event-libs libx11 libxdamage libxext libxfixes libxxf86vm libxcb libxshmfence tslib libfontenc gdbm sqlite-libs libxau libxdmcp libbsd
ERROR: unsatisfiable constraints:
  Huh? Error reporter did not find the broken constraints.
```

@magmastonealex: this is a bug in apk, but we'll need some more information. Are you able to reproduce this and could you try to minimize the package list, that triggers this error?

Thanks for reporting!

**Comment by drebrez** [comment]
I'm getting the same error by selecting the `qemu-amd64` device and running `pmbootstrap install`

**Comment by ollieparanoid** [comment]
Thanks, that's very helpful! Looks like `apk` can't handle the case when two packages provide the same `so:` file. I'm leaving this open until we properly report it upstream.

**Comment by ollieparanoid** [comment]
So I didn't report it upstream because I wasn't able to prepare data that triggers the bug yet. Now there's this upstream discussion now with tips on how to debug this issue: https://lists.alpinelinux.org/alpine-devel/5992.html

**Comment by ollieparanoid** [comment]
Actually this issue is a duplicate of #237, because `dbus-nox11` did also have `provides="$pkgname"`, and I made an upstream bugreport for that [here](https://bugs.alpinelinux.org/issues/7586). Alpine developers [fixed it](https://lists.alpinelinux.org/alpine-devel/6003.html), thanks a lot!
