### ISSUE TITLE
Package `dbus-nox11` breaks xfce4 

### ISSUE THREAD

**Issue by drebrez** [postmarketOS/pmbootstrap#956]
The package `dbus-nox11` gets installed instead of the original one and doesn't contain the `x11` sub-package with the required `/usr/bin/dbus-launch`.
Also `/usr/bin/dbus-uuidgen` is missing and causes problems.

**Comment by drebrez** [comment]
After investigating a little bit more I found out that only `dbus-nox11-libs` gets installed.
Installing `apk add dbus-nox11` adds all the required files and xfce4 starts working

**Comment by PureTryOut** [comment]
So a fix would be adding a dependency on it's parent package to `dbus-nox11-libs` then?

To be honest, I wonder if we can't just get rid of `dbus-nox11` again. I originally added it because of #377. Is that still a problem?

**Comment by ollieparanoid** [comment]
I've removed the `dbus-nox11` package from `aports` and from the repo, and rebuilt `postmarketos-ui-plasma-mobile`. Could you please check if the issue has gone away?

**Comment by drebrez** [comment]
@ollieparanoid I've installed everything from scratch (zap, init, install), flashed on device and xfce4 started successfully.
```
localhost:~$ apk info -vv | grep dbus
dbus-libs-1.10.24-r0 - Libraries for acces D-BUS
dbus-1.10.24-r0 - Freedesktop.org message bus system
dbus-glib-0.108-r1 - GLib bindings for DBUS
dbus-x11-1.10.24-r0 - X11-requiring add-ons for D-BUS
```
