### ISSUE TITLE
pmbootstrap install should set the root password

### ISSUE THREAD

**Issue by zhuowei** [postmarketOS/pmbootstrap#960]
Currently we set the main user's password, but not the root user's.

To reproduce:

- run `su` on postmarketOS when logged in as a standard user, or log in as "root" in a qemu image with "none" ui

Expected:

- postmarketOS asks me for a root password

Actual:

- no password is needed.

**Comment by ollieparanoid** [comment]
Thanks for reporting! We used to set both the user password *and* the root password, but it was annoying to type in 2 passwords (+ FDE) each install. That's why we only set the user password now.

I've made a PR, that disables the root login properly (sudo is still working) in #962.

**Comment by drebrez** [comment]
I agree that disabling the root login is better than prompting for a root password

**Comment by ollieparanoid** [comment]
Fixed in #962 (I'll write that into the commit message in the future instead of the title, so GitHub picks it up correctly).
