### ISSUE TITLE
plasma-mobile does not work in Qemu

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#973]
I think our `plasma-mobile` packaging isn't in a good state currently.

This does not mean that @PureTryOut did a bad job - after all it worked for him, and he was able to provide Qemu screenshots and videos, and at some point @zhuowei also had it running on a device (although no photo exists as far as I know).

But it broke along the way, and I blame that we don't test the UI automatically. Otherwise we would have noticed the breakage before merging the code that breaks it. So I recommend the following:
* make plasma-mobile run in Qemu again (this issue!)
* #969 automated travis test case, that verifies that it boots up (this is the easy part)
* run it on a real device (all needed changes can be made with more confidence now)
* post the next blog post and mention our plasma progress prominently (https://github.com/postmarketOS/postmarketos.org/issues/40)

For reference, we have automatic login as user enabled on `tty1`, and we install [`start_plasma.sh`](https://github.com/postmarketOS/pmbootstrap/blob/master/aports/main/postmarketos-ui-plasma-mobile/start_plasma.sh) as profile script. This is a workaround until we have a proper display manager #656 (out of scope for this issue).

Here is my experience, when running it in Qemu, with `pmbootstrap qemu --spice` (full log below).
**Categorizing the unknown messages is already helpful, and fixing stuff is of course appreciated.**

#### Probably fatal
- [x] kwin does not get installed (fixed, added it as dependency to `postmarketos-ui-plasma-mobile`)
- [x] `Cannot mix incompatible Qt library (version 0x50901) with this library (version 0x50903)` seems to be a new problem introduced with the binary repository. Possibly related: automatically detect soname bumps (#893). Fix + test case on the way in #976.
- [ ] `org.kde.kwindowsystem: Could not find any platform plugin` what is a platform plugin, drm and framebuffer? and why can't it find any?

#### Unknown
- [x] `/usr/bin/plasma-phone: line 33: /usr/lib/ksyncdbusenv: not found`
- [ ] `init: must be run as PID 1` <- what the hell?
- [ ] `Error org.freedesktop.DBus.Error.ServiceUnknown: The name com.google.code.AccountsSSO.SingleSignOn was not provided by any .service files`
- [ ] `Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Telepathy.MissionControl5 was not provided by any .service files`
- [x] `/usr/bin/plasma-phone: line 52: /usr/lib/org_kde_powerdevil: not found`
- [x] `/usr/bin/plasma-phone: line 49: /usr/lib/polkit-kde-authentication-agent-1: not found`

#### Probably not fatal
- [x] `Failed to initialize glamor, falling back to sw` as it says, it should fall back to software rendering. that might be caused by the `--spice` parameter I'm using - though when we check if plasma-mobile boots up in Travis (#969), we'll probably not have 3D working either. So that should work as well.
- [ ] `daemon.warn console-kit-daemon[1137]: WARNING: failed to mute FD with KDSKBMUTE` - FD stands for filedescriptor, so it's unable to mute some log output?
- [ ] pulseaudio errors

#### Not fatal
- [x] consolekit2 throws a warning, because it is inside the `/etc/profile.d/start_plasma.sh` script, which we run as user. It complains that it needs to be ran as root. We are starting it elsewhere as root through, as `ps aux | grep console` reveals, so we only need to fix where it gets started as user and confirm that it still starts up afterwards.
- [ ] `kglobalaccel-runtime: Failed to register service org.kde.kglobalaccel` and subsequent `Failed to connect to the kglobalaccel daemon` (@bhush9 said in the chat, that this is not fatal)

#### `logread` output from `pmbootstrap qemu --spice`
```
Dec  3 18:51:41 localhost user.notice user:plasma-mobile: kglobalaccel-runtime: Failed to register service org.kde.kglobalaccel
Dec  3 18:51:47 localhost daemon.warn console-kit-daemon[1137]: WARNING: failed to mute FD with KDSKBMUTE
Dec  3 18:51:47 localhost user.notice user:plasma-mobile: Couldn't start kglobalaccel from org.kde.kglobalaccel.service: QDBusError("org.freedesktop.DBus.Error.Disconnected", "Not connected to D-Bus server")
Dec  3 18:51:47 localhost user.notice user:plasma-mobile: Failed to connect to the kglobalaccel daemon QDBusError("org.freedesktop.DBus.Error.Disconnected", "Not connected to D-Bus server")
Dec  3 18:51:47 localhost user.notice user:plasma-mobile: Failed to connect to the kglobalaccel daemon QDBusError("org.freedesktop.DBus.Error.Disconnected", "Not connected to D-Bus server")
Dec  3 18:51:47 localhost user.notice user:plasma-mobile: Failed to connect to the kglobalaccel daemon QDBusError("org.freedesktop.DBus.Error.Disconnected", "Not connected to D-Bus server")
Dec  3 18:51:47 localhost user.notice user:plasma-mobile: pci id for fd 26: 1b36:0100, driver (null)
Dec  3 18:51:49 localhost user.notice user:plasma-mobile: OpenGL vendor string:                   VMware, Inc.
Dec  3 18:51:49 localhost user.notice user:plasma-mobile: OpenGL renderer string:                 llvmpipe (LLVM 5.0, 128 bits)
Dec  3 18:51:49 localhost user.notice user:plasma-mobile: OpenGL version string:                  3.0 Mesa 17.2.4
Dec  3 18:51:49 localhost user.notice user:plasma-mobile: OpenGL shading language version string: 1.30
Dec  3 18:51:49 localhost user.notice user:plasma-mobile: Driver:                                 Unknown
Dec  3 18:51:49 localhost user.notice user:plasma-mobile: GPU class:                              Unknown
Dec  3 18:51:49 localhost user.notice user:plasma-mobile: OpenGL version:                         3.0
Dec  3 18:51:49 localhost user.notice user:plasma-mobile: GLSL version:                           1.30
Dec  3 18:51:49 localhost user.notice user:plasma-mobile: Mesa version:                           17.2.4
Dec  3 18:51:49 localhost user.notice user:plasma-mobile: Linux kernel version:                   4.9.65
Dec  3 18:51:49 localhost user.notice user:plasma-mobile: Requires strict binding:                no
Dec  3 18:51:49 localhost user.notice user:plasma-mobile: GLSL shaders:                           yes
Dec  3 18:51:49 localhost user.notice user:plasma-mobile: Texture NPOT support:                   yes
Dec  3 18:51:49 localhost user.notice user:plasma-mobile: Virtual Machine:                        no
Dec  3 18:51:49 localhost user.notice user:plasma-mobile: Disabling glamor and dri3, EGL setup failed
Dec  3 18:51:49 localhost user.notice user:plasma-mobile: Failed to initialize glamor, falling back to sw
Dec  3 18:51:50 localhost user.notice user:plasma-mobile: X-Server started on display :0
Dec  3 18:51:50 localhost user.notice user:plasma-mobile: /usr/bin/plasma-phone: line 33: /usr/lib/ksyncdbusenv: not found
Dec  3 18:51:50 localhost user.notice user:plasma-mobile: init: must be run as PID 1
Dec  3 18:51:50 localhost user.notice user:plasma-mobile: Error org.freedesktop.DBus.Error.ServiceUnknown: The name com.google.code.AccountsSSO.SingleSignOn was not provided by any .service files
Dec  3 18:51:50 localhost user.notice user:plasma-mobile: Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Telepathy.MissionControl5 was not provided by any .service files
Dec  3 18:51:51 localhost user.notice user:plasma-mobile: /usr/bin/plasma-phone: line 52: /usr/lib/org_kde_powerdevil: not found
Dec  3 18:51:51 localhost user.notice user:plasma-mobile: /usr/bin/plasma-phone: line 49: /usr/lib/polkit-kde-authentication-agent-1: not found
Dec  3 18:51:52 localhost user.warn pulseaudio[1245]: [pulseaudio] authkey.c: Failed to open cookie file '/home/user/.config/pulse/cookie': No such file or directory
Dec  3 18:51:52 localhost user.warn pulseaudio[1245]: [pulseaudio] authkey.c: Failed to load authentication key '/home/user/.config/pulse/cookie': No such file or directory
Dec  3 18:51:52 localhost user.warn pulseaudio[1245]: [pulseaudio] authkey.c: Failed to open cookie file '/home/user/.pulse-cookie': No such file or directory
Dec  3 18:51:52 localhost user.warn pulseaudio[1245]: [pulseaudio] authkey.c: Failed to load authentication key '/home/user/.pulse-cookie': No such file or directory
Dec  3 18:51:57 localhost user.notice user:plasma-mobile: Failed to connect to the kglobalaccel daemon QDBusError("org.freedesktop.DBus.Error.Disconnected", "Not connected to D-Bus server")
(... this message comes 10 times or so)
Dec  3 18:51:57 localhost user.notice user:plasma-mobile: org.kde.kwindowsystem: Could not find any platform plugin
Dec  3 18:51:57 localhost user.notice user:plasma-mobile: Configuring Lock Action
Dec  3 18:51:57 localhost user.notice user:plasma-mobile: Failed to connect to the kglobalaccel daemon QDBusError("org.freedesktop.DBus.Error.Disconnected", "Not connected to D-Bus server")
Dec  3 18:51:57 localhost user.notice user:plasma-mobile: Failed to connect to the kglobalaccel daemon QDBusError("org.freedesktop.DBus.Error.Disconnected", "Not connected to D-Bus server")
Dec  3 18:51:59 localhost user.notice user:plasma-mobile: Cannot mix incompatible Qt library (version 0x50901) with this library (version 0x50903)
Dec  3 18:51:59 localhost user.notice user:plasma-mobile: (EE)
Dec  3 18:51:59 localhost user.notice user:plasma-mobile: Fatal server error:
Dec  3 18:51:59 localhost user.notice user:plasma-mobile: (EE) failed to read Wayland events: Broken pipe
Dec  3 18:51:59 localhost user.notice user:plasma-mobile: (EE)
Dec  3 17:51:59 localhost daemon.warn console-kit-daemon[1137]: WARNING: failed to unmute FD with KDSKBMUTE
```

**Comment by bhush9** [comment]
`Cannot mix incompatible Qt library (version 0x50901) with this library (version 0x50903) `

Means one of module is still qt 5.9.1

Please grep for this version and fix that package

**Comment by PureTryOut** [comment]
```
org.kde.kwindowsystem: Could not find any platform plugin
```

As I recall, this means either Wayland, X11, etc. @bhush9 reported earlier that this log message is a bug, and it works fine. The log should later on show it runs with Wayland fine.

```
/usr/bin/plasma-phone: line 52: /usr/lib/org_kde_powerdevil: not found
```

Makes no sense, as `powerdevil` should be installed.

```
/usr/bin/plasma-phone: line 49: /usr/lib/polkit-kde-authentication-agent-1: not found
```

Again, makes non sense, as `polkit-kde-agent` should be installed.

```
Failed to initialize glamor, falling back to sw
```

Is indeed caused by `--spice`. Should not happen with `dri-virtio`.

It's weird that `kwin` isn't installed at all. However I wonder if adding `kwin`  to the `postmarketos-ui-plasma-mobile` dependencies is the right solution. Doesn't `plasma-workspace` (which then depends on `kwin`) make more sense?

**Comment by bhush9** [comment]
> Failed to initialize glamor, falling back to sw

Is coming from Xwayland, Xwayland can't use the opengl it seems here

**Comment by ollieparanoid** [comment]
Closing, this is outdated. Plasma mobile works again in Qemu, and even on real devices (see [latest blog post](https://postmarketos.org/blog/2017/12/31/219-days-of-postmarketOS/)).
