### ISSUE TITLE
[Plasma] Top drawer and background missing on first boot

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#979]
When booting plasma mobile directly after the installation, the top drawer and the background are missing. The top drawer appears when booting the second time. I've tested all this in Qemu.

@PureTryOut wrote:
> if you also want the background to appear, remove ~/.config/plasma-org.kde.plasma.phone-appletsrc once and reboot. that will however make the top drawer disappear...
> yeah it's all very strange, I know

@bhush9 and @PureTryOut (or whoever else knows):
* Is this an upstream bug?
* How can we assist with fixing this?
* Is there a method to get both the background and the top drawer working at the same time?

@bhush9, if you have time and disk space, you could reproduce this in a few minutes (as we have binary packages now):
```shell
git clone https://github.com/postmarketOS/pmbootstrap
cd pmbootstrap
./pmbootstrap.py init # select qemu-amd64 and plasma-mobile, leave defaults for the rest
./pmbootstrap.py install --no-fde
./pmbootstrap.py qemu --image-size=2G
```

**Comment by bhush9** [comment]
I am currently trying to install it locally

But for starters.. It is possible that this is upstream bug. Can you provide `~/.config/plasma-org.kde.plasma.phone-appletrc` from both first and 2nd boot?

**Comment by PureTryOut** [comment]
Content on first boot (before removing it):

```
[Containments][1]
activityId=c5103b42-fa80-4da8-b7d1-f7f4504ac620
formfactor=0
immutability=1
lastScreen=0
location=0
plugin=org.kde.phone.homescreen
wallpaperplugin=org.kde.image

[Containments][1][Applets][2]
immutability=1
plugin=org.kde.plasma.analogclock

[Containments][1][General]
AppletOrder=2

[Containments][1][Wallpaper][org.kde.image][General]
Image=org.kde.plasma.phone.lockers

[Containments][3]
activityId=
formfactor=2
immutability=1
lastScreen=0
location=3
plugin=org.kde.phone.panel
wallpaperplugin=org.kde.image

[Containments][3][Applets][4]
immutability=1
plugin=org.kde.phone.notifications

[Containments][3][Applets][6]
immutability=1
plugin=org.kde.plasma.battery

[Containments][3][Applets][8]
immutability=1
plugin=org.kde.phone.activities

[Containments][9]
activityId=
formfactor=2
immutability=1
lastScreen=0
location=4
plugin=org.kde.phone.taskpanel
wallpaperplugin=org.kde.image
```

Content on second boot (after removing it the first boot):

```
[Containments][1]
activityId=f0198ae0-aec6-423e-92f5-ba419ca9fff4
formfactor=0
immutability=1
lastScreen=0
location=0
plugin=org.kde.phone.homescreen
wallpaperplugin=org.kde.image

[Containments][1][Applets][2]
immutability=1
plugin=org.kde.plasma.analogclock

[Containments][1][General]
AppletOrder=2

[Containments][1][Wallpaper][org.kde.image][General]
Image=org.kde.plasma.phone.lockers

[Containments][3]
activityId=
formfactor=2
immutability=1
lastScreen=0
location=3
plugin=org.kde.phone.panel
wallpaperplugin=org.kde.image

[Containments][3][Applets][4]
immutability=1
plugin=org.kde.phone.notifications

[Containments][3][Applets][6]
immutability=1
plugin=org.kde.plasma.battery

[Containments][3][Applets][8]
immutability=1
plugin=org.kde.phone.activities

[Containments][9]
activityId=
formfactor=2
immutability=1
lastScreen=0
location=4
plugin=org.kde.phone.taskpanel
wallpaperplugin=org.kde.image
```
```

**Comment by ollieparanoid** [comment]
@bhush9 said the fix is:
> You need to package plasma-pa and plasma-nm 

@PureTryOut then rebased #388 in order to get there.

**Comment by PureTryOut** [comment]
Well rebasing #388 wasn't part of this. I have plasma-pa and plasma-nm both packaged locally, however currently this seems to crash Plasma after a second or two on a real device. I'm going to push what I have so far and make a PR with the `do_not_merge` label on it, so at least others can verify if it happens for them too or it's just me.

That said, this doesn't seem to have anything to do with the black background, as that still happens for me on x86_64 Qemu.
