### ISSUE TITLE
ERROR: git-2.15.0-r1: BAD signature

### ISSUE THREAD

**Issue by PureTryOut** [postmarketOS/pmbootstrap#981]
So as part of the packages I install by default to any device is git.

When installing the base system (and thus git as well) (`./pmbootstrap.py install`), it errors out with the following:

```
ERROR: git-2.15.0-r1: BAD signature
```

Since this only seems to happen with an armhf device (Qemu amd64 installs fine), this might actually be an upstream issue. I'm not entirely sure though.

**Comment by ollieparanoid** [comment]
Maybe the download of that package got interrupted. Could you delete it, then try again?
```shell
sudo rm -v ~/code/pmbootstrap/cache_apk_armhf/git-*
```

**Comment by PureTryOut** [comment]
I asked on [#alpine-linux:alpinelinux.org](https://matrix.to/#/#alpine-linux:alpinelinux.org), and got a useful response. Seems an upstream issue.

\_ikke\_ said:
> git has been reverted (but pkgrel bumped)
> So someone needs to invalidate the cached version on cdn
> the revert made it go to 2.15.0-1, which already existed before
