### ISSUE TITLE
N900: keyboard layout needs to be loaded manually

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#991]
@pieniek wrote in https://github.com/postmarketOS/pmbootstrap/issues/961#issuecomment-350322107:
> One more thing - when I installed postmarket some time ago the keyboard layout was loaded out of the box, now I had to load it manually after fresh install.

@dviaznikov:
> I can confirm @pieniek 's issue about keyboard layout.

**Comment by dviaznikov** [comment]
As far as I remember, it is only XFCE-related issue, TTY is working okay.
In my case from fresh installation of postmarketOS XFCE don't list nokia_vndr/rx_51 keyboard layout and should be directed manually via editing `$HOME/.config/xfce4/xfconf/xfce-perchannel-xml/keyboard-layout.xml`

**Comment by ollieparanoid** [comment]
How about writing it into a Xorg config file instead, which we could ship with the N900? That way it should work for all X11 interfaces.

PR #924 shows how such a per-device X11 config could be added in case someone wants to work on this (it's pretty easy actually, and as usually we're happy to help if you get stuck).
